// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/constants.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/constants.h>
#include "abi_check.h"

#include <windows.h>   // GENERIC_*/KEY_*/WAIT_*/TOKEN_*/SECTION_*/STANDARD_RIGHTS_*/...
#include <objbase.h>   // VARENUM, CLSCTX, VARIANT_BOOL/VARIANT_TRUE/VARIANT_FALSE

// value parity for an SDK enumerator (abi spells it as a plain enum member in
// namespace sprt_abi, not as a __SPRT_ macro).
#define SPRT_ENUM(name) \
	static_assert((long long)(sprt_abi::name) == (long long)(name), \
			"enum " #name " != SDK")

// === misc scalars ==========================================================
SPRT_CONST(ANYSIZE_ARRAY);
SPRT_CONST(FALSE);
SPRT_CONST(TRUE);
SPRT_CONST(MAX_PATH);
SPRT_CONST(MAXIMUM_WAIT_OBJECTS);
SPRT_CONST(MAX_COMPUTERNAME_LENGTH);

// === RRF_* (registry value retrieval flags) ================================
SPRT_CONST(RRF_RT_REG_NONE);
SPRT_CONST(RRF_RT_REG_SZ);
SPRT_CONST(RRF_RT_REG_EXPAND_SZ);
SPRT_CONST(RRF_RT_REG_BINARY);
SPRT_CONST(RRF_RT_REG_DWORD);
SPRT_CONST(RRF_RT_REG_MULTI_SZ);
SPRT_CONST(RRF_RT_REG_QWORD);
SPRT_CONST(RRF_RT_DWORD);
SPRT_CONST(RRF_RT_QWORD);
SPRT_CONST(RRF_RT_ANY);
SPRT_CONST(RRF_SUBKEY_WOW6464KEY);
SPRT_CONST(RRF_SUBKEY_WOW6432KEY);
SPRT_CONST(RRF_WOW64_MASK);
SPRT_CONST(RRF_NOEXPAND);
SPRT_CONST(RRF_ZEROONFAILURE);

// === REG_* (registry value types, winnt.h) =================================
SPRT_CONST(REG_NONE);
SPRT_CONST(REG_SZ);
SPRT_CONST(REG_EXPAND_SZ);
SPRT_CONST(REG_BINARY);
SPRT_CONST(REG_DWORD);
SPRT_CONST(REG_MULTI_SZ);
SPRT_CONST(REG_QWORD);

// === VARENUM (VT_*) ========================================================
SPRT_ENUM(VT_EMPTY);
SPRT_ENUM(VT_NULL);
SPRT_ENUM(VT_I2);
SPRT_ENUM(VT_I4);
SPRT_ENUM(VT_R4);
SPRT_ENUM(VT_R8);
SPRT_ENUM(VT_CY);
SPRT_ENUM(VT_DATE);
SPRT_ENUM(VT_BSTR);
SPRT_ENUM(VT_DISPATCH);
SPRT_ENUM(VT_ERROR);
SPRT_ENUM(VT_BOOL);
SPRT_ENUM(VT_VARIANT);
SPRT_ENUM(VT_UNKNOWN);
SPRT_ENUM(VT_DECIMAL);
SPRT_ENUM(VT_I1);
SPRT_ENUM(VT_UI1);
SPRT_ENUM(VT_UI2);
SPRT_ENUM(VT_UI4);
SPRT_ENUM(VT_I8);
SPRT_ENUM(VT_UI8);
SPRT_ENUM(VT_INT);
SPRT_ENUM(VT_UINT);
SPRT_ENUM(VT_VOID);
SPRT_ENUM(VT_HRESULT);
SPRT_ENUM(VT_PTR);
SPRT_ENUM(VT_SAFEARRAY);
SPRT_ENUM(VT_CARRAY);
SPRT_ENUM(VT_USERDEFINED);
SPRT_ENUM(VT_LPSTR);
SPRT_ENUM(VT_LPWSTR);
SPRT_ENUM(VT_FILETIME);
SPRT_ENUM(VT_BLOB);
SPRT_ENUM(VT_STREAM);
SPRT_ENUM(VT_STORAGE);
SPRT_ENUM(VT_STREAMED_OBJECT);
SPRT_ENUM(VT_STORED_OBJECT);
SPRT_ENUM(VT_BLOB_OBJECT);
SPRT_ENUM(VT_CF);
SPRT_ENUM(VT_CLSID);
SPRT_ENUM(VT_VECTOR);
SPRT_ENUM(VT_ARRAY);
SPRT_ENUM(VT_BYREF);
SPRT_ENUM(VT_RESERVED);
SPRT_ENUM(VT_ILLEGAL);
SPRT_ENUM(VT_ILLEGALMASKED);
SPRT_ENUM(VT_TYPEMASK);

// === VARIANT_BOOL ==========================================================
SPRT_CONST(VARIANT_TRUE);
SPRT_CONST(VARIANT_FALSE);

// === CLSCTX ================================================================
SPRT_ENUM(CLSCTX_INPROC_SERVER);
SPRT_ENUM(CLSCTX_INPROC_HANDLER);
SPRT_ENUM(CLSCTX_LOCAL_SERVER);
SPRT_ENUM(CLSCTX_INPROC_SERVER16);
SPRT_ENUM(CLSCTX_REMOTE_SERVER);
SPRT_ENUM(CLSCTX_INPROC_HANDLER16);
SPRT_ENUM(CLSCTX_RESERVED1);
SPRT_ENUM(CLSCTX_RESERVED2);
SPRT_ENUM(CLSCTX_RESERVED3);
SPRT_ENUM(CLSCTX_RESERVED4);
SPRT_ENUM(CLSCTX_NO_CODE_DOWNLOAD);
SPRT_ENUM(CLSCTX_RESERVED5);
SPRT_ENUM(CLSCTX_NO_CUSTOM_MARSHAL);
SPRT_ENUM(CLSCTX_ENABLE_CODE_DOWNLOAD);
SPRT_ENUM(CLSCTX_NO_FAILURE_LOG);
SPRT_ENUM(CLSCTX_DISABLE_AAA);
SPRT_ENUM(CLSCTX_ENABLE_AAA);
SPRT_ENUM(CLSCTX_FROM_DEFAULT_CONTEXT);
SPRT_ENUM(CLSCTX_ACTIVATE_X86_SERVER);
SPRT_ENUM(CLSCTX_ACTIVATE_32_BIT_SERVER);
SPRT_ENUM(CLSCTX_ACTIVATE_64_BIT_SERVER);
SPRT_ENUM(CLSCTX_ENABLE_CLOAKING);
SPRT_ENUM(CLSCTX_APPCONTAINER);
SPRT_ENUM(CLSCTX_ACTIVATE_AAA_AS_IU);
SPRT_ENUM(CLSCTX_RESERVED6);
SPRT_ENUM(CLSCTX_ACTIVATE_ARM32_SERVER);
SPRT_ENUM(CLSCTX_ALLOW_LOWER_TRUST_REGISTRATION);
SPRT_ENUM(CLSCTX_PS_DLL);
// CLSCTX_ALL is a *macro* in the SDK (combaseapi.h) but an enum member in the abi;
// the bare identifier would macro-expand, so capture the SDK value, drop the macro,
// then compare it against the abi enumerator.
static constexpr long long __sdk_clsctx_all = CLSCTX_ALL;
#undef CLSCTX_ALL
static_assert((long long) (sprt_abi::CLSCTX_ALL) == __sdk_clsctx_all,
		"sprt_abi::CLSCTX_ALL != SDK CLSCTX_ALL");

// === HRESULT helper macros (function-like: check a sample expansion) ========
// __SPRT_HRESULT_CODE(hr) must extract the low 16 bits exactly like the SDK's
// HRESULT_CODE. 0x8007000E == E_OUTOFMEMORY -> facility WIN32, code 0x000E.
static_assert(__SPRT_HRESULT_CODE(0x8007000EL) == HRESULT_CODE(0x8007000EL),
		"__SPRT_HRESULT_CODE != SDK HRESULT_CODE");
static_assert(__SPRT_HRESULT_CODE(0x80070005L) == HRESULT_CODE(0x80070005L),
		"__SPRT_HRESULT_CODE != SDK HRESULT_CODE");

// === handle duplication ====================================================
SPRT_CONST(DUPLICATE_CLOSE_SOURCE);
SPRT_CONST(DUPLICATE_SAME_ACCESS);

// === WAIT_* ================================================================
SPRT_CONST(WAIT_FAILED);
SPRT_CONST(WAIT_OBJECT_0);
SPRT_CONST(WAIT_ABANDONED);
SPRT_CONST(WAIT_ABANDONED_0);
SPRT_CONST(WAIT_IO_COMPLETION);

// === special values ========================================================
SPRT_CONST(INVALID_FILE_ATTRIBUTES);
SPRT_CONST(INFINITE);

// === HANDLE_FLAG_* =========================================================
SPRT_CONST(HANDLE_FLAG_INHERIT);
SPRT_CONST(HANDLE_FLAG_PROTECT_FROM_CLOSE);

// === LMEM_* (local memory flags) ===========================================
SPRT_CONST(LMEM_FIXED);
SPRT_CONST(LMEM_MOVEABLE);
SPRT_CONST(LMEM_NOCOMPACT);
SPRT_CONST(LMEM_NODISCARD);
SPRT_CONST(LMEM_ZEROINIT);
SPRT_CONST(LMEM_MODIFY);
SPRT_CONST(LMEM_DISCARDABLE);
SPRT_CONST(LMEM_VALID_FLAGS);
SPRT_CONST(LMEM_INVALID_HANDLE);

SPRT_CONST(STACK_SIZE_PARAM_IS_A_RESERVATION);

// === SEM_* =================================================================
SPRT_CONST(SEM_FAILCRITICALERRORS);
SPRT_CONST(SEM_NOGPFAULTERRORBOX);
SPRT_CONST(SEM_NOALIGNMENTFAULTEXCEPT);
SPRT_CONST(SEM_NOOPENFILEERRORBOX);

// === GENERIC_* access rights ===============================================
SPRT_CONST(GENERIC_READ);
SPRT_CONST(GENERIC_WRITE);
SPRT_CONST(GENERIC_EXECUTE);
SPRT_CONST(GENERIC_ALL);

// === standard/specific access rights =======================================
// abi now spells this __SPRT_DELETE (was __SPRT__DELETE), matching the SDK DELETE.
SPRT_CONST(DELETE);
SPRT_CONST(READ_CONTROL);
SPRT_CONST(WRITE_DAC);
SPRT_CONST(WRITE_OWNER);
SPRT_CONST(SYNCHRONIZE);
SPRT_CONST(STANDARD_RIGHTS_REQUIRED);
SPRT_CONST(STANDARD_RIGHTS_READ);
SPRT_CONST(STANDARD_RIGHTS_WRITE);
SPRT_CONST(STANDARD_RIGHTS_EXECUTE);
SPRT_CONST(STANDARD_RIGHTS_ALL);
SPRT_CONST(SPECIFIC_RIGHTS_ALL);

// === KEY_* (registry key access rights) ====================================
SPRT_CONST(KEY_QUERY_VALUE);
SPRT_CONST(KEY_SET_VALUE);
SPRT_CONST(KEY_CREATE_SUB_KEY);
SPRT_CONST(KEY_ENUMERATE_SUB_KEYS);
SPRT_CONST(KEY_NOTIFY);
SPRT_CONST(KEY_CREATE_LINK);
SPRT_CONST(KEY_WOW64_32KEY);
SPRT_CONST(KEY_WOW64_64KEY);
SPRT_CONST(KEY_WOW64_RES);
SPRT_CONST(KEY_READ);
SPRT_CONST(KEY_WRITE);
SPRT_CONST(KEY_EXECUTE);
SPRT_CONST(KEY_ALL_ACCESS);

// === VS_FFI_* / VFT_* (version-info file flags) ============================
SPRT_CONST(VS_FFI_STRUCVERSION);
SPRT_CONST(VS_FFI_FILEFLAGSMASK);
SPRT_CONST(VFT_UNKNOWN);
SPRT_CONST(VFT_APP);
SPRT_CONST(VFT_DLL);
SPRT_CONST(VFT_DRV);
SPRT_CONST(VFT_FONT);
SPRT_CONST(VFT_VXD);
SPRT_CONST(VFT_STATIC_LIB);

// === PROCESSOR_ARCHITECTURE_* ==============================================
SPRT_CONST(PROCESSOR_ARCHITECTURE_INTEL);
SPRT_CONST(PROCESSOR_ARCHITECTURE_MIPS);
SPRT_CONST(PROCESSOR_ARCHITECTURE_ALPHA);
SPRT_CONST(PROCESSOR_ARCHITECTURE_PPC);
SPRT_CONST(PROCESSOR_ARCHITECTURE_SHX);
SPRT_CONST(PROCESSOR_ARCHITECTURE_ARM);
SPRT_CONST(PROCESSOR_ARCHITECTURE_IA64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_ALPHA64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_MSIL);
SPRT_CONST(PROCESSOR_ARCHITECTURE_AMD64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_IA32_ON_WIN64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_NEUTRAL);
SPRT_CONST(PROCESSOR_ARCHITECTURE_ARM64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64);
SPRT_CONST(PROCESSOR_ARCHITECTURE_IA32_ON_ARM64);

// === TOKEN_* access rights =================================================
SPRT_CONST(TOKEN_ASSIGN_PRIMARY);
SPRT_CONST(TOKEN_DUPLICATE);
SPRT_CONST(TOKEN_IMPERSONATE);
SPRT_CONST(TOKEN_QUERY);
SPRT_CONST(TOKEN_QUERY_SOURCE);
SPRT_CONST(TOKEN_ADJUST_PRIVILEGES);
SPRT_CONST(TOKEN_ADJUST_GROUPS);
SPRT_CONST(TOKEN_ADJUST_DEFAULT);
SPRT_CONST(TOKEN_ADJUST_SESSIONID);

// === SECTION_* access rights ===============================================
SPRT_CONST(SECTION_QUERY);
SPRT_CONST(SECTION_MAP_WRITE);
SPRT_CONST(SECTION_MAP_READ);
SPRT_CONST(SECTION_MAP_EXECUTE);
SPRT_CONST(SECTION_EXTEND_SIZE);
SPRT_CONST(SECTION_MAP_EXECUTE_EXPLICIT);
SPRT_CONST(SECTION_ALL_ACCESS);

// === VER_PLATFORM_* ========================================================
SPRT_CONST(VER_PLATFORM_WIN32s);
SPRT_CONST(VER_PLATFORM_WIN32_WINDOWS);
SPRT_CONST(VER_PLATFORM_WIN32_NT);

// === FILE_TYPE_* ===========================================================
SPRT_CONST(FILE_TYPE_UNKNOWN);
SPRT_CONST(FILE_TYPE_DISK);
SPRT_CONST(FILE_TYPE_CHAR);
SPRT_CONST(FILE_TYPE_PIPE);
SPRT_CONST(FILE_TYPE_REMOTE);

// === OMITTED ===============================================================
// Pointer/handle-valued (can't go through the integer static_assert):
//   HKEY_* (all), INVALID_HANDLE_VALUE.
// SPRT-specific / not exposed by <windows.h>+<objbase.h>:
//   WBEM_GENERIC_FLAG_TYPE (wbemcli.h enum, not COM-core).
// Function-like macros (not constants): SUCCEEDED, FAILED.

#include <wbemcli.h>

// === WBEM_GENERIC_FLAG_TYPE ===
SPRT_ENUM(WBEM_FLAG_RETURN_IMMEDIATELY);
SPRT_ENUM(WBEM_FLAG_RETURN_WBEM_COMPLETE);
SPRT_ENUM(WBEM_FLAG_BIDIRECTIONAL);
SPRT_ENUM(WBEM_FLAG_FORWARD_ONLY);
SPRT_ENUM(WBEM_FLAG_NO_ERROR_OBJECT);
SPRT_ENUM(WBEM_FLAG_RETURN_ERROR_OBJECT);
SPRT_ENUM(WBEM_FLAG_SEND_STATUS);
SPRT_ENUM(WBEM_FLAG_DONT_SEND_STATUS);
SPRT_ENUM(WBEM_FLAG_ENSURE_LOCATABLE);
SPRT_ENUM(WBEM_FLAG_DIRECT_READ);
SPRT_ENUM(WBEM_FLAG_SEND_ONLY_SELECTED);
SPRT_ENUM(WBEM_RETURN_WHEN_COMPLETE);
SPRT_ENUM(WBEM_RETURN_IMMEDIATELY);
SPRT_ENUM(WBEM_MASK_RESERVED_FLAGS);
SPRT_ENUM(WBEM_FLAG_USE_AMENDED_QUALIFIERS);
SPRT_ENUM(WBEM_FLAG_STRONG_VALIDATION);
