// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/thread_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/thread_api.h>
#include "abi_check.h"

#include <windows.h>    // SRWLOCK, THREAD_*, TLS_*, WT_*, FIBER_FLAG_*
#include <tlhelp32.h>   // THREADENTRY32, TH32CS_*

// === THREAD_* access rights =================================================
SPRT_CONST(THREAD_TERMINATE);
SPRT_CONST(THREAD_SUSPEND_RESUME);
SPRT_CONST(THREAD_GET_CONTEXT);
SPRT_CONST(THREAD_SET_CONTEXT);
SPRT_CONST(THREAD_QUERY_INFORMATION);
SPRT_CONST(THREAD_SET_INFORMATION);
SPRT_CONST(THREAD_SET_THREAD_TOKEN);
SPRT_CONST(THREAD_IMPERSONATE);
SPRT_CONST(THREAD_DIRECT_IMPERSONATION);
SPRT_CONST(THREAD_SET_LIMITED_INFORMATION);
SPRT_CONST(THREAD_QUERY_LIMITED_INFORMATION);
SPRT_CONST(THREAD_RESUME);

// === THREAD_BASE_PRIORITY_* =================================================
SPRT_CONST(THREAD_BASE_PRIORITY_LOWRT);
SPRT_CONST(THREAD_BASE_PRIORITY_MAX);
SPRT_CONST(THREAD_BASE_PRIORITY_MIN);
SPRT_CONST(THREAD_BASE_PRIORITY_IDLE);

// === THREAD_PRIORITY_* ======================================================
SPRT_CONST(THREAD_PRIORITY_LOWEST);
SPRT_CONST(THREAD_PRIORITY_BELOW_NORMAL);
SPRT_CONST(THREAD_PRIORITY_NORMAL);
SPRT_CONST(THREAD_PRIORITY_HIGHEST);
SPRT_CONST(THREAD_PRIORITY_ABOVE_NORMAL);
SPRT_CONST(THREAD_PRIORITY_TIME_CRITICAL);
SPRT_CONST(THREAD_PRIORITY_IDLE);

// === TH32CS_* (CreateToolhelp32Snapshot flags) ==============================
SPRT_CONST(TH32CS_SNAPHEAPLIST);
SPRT_CONST(TH32CS_SNAPPROCESS);
SPRT_CONST(TH32CS_SNAPTHREAD);
SPRT_CONST(TH32CS_SNAPMODULE);
SPRT_CONST(TH32CS_SNAPMODULE32);
SPRT_CONST(TH32CS_SNAPALL);
SPRT_CONST(TH32CS_INHERIT);

// === WT_* (thread-pool / RegisterWaitForSingleObject flags) =================
SPRT_CONST(WT_EXECUTEDEFAULT);
SPRT_CONST(WT_EXECUTEINIOTHREAD);
SPRT_CONST(WT_EXECUTEINUITHREAD);
SPRT_CONST(WT_EXECUTEINWAITTHREAD);
SPRT_CONST(WT_EXECUTEONLYONCE);
SPRT_CONST(WT_EXECUTEINTIMERTHREAD);
SPRT_CONST(WT_EXECUTELONGFUNCTION);
SPRT_CONST(WT_EXECUTEINPERSISTENTIOTHREAD);
SPRT_CONST(WT_EXECUTEINPERSISTENTTHREAD);
SPRT_CONST(WT_TRANSFER_IMPERSONATION);

// === misc ===================================================================
SPRT_CONST(FIBER_FLAG_FLOAT_SWITCH);
SPRT_CONST(TLS_OUT_OF_INDEXES);

// Omitted (not integer constants): RTL_SRWLOCK_INIT / SRWLOCK_INIT are `{0}`
// aggregate initializers. QUEUE_USER_APC_FLAGS_* and CpuSetInformation are
// SPRT-local enum values (no __SPRT_ macro form).

// === SRWLOCK / RTL_SRWLOCK ==================================================
SPRT_SIZE(RTL_SRWLOCK);
SPRT_OFFSET(RTL_SRWLOCK, Ptr);
SPRT_SIZE(SRWLOCK);
SPRT_OFFSET(SRWLOCK, Ptr);

// === THREADENTRY32 ==========================================================
SPRT_SIZE(THREADENTRY32);
SPRT_OFFSET(THREADENTRY32, dwSize);
SPRT_OFFSET(THREADENTRY32, cntUsage);
SPRT_OFFSET(THREADENTRY32, th32ThreadID);
SPRT_OFFSET(THREADENTRY32, th32OwnerProcessID);
SPRT_OFFSET(THREADENTRY32, tpBasePri);
SPRT_OFFSET(THREADENTRY32, tpDeltaPri);
SPRT_OFFSET(THREADENTRY32, dwFlags);

// === SYSTEM_CPU_SET_INFORMATION =============================================
SPRT_SIZE(SYSTEM_CPU_SET_INFORMATION);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, Size);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, Type);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.Id);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.Group);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.LogicalProcessorIndex);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.CoreIndex);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.LastLevelCacheIndex);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.NumaNodeIndex);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.EfficiencyClass);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, CpuSet.AllocationTag);
// Bitfield members (Parked/Allocated/... AllFlags) and the Reserved/
// SchedulingClass overlap live in anonymous unions -> offsets not takeable.

// === CPU_SET_INFORMATION_TYPE ===
SPRT_ENUM(CpuSetInformation);

// === QUEUE_USER_APC_FLAGS ===
SPRT_ENUM(QUEUE_USER_APC_FLAGS_NONE);
SPRT_ENUM(QUEUE_USER_APC_FLAGS_SPECIAL_USER_APC);
SPRT_ENUM(QUEUE_USER_APC_CALLBACK_DATA_CONTEXT);

// === SYSTEM_CPU_SET_INFORMATION ===
SPRT_SIZE(SYSTEM_CPU_SET_INFORMATION);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, Size);
SPRT_OFFSET(SYSTEM_CPU_SET_INFORMATION, Type);
