// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// ---------------------------------------------------------------------------
// Static WINAPI-parity check for the Windows __SPRT_* socket + netinet constants.
//
// On the Windows target the SPRT socket shims (runtime/libc_wrapper) forward
// constants straight through to native Winsock without translation, e.g.
//
//     ::send(fd, buf, n, __flags);      // __flags carries __SPRT_MSG_* bits
//     ::socket(__SPRT_AF_INET, __SPRT_SOCK_STREAM, 0);
//     ::setsockopt(fd, IPPROTO_IPV6, __SPRT_IPV6_V6ONLY, ...);
//
// so every __SPRT_* value that reaches Winsock MUST equal the value in the real
// Windows SDK header. This covers both the core socket table (windows_sprt/
// sockdef.h) and the cross netinet table (__sprt_netinet.h, whose IP_/IPV6_/
// MCAST_/INET*_ADDRSTRLEN values are Windows-selected via SPRT_WINDOWS).
//
// The runtime's own asserts (SPRuntimeCSysSocket.cpp) only compile in the
// *hosted* branch (and only validate the Linux values), so they never see
// Winsock's numbers; this TU closes that gap by pinning the __SPRT_* tables
// against the live SDK headers in runtime/toolchains/src/xwin/splat.
//
// It is compile-time only: parse-check it with
//     clang --target=x86_64-pc-windows-msvc -fsyntax-only ...   (see check.sh)
// A clean compile means every checked constant matches; a failing static_assert
// names the diverging constant.
// ---------------------------------------------------------------------------

#include <winsock2.h>   // core SOCK_/AF_/SO_/MSG_/SOL_SOCKET/SOMAXCONN, SD_*, ws2def
#include <ws2tcpip.h>   // IPv6 / addrinfo level constants
#include <mstcpip.h>    // SO_ORIGINAL_DST, SO_REUSE_*PORT, SO_RECEIVED_*, IP6T_SO_ORIGINAL_DST
#include <ws2ipdef.h>   // IP_* / IPV6_* option numbers
#include <afunix.h>     // AF_UNIX

// The namespaced portable table under test (macros only, no dependencies).
#include <sprt/c/cross/windows_sprt/sockdef.h>
#include <sprt/c/cross/__sprt_netinet.h>

// Assert that __SPRT_<name> equals the identically-named Winsock constant.
#define SPRT_SAME(name) \
	static_assert(__SPRT_##name == (name), "__SPRT_" #name " != Winsock " #name)

// Assert against a differently-named native constant (POSIX name -> Win32 name).
#define SPRT_MAP(sprt, native) \
	static_assert(__SPRT_##sprt == (native), "__SPRT_" #sprt " != Winsock " #native)

// === shutdown() how: POSIX SHUT_* map to Winsock SD_* ======================
SPRT_MAP(SHUT_RD, SD_RECEIVE);
SPRT_MAP(SHUT_WR, SD_SEND);
SPRT_MAP(SHUT_RDWR, SD_BOTH);

// === socket types ==========================================================
SPRT_SAME(SOCK_STREAM);
SPRT_SAME(SOCK_DGRAM);
SPRT_SAME(SOCK_RAW);
SPRT_SAME(SOCK_RDM);
SPRT_SAME(SOCK_SEQPACKET);
// SOCK_CLOEXEC / SOCK_NONBLOCK: Linux accept4() flag bits emulated by SPRT;
// Winsock has no equivalent, so there is nothing to pin them against.

// === address / protocol families ==========================================
SPRT_SAME(AF_UNSPEC);
SPRT_SAME(AF_UNIX);
SPRT_MAP(AF_LOCAL, AF_UNIX);   // POSIX alias; Winsock only spells it AF_UNIX
SPRT_SAME(AF_INET);
SPRT_SAME(AF_INET6);
SPRT_SAME(AF_IMPLINK);
SPRT_SAME(AF_PUP);
SPRT_SAME(AF_CHAOS);
SPRT_SAME(AF_NS);
SPRT_SAME(AF_IPX);
SPRT_SAME(AF_ISO);
SPRT_SAME(AF_OSI);
SPRT_SAME(AF_ECMA);
SPRT_SAME(AF_DATAKIT);
SPRT_SAME(AF_CCITT);
SPRT_SAME(AF_SNA);
SPRT_SAME(AF_DECnet);
SPRT_SAME(AF_DLI);
SPRT_SAME(AF_LAT);
SPRT_SAME(AF_HYLINK);
SPRT_SAME(AF_APPLETALK);
SPRT_SAME(AF_NETBIOS);
SPRT_SAME(AF_VOICEVIEW);
SPRT_SAME(AF_FIREFOX);
SPRT_SAME(AF_UNKNOWN1);
SPRT_SAME(AF_BAN);
SPRT_SAME(AF_ATM);
SPRT_SAME(AF_CLUSTER);
SPRT_SAME(AF_12844);
SPRT_SAME(AF_IRDA);
SPRT_SAME(AF_NETDES);
SPRT_SAME(AF_TCNPROCESS);
SPRT_SAME(AF_TCNMESSAGE);
SPRT_SAME(AF_ICLFXBM);
SPRT_SAME(AF_BTH);
SPRT_SAME(AF_LINK);
SPRT_SAME(AF_HYPERV);
SPRT_SAME(AF_MAX);

SPRT_SAME(PF_UNSPEC);
SPRT_SAME(PF_UNIX);
SPRT_SAME(PF_INET);
SPRT_SAME(PF_IMPLINK);
SPRT_SAME(PF_PUP);
SPRT_SAME(PF_CHAOS);
SPRT_SAME(PF_NS);
SPRT_SAME(PF_IPX);
SPRT_SAME(PF_ISO);
SPRT_SAME(PF_OSI);
SPRT_SAME(PF_ECMA);
SPRT_SAME(PF_DATAKIT);
SPRT_SAME(PF_CCITT);
SPRT_SAME(PF_SNA);
SPRT_SAME(PF_DECnet);
SPRT_SAME(PF_DLI);
SPRT_SAME(PF_LAT);
SPRT_SAME(PF_HYLINK);
SPRT_SAME(PF_APPLETALK);
SPRT_SAME(PF_VOICEVIEW);
SPRT_SAME(PF_FIREFOX);
SPRT_SAME(PF_UNKNOWN1);
SPRT_SAME(PF_BAN);
SPRT_SAME(PF_ATM);
SPRT_SAME(PF_INET6);
SPRT_SAME(PF_BTH);
// Winsock provides no PF_LINK / PF_HYPERV alias; pin the SPRT PF alias against
// the AF_ spelling it is defined to equal (AF_LINK / AF_HYPERV are checked above).
SPRT_MAP(PF_LINK, AF_LINK);
SPRT_MAP(PF_HYPERV, AF_HYPERV);
SPRT_SAME(PF_MAX);

// === SOL_ levels ===========================================================
SPRT_SAME(SOL_SOCKET);
#ifdef SOL_IP
SPRT_SAME(SOL_IP);
#endif
#ifdef SOL_IPV6
SPRT_SAME(SOL_IPV6);
#endif

// === SO_ options ===========================================================
SPRT_SAME(SO_REUSEADDR);
SPRT_SAME(SO_TYPE);
SPRT_SAME(SO_ERROR);
SPRT_SAME(SO_DONTROUTE);
SPRT_SAME(SO_BROADCAST);
SPRT_SAME(SO_SNDBUF);
SPRT_SAME(SO_RCVBUF);
SPRT_SAME(SO_KEEPALIVE);
SPRT_SAME(SO_OOBINLINE);
SPRT_SAME(SO_LINGER);
// SO_REUSEPORT: BSD/Linux option emulated by SPRT; no Winsock equivalent.
SPRT_SAME(SO_DEBUG);
SPRT_SAME(SO_ACCEPTCONN);
SPRT_SAME(SO_USELOOPBACK);
SPRT_SAME(SO_DONTLINGER);
SPRT_SAME(SO_EXCLUSIVEADDRUSE);
SPRT_SAME(SO_SNDLOWAT);
SPRT_SAME(SO_RCVLOWAT);
SPRT_SAME(SO_SNDTIMEO);
SPRT_SAME(SO_RCVTIMEO);
SPRT_SAME(SO_BSP_STATE);
SPRT_SAME(SO_GROUP_ID);
SPRT_SAME(SO_GROUP_PRIORITY);
SPRT_SAME(SO_MAX_MSG_SIZE);
SPRT_SAME(SO_CONDITIONAL_ACCEPT);
SPRT_SAME(SO_PAUSE_ACCEPT);
SPRT_SAME(SO_COMPARTMENT_ID);
SPRT_SAME(SO_RANDOMIZE_PORT);
SPRT_SAME(SO_PORT_SCALABILITY);
SPRT_SAME(SO_REUSE_UNICASTPORT);
SPRT_SAME(SO_REUSE_MULTICASTPORT);
SPRT_SAME(SO_ORIGINAL_DST);
SPRT_SAME(SO_RECEIVED_HOPLIMIT);
SPRT_SAME(SO_RECEIVED_PROCESSOR);
SPRT_SAME(IP6T_SO_ORIGINAL_DST);

// === MSG_ flags ============================================================
SPRT_SAME(MSG_OOB);
SPRT_SAME(MSG_PEEK);
SPRT_SAME(MSG_DONTROUTE);
SPRT_SAME(MSG_CTRUNC);
SPRT_SAME(MSG_TRUNC);
SPRT_SAME(MSG_WAITALL);
SPRT_SAME(MSG_PARTIAL);
SPRT_SAME(MSG_MAXIOVLEN);
// MSG_DONTWAIT / MSG_EOR / MSG_NOSIGNAL: POSIX flags emulated by SPRT; Winsock
// has no equivalent bit, so they are intentionally left unpinned.

// === SOMAXCONN =============================================================
SPRT_SAME(SOMAXCONN);

// ===========================================================================
// netinet constants from <sprt/c/cross/__sprt_netinet.h>. On this target it
// resolves to its SPRT_WINDOWS values; each is pinned against the live SDK.
// IPPROTO_* are a Winsock enum (not macros) so they are asserted directly;
// the macro families are #ifdef-guarded (Linux-only options Winsock lacks are
// skipped automatically).
// ===========================================================================

// --- Address string lengths ---
#ifdef INET_ADDRSTRLEN
SPRT_SAME(INET_ADDRSTRLEN);
#endif
#ifdef INET6_ADDRSTRLEN
SPRT_SAME(INET6_ADDRSTRLEN);
#endif

// --- IP protocol numbers (Winsock enum) ---
SPRT_SAME(IPPROTO_IP);
SPRT_SAME(IPPROTO_HOPOPTS);
SPRT_SAME(IPPROTO_ICMP);
SPRT_SAME(IPPROTO_IGMP);
SPRT_SAME(IPPROTO_TCP);
SPRT_SAME(IPPROTO_EGP);
SPRT_SAME(IPPROTO_PUP);
SPRT_SAME(IPPROTO_UDP);
SPRT_SAME(IPPROTO_IDP);
SPRT_SAME(IPPROTO_IPV6);
SPRT_SAME(IPPROTO_ROUTING);
SPRT_SAME(IPPROTO_FRAGMENT);
SPRT_SAME(IPPROTO_ESP);
SPRT_SAME(IPPROTO_AH);
SPRT_SAME(IPPROTO_ICMPV6);
SPRT_SAME(IPPROTO_NONE);
SPRT_SAME(IPPROTO_DSTOPTS);
SPRT_SAME(IPPROTO_PIM);
SPRT_SAME(IPPROTO_SCTP);
SPRT_SAME(IPPROTO_RAW);
SPRT_SAME(IPPROTO_MAX);

// --- Ports / IPv4 address classes ---
#ifdef IPPORT_RESERVED
SPRT_SAME(IPPORT_RESERVED);
#endif
#ifdef IN_CLASSA_NET
SPRT_SAME(IN_CLASSA_NET);
#endif
#ifdef IN_CLASSA_NSHIFT
SPRT_SAME(IN_CLASSA_NSHIFT);
#endif
#ifdef IN_CLASSA_HOST
SPRT_SAME(IN_CLASSA_HOST);
#endif
#ifdef IN_CLASSA_MAX
SPRT_SAME(IN_CLASSA_MAX);
#endif
#ifdef IN_CLASSB_NET
SPRT_SAME(IN_CLASSB_NET);
#endif
#ifdef IN_CLASSB_NSHIFT
SPRT_SAME(IN_CLASSB_NSHIFT);
#endif
#ifdef IN_CLASSB_HOST
SPRT_SAME(IN_CLASSB_HOST);
#endif
#ifdef IN_CLASSB_MAX
SPRT_SAME(IN_CLASSB_MAX);
#endif
#ifdef IN_CLASSC_NET
SPRT_SAME(IN_CLASSC_NET);
#endif
#ifdef IN_CLASSC_NSHIFT
SPRT_SAME(IN_CLASSC_NSHIFT);
#endif
#ifdef IN_CLASSC_HOST
SPRT_SAME(IN_CLASSC_HOST);
#endif
#ifdef IN_LOOPBACKNET
SPRT_SAME(IN_LOOPBACKNET);
#endif

// --- IPv4 options (IPPROTO_IP level) ---
#ifdef IP_TOS
SPRT_SAME(IP_TOS);
#endif
#ifdef IP_TTL
SPRT_SAME(IP_TTL);
#endif
#ifdef IP_HDRINCL
SPRT_SAME(IP_HDRINCL);
#endif
#ifdef IP_OPTIONS
SPRT_SAME(IP_OPTIONS);
#endif
#ifdef IP_ROUTER_ALERT
SPRT_SAME(IP_ROUTER_ALERT);
#endif
#ifdef IP_RECVOPTS
SPRT_SAME(IP_RECVOPTS);
#endif
#ifdef IP_RETOPTS
SPRT_SAME(IP_RETOPTS);
#endif
#ifdef IP_PKTINFO
SPRT_SAME(IP_PKTINFO);
#endif
#ifdef IP_PKTOPTIONS
SPRT_SAME(IP_PKTOPTIONS);
#endif
#ifdef IP_PMTUDISC
SPRT_SAME(IP_PMTUDISC);
#endif
#ifdef IP_MTU_DISCOVER
SPRT_SAME(IP_MTU_DISCOVER);
#endif
#ifdef IP_RECVERR
SPRT_SAME(IP_RECVERR);
#endif
#ifdef IP_RECVTTL
SPRT_SAME(IP_RECVTTL);
#endif
#ifdef IP_RECVTOS
SPRT_SAME(IP_RECVTOS);
#endif
#ifdef IP_MTU
SPRT_SAME(IP_MTU);
#endif
#ifdef IP_FREEBIND
SPRT_SAME(IP_FREEBIND);
#endif
#ifdef IP_IPSEC_POLICY
SPRT_SAME(IP_IPSEC_POLICY);
#endif
#ifdef IP_XFRM_POLICY
SPRT_SAME(IP_XFRM_POLICY);
#endif
#ifdef IP_PASSSEC
SPRT_SAME(IP_PASSSEC);
#endif
#ifdef IP_TRANSPARENT
SPRT_SAME(IP_TRANSPARENT);
#endif
#ifdef IP_ORIGDSTADDR
SPRT_SAME(IP_ORIGDSTADDR);
#endif
#ifdef IP_RECVORIGDSTADDR
SPRT_SAME(IP_RECVORIGDSTADDR);
#endif
#ifdef IP_MINTTL
SPRT_SAME(IP_MINTTL);
#endif
#ifdef IP_NODEFRAG
SPRT_SAME(IP_NODEFRAG);
#endif
#ifdef IP_CHECKSUM
SPRT_SAME(IP_CHECKSUM);
#endif
#ifdef IP_BIND_ADDRESS_NO_PORT
SPRT_SAME(IP_BIND_ADDRESS_NO_PORT);
#endif
#ifdef IP_RECVFRAGSIZE
SPRT_SAME(IP_RECVFRAGSIZE);
#endif
#ifdef IP_RECVERR_RFC4884
SPRT_SAME(IP_RECVERR_RFC4884);
#endif
#ifdef IP_MULTICAST_IF
SPRT_SAME(IP_MULTICAST_IF);
#endif
#ifdef IP_MULTICAST_TTL
SPRT_SAME(IP_MULTICAST_TTL);
#endif
#ifdef IP_MULTICAST_LOOP
SPRT_SAME(IP_MULTICAST_LOOP);
#endif
#ifdef IP_ADD_MEMBERSHIP
SPRT_SAME(IP_ADD_MEMBERSHIP);
#endif
#ifdef IP_DROP_MEMBERSHIP
SPRT_SAME(IP_DROP_MEMBERSHIP);
#endif
#ifdef IP_UNBLOCK_SOURCE
SPRT_SAME(IP_UNBLOCK_SOURCE);
#endif
#ifdef IP_BLOCK_SOURCE
SPRT_SAME(IP_BLOCK_SOURCE);
#endif
#ifdef IP_ADD_SOURCE_MEMBERSHIP
SPRT_SAME(IP_ADD_SOURCE_MEMBERSHIP);
#endif
#ifdef IP_DROP_SOURCE_MEMBERSHIP
SPRT_SAME(IP_DROP_SOURCE_MEMBERSHIP);
#endif
#ifdef IP_MSFILTER
SPRT_SAME(IP_MSFILTER);
#endif
#ifdef IP_MULTICAST_ALL
SPRT_SAME(IP_MULTICAST_ALL);
#endif
#ifdef IP_UNICAST_IF
SPRT_SAME(IP_UNICAST_IF);
#endif
#ifdef IP_RECVRETOPTS
SPRT_SAME(IP_RECVRETOPTS);
#endif
#ifdef IP_DONTFRAGMENT
SPRT_SAME(IP_DONTFRAGMENT);
#endif
#ifdef IP_HOPLIMIT
SPRT_SAME(IP_HOPLIMIT);
#endif
#ifdef IP_RECEIVE_BROADCAST
SPRT_SAME(IP_RECEIVE_BROADCAST);
#endif
#ifdef IP_RECVIF
SPRT_SAME(IP_RECVIF);
#endif
#ifdef IP_RECVDSTADDR
SPRT_SAME(IP_RECVDSTADDR);
#endif
#ifdef IP_IFLIST
SPRT_SAME(IP_IFLIST);
#endif
#ifdef IP_ADD_IFLIST
SPRT_SAME(IP_ADD_IFLIST);
#endif
#ifdef IP_DEL_IFLIST
SPRT_SAME(IP_DEL_IFLIST);
#endif
#ifdef IP_RTHDR
SPRT_SAME(IP_RTHDR);
#endif
#ifdef IP_GET_IFLIST
SPRT_SAME(IP_GET_IFLIST);
#endif
#ifdef IP_RECVRTHDR
SPRT_SAME(IP_RECVRTHDR);
#endif
#ifdef IP_TCLASS
SPRT_SAME(IP_TCLASS);
#endif
#ifdef IP_RECVTCLASS
SPRT_SAME(IP_RECVTCLASS);
#endif
#ifdef IP_ORIGINAL_ARRIVAL_IF
SPRT_SAME(IP_ORIGINAL_ARRIVAL_IF);
#endif
#ifdef IP_ECN
SPRT_SAME(IP_ECN);
#endif
#ifdef IP_RECVECN
SPRT_SAME(IP_RECVECN);
#endif
#ifdef IP_PKTINFO_EX
SPRT_SAME(IP_PKTINFO_EX);
#endif
#ifdef IP_WFP_REDIRECT_RECORDS
SPRT_SAME(IP_WFP_REDIRECT_RECORDS);
#endif
#ifdef IP_WFP_REDIRECT_CONTEXT
SPRT_SAME(IP_WFP_REDIRECT_CONTEXT);
#endif
#ifdef IP_NRT_INTERFACE
SPRT_SAME(IP_NRT_INTERFACE);
#endif
#ifdef IP_USER_MTU
SPRT_SAME(IP_USER_MTU);
#endif
#ifdef IP_PMTUDISC_DONT
SPRT_SAME(IP_PMTUDISC_DONT);
#endif
#ifdef IP_PMTUDISC_WANT
SPRT_SAME(IP_PMTUDISC_WANT);
#endif
#ifdef IP_PMTUDISC_DO
SPRT_SAME(IP_PMTUDISC_DO);
#endif
#ifdef IP_PMTUDISC_PROBE
SPRT_SAME(IP_PMTUDISC_PROBE);
#endif
#ifdef IP_PMTUDISC_INTERFACE
SPRT_SAME(IP_PMTUDISC_INTERFACE);
#endif
#ifdef IP_PMTUDISC_OMIT
SPRT_SAME(IP_PMTUDISC_OMIT);
#endif
#ifdef IP_DEFAULT_MULTICAST_TTL
SPRT_SAME(IP_DEFAULT_MULTICAST_TTL);
#endif
#ifdef IP_DEFAULT_MULTICAST_LOOP
SPRT_SAME(IP_DEFAULT_MULTICAST_LOOP);
#endif
#ifdef IP_MAX_MEMBERSHIPS
SPRT_SAME(IP_MAX_MEMBERSHIPS);
#endif

// --- IPv6 options (IPPROTO_IPV6 level) ---
#ifdef IPV6_ADDRFORM
SPRT_SAME(IPV6_ADDRFORM);
#endif
#ifdef IPV6_2292PKTINFO
SPRT_SAME(IPV6_2292PKTINFO);
#endif
#ifdef IPV6_2292HOPOPTS
SPRT_SAME(IPV6_2292HOPOPTS);
#endif
#ifdef IPV6_2292DSTOPTS
SPRT_SAME(IPV6_2292DSTOPTS);
#endif
#ifdef IPV6_2292RTHDR
SPRT_SAME(IPV6_2292RTHDR);
#endif
#ifdef IPV6_2292PKTOPTIONS
SPRT_SAME(IPV6_2292PKTOPTIONS);
#endif
#ifdef IPV6_CHECKSUM
SPRT_SAME(IPV6_CHECKSUM);
#endif
#ifdef IPV6_2292HOPLIMIT
SPRT_SAME(IPV6_2292HOPLIMIT);
#endif
#ifdef IPV6_NEXTHOP
SPRT_SAME(IPV6_NEXTHOP);
#endif
#ifdef IPV6_AUTHHDR
SPRT_SAME(IPV6_AUTHHDR);
#endif
#ifdef IPV6_UNICAST_HOPS
SPRT_SAME(IPV6_UNICAST_HOPS);
#endif
#ifdef IPV6_MULTICAST_IF
SPRT_SAME(IPV6_MULTICAST_IF);
#endif
#ifdef IPV6_MULTICAST_HOPS
SPRT_SAME(IPV6_MULTICAST_HOPS);
#endif
#ifdef IPV6_MULTICAST_LOOP
SPRT_SAME(IPV6_MULTICAST_LOOP);
#endif
#ifdef IPV6_JOIN_GROUP
SPRT_SAME(IPV6_JOIN_GROUP);
#endif
#ifdef IPV6_LEAVE_GROUP
SPRT_SAME(IPV6_LEAVE_GROUP);
#endif
#ifdef IPV6_ROUTER_ALERT
SPRT_SAME(IPV6_ROUTER_ALERT);
#endif
#ifdef IPV6_MTU_DISCOVER
SPRT_SAME(IPV6_MTU_DISCOVER);
#endif
#ifdef IPV6_MTU
SPRT_SAME(IPV6_MTU);
#endif
#ifdef IPV6_RECVERR
SPRT_SAME(IPV6_RECVERR);
#endif
#ifdef IPV6_V6ONLY
SPRT_SAME(IPV6_V6ONLY);
#endif
#ifdef IPV6_JOIN_ANYCAST
SPRT_SAME(IPV6_JOIN_ANYCAST);
#endif
#ifdef IPV6_LEAVE_ANYCAST
SPRT_SAME(IPV6_LEAVE_ANYCAST);
#endif
#ifdef IPV6_MULTICAST_ALL
SPRT_SAME(IPV6_MULTICAST_ALL);
#endif
#ifdef IPV6_ROUTER_ALERT_ISOLATE
SPRT_SAME(IPV6_ROUTER_ALERT_ISOLATE);
#endif
#ifdef IPV6_IPSEC_POLICY
SPRT_SAME(IPV6_IPSEC_POLICY);
#endif
#ifdef IPV6_XFRM_POLICY
SPRT_SAME(IPV6_XFRM_POLICY);
#endif
#ifdef IPV6_HDRINCL
SPRT_SAME(IPV6_HDRINCL);
#endif
#ifdef IPV6_RECVPKTINFO
SPRT_SAME(IPV6_RECVPKTINFO);
#endif
#ifdef IPV6_PKTINFO
SPRT_SAME(IPV6_PKTINFO);
#endif
#ifdef IPV6_RECVHOPLIMIT
SPRT_SAME(IPV6_RECVHOPLIMIT);
#endif
#ifdef IPV6_HOPLIMIT
SPRT_SAME(IPV6_HOPLIMIT);
#endif
#ifdef IPV6_RECVHOPOPTS
SPRT_SAME(IPV6_RECVHOPOPTS);
#endif
#ifdef IPV6_HOPOPTS
SPRT_SAME(IPV6_HOPOPTS);
#endif
#ifdef IPV6_RTHDRDSTOPTS
SPRT_SAME(IPV6_RTHDRDSTOPTS);
#endif
#ifdef IPV6_RECVRTHDR
SPRT_SAME(IPV6_RECVRTHDR);
#endif
#ifdef IPV6_RTHDR
SPRT_SAME(IPV6_RTHDR);
#endif
#ifdef IPV6_RECVDSTOPTS
SPRT_SAME(IPV6_RECVDSTOPTS);
#endif
#ifdef IPV6_DSTOPTS
SPRT_SAME(IPV6_DSTOPTS);
#endif
#ifdef IPV6_RECVPATHMTU
SPRT_SAME(IPV6_RECVPATHMTU);
#endif
#ifdef IPV6_PATHMTU
SPRT_SAME(IPV6_PATHMTU);
#endif
#ifdef IPV6_DONTFRAG
SPRT_SAME(IPV6_DONTFRAG);
#endif
#ifdef IPV6_RECVTCLASS
SPRT_SAME(IPV6_RECVTCLASS);
#endif
#ifdef IPV6_TCLASS
SPRT_SAME(IPV6_TCLASS);
#endif
#ifdef IPV6_AUTOFLOWLABEL
SPRT_SAME(IPV6_AUTOFLOWLABEL);
#endif
#ifdef IPV6_ADDR_PREFERENCES
SPRT_SAME(IPV6_ADDR_PREFERENCES);
#endif
#ifdef IPV6_MINHOPCOUNT
SPRT_SAME(IPV6_MINHOPCOUNT);
#endif
#ifdef IPV6_ORIGDSTADDR
SPRT_SAME(IPV6_ORIGDSTADDR);
#endif
#ifdef IPV6_RECVORIGDSTADDR
SPRT_SAME(IPV6_RECVORIGDSTADDR);
#endif
#ifdef IPV6_TRANSPARENT
SPRT_SAME(IPV6_TRANSPARENT);
#endif
#ifdef IPV6_UNICAST_IF
SPRT_SAME(IPV6_UNICAST_IF);
#endif
#ifdef IPV6_RECVFRAGSIZE
SPRT_SAME(IPV6_RECVFRAGSIZE);
#endif
#ifdef IPV6_FREEBIND
SPRT_SAME(IPV6_FREEBIND);
#endif
#ifdef IPV6_PROTECTION_LEVEL
SPRT_SAME(IPV6_PROTECTION_LEVEL);
#endif
#ifdef IPV6_RECVIF
SPRT_SAME(IPV6_RECVIF);
#endif
#ifdef IPV6_RECVDSTADDR
SPRT_SAME(IPV6_RECVDSTADDR);
#endif
#ifdef IPV6_IFLIST
SPRT_SAME(IPV6_IFLIST);
#endif
#ifdef IPV6_ADD_IFLIST
SPRT_SAME(IPV6_ADD_IFLIST);
#endif
#ifdef IPV6_DEL_IFLIST
SPRT_SAME(IPV6_DEL_IFLIST);
#endif
#ifdef IPV6_GET_IFLIST
SPRT_SAME(IPV6_GET_IFLIST);
#endif
#ifdef IPV6_ECN
SPRT_SAME(IPV6_ECN);
#endif
#ifdef IPV6_RECVECN
SPRT_SAME(IPV6_RECVECN);
#endif
#ifdef IPV6_PKTINFO_EX
SPRT_SAME(IPV6_PKTINFO_EX);
#endif
#ifdef IPV6_WFP_REDIRECT_RECORDS
SPRT_SAME(IPV6_WFP_REDIRECT_RECORDS);
#endif
#ifdef IPV6_WFP_REDIRECT_CONTEXT
SPRT_SAME(IPV6_WFP_REDIRECT_CONTEXT);
#endif
#ifdef IPV6_NRT_INTERFACE
SPRT_SAME(IPV6_NRT_INTERFACE);
#endif
#ifdef IPV6_USER_MTU
SPRT_SAME(IPV6_USER_MTU);
#endif
#ifdef IPV6_ADD_MEMBERSHIP
SPRT_SAME(IPV6_ADD_MEMBERSHIP);
#endif
#ifdef IPV6_DROP_MEMBERSHIP
SPRT_SAME(IPV6_DROP_MEMBERSHIP);
#endif
#ifdef IPV6_RXHOPOPTS
SPRT_SAME(IPV6_RXHOPOPTS);
#endif
#ifdef IPV6_RXDSTOPTS
SPRT_SAME(IPV6_RXDSTOPTS);
#endif
#ifdef IPV6_PMTUDISC_DONT
SPRT_SAME(IPV6_PMTUDISC_DONT);
#endif
#ifdef IPV6_PMTUDISC_WANT
SPRT_SAME(IPV6_PMTUDISC_WANT);
#endif
#ifdef IPV6_PMTUDISC_DO
SPRT_SAME(IPV6_PMTUDISC_DO);
#endif
#ifdef IPV6_PMTUDISC_PROBE
SPRT_SAME(IPV6_PMTUDISC_PROBE);
#endif
#ifdef IPV6_PMTUDISC_INTERFACE
SPRT_SAME(IPV6_PMTUDISC_INTERFACE);
#endif
#ifdef IPV6_PMTUDISC_OMIT
SPRT_SAME(IPV6_PMTUDISC_OMIT);
#endif
#ifdef IPV6_PREFER_SRC_TMP
SPRT_SAME(IPV6_PREFER_SRC_TMP);
#endif
#ifdef IPV6_PREFER_SRC_PUBLIC
SPRT_SAME(IPV6_PREFER_SRC_PUBLIC);
#endif
#ifdef IPV6_PREFER_SRC_PUBTMP_DEFAULT
SPRT_SAME(IPV6_PREFER_SRC_PUBTMP_DEFAULT);
#endif
#ifdef IPV6_PREFER_SRC_COA
SPRT_SAME(IPV6_PREFER_SRC_COA);
#endif
#ifdef IPV6_PREFER_SRC_HOME
SPRT_SAME(IPV6_PREFER_SRC_HOME);
#endif
#ifdef IPV6_PREFER_SRC_CGA
SPRT_SAME(IPV6_PREFER_SRC_CGA);
#endif
#ifdef IPV6_PREFER_SRC_NONCGA
SPRT_SAME(IPV6_PREFER_SRC_NONCGA);
#endif
#ifdef IPV6_RTHDR_LOOSE
SPRT_SAME(IPV6_RTHDR_LOOSE);
#endif
#ifdef IPV6_RTHDR_STRICT
SPRT_SAME(IPV6_RTHDR_STRICT);
#endif
#ifdef IPV6_RTHDR_TYPE_0
SPRT_SAME(IPV6_RTHDR_TYPE_0);
#endif

// --- MCAST_* group membership (Winsock macros; enum EXCLUDE/INCLUDE skipped) ---
#ifdef MCAST_JOIN_GROUP
SPRT_SAME(MCAST_JOIN_GROUP);
#endif
#ifdef MCAST_LEAVE_GROUP
SPRT_SAME(MCAST_LEAVE_GROUP);
#endif
#ifdef MCAST_BLOCK_SOURCE
SPRT_SAME(MCAST_BLOCK_SOURCE);
#endif
#ifdef MCAST_UNBLOCK_SOURCE
SPRT_SAME(MCAST_UNBLOCK_SOURCE);
#endif
#ifdef MCAST_JOIN_SOURCE_GROUP
SPRT_SAME(MCAST_JOIN_SOURCE_GROUP);
#endif
#ifdef MCAST_LEAVE_SOURCE_GROUP
SPRT_SAME(MCAST_LEAVE_SOURCE_GROUP);
#endif

// --- TCP options (IPPROTO_TCP level); guarded on the Winsock macro -----------
#ifdef TCP_AO_ADD_KEY
SPRT_SAME(TCP_AO_ADD_KEY);
#endif
#ifdef TCP_AO_DEL_KEY
SPRT_SAME(TCP_AO_DEL_KEY);
#endif
#ifdef TCP_AO_GET_KEYS
SPRT_SAME(TCP_AO_GET_KEYS);
#endif
#ifdef TCP_AO_INFO
SPRT_SAME(TCP_AO_INFO);
#endif
#ifdef TCP_AO_KEYF_EXCLUDE_OPT
SPRT_SAME(TCP_AO_KEYF_EXCLUDE_OPT);
#endif
#ifdef TCP_AO_KEYF_IFINDEX
SPRT_SAME(TCP_AO_KEYF_IFINDEX);
#endif
#ifdef TCP_AO_MAXKEYLEN
SPRT_SAME(TCP_AO_MAXKEYLEN);
#endif
#ifdef TCP_AO_REPAIR
SPRT_SAME(TCP_AO_REPAIR);
#endif
#ifdef TCP_ATMARK
SPRT_SAME(TCP_ATMARK);
#endif
#ifdef TCP_CA_CWR
SPRT_SAME(TCP_CA_CWR);
#endif
#ifdef TCP_CA_D
SPRT_SAME(TCP_CA_D);
#endif
#ifdef TCP_CA_L
SPRT_SAME(TCP_CA_L);
#endif
#ifdef TCP_CA_O
SPRT_SAME(TCP_CA_O);
#endif
#ifdef TCP_CA_R
SPRT_SAME(TCP_CA_R);
#endif
#ifdef TCP_CC_INFO
SPRT_SAME(TCP_CC_INFO);
#endif
#ifdef TCP_CLIENT_SND_WND
SPRT_SAME(TCP_CLIENT_SND_WND);
#endif
#ifdef TCP_CM_INQ
SPRT_SAME(TCP_CM_INQ);
#endif
#ifdef TCP_CONGESTION
SPRT_SAME(TCP_CONGESTION);
#endif
#ifdef TCP_CONGESTION_ALGORITHM
SPRT_SAME(TCP_CONGESTION_ALGORITHM);
#endif
#ifdef TCP_CONNECTION_INFO
SPRT_SAME(TCP_CONNECTION_INFO);
#endif
#ifdef TCP_CONNECTIONTIMEOUT
SPRT_SAME(TCP_CONNECTIONTIMEOUT);
#endif
#ifdef TCP_COOKIE_IN_ALWAYS
SPRT_SAME(TCP_COOKIE_IN_ALWAYS);
#endif
#ifdef TCP_COOKIE_MAX
SPRT_SAME(TCP_COOKIE_MAX);
#endif
#ifdef TCP_COOKIE_MIN
SPRT_SAME(TCP_COOKIE_MIN);
#endif
#ifdef TCP_COOKIE_OUT_NEVER
SPRT_SAME(TCP_COOKIE_OUT_NEVER);
#endif
#ifdef TCP_COOKIE_PAIR_SIZE
SPRT_SAME(TCP_COOKIE_PAIR_SIZE);
#endif
#ifdef TCP_COOKIE_TRANSACTIONS
SPRT_SAME(TCP_COOKIE_TRANSACTIONS);
#endif
#ifdef TCP_CORK
SPRT_SAME(TCP_CORK);
#endif
#ifdef TCP_DEFER_ACCEPT
SPRT_SAME(TCP_DEFER_ACCEPT);
#endif
#ifdef TCP_DELAY_FIN_ACK
SPRT_SAME(TCP_DELAY_FIN_ACK);
#endif
#ifdef TCP_ENABLE_ECN
SPRT_SAME(TCP_ENABLE_ECN);
#endif
#ifdef TCP_EXPEDITED_1122
SPRT_SAME(TCP_EXPEDITED_1122);
#endif
#ifdef TCP_FAIL_CONNECT_ON_ICMP_ERROR
SPRT_SAME(TCP_FAIL_CONNECT_ON_ICMP_ERROR);
#endif
#ifdef TCP_FASTOPEN
SPRT_SAME(TCP_FASTOPEN);
#endif
#ifdef TCP_FASTOPEN_CONNECT
SPRT_SAME(TCP_FASTOPEN_CONNECT);
#endif
#ifdef TCP_FASTOPEN_KEY
SPRT_SAME(TCP_FASTOPEN_KEY);
#endif
#ifdef TCP_FASTOPEN_NO_COOKIE
SPRT_SAME(TCP_FASTOPEN_NO_COOKIE);
#endif
#ifdef TCP_H
SPRT_SAME(TCP_H);
#endif
#ifdef TCP_H_
SPRT_SAME(TCP_H_);
#endif
#ifdef TCP_ICMP_ERROR_INFO
SPRT_SAME(TCP_ICMP_ERROR_INFO);
#endif
#ifdef TCP_INFO
SPRT_SAME(TCP_INFO);
#endif
#ifdef TCP_INITIAL_RTO
SPRT_SAME(TCP_INITIAL_RTO);
#endif
#ifdef TCP_INITIAL_RTO_DEFAULT_MAX_SYN_RETRANSMISSIONS
SPRT_SAME(TCP_INITIAL_RTO_DEFAULT_MAX_SYN_RETRANSMISSIONS);
#endif
#ifdef TCP_INITIAL_RTO_DEFAULT_RTT
SPRT_SAME(TCP_INITIAL_RTO_DEFAULT_RTT);
#endif
#ifdef TCP_INITIAL_RTO_NO_SYN_RETRANSMISSIONS
SPRT_SAME(TCP_INITIAL_RTO_NO_SYN_RETRANSMISSIONS);
#endif
#ifdef TCP_INITIAL_RTO_UNSPECIFIED_MAX_SYN_RETRANSMISSIONS
SPRT_SAME(TCP_INITIAL_RTO_UNSPECIFIED_MAX_SYN_RETRANSMISSIONS);
#endif
#ifdef TCP_INITIAL_RTO_UNSPECIFIED_RTT
SPRT_SAME(TCP_INITIAL_RTO_UNSPECIFIED_RTT);
#endif
#ifdef TCP_INQ
SPRT_SAME(TCP_INQ);
#endif
#ifdef TCP_IPV4
SPRT_SAME(TCP_IPV4);
#endif
#ifdef TCP_IPV6
SPRT_SAME(TCP_IPV6);
#endif
#ifdef TCP_IS_MPTCP
SPRT_SAME(TCP_IS_MPTCP);
#endif
#ifdef TCP_KEEPALIVE
SPRT_SAME(TCP_KEEPALIVE);
#endif
#ifdef TCP_KEEPCNT
SPRT_SAME(TCP_KEEPCNT);
#endif
#ifdef TCP_KEEPIDLE
SPRT_SAME(TCP_KEEPIDLE);
#endif
#ifdef TCP_KEEPINTVL
SPRT_SAME(TCP_KEEPINTVL);
#endif
#ifdef TCP_LINGER2
SPRT_SAME(TCP_LINGER2);
#endif
#ifdef TCP_MAXHLEN
SPRT_SAME(TCP_MAXHLEN);
#endif
#ifdef TCP_MAXOLEN
SPRT_SAME(TCP_MAXOLEN);
#endif
#ifdef TCP_MAXRT
SPRT_SAME(TCP_MAXRT);
#endif
#ifdef TCP_MAXRTMS
SPRT_SAME(TCP_MAXRTMS);
#endif
#ifdef TCP_MAX_SACK
SPRT_SAME(TCP_MAX_SACK);
#endif
#ifdef TCP_MAXSEG
SPRT_SAME(TCP_MAXSEG);
#endif
#ifdef TCP_MAXWIN
SPRT_SAME(TCP_MAXWIN);
#endif
#ifdef TCP_MAX_WINSHIFT
SPRT_SAME(TCP_MAX_WINSHIFT);
#endif
#ifdef TCP_MD5SIG
SPRT_SAME(TCP_MD5SIG);
#endif
#ifdef TCP_MD5SIG_EXT
SPRT_SAME(TCP_MD5SIG_EXT);
#endif
#ifdef TCP_MD5SIG_FLAG_IFINDEX
SPRT_SAME(TCP_MD5SIG_FLAG_IFINDEX);
#endif
#ifdef TCP_MD5SIG_FLAG_PREFIX
SPRT_SAME(TCP_MD5SIG_FLAG_PREFIX);
#endif
#ifdef TCP_MD5SIG_MAXKEYLEN
SPRT_SAME(TCP_MD5SIG_MAXKEYLEN);
#endif
#ifdef TCP_MINMSS
SPRT_SAME(TCP_MINMSS);
#endif
#ifdef TCP_MSS
SPRT_SAME(TCP_MSS);
#endif
#ifdef TCP_MSS_DEFAULT
SPRT_SAME(TCP_MSS_DEFAULT);
#endif
#ifdef TCP_MSS_DESIRED
SPRT_SAME(TCP_MSS_DESIRED);
#endif
#ifdef TCP_NODELAY
SPRT_SAME(TCP_NODELAY);
#endif
#ifdef TCP_NOOPT
SPRT_SAME(TCP_NOOPT);
#endif
#ifdef TCP_NOPUSH
SPRT_SAME(TCP_NOPUSH);
#endif
#ifdef TCP_NOSYNRETRIES
SPRT_SAME(TCP_NOSYNRETRIES);
#endif
#ifdef TCP_NOTSENT_LOWAT
SPRT_SAME(TCP_NOTSENT_LOWAT);
#endif
#ifdef TCP_NOURG
SPRT_SAME(TCP_NOURG);
#endif
#ifdef TCP_OFFLOAD_NO_PREFERENCE
SPRT_SAME(TCP_OFFLOAD_NO_PREFERENCE);
#endif
#ifdef TCP_OFFLOAD_NOT_PREFERRED
SPRT_SAME(TCP_OFFLOAD_NOT_PREFERRED);
#endif
#ifdef TCP_OFFLOAD_PREFERENCE
SPRT_SAME(TCP_OFFLOAD_PREFERENCE);
#endif
#ifdef TCP_OFFLOAD_PREFERRED
SPRT_SAME(TCP_OFFLOAD_PREFERRED);
#endif
#ifdef TCP_QUEUE_SEQ
SPRT_SAME(TCP_QUEUE_SEQ);
#endif
#ifdef TCP_QUICKACK
SPRT_SAME(TCP_QUICKACK);
#endif
#ifdef TCP_RECEIVE_ZEROCOPY_FLAG_TLB_CLEAN_HINT
SPRT_SAME(TCP_RECEIVE_ZEROCOPY_FLAG_TLB_CLEAN_HINT);
#endif
#ifdef TCP_REPAIR
SPRT_SAME(TCP_REPAIR);
#endif
#ifdef TCP_REPAIR_OFF
SPRT_SAME(TCP_REPAIR_OFF);
#endif
#ifdef TCP_REPAIR_OFF_NO_WP
SPRT_SAME(TCP_REPAIR_OFF_NO_WP);
#endif
#ifdef TCP_REPAIR_ON
SPRT_SAME(TCP_REPAIR_ON);
#endif
#ifdef TCP_REPAIR_OPTIONS
SPRT_SAME(TCP_REPAIR_OPTIONS);
#endif
#ifdef TCP_REPAIR_QUEUE
SPRT_SAME(TCP_REPAIR_QUEUE);
#endif
#ifdef TCP_REPAIR_WINDOW
SPRT_SAME(TCP_REPAIR_WINDOW);
#endif
#ifdef TCP_RXT_CONNDROPTIME
SPRT_SAME(TCP_RXT_CONNDROPTIME);
#endif
#ifdef TCP_RXT_FINDROP
SPRT_SAME(TCP_RXT_FINDROP);
#endif
#ifdef TCP_SAVED_SYN
SPRT_SAME(TCP_SAVED_SYN);
#endif
#ifdef TCP_SAVE_SYN
SPRT_SAME(TCP_SAVE_SYN);
#endif
#ifdef TCP_S_DATA_IN
SPRT_SAME(TCP_S_DATA_IN);
#endif
#ifdef TCP_S_DATA_OUT
SPRT_SAME(TCP_S_DATA_OUT);
#endif
#ifdef TCP_SENDMOREACKS
SPRT_SAME(TCP_SENDMOREACKS);
#endif
#ifdef TCP_SET_ACK_FREQUENCY
SPRT_SAME(TCP_SET_ACK_FREQUENCY);
#endif
#ifdef TCP_SET_ICW
SPRT_SAME(TCP_SET_ICW);
#endif
#ifdef TCP_STDURG
SPRT_SAME(TCP_STDURG);
#endif
#ifdef TCP_SYNCNT
SPRT_SAME(TCP_SYNCNT);
#endif
#ifdef TCP_THIN_DUPACK
SPRT_SAME(TCP_THIN_DUPACK);
#endif
#ifdef TCP_THIN_LINEAR_TIMEOUTS
SPRT_SAME(TCP_THIN_LINEAR_TIMEOUTS);
#endif
#ifdef TCP_TIMESTAMP
SPRT_SAME(TCP_TIMESTAMP);
#endif
#ifdef TCP_TIMESTAMPS
SPRT_SAME(TCP_TIMESTAMPS);
#endif
#ifdef TCP_TX_DELAY
SPRT_SAME(TCP_TX_DELAY);
#endif
#ifdef TCP_ULP
SPRT_SAME(TCP_ULP);
#endif
#ifdef TCP_USER_TIMEOUT
SPRT_SAME(TCP_USER_TIMEOUT);
#endif
#ifdef TCP_WINDOW_CLAMP
SPRT_SAME(TCP_WINDOW_CLAMP);
#endif
#ifdef TCP_ZEROCOPY_RECEIVE
SPRT_SAME(TCP_ZEROCOPY_RECEIVE);
#endif
