// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/user_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/user_api.h>
#include "abi_check.h"

#include <windows.h> // winuser.h: WNDCLASSW, WINDOWPOS, MINMAXINFO, MENUITEMINFOW, ...

// === KF_* (keystroke flags) ================================================
SPRT_CONST(KF_EXTENDED);
SPRT_CONST(KF_DLGMODE);
SPRT_CONST(KF_MENUMODE);
SPRT_CONST(KF_ALTDOWN);
SPRT_CONST(KF_REPEAT);
SPRT_CONST(KF_UP);

// === VK_* (virtual key codes) ==============================================
SPRT_CONST(VK_LBUTTON);
SPRT_CONST(VK_RBUTTON);
SPRT_CONST(VK_CANCEL);
SPRT_CONST(VK_MBUTTON);
SPRT_CONST(VK_BACK);
SPRT_CONST(VK_TAB);
SPRT_CONST(VK_CLEAR);
SPRT_CONST(VK_RETURN);
SPRT_CONST(VK_SHIFT);
SPRT_CONST(VK_CONTROL);
SPRT_CONST(VK_MENU);
SPRT_CONST(VK_PAUSE);
SPRT_CONST(VK_CAPITAL);
SPRT_CONST(VK_KANA);
SPRT_CONST(VK_HANGEUL);
SPRT_CONST(VK_HANGUL);
SPRT_CONST(VK_IME_ON);
SPRT_CONST(VK_JUNJA);
SPRT_CONST(VK_FINAL);
SPRT_CONST(VK_HANJA);
SPRT_CONST(VK_KANJI);
SPRT_CONST(VK_IME_OFF);
SPRT_CONST(VK_ESCAPE);
SPRT_CONST(VK_CONVERT);
SPRT_CONST(VK_NONCONVERT);
SPRT_CONST(VK_ACCEPT);
SPRT_CONST(VK_MODECHANGE);
SPRT_CONST(VK_SPACE);
SPRT_CONST(VK_PRIOR);
SPRT_CONST(VK_NEXT);
SPRT_CONST(VK_END);
SPRT_CONST(VK_HOME);
SPRT_CONST(VK_LEFT);
SPRT_CONST(VK_UP);
SPRT_CONST(VK_RIGHT);
SPRT_CONST(VK_DOWN);
SPRT_CONST(VK_SELECT);
SPRT_CONST(VK_PRINT);
SPRT_CONST(VK_EXECUTE);
SPRT_CONST(VK_SNAPSHOT);
SPRT_CONST(VK_INSERT);
SPRT_CONST(VK_DELETE);
SPRT_CONST(VK_HELP);
SPRT_CONST(VK_LWIN);
SPRT_CONST(VK_RWIN);
SPRT_CONST(VK_APPS);
SPRT_CONST(VK_SLEEP);
SPRT_CONST(VK_NUMPAD0);
SPRT_CONST(VK_NUMPAD1);
SPRT_CONST(VK_NUMPAD2);
SPRT_CONST(VK_NUMPAD3);
SPRT_CONST(VK_NUMPAD4);
SPRT_CONST(VK_NUMPAD5);
SPRT_CONST(VK_NUMPAD6);
SPRT_CONST(VK_NUMPAD7);
SPRT_CONST(VK_NUMPAD8);
SPRT_CONST(VK_NUMPAD9);
SPRT_CONST(VK_MULTIPLY);
SPRT_CONST(VK_ADD);
SPRT_CONST(VK_SEPARATOR);
SPRT_CONST(VK_SUBTRACT);
SPRT_CONST(VK_DECIMAL);
SPRT_CONST(VK_DIVIDE);
SPRT_CONST(VK_F1);
SPRT_CONST(VK_F2);
SPRT_CONST(VK_F3);
SPRT_CONST(VK_F4);
SPRT_CONST(VK_F5);
SPRT_CONST(VK_F6);
SPRT_CONST(VK_F7);
SPRT_CONST(VK_F8);
SPRT_CONST(VK_F9);
SPRT_CONST(VK_F10);
SPRT_CONST(VK_F11);
SPRT_CONST(VK_F12);
SPRT_CONST(VK_F13);
SPRT_CONST(VK_F14);
SPRT_CONST(VK_F15);
SPRT_CONST(VK_F16);
SPRT_CONST(VK_F17);
SPRT_CONST(VK_F18);
SPRT_CONST(VK_F19);
SPRT_CONST(VK_F20);
SPRT_CONST(VK_F21);
SPRT_CONST(VK_F22);
SPRT_CONST(VK_F23);
SPRT_CONST(VK_F24);
SPRT_CONST(VK_NUMLOCK);
SPRT_CONST(VK_SCROLL);
SPRT_CONST(VK_LSHIFT);
SPRT_CONST(VK_RSHIFT);
SPRT_CONST(VK_LCONTROL);
SPRT_CONST(VK_RCONTROL);
SPRT_CONST(VK_LMENU);
SPRT_CONST(VK_RMENU);
SPRT_CONST(VK_PROCESSKEY);

// === XBUTTON* ==============================================================
SPRT_CONST(XBUTTON1);
SPRT_CONST(XBUTTON2);

// === SPI_* (SystemParametersInfo) ==========================================
SPRT_CONST(SPI_GETBEEP);
SPRT_CONST(SPI_SETBEEP);
SPRT_CONST(SPI_GETMOUSE);
SPRT_CONST(SPI_SETMOUSE);
SPRT_CONST(SPI_GETBORDER);
SPRT_CONST(SPI_SETBORDER);
SPRT_CONST(SPI_GETKEYBOARDSPEED);
SPRT_CONST(SPI_SETKEYBOARDSPEED);
SPRT_CONST(SPI_LANGDRIVER);
SPRT_CONST(SPI_ICONHORIZONTALSPACING);
SPRT_CONST(SPI_GETSCREENSAVETIMEOUT);
SPRT_CONST(SPI_SETSCREENSAVETIMEOUT);
SPRT_CONST(SPI_GETSCREENSAVEACTIVE);
SPRT_CONST(SPI_SETSCREENSAVEACTIVE);
SPRT_CONST(SPI_GETGRIDGRANULARITY);
SPRT_CONST(SPI_SETGRIDGRANULARITY);
SPRT_CONST(SPI_SETDESKWALLPAPER);
SPRT_CONST(SPI_SETDESKPATTERN);
SPRT_CONST(SPI_GETKEYBOARDDELAY);
SPRT_CONST(SPI_SETKEYBOARDDELAY);
SPRT_CONST(SPI_ICONVERTICALSPACING);
SPRT_CONST(SPI_GETICONTITLEWRAP);
SPRT_CONST(SPI_SETICONTITLEWRAP);
SPRT_CONST(SPI_GETMENUDROPALIGNMENT);
SPRT_CONST(SPI_SETMENUDROPALIGNMENT);
SPRT_CONST(SPI_SETDOUBLECLKWIDTH);
SPRT_CONST(SPI_SETDOUBLECLKHEIGHT);
SPRT_CONST(SPI_GETICONTITLELOGFONT);
SPRT_CONST(SPI_SETDOUBLECLICKTIME);
SPRT_CONST(SPI_SETMOUSEBUTTONSWAP);
SPRT_CONST(SPI_SETICONTITLELOGFONT);
SPRT_CONST(SPI_GETFASTTASKSWITCH);
SPRT_CONST(SPI_SETFASTTASKSWITCH);
SPRT_CONST(SPI_SETDRAGFULLWINDOWS);
SPRT_CONST(SPI_GETDRAGFULLWINDOWS);
SPRT_CONST(SPI_GETNONCLIENTMETRICS);
SPRT_CONST(SPI_SETNONCLIENTMETRICS);
SPRT_CONST(SPI_GETMINIMIZEDMETRICS);
SPRT_CONST(SPI_SETMINIMIZEDMETRICS);
SPRT_CONST(SPI_GETICONMETRICS);
SPRT_CONST(SPI_SETICONMETRICS);
SPRT_CONST(SPI_SETWORKAREA);
SPRT_CONST(SPI_GETWORKAREA);
SPRT_CONST(SPI_SETPENWINDOWS);
SPRT_CONST(SPI_GETHIGHCONTRAST);
SPRT_CONST(SPI_SETHIGHCONTRAST);
SPRT_CONST(SPI_GETKEYBOARDPREF);
SPRT_CONST(SPI_SETKEYBOARDPREF);
SPRT_CONST(SPI_GETSCREENREADER);
SPRT_CONST(SPI_SETSCREENREADER);
SPRT_CONST(SPI_GETANIMATION);
SPRT_CONST(SPI_SETANIMATION);
SPRT_CONST(SPI_GETFONTSMOOTHING);
SPRT_CONST(SPI_SETFONTSMOOTHING);
SPRT_CONST(SPI_SETDRAGWIDTH);
SPRT_CONST(SPI_SETDRAGHEIGHT);
SPRT_CONST(SPI_SETHANDHELD);
SPRT_CONST(SPI_GETLOWPOWERTIMEOUT);
SPRT_CONST(SPI_GETPOWEROFFTIMEOUT);
SPRT_CONST(SPI_SETLOWPOWERTIMEOUT);
SPRT_CONST(SPI_SETPOWEROFFTIMEOUT);
SPRT_CONST(SPI_GETLOWPOWERACTIVE);
SPRT_CONST(SPI_GETPOWEROFFACTIVE);
SPRT_CONST(SPI_SETLOWPOWERACTIVE);
SPRT_CONST(SPI_SETPOWEROFFACTIVE);
SPRT_CONST(SPI_SETCURSORS);
SPRT_CONST(SPI_SETICONS);
SPRT_CONST(SPI_GETDEFAULTINPUTLANG);
SPRT_CONST(SPI_SETDEFAULTINPUTLANG);
SPRT_CONST(SPI_SETLANGTOGGLE);
SPRT_CONST(SPI_GETWINDOWSEXTENSION);
SPRT_CONST(SPI_SETMOUSETRAILS);
SPRT_CONST(SPI_GETMOUSETRAILS);
SPRT_CONST(SPI_SETSCREENSAVERRUNNING);
SPRT_CONST(SPI_SCREENSAVERRUNNING);
SPRT_CONST(SPI_GETFILTERKEYS);
SPRT_CONST(SPI_SETFILTERKEYS);
SPRT_CONST(SPI_GETTOGGLEKEYS);
SPRT_CONST(SPI_SETTOGGLEKEYS);
SPRT_CONST(SPI_GETMOUSEKEYS);
SPRT_CONST(SPI_SETMOUSEKEYS);
SPRT_CONST(SPI_GETSHOWSOUNDS);
SPRT_CONST(SPI_SETSHOWSOUNDS);
SPRT_CONST(SPI_GETSTICKYKEYS);
SPRT_CONST(SPI_SETSTICKYKEYS);
SPRT_CONST(SPI_GETACCESSTIMEOUT);
SPRT_CONST(SPI_SETACCESSTIMEOUT);
SPRT_CONST(SPI_GETSERIALKEYS);
SPRT_CONST(SPI_SETSERIALKEYS);
SPRT_CONST(SPI_GETSOUNDSENTRY);
SPRT_CONST(SPI_SETSOUNDSENTRY);
SPRT_CONST(SPI_GETSNAPTODEFBUTTON);
SPRT_CONST(SPI_SETSNAPTODEFBUTTON);
SPRT_CONST(SPI_GETMOUSEHOVERWIDTH);
SPRT_CONST(SPI_SETMOUSEHOVERWIDTH);
SPRT_CONST(SPI_GETMOUSEHOVERHEIGHT);
SPRT_CONST(SPI_SETMOUSEHOVERHEIGHT);
SPRT_CONST(SPI_GETMOUSEHOVERTIME);
SPRT_CONST(SPI_SETMOUSEHOVERTIME);
SPRT_CONST(SPI_GETWHEELSCROLLLINES);
SPRT_CONST(SPI_SETWHEELSCROLLLINES);
SPRT_CONST(SPI_GETMENUSHOWDELAY);
SPRT_CONST(SPI_SETMENUSHOWDELAY);
SPRT_CONST(SPI_GETWHEELSCROLLCHARS);
SPRT_CONST(SPI_SETWHEELSCROLLCHARS);
SPRT_CONST(SPI_GETSHOWIMEUI);
SPRT_CONST(SPI_SETSHOWIMEUI);
SPRT_CONST(SPI_GETMOUSESPEED);
SPRT_CONST(SPI_SETMOUSESPEED);
SPRT_CONST(SPI_GETSCREENSAVERRUNNING);
SPRT_CONST(SPI_GETDESKWALLPAPER);
SPRT_CONST(SPI_GETAUDIODESCRIPTION);
SPRT_CONST(SPI_SETAUDIODESCRIPTION);
SPRT_CONST(SPI_GETSCREENSAVESECURE);
SPRT_CONST(SPI_SETSCREENSAVESECURE);
SPRT_CONST(SPI_GETHUNGAPPTIMEOUT);
SPRT_CONST(SPI_SETHUNGAPPTIMEOUT);
SPRT_CONST(SPI_GETWAITTOKILLTIMEOUT);
SPRT_CONST(SPI_SETWAITTOKILLTIMEOUT);
SPRT_CONST(SPI_GETWAITTOKILLSERVICETIMEOUT);
SPRT_CONST(SPI_SETWAITTOKILLSERVICETIMEOUT);
SPRT_CONST(SPI_GETMOUSEDOCKTHRESHOLD);
SPRT_CONST(SPI_SETMOUSEDOCKTHRESHOLD);
SPRT_CONST(SPI_GETPENDOCKTHRESHOLD);
SPRT_CONST(SPI_SETPENDOCKTHRESHOLD);
SPRT_CONST(SPI_GETWINARRANGING);
SPRT_CONST(SPI_SETWINARRANGING);
SPRT_CONST(SPI_GETMOUSEDRAGOUTTHRESHOLD);
SPRT_CONST(SPI_SETMOUSEDRAGOUTTHRESHOLD);
SPRT_CONST(SPI_GETPENDRAGOUTTHRESHOLD);
SPRT_CONST(SPI_SETPENDRAGOUTTHRESHOLD);
SPRT_CONST(SPI_GETMOUSESIDEMOVETHRESHOLD);
SPRT_CONST(SPI_SETMOUSESIDEMOVETHRESHOLD);
SPRT_CONST(SPI_GETPENSIDEMOVETHRESHOLD);
SPRT_CONST(SPI_SETPENSIDEMOVETHRESHOLD);
SPRT_CONST(SPI_GETDRAGFROMMAXIMIZE);
SPRT_CONST(SPI_SETDRAGFROMMAXIMIZE);
SPRT_CONST(SPI_GETSNAPSIZING);
SPRT_CONST(SPI_SETSNAPSIZING);
SPRT_CONST(SPI_GETDOCKMOVING);
SPRT_CONST(SPI_SETDOCKMOVING);
SPRT_CONST(SPI_GETLOGICALDPIOVERRIDE);
SPRT_CONST(SPI_SETLOGICALDPIOVERRIDE);
SPRT_CONST(SPI_GETTOUCHPADPARAMETERS);
SPRT_CONST(SPI_SETTOUCHPADPARAMETERS);
SPRT_CONST(SPI_GETACTIVEWINDOWTRACKING);
SPRT_CONST(SPI_SETACTIVEWINDOWTRACKING);
SPRT_CONST(SPI_GETMENUANIMATION);
SPRT_CONST(SPI_SETMENUANIMATION);
SPRT_CONST(SPI_GETCOMBOBOXANIMATION);
SPRT_CONST(SPI_SETCOMBOBOXANIMATION);
SPRT_CONST(SPI_GETLISTBOXSMOOTHSCROLLING);
SPRT_CONST(SPI_SETLISTBOXSMOOTHSCROLLING);
SPRT_CONST(SPI_GETGRADIENTCAPTIONS);
SPRT_CONST(SPI_SETGRADIENTCAPTIONS);
SPRT_CONST(SPI_GETKEYBOARDCUES);
SPRT_CONST(SPI_SETKEYBOARDCUES);
SPRT_CONST(SPI_GETMENUUNDERLINES);
SPRT_CONST(SPI_SETMENUUNDERLINES);
SPRT_CONST(SPI_GETACTIVEWNDTRKZORDER);
SPRT_CONST(SPI_SETACTIVEWNDTRKZORDER);
SPRT_CONST(SPI_GETHOTTRACKING);
SPRT_CONST(SPI_SETHOTTRACKING);
SPRT_CONST(SPI_GETMENUFADE);
SPRT_CONST(SPI_SETMENUFADE);
SPRT_CONST(SPI_GETSELECTIONFADE);
SPRT_CONST(SPI_SETSELECTIONFADE);
SPRT_CONST(SPI_GETTOOLTIPANIMATION);
SPRT_CONST(SPI_SETTOOLTIPANIMATION);
SPRT_CONST(SPI_GETTOOLTIPFADE);
SPRT_CONST(SPI_SETTOOLTIPFADE);
SPRT_CONST(SPI_GETCURSORSHADOW);
SPRT_CONST(SPI_SETCURSORSHADOW);
SPRT_CONST(SPI_GETMOUSESONAR);
SPRT_CONST(SPI_SETMOUSESONAR);
SPRT_CONST(SPI_GETMOUSECLICKLOCK);
SPRT_CONST(SPI_SETMOUSECLICKLOCK);
SPRT_CONST(SPI_GETMOUSEVANISH);
SPRT_CONST(SPI_SETMOUSEVANISH);
SPRT_CONST(SPI_GETFLATMENU);
SPRT_CONST(SPI_SETFLATMENU);
SPRT_CONST(SPI_GETDROPSHADOW);
SPRT_CONST(SPI_SETDROPSHADOW);
SPRT_CONST(SPI_GETBLOCKSENDINPUTRESETS);
SPRT_CONST(SPI_SETBLOCKSENDINPUTRESETS);
SPRT_CONST(SPI_GETUIEFFECTS);
SPRT_CONST(SPI_SETUIEFFECTS);
SPRT_CONST(SPI_GETDISABLEOVERLAPPEDCONTENT);
SPRT_CONST(SPI_SETDISABLEOVERLAPPEDCONTENT);
SPRT_CONST(SPI_GETCLIENTAREAANIMATION);
SPRT_CONST(SPI_SETCLIENTAREAANIMATION);
SPRT_CONST(SPI_GETCLEARTYPE);
SPRT_CONST(SPI_SETCLEARTYPE);
SPRT_CONST(SPI_GETSPEECHRECOGNITION);
SPRT_CONST(SPI_SETSPEECHRECOGNITION);
SPRT_CONST(SPI_GETCARETBROWSING);
SPRT_CONST(SPI_SETCARETBROWSING);
SPRT_CONST(SPI_GETTHREADLOCALINPUTSETTINGS);
SPRT_CONST(SPI_SETTHREADLOCALINPUTSETTINGS);
SPRT_CONST(SPI_GETSYSTEMLANGUAGEBAR);
SPRT_CONST(SPI_SETSYSTEMLANGUAGEBAR);
SPRT_CONST(SPI_GETFOREGROUNDLOCKTIMEOUT);
SPRT_CONST(SPI_SETFOREGROUNDLOCKTIMEOUT);
SPRT_CONST(SPI_GETACTIVEWNDTRKTIMEOUT);
SPRT_CONST(SPI_SETACTIVEWNDTRKTIMEOUT);
SPRT_CONST(SPI_GETFOREGROUNDFLASHCOUNT);
SPRT_CONST(SPI_SETFOREGROUNDFLASHCOUNT);
SPRT_CONST(SPI_GETCARETWIDTH);
SPRT_CONST(SPI_SETCARETWIDTH);
SPRT_CONST(SPI_GETMOUSECLICKLOCKTIME);
SPRT_CONST(SPI_SETMOUSECLICKLOCKTIME);
SPRT_CONST(SPI_GETFONTSMOOTHINGTYPE);
SPRT_CONST(SPI_SETFONTSMOOTHINGTYPE);
SPRT_CONST(SPI_GETFONTSMOOTHINGCONTRAST);
SPRT_CONST(SPI_SETFONTSMOOTHINGCONTRAST);
SPRT_CONST(SPI_GETFOCUSBORDERWIDTH);
SPRT_CONST(SPI_SETFOCUSBORDERWIDTH);
SPRT_CONST(SPI_GETFOCUSBORDERHEIGHT);
SPRT_CONST(SPI_SETFOCUSBORDERHEIGHT);
SPRT_CONST(SPI_GETFONTSMOOTHINGORIENTATION);
SPRT_CONST(SPI_SETFONTSMOOTHINGORIENTATION);
SPRT_CONST(SPI_GETMINIMUMHITRADIUS);
SPRT_CONST(SPI_SETMINIMUMHITRADIUS);
SPRT_CONST(SPI_GETMESSAGEDURATION);
SPRT_CONST(SPI_SETMESSAGEDURATION);
SPRT_CONST(SPI_GETCONTACTVISUALIZATION);
SPRT_CONST(SPI_SETCONTACTVISUALIZATION);
SPRT_CONST(SPI_GETGESTUREVISUALIZATION);
SPRT_CONST(SPI_SETGESTUREVISUALIZATION);
SPRT_CONST(SPI_GETMOUSEWHEELROUTING);
SPRT_CONST(SPI_SETMOUSEWHEELROUTING);
SPRT_CONST(SPI_GETPENVISUALIZATION);
SPRT_CONST(SPI_SETPENVISUALIZATION);

// === SW_* (ShowWindow) =====================================================
SPRT_CONST(SW_HIDE);
SPRT_CONST(SW_SHOWNORMAL);
SPRT_CONST(SW_NORMAL);
SPRT_CONST(SW_SHOWMINIMIZED);
SPRT_CONST(SW_SHOWMAXIMIZED);
SPRT_CONST(SW_MAXIMIZE);
SPRT_CONST(SW_SHOWNOACTIVATE);
SPRT_CONST(SW_SHOW);
SPRT_CONST(SW_MINIMIZE);
SPRT_CONST(SW_SHOWMINNOACTIVE);
SPRT_CONST(SW_SHOWNA);
SPRT_CONST(SW_RESTORE);
SPRT_CONST(SW_SHOWDEFAULT);
SPRT_CONST(SW_FORCEMINIMIZE);
SPRT_CONST(SW_MAX);

// === WA_* (WM_ACTIVATE) ====================================================
SPRT_CONST(WA_INACTIVE);
SPRT_CONST(WA_ACTIVE);
SPRT_CONST(WA_CLICKACTIVE);

// === GWL_* / GWLP_* ========================================================
// GWL_WNDPROC/HINSTANCE/HWNDPARENT/USERDATA/ID are SDK '#ifndef _WIN64' only;
// on the x64/arm64 targets the SDK exposes just the GWLP_* forms + GWL_STYLE/EXSTYLE.
SPRT_CONST(GWL_STYLE);
SPRT_CONST(GWL_EXSTYLE);
SPRT_CONST(GWLP_WNDPROC);
SPRT_CONST(GWLP_HINSTANCE);
SPRT_CONST(GWLP_HWNDPARENT);
SPRT_CONST(GWLP_USERDATA);
SPRT_CONST(GWLP_ID);

// === WS_* (window styles) ==================================================
SPRT_CONST(WS_OVERLAPPED);
SPRT_CONST(WS_POPUP);
SPRT_CONST(WS_CHILD);
SPRT_CONST(WS_MINIMIZE);
SPRT_CONST(WS_VISIBLE);
SPRT_CONST(WS_DISABLED);
SPRT_CONST(WS_CLIPSIBLINGS);
SPRT_CONST(WS_CLIPCHILDREN);
SPRT_CONST(WS_MAXIMIZE);
SPRT_CONST(WS_CAPTION);
SPRT_CONST(WS_BORDER);
SPRT_CONST(WS_DLGFRAME);
SPRT_CONST(WS_VSCROLL);
SPRT_CONST(WS_HSCROLL);
SPRT_CONST(WS_SYSMENU);
SPRT_CONST(WS_THICKFRAME);
SPRT_CONST(WS_GROUP);
SPRT_CONST(WS_TABSTOP);
SPRT_CONST(WS_MINIMIZEBOX);
SPRT_CONST(WS_MAXIMIZEBOX);
SPRT_CONST(WS_TILED);
SPRT_CONST(WS_ICONIC);
SPRT_CONST(WS_SIZEBOX);
SPRT_CONST(WS_OVERLAPPEDWINDOW);
SPRT_CONST(WS_TILEDWINDOW);
SPRT_CONST(WS_POPUPWINDOW);
SPRT_CONST(WS_CHILDWINDOW);

// === WS_EX_* (extended window styles) ======================================
SPRT_CONST(WS_EX_DLGMODALFRAME);
SPRT_CONST(WS_EX_NOPARENTNOTIFY);
SPRT_CONST(WS_EX_TOPMOST);
SPRT_CONST(WS_EX_ACCEPTFILES);
SPRT_CONST(WS_EX_TRANSPARENT);
SPRT_CONST(WS_EX_MDICHILD);
SPRT_CONST(WS_EX_TOOLWINDOW);
SPRT_CONST(WS_EX_WINDOWEDGE);
SPRT_CONST(WS_EX_CLIENTEDGE);
SPRT_CONST(WS_EX_CONTEXTHELP);
SPRT_CONST(WS_EX_RIGHT);
SPRT_CONST(WS_EX_LEFT);
SPRT_CONST(WS_EX_RTLREADING);
SPRT_CONST(WS_EX_LTRREADING);
SPRT_CONST(WS_EX_LEFTSCROLLBAR);
SPRT_CONST(WS_EX_RIGHTSCROLLBAR);
SPRT_CONST(WS_EX_CONTROLPARENT);
SPRT_CONST(WS_EX_STATICEDGE);
SPRT_CONST(WS_EX_APPWINDOW);
SPRT_CONST(WS_EX_OVERLAPPEDWINDOW);
SPRT_CONST(WS_EX_PALETTEWINDOW);
SPRT_CONST(WS_EX_LAYERED);
SPRT_CONST(WS_EX_NOINHERITLAYOUT);
SPRT_CONST(WS_EX_NOREDIRECTIONBITMAP);
SPRT_CONST(WS_EX_LAYOUTRTL);
SPRT_CONST(WS_EX_COMPOSITED);
SPRT_CONST(WS_EX_NOACTIVATE);

// === CW_ / CS_ =============================================================
SPRT_CONST(CW_USEDEFAULT);
SPRT_CONST(CS_VREDRAW);
SPRT_CONST(CS_HREDRAW);
SPRT_CONST(CS_DBLCLKS);
SPRT_CONST(CS_OWNDC);
SPRT_CONST(CS_CLASSDC);
SPRT_CONST(CS_PARENTDC);
SPRT_CONST(CS_NOCLOSE);
SPRT_CONST(CS_SAVEBITS);
SPRT_CONST(CS_BYTEALIGNCLIENT);
SPRT_CONST(CS_BYTEALIGNWINDOW);
SPRT_CONST(CS_GLOBALCLASS);

// === IMAGE_* / LR_* (LoadImage) ============================================
SPRT_CONST(IMAGE_BITMAP);
SPRT_CONST(IMAGE_ICON);
SPRT_CONST(IMAGE_CURSOR);
SPRT_CONST(IMAGE_ENHMETAFILE);
SPRT_CONST(LR_DEFAULTCOLOR);
SPRT_CONST(LR_MONOCHROME);
SPRT_CONST(LR_COLOR);
SPRT_CONST(LR_COPYRETURNORG);
SPRT_CONST(LR_COPYDELETEORG);
SPRT_CONST(LR_LOADFROMFILE);
SPRT_CONST(LR_LOADTRANSPARENT);
SPRT_CONST(LR_DEFAULTSIZE);
SPRT_CONST(LR_VGACOLOR);
SPRT_CONST(LR_LOADMAP3DCOLORS);
SPRT_CONST(LR_CREATEDIBSECTION);
SPRT_CONST(LR_COPYFROMRESOURCE);
SPRT_CONST(LR_SHARED);

// === stock objects (GetStockObject) ========================================
SPRT_CONST(WHITE_BRUSH);
SPRT_CONST(LTGRAY_BRUSH);
SPRT_CONST(GRAY_BRUSH);
SPRT_CONST(DKGRAY_BRUSH);
SPRT_CONST(BLACK_BRUSH);
SPRT_CONST(NULL_BRUSH);
SPRT_CONST(HOLLOW_BRUSH);
SPRT_CONST(WHITE_PEN);
SPRT_CONST(BLACK_PEN);
SPRT_CONST(NULL_PEN);
SPRT_CONST(OEM_FIXED_FONT);
SPRT_CONST(ANSI_FIXED_FONT);
SPRT_CONST(ANSI_VAR_FONT);
SPRT_CONST(SYSTEM_FONT);
SPRT_CONST(DEVICE_DEFAULT_FONT);
SPRT_CONST(DEFAULT_PALETTE);
SPRT_CONST(SYSTEM_FIXED_FONT);
SPRT_CONST(DEFAULT_GUI_FONT);

// === SWP_* (SetWindowPos) ==================================================
// SWP_NONE is SPRT-only (no SDK counterpart) -> omitted.
SPRT_CONST(SWP_NONE);
SPRT_CONST(SWP_NOSIZE);
SPRT_CONST(SWP_NOMOVE);
SPRT_CONST(SWP_NOZORDER);
SPRT_CONST(SWP_NOREDRAW);
SPRT_CONST(SWP_NOACTIVATE);
SPRT_CONST(SWP_FRAMECHANGED);
SPRT_CONST(SWP_SHOWWINDOW);
SPRT_CONST(SWP_HIDEWINDOW);
SPRT_CONST(SWP_NOCOPYBITS);
SPRT_CONST(SWP_NOOWNERZORDER);
SPRT_CONST(SWP_NOSENDCHANGING);
SPRT_CONST(SWP_DRAWFRAME);
SPRT_CONST(SWP_NOREPOSITION);
SPRT_CONST(SWP_DEFERERASE);
SPRT_CONST(SWP_ASYNCWINDOWPOS);

// === SC_* (WM_SYSCOMMAND) ==================================================
SPRT_CONST(SC_SIZE);
SPRT_CONST(SC_MOVE);
SPRT_CONST(SC_MINIMIZE);
SPRT_CONST(SC_MAXIMIZE);
SPRT_CONST(SC_NEXTWINDOW);
SPRT_CONST(SC_PREVWINDOW);
SPRT_CONST(SC_CLOSE);
SPRT_CONST(SC_VSCROLL);
SPRT_CONST(SC_HSCROLL);
SPRT_CONST(SC_MOUSEMENU);
SPRT_CONST(SC_KEYMENU);
SPRT_CONST(SC_ARRANGE);
SPRT_CONST(SC_RESTORE);
SPRT_CONST(SC_TASKLIST);
SPRT_CONST(SC_SCREENSAVE);
SPRT_CONST(SC_HOTKEY);
SPRT_CONST(SC_DEFAULT);
SPRT_CONST(SC_MONITORPOWER);
SPRT_CONST(SC_CONTEXTHELP);
SPRT_CONST(SC_SEPARATOR);

// === MF_* (menu flags) =====================================================
SPRT_CONST(MF_INSERT);
SPRT_CONST(MF_CHANGE);
SPRT_CONST(MF_APPEND);
SPRT_CONST(MF_DELETE);
SPRT_CONST(MF_REMOVE);
SPRT_CONST(MF_BYCOMMAND);
SPRT_CONST(MF_BYPOSITION);
SPRT_CONST(MF_SEPARATOR);
SPRT_CONST(MF_ENABLED);
SPRT_CONST(MF_GRAYED);
SPRT_CONST(MF_DISABLED);
SPRT_CONST(MF_UNCHECKED);
SPRT_CONST(MF_CHECKED);
SPRT_CONST(MF_USECHECKBITMAPS);
SPRT_CONST(MF_STRING);
SPRT_CONST(MF_BITMAP);
SPRT_CONST(MF_OWNERDRAW);
SPRT_CONST(MF_POPUP);
SPRT_CONST(MF_MENUBARBREAK);
SPRT_CONST(MF_MENUBREAK);
SPRT_CONST(MF_UNHILITE);
SPRT_CONST(MF_HILITE);
SPRT_CONST(MF_DEFAULT);
SPRT_CONST(MF_SYSMENU);
SPRT_CONST(MF_HELP);
SPRT_CONST(MF_RIGHTJUSTIFY);
SPRT_CONST(MF_MOUSESELECT);

// === MIIM_* (MENUITEMINFO fMask) ===========================================
SPRT_CONST(MIIM_STATE);
SPRT_CONST(MIIM_ID);
SPRT_CONST(MIIM_SUBMENU);
SPRT_CONST(MIIM_CHECKMARKS);
SPRT_CONST(MIIM_TYPE);
SPRT_CONST(MIIM_DATA);
SPRT_CONST(MIIM_STRING);
SPRT_CONST(MIIM_BITMAP);
SPRT_CONST(MIIM_FTYPE);

// === TPM_* (TrackPopupMenu) ================================================
SPRT_CONST(TPM_LEFTBUTTON);
SPRT_CONST(TPM_RIGHTBUTTON);
SPRT_CONST(TPM_LEFTALIGN);
SPRT_CONST(TPM_CENTERALIGN);
SPRT_CONST(TPM_RIGHTALIGN);
SPRT_CONST(TPM_TOPALIGN);
SPRT_CONST(TPM_VCENTERALIGN);
SPRT_CONST(TPM_BOTTOMALIGN);
SPRT_CONST(TPM_HORIZONTAL);
SPRT_CONST(TPM_VERTICAL);
SPRT_CONST(TPM_NONOTIFY);
SPRT_CONST(TPM_RETURNCMD);
SPRT_CONST(TPM_RECURSE);
SPRT_CONST(TPM_HORPOSANIMATION);
SPRT_CONST(TPM_HORNEGANIMATION);
SPRT_CONST(TPM_VERPOSANIMATION);
SPRT_CONST(TPM_VERNEGANIMATION);
SPRT_CONST(TPM_NOANIMATION);
SPRT_CONST(TPM_LAYOUTRTL);
SPRT_CONST(TPM_WORKAREA);

// === HT* (hit test) ========================================================
SPRT_CONST(HTERROR);
SPRT_CONST(HTTRANSPARENT);
SPRT_CONST(HTNOWHERE);
SPRT_CONST(HTCLIENT);
SPRT_CONST(HTCAPTION);
SPRT_CONST(HTSYSMENU);
SPRT_CONST(HTGROWBOX);
SPRT_CONST(HTSIZE);
SPRT_CONST(HTMENU);
SPRT_CONST(HTHSCROLL);
SPRT_CONST(HTVSCROLL);
SPRT_CONST(HTMINBUTTON);
SPRT_CONST(HTMAXBUTTON);
SPRT_CONST(HTLEFT);
SPRT_CONST(HTRIGHT);
SPRT_CONST(HTTOP);
SPRT_CONST(HTTOPLEFT);
SPRT_CONST(HTTOPRIGHT);
SPRT_CONST(HTBOTTOM);
SPRT_CONST(HTBOTTOMLEFT);
SPRT_CONST(HTBOTTOMRIGHT);
SPRT_CONST(HTBORDER);
SPRT_CONST(HTREDUCE);
SPRT_CONST(HTZOOM);
SPRT_CONST(HTSIZEFIRST);
SPRT_CONST(HTSIZELAST);
SPRT_CONST(HTOBJECT);
SPRT_CONST(HTCLOSE);
SPRT_CONST(HTHELP);

// === TME_* (TrackMouseEvent) ===============================================
SPRT_CONST(TME_HOVER);
SPRT_CONST(TME_LEAVE);
SPRT_CONST(TME_NONCLIENT);
SPRT_CONST(TME_QUERY);
SPRT_CONST(TME_CANCEL);

// === WMSZ_* (WM_SIZING) ====================================================
SPRT_CONST(WMSZ_LEFT);
SPRT_CONST(WMSZ_RIGHT);
SPRT_CONST(WMSZ_TOP);
SPRT_CONST(WMSZ_TOPLEFT);
SPRT_CONST(WMSZ_TOPRIGHT);
SPRT_CONST(WMSZ_BOTTOM);
SPRT_CONST(WMSZ_BOTTOMLEFT);
SPRT_CONST(WMSZ_BOTTOMRIGHT);

// === SIZE_* (WM_SIZE) ======================================================
SPRT_CONST(SIZE_RESTORED);
SPRT_CONST(SIZE_MINIMIZED);
SPRT_CONST(SIZE_MAXIMIZED);
SPRT_CONST(SIZE_MAXSHOW);
SPRT_CONST(SIZE_MAXHIDE);

// === MAPVK_* (MapVirtualKey) ===============================================
SPRT_CONST(MAPVK_VK_TO_VSC);
SPRT_CONST(MAPVK_VSC_TO_VK);
SPRT_CONST(MAPVK_VK_TO_CHAR);
SPRT_CONST(MAPVK_VSC_TO_VK_EX);
SPRT_CONST(MAPVK_VK_TO_VSC_EX);

// === misc ==================================================================
SPRT_CONST(WHEEL_DELTA);

// === MB_* (MessageBox) =====================================================
SPRT_CONST(MB_OK);
SPRT_CONST(MB_OKCANCEL);
SPRT_CONST(MB_ABORTRETRYIGNORE);
SPRT_CONST(MB_YESNOCANCEL);
SPRT_CONST(MB_YESNO);
SPRT_CONST(MB_RETRYCANCEL);
SPRT_CONST(MB_CANCELTRYCONTINUE);
SPRT_CONST(MB_ICONHAND);
SPRT_CONST(MB_ICONQUESTION);
SPRT_CONST(MB_ICONEXCLAMATION);
SPRT_CONST(MB_ICONASTERISK);
SPRT_CONST(MB_USERICON);
SPRT_CONST(MB_ICONWARNING);
SPRT_CONST(MB_ICONERROR);
SPRT_CONST(MB_ICONINFORMATION);
SPRT_CONST(MB_ICONSTOP);
SPRT_CONST(MB_DEFBUTTON1);
SPRT_CONST(MB_DEFBUTTON2);
SPRT_CONST(MB_DEFBUTTON3);
SPRT_CONST(MB_DEFBUTTON4);
SPRT_CONST(MB_APPLMODAL);
SPRT_CONST(MB_SYSTEMMODAL);
SPRT_CONST(MB_TASKMODAL);
SPRT_CONST(MB_HELP);
SPRT_CONST(MB_NOFOCUS);
SPRT_CONST(MB_SETFOREGROUND);
SPRT_CONST(MB_DEFAULT_DESKTOP_ONLY);
SPRT_CONST(MB_TOPMOST);
SPRT_CONST(MB_RIGHT);
SPRT_CONST(MB_RTLREADING);
SPRT_CONST(MB_SERVICE_NOTIFICATION);
SPRT_CONST(MB_TYPEMASK);
SPRT_CONST(MB_ICONMASK);
SPRT_CONST(MB_DEFMASK);
SPRT_CONST(MB_MODEMASK);
SPRT_CONST(MB_MISCMASK);

// Omitted (pointer/handle/string- or macro-valued, no integer static_assert):
//   MAKEINTRESOURCE (macro); IDI_* / IDC_* (MAKEINTRESOURCE pointers);
//   HWND_TOP/BOTTOM/TOPMOST/NOTOPMOST ((HWND) casts).

// === WNDCLASSW =============================================================
SPRT_SIZE(WNDCLASSW);
SPRT_OFFSET(WNDCLASSW, style);
SPRT_OFFSET(WNDCLASSW, lpfnWndProc);
SPRT_OFFSET(WNDCLASSW, cbClsExtra);
SPRT_OFFSET(WNDCLASSW, cbWndExtra);
SPRT_OFFSET(WNDCLASSW, hInstance);
SPRT_OFFSET(WNDCLASSW, hIcon);
SPRT_OFFSET(WNDCLASSW, hCursor);
SPRT_OFFSET(WNDCLASSW, hbrBackground);
SPRT_OFFSET(WNDCLASSW, lpszMenuName);
SPRT_OFFSET(WNDCLASSW, lpszClassName);

// === STYLESTRUCT ===========================================================
SPRT_SIZE(STYLESTRUCT);
SPRT_OFFSET(STYLESTRUCT, styleOld);
SPRT_OFFSET(STYLESTRUCT, styleNew);

// === WINDOWPOS =============================================================
SPRT_SIZE(WINDOWPOS);
SPRT_OFFSET(WINDOWPOS, hwnd);
SPRT_OFFSET(WINDOWPOS, hwndInsertAfter);
SPRT_OFFSET(WINDOWPOS, x);
SPRT_OFFSET(WINDOWPOS, y);
SPRT_OFFSET(WINDOWPOS, cx);
SPRT_OFFSET(WINDOWPOS, cy);
SPRT_OFFSET(WINDOWPOS, flags);

// === NCCALCSIZE_PARAMS =====================================================
SPRT_SIZE(NCCALCSIZE_PARAMS);
SPRT_OFFSET(NCCALCSIZE_PARAMS, rgrc);
SPRT_OFFSET(NCCALCSIZE_PARAMS, lppos);

// === MINMAXINFO ============================================================
SPRT_SIZE(MINMAXINFO);
SPRT_OFFSET(MINMAXINFO, ptReserved);
SPRT_OFFSET(MINMAXINFO, ptMaxSize);
SPRT_OFFSET(MINMAXINFO, ptMaxPosition);
SPRT_OFFSET(MINMAXINFO, ptMinTrackSize);
SPRT_OFFSET(MINMAXINFO, ptMaxTrackSize);

// === MENUITEMINFOW =========================================================
SPRT_SIZE(MENUITEMINFOW);
SPRT_OFFSET(MENUITEMINFOW, cbSize);
SPRT_OFFSET(MENUITEMINFOW, fMask);
SPRT_OFFSET(MENUITEMINFOW, fType);
SPRT_OFFSET(MENUITEMINFOW, fState);
SPRT_OFFSET(MENUITEMINFOW, wID);
SPRT_OFFSET(MENUITEMINFOW, hSubMenu);
SPRT_OFFSET(MENUITEMINFOW, hbmpChecked);
SPRT_OFFSET(MENUITEMINFOW, hbmpUnchecked);
SPRT_OFFSET(MENUITEMINFOW, dwItemData);
SPRT_OFFSET(MENUITEMINFOW, dwTypeData);
SPRT_OFFSET(MENUITEMINFOW, cch);
SPRT_OFFSET(MENUITEMINFOW, hbmpItem);

// === WINDOWPLACEMENT =======================================================
// (Previously diverged: the abi struct had a trailing `RECT rcDevice` that the SDK
// only declares under `#ifdef _MAC`, inflating sizeof to 60 vs 44. Fixed in abi.)
SPRT_SIZE(WINDOWPLACEMENT);
SPRT_OFFSET(WINDOWPLACEMENT, length);
SPRT_OFFSET(WINDOWPLACEMENT, flags);
SPRT_OFFSET(WINDOWPLACEMENT, showCmd);
SPRT_OFFSET(WINDOWPLACEMENT, ptMinPosition);
SPRT_OFFSET(WINDOWPLACEMENT, ptMaxPosition);
SPRT_OFFSET(WINDOWPLACEMENT, rcNormalPosition);
// rcDevice: SPRT-only trailing field (SDK gates it behind _MAC) -> no SDK offset.

// === TRACKMOUSEEVENT =======================================================
SPRT_SIZE(TRACKMOUSEEVENT);
SPRT_OFFSET(TRACKMOUSEEVENT, cbSize);
SPRT_OFFSET(TRACKMOUSEEVENT, dwFlags);
SPRT_OFFSET(TRACKMOUSEEVENT, hwndTrack);
SPRT_OFFSET(TRACKMOUSEEVENT, dwHoverTime);
