// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/security_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/security_api.h>
#include "abi_check.h"

#include <windows.h>   // ACL, SID, LUID, TOKEN_*, SECURITY_INFORMATION, SE_*, E_*, EVENTLOG_*
#include <accctrl.h>   // SE_OBJECT_TYPE, TRUSTEE_*, ACCESS_MODE, MULTIPLE_TRUSTEE_OPERATION, EXPLICIT_ACCESS_W

// enum-value parity: the abi enums live in sprt_abi, the SDK's in global scope;
// neither side is a __SPRT_ macro, so compare the enumerators directly.
#define SPRT_ENUM(name) \
	static_assert((long long)(sprt_abi::name) == (long long)(::name), \
			"enum " #name " != SDK")

// === SECURITY_INFORMATION flags ============================================
SPRT_CONST(OWNER_SECURITY_INFORMATION);
SPRT_CONST(GROUP_SECURITY_INFORMATION);
SPRT_CONST(DACL_SECURITY_INFORMATION);
SPRT_CONST(SACL_SECURITY_INFORMATION);
SPRT_CONST(LABEL_SECURITY_INFORMATION);
SPRT_CONST(ATTRIBUTE_SECURITY_INFORMATION);
SPRT_CONST(SCOPE_SECURITY_INFORMATION);
SPRT_CONST(PROCESS_TRUST_LABEL_SECURITY_INFORMATION);
SPRT_CONST(ACCESS_FILTER_SECURITY_INFORMATION);
SPRT_CONST(BACKUP_SECURITY_INFORMATION);
SPRT_CONST(PROTECTED_DACL_SECURITY_INFORMATION);
SPRT_CONST(PROTECTED_SACL_SECURITY_INFORMATION);
SPRT_CONST(UNPROTECTED_DACL_SECURITY_INFORMATION);
SPRT_CONST(UNPROTECTED_SACL_SECURITY_INFORMATION);

// === SECURITY_CAPABILITY_* (well-known capability RIDs) ====================
SPRT_CONST(SECURITY_CAPABILITY_INTERNET_CLIENT);
SPRT_CONST(SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER);
SPRT_CONST(SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER);
SPRT_CONST(SECURITY_CAPABILITY_PICTURES_LIBRARY);
SPRT_CONST(SECURITY_CAPABILITY_VIDEOS_LIBRARY);
SPRT_CONST(SECURITY_CAPABILITY_MUSIC_LIBRARY);
SPRT_CONST(SECURITY_CAPABILITY_DOCUMENTS_LIBRARY);
SPRT_CONST(SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION);
SPRT_CONST(SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES);
SPRT_CONST(SECURITY_CAPABILITY_REMOVABLE_STORAGE);
SPRT_CONST(SECURITY_CAPABILITY_APPOINTMENTS);
SPRT_CONST(SECURITY_CAPABILITY_CONTACTS);
SPRT_CONST(SECURITY_CAPABILITY_INTERNET_EXPLORER);

// === App-package / capability RID counts ===================================
// __SPRT_SECURITY_APP_PACKAGE_AUTHORITY is a {..} brace initializer, not an
// integer -> skip.
SPRT_CONST(SECURITY_APP_PACKAGE_BASE_RID);
SPRT_CONST(SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT);
SPRT_CONST(SECURITY_APP_PACKAGE_RID_COUNT);
SPRT_CONST(SECURITY_CAPABILITY_BASE_RID);
SPRT_CONST(SECURITY_CAPABILITY_APP_RID);
SPRT_CONST(SECURITY_CAPABILITY_APP_SILO_RID);
SPRT_CONST(SECURITY_BUILTIN_CAPABILITY_RID_COUNT);
SPRT_CONST(SECURITY_CAPABILITY_RID_COUNT);
SPRT_CONST(SECURITY_PARENT_PACKAGE_RID_COUNT);
SPRT_CONST(SECURITY_CHILD_PACKAGE_RID_COUNT);

// === ACE inherit flags =====================================================
SPRT_CONST(OBJECT_INHERIT_ACE);
SPRT_CONST(CONTAINER_INHERIT_ACE);
SPRT_CONST(NO_PROPAGATE_INHERIT_ACE);
SPRT_CONST(INHERIT_ONLY_ACE);
SPRT_CONST(INHERITED_ACE);
SPRT_CONST(VALID_INHERIT_FLAGS);

// === SE_GROUP_* attributes =================================================
SPRT_CONST(SE_GROUP_MANDATORY);
SPRT_CONST(SE_GROUP_ENABLED_BY_DEFAULT);
SPRT_CONST(SE_GROUP_ENABLED);
SPRT_CONST(SE_GROUP_OWNER);
SPRT_CONST(SE_GROUP_USE_FOR_DENY_ONLY);
SPRT_CONST(SE_GROUP_INTEGRITY);
SPRT_CONST(SE_GROUP_INTEGRITY_ENABLED);
SPRT_CONST(SE_GROUP_LOGON_ID);
SPRT_CONST(SE_GROUP_RESOURCE);

// === SE_PRIVILEGE_* attributes =============================================
SPRT_CONST(SE_PRIVILEGE_ENABLED_BY_DEFAULT);
SPRT_CONST(SE_PRIVILEGE_ENABLED);
SPRT_CONST(SE_PRIVILEGE_REMOVED);
SPRT_CONST(SE_PRIVILEGE_USED_FOR_ACCESS);
SPRT_CONST(SE_PRIVILEGE_VALID_ATTRIBUTES);

// === HRESULT values ========================================================
SPRT_CONST(E_ACCESSDENIED);
SPRT_CONST(E_INVALIDARG);

// === EVENTLOG_* types ======================================================
SPRT_CONST(EVENTLOG_SUCCESS);
SPRT_CONST(EVENTLOG_ERROR_TYPE);
SPRT_CONST(EVENTLOG_WARNING_TYPE);
SPRT_CONST(EVENTLOG_INFORMATION_TYPE);
SPRT_CONST(EVENTLOG_AUDIT_SUCCESS);
SPRT_CONST(EVENTLOG_AUDIT_FAILURE);

// === enums (accctrl.h) =====================================================
SPRT_SIZE(SE_OBJECT_TYPE);
SPRT_ENUM(SE_UNKNOWN_OBJECT_TYPE);
SPRT_ENUM(SE_FILE_OBJECT);
SPRT_ENUM(SE_SERVICE);
SPRT_ENUM(SE_PRINTER);
SPRT_ENUM(SE_REGISTRY_KEY);
SPRT_ENUM(SE_LMSHARE);
SPRT_ENUM(SE_KERNEL_OBJECT);
SPRT_ENUM(SE_WINDOW_OBJECT);
SPRT_ENUM(SE_DS_OBJECT);
SPRT_ENUM(SE_DS_OBJECT_ALL);
SPRT_ENUM(SE_PROVIDER_DEFINED_OBJECT);
SPRT_ENUM(SE_WMIGUID_OBJECT);
SPRT_ENUM(SE_REGISTRY_WOW64_32KEY);
SPRT_ENUM(SE_REGISTRY_WOW64_64KEY);

SPRT_SIZE(ACCESS_MODE);
SPRT_ENUM(NOT_USED_ACCESS);
SPRT_ENUM(GRANT_ACCESS);
SPRT_ENUM(SET_ACCESS);
SPRT_ENUM(DENY_ACCESS);
SPRT_ENUM(REVOKE_ACCESS);
SPRT_ENUM(SET_AUDIT_SUCCESS);
SPRT_ENUM(SET_AUDIT_FAILURE);

SPRT_SIZE(MULTIPLE_TRUSTEE_OPERATION);
SPRT_ENUM(NO_MULTIPLE_TRUSTEE);
SPRT_ENUM(TRUSTEE_IS_IMPERSONATE);

SPRT_SIZE(TRUSTEE_FORM);
SPRT_ENUM(TRUSTEE_IS_SID);
SPRT_ENUM(TRUSTEE_IS_NAME);
SPRT_ENUM(TRUSTEE_BAD_FORM);
SPRT_ENUM(TRUSTEE_IS_OBJECTS_AND_SID);
SPRT_ENUM(TRUSTEE_IS_OBJECTS_AND_NAME);

SPRT_SIZE(TRUSTEE_TYPE);
SPRT_ENUM(TRUSTEE_IS_UNKNOWN);
SPRT_ENUM(TRUSTEE_IS_USER);
SPRT_ENUM(TRUSTEE_IS_GROUP);
SPRT_ENUM(TRUSTEE_IS_DOMAIN);
SPRT_ENUM(TRUSTEE_IS_ALIAS);
SPRT_ENUM(TRUSTEE_IS_WELL_KNOWN_GROUP);
SPRT_ENUM(TRUSTEE_IS_DELETED);
SPRT_ENUM(TRUSTEE_IS_INVALID);
SPRT_ENUM(TRUSTEE_IS_COMPUTER);

// === ACL ===================================================================
SPRT_SIZE(ACL);
SPRT_OFFSET(ACL, AclRevision);
SPRT_OFFSET(ACL, Sbz1);
SPRT_OFFSET(ACL, AclSize);
SPRT_OFFSET(ACL, AceCount);
SPRT_OFFSET(ACL, Sbz2);

// === SID_IDENTIFIER_AUTHORITY ==============================================
SPRT_SIZE(SID_IDENTIFIER_AUTHORITY);
SPRT_OFFSET(SID_IDENTIFIER_AUTHORITY, Value);

// === SID (SubAuthority is a [1] flex array; ANYSIZE_ARRAY==1, sizeof matches)
SPRT_SIZE(SID);
SPRT_OFFSET(SID, Revision);
SPRT_OFFSET(SID, SubAuthorityCount);
SPRT_OFFSET(SID, IdentifierAuthority);
SPRT_OFFSET(SID, SubAuthority);

// === TOKEN_PRIMARY_GROUP ===================================================
SPRT_SIZE(TOKEN_PRIMARY_GROUP);
SPRT_OFFSET(TOKEN_PRIMARY_GROUP, PrimaryGroup);

// === TRUSTEE_W (accctrl.h; SDK ptstrName is LPWCH vs abi LPWSTR - both ptrs)
SPRT_SIZE(TRUSTEE_W);
SPRT_OFFSET(TRUSTEE_W, pMultipleTrustee);
SPRT_OFFSET(TRUSTEE_W, MultipleTrusteeOperation);
SPRT_OFFSET(TRUSTEE_W, TrusteeForm);
SPRT_OFFSET(TRUSTEE_W, TrusteeType);
SPRT_OFFSET(TRUSTEE_W, ptstrName);

// === EXPLICIT_ACCESS_W (accctrl.h) =========================================
SPRT_SIZE(EXPLICIT_ACCESS_W);
SPRT_OFFSET(EXPLICIT_ACCESS_W, grfAccessPermissions);
SPRT_OFFSET(EXPLICIT_ACCESS_W, grfAccessMode);
SPRT_OFFSET(EXPLICIT_ACCESS_W, grfInheritance);
SPRT_OFFSET(EXPLICIT_ACCESS_W, Trustee);

// === SID_AND_ATTRIBUTES ====================================================
SPRT_SIZE(SID_AND_ATTRIBUTES);
SPRT_OFFSET(SID_AND_ATTRIBUTES, Sid);
SPRT_OFFSET(SID_AND_ATTRIBUTES, Attributes);

// === TOKEN_USER ============================================================
SPRT_SIZE(TOKEN_USER);
SPRT_OFFSET(TOKEN_USER, User);

// === TOKEN_GROUPS (Groups is a [1] flex array; ANYSIZE_ARRAY==1) ===========
SPRT_SIZE(TOKEN_GROUPS);
SPRT_OFFSET(TOKEN_GROUPS, GroupCount);
SPRT_OFFSET(TOKEN_GROUPS, Groups);

// === SECURITY_CAPABILITIES =================================================
SPRT_SIZE(SECURITY_CAPABILITIES);
SPRT_OFFSET(SECURITY_CAPABILITIES, AppContainerSid);
SPRT_OFFSET(SECURITY_CAPABILITIES, Capabilities);
SPRT_OFFSET(SECURITY_CAPABILITIES, CapabilityCount);
SPRT_OFFSET(SECURITY_CAPABILITIES, Reserved);

// === TOKEN_APPCONTAINER_INFORMATION ========================================
SPRT_SIZE(TOKEN_APPCONTAINER_INFORMATION);
SPRT_OFFSET(TOKEN_APPCONTAINER_INFORMATION, TokenAppContainer);

// === LUID ==================================================================
SPRT_SIZE(LUID);
SPRT_OFFSET(LUID, LowPart);
SPRT_OFFSET(LUID, HighPart);

// === LUID_AND_ATTRIBUTES ===================================================
SPRT_SIZE(LUID_AND_ATTRIBUTES);
SPRT_OFFSET(LUID_AND_ATTRIBUTES, Luid);
SPRT_OFFSET(LUID_AND_ATTRIBUTES, Attributes);

// === TOKEN_PRIVILEGES (Privileges is a [1] flex array; ANYSIZE_ARRAY==1) ===
SPRT_SIZE(TOKEN_PRIVILEGES);
SPRT_OFFSET(TOKEN_PRIVILEGES, PrivilegeCount);
SPRT_OFFSET(TOKEN_PRIVILEGES, Privileges);
