// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/winver.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/winver.h>
#include "abi_check.h"

#include <windows.h>   // OSVERSIONINFOW / OSVERSIONINFOEXW / OSVERSIONINFOA + VER_* (winnt.h) and,
                       // via winver.h, the VS_VERSION_INFO / VS_FFI_* / VS_FF_* / VOS_* / VFT_* /
                       // VFT2_* resource constants (verrsrc.h — unguarded, so do not re-include it)

// === VER_* condition operators =============================================
SPRT_CONST(VER_EQUAL);
SPRT_CONST(VER_GREATER);
SPRT_CONST(VER_GREATER_EQUAL);
SPRT_CONST(VER_LESS);
SPRT_CONST(VER_LESS_EQUAL);
SPRT_CONST(VER_AND);
SPRT_CONST(VER_OR);
SPRT_CONST(VER_CONDITION_MASK);
SPRT_CONST(VER_NUM_BITS_PER_CONDITION_MASK);

// === VER_* type mask bits ==================================================
SPRT_CONST(VER_MINORVERSION);
SPRT_CONST(VER_MAJORVERSION);
SPRT_CONST(VER_BUILDNUMBER);
SPRT_CONST(VER_PLATFORMID);
SPRT_CONST(VER_SERVICEPACKMINOR);
SPRT_CONST(VER_SERVICEPACKMAJOR);
SPRT_CONST(VER_SUITENAME);
SPRT_CONST(VER_PRODUCT_TYPE);

// === OSVERSIONINFOW ========================================================
SPRT_SIZE(OSVERSIONINFOW);
SPRT_OFFSET(OSVERSIONINFOW, dwOSVersionInfoSize);
SPRT_OFFSET(OSVERSIONINFOW, dwMajorVersion);
SPRT_OFFSET(OSVERSIONINFOW, dwMinorVersion);
SPRT_OFFSET(OSVERSIONINFOW, dwBuildNumber);
SPRT_OFFSET(OSVERSIONINFOW, dwPlatformId);
SPRT_OFFSET(OSVERSIONINFOW, szCSDVersion);

// === OSVERSIONINFOEXW ======================================================
SPRT_SIZE(OSVERSIONINFOEXW);
SPRT_OFFSET(OSVERSIONINFOEXW, dwOSVersionInfoSize);
SPRT_OFFSET(OSVERSIONINFOEXW, dwMajorVersion);
SPRT_OFFSET(OSVERSIONINFOEXW, dwMinorVersion);
SPRT_OFFSET(OSVERSIONINFOEXW, dwBuildNumber);
SPRT_OFFSET(OSVERSIONINFOEXW, dwPlatformId);
SPRT_OFFSET(OSVERSIONINFOEXW, szCSDVersion);
SPRT_OFFSET(OSVERSIONINFOEXW, wServicePackMajor);
SPRT_OFFSET(OSVERSIONINFOEXW, wServicePackMinor);
SPRT_OFFSET(OSVERSIONINFOEXW, wSuiteMask);
SPRT_OFFSET(OSVERSIONINFOEXW, wProductType);
SPRT_OFFSET(OSVERSIONINFOEXW, wReserved);

// === OSVERSIONINFOA ========================================================
SPRT_SIZE(OSVERSIONINFOA);
SPRT_OFFSET(OSVERSIONINFOA, dwOSVersionInfoSize);
SPRT_OFFSET(OSVERSIONINFOA, dwMajorVersion);
SPRT_OFFSET(OSVERSIONINFOA, dwMinorVersion);
SPRT_OFFSET(OSVERSIONINFOA, dwBuildNumber);
SPRT_OFFSET(OSVERSIONINFOA, dwPlatformId);
SPRT_OFFSET(OSVERSIONINFOA, szCSDVersion);

// === VS_VERSIONINFO resource constants (verrsrc.h) =========================
SPRT_CONST(VS_VERSION_INFO);
SPRT_CONST(VS_USER_DEFINED);

SPRT_CONST(VS_FFI_SIGNATURE);
SPRT_CONST(VS_FFI_STRUCVERSION);
SPRT_CONST(VS_FFI_FILEFLAGSMASK);

SPRT_CONST(VS_FF_DEBUG);
SPRT_CONST(VS_FF_PRERELEASE);
SPRT_CONST(VS_FF_PATCHED);
SPRT_CONST(VS_FF_PRIVATEBUILD);
SPRT_CONST(VS_FF_INFOINFERRED);
SPRT_CONST(VS_FF_SPECIALBUILD);

// --- FILEOS (VOS_*) high word: OS family --------------------------------------
SPRT_CONST(VOS_UNKNOWN);
SPRT_CONST(VOS_DOS);
SPRT_CONST(VOS_OS216);
SPRT_CONST(VOS_OS232);
SPRT_CONST(VOS_NT);
SPRT_CONST(VOS_WINCE);

// --- FILEOS (VOS__*) low word: target subsystem -------------------------------
SPRT_CONST(VOS__BASE);
SPRT_CONST(VOS__WINDOWS16);
SPRT_CONST(VOS__PM16);
SPRT_CONST(VOS__PM32);
SPRT_CONST(VOS__WINDOWS32);

// --- FILEOS combined values ---------------------------------------------------
SPRT_CONST(VOS_DOS_WINDOWS16);
SPRT_CONST(VOS_DOS_WINDOWS32);
SPRT_CONST(VOS_OS216_PM16);
SPRT_CONST(VOS_OS232_PM32);
SPRT_CONST(VOS_NT_WINDOWS32);

// --- FILETYPE (VFT_*) ---------------------------------------------------------
SPRT_CONST(VFT_UNKNOWN);
SPRT_CONST(VFT_APP);
SPRT_CONST(VFT_DLL);
SPRT_CONST(VFT_DRV);
SPRT_CONST(VFT_FONT);
SPRT_CONST(VFT_VXD);
SPRT_CONST(VFT_STATIC_LIB);

// --- FILESUBTYPE (VFT2_*) for drivers and fonts -------------------------------
SPRT_CONST(VFT2_UNKNOWN);
SPRT_CONST(VFT2_DRV_PRINTER);
SPRT_CONST(VFT2_DRV_KEYBOARD);
SPRT_CONST(VFT2_DRV_LANGUAGE);
SPRT_CONST(VFT2_DRV_DISPLAY);
SPRT_CONST(VFT2_DRV_MOUSE);
SPRT_CONST(VFT2_DRV_NETWORK);
SPRT_CONST(VFT2_DRV_SYSTEM);
SPRT_CONST(VFT2_DRV_INSTALLABLE);
SPRT_CONST(VFT2_DRV_SOUND);
SPRT_CONST(VFT2_DRV_COMM);
SPRT_CONST(VFT2_DRV_INPUTMETHOD);
SPRT_CONST(VFT2_DRV_VERSIONED_PRINTER);
SPRT_CONST(VFT2_FONT_RASTER);
SPRT_CONST(VFT2_FONT_VECTOR);
SPRT_CONST(VFT2_FONT_TRUETYPE);
