// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/context_api.h <-> Windows SDK parity. Compile-time only; see check.sh.
//
// ARCH-SPECIFIC: CONTEXT / RUNTIME_FUNCTION / DISPATCHER_CONTEXT layouts differ
// between x86_64 and aarch64, so their asserts are guarded with _M_X64 / _M_ARM64.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/context_api.h>
#include "abi_check.h"

#include <windows.h>   // CONTEXT, NT_TIB, EXCEPTION_RECORD/POINTERS, UNWIND_HISTORY_TABLE, IMAGE_FILE_*, UNW_FLAG_*
#include <setjmp.h>   // _JBLEN, SETJMP_FLOAT128, _JUMP_BUFFER
struct _ThrowInfo;   // clang has no pre-injected MSVC EH type; forward-declare for ehdata.h
#include <ehdata.h>   // UNWIND_CODE, UNWIND_INFO

// === constants: PE image file header =======================================
SPRT_CONST(IMAGE_SIZEOF_FILE_HEADER);

SPRT_CONST(IMAGE_FILE_RELOCS_STRIPPED);
SPRT_CONST(IMAGE_FILE_EXECUTABLE_IMAGE);
SPRT_CONST(IMAGE_FILE_LINE_NUMS_STRIPPED);
SPRT_CONST(IMAGE_FILE_LOCAL_SYMS_STRIPPED);
SPRT_CONST(IMAGE_FILE_AGGRESIVE_WS_TRIM);
SPRT_CONST(IMAGE_FILE_LARGE_ADDRESS_AWARE);
SPRT_CONST(IMAGE_FILE_BYTES_REVERSED_LO);
SPRT_CONST(IMAGE_FILE_32BIT_MACHINE);
SPRT_CONST(IMAGE_FILE_DEBUG_STRIPPED);
SPRT_CONST(IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP);
SPRT_CONST(IMAGE_FILE_NET_RUN_FROM_SWAP);
SPRT_CONST(IMAGE_FILE_SYSTEM);
SPRT_CONST(IMAGE_FILE_DLL);
SPRT_CONST(IMAGE_FILE_UP_SYSTEM_ONLY);
SPRT_CONST(IMAGE_FILE_BYTES_REVERSED_HI);

// === constants: machine types ==============================================
SPRT_CONST(IMAGE_FILE_MACHINE_UNKNOWN);
SPRT_CONST(IMAGE_FILE_MACHINE_TARGET_HOST);
SPRT_CONST(IMAGE_FILE_MACHINE_I386);
SPRT_CONST(IMAGE_FILE_MACHINE_R3000);
SPRT_CONST(IMAGE_FILE_MACHINE_R4000);
SPRT_CONST(IMAGE_FILE_MACHINE_R10000);
SPRT_CONST(IMAGE_FILE_MACHINE_WCEMIPSV2);
SPRT_CONST(IMAGE_FILE_MACHINE_ALPHA);
SPRT_CONST(IMAGE_FILE_MACHINE_SH3);
SPRT_CONST(IMAGE_FILE_MACHINE_SH3DSP);
SPRT_CONST(IMAGE_FILE_MACHINE_SH3E);
SPRT_CONST(IMAGE_FILE_MACHINE_SH4);
SPRT_CONST(IMAGE_FILE_MACHINE_SH5);
SPRT_CONST(IMAGE_FILE_MACHINE_ARM);
SPRT_CONST(IMAGE_FILE_MACHINE_THUMB);
SPRT_CONST(IMAGE_FILE_MACHINE_ARMNT);
SPRT_CONST(IMAGE_FILE_MACHINE_AM33);
SPRT_CONST(IMAGE_FILE_MACHINE_POWERPC);
SPRT_CONST(IMAGE_FILE_MACHINE_POWERPCFP);
SPRT_CONST(IMAGE_FILE_MACHINE_IA64);
SPRT_CONST(IMAGE_FILE_MACHINE_MIPS16);
SPRT_CONST(IMAGE_FILE_MACHINE_ALPHA64);
SPRT_CONST(IMAGE_FILE_MACHINE_MIPSFPU);
SPRT_CONST(IMAGE_FILE_MACHINE_MIPSFPU16);
SPRT_CONST(IMAGE_FILE_MACHINE_AXP64);
SPRT_CONST(IMAGE_FILE_MACHINE_TRICORE);
SPRT_CONST(IMAGE_FILE_MACHINE_CEF);
SPRT_CONST(IMAGE_FILE_MACHINE_EBC);
SPRT_CONST(IMAGE_FILE_MACHINE_AMD64);
SPRT_CONST(IMAGE_FILE_MACHINE_M32R);
SPRT_CONST(IMAGE_FILE_MACHINE_ARM64);
SPRT_CONST(IMAGE_FILE_MACHINE_CEE);

// === constants: unwind flags ===============================================
SPRT_CONST(UNW_FLAG_NHANDLER);
SPRT_CONST(UNW_FLAG_EHANDLER);
SPRT_CONST(UNW_FLAG_UHANDLER);
#if defined(_M_X64)
SPRT_CONST(UNW_FLAG_CHAININFO);   // x86_64-only in the SDK
#endif

// === constants: exception codes (STATUS_* aliases) =========================
SPRT_CONST(STILL_ACTIVE);
SPRT_CONST(EXCEPTION_ACCESS_VIOLATION);
SPRT_CONST(EXCEPTION_DATATYPE_MISALIGNMENT);
SPRT_CONST(EXCEPTION_BREAKPOINT);
SPRT_CONST(EXCEPTION_SINGLE_STEP);
SPRT_CONST(EXCEPTION_ARRAY_BOUNDS_EXCEEDED);
SPRT_CONST(EXCEPTION_FLT_DENORMAL_OPERAND);
SPRT_CONST(EXCEPTION_FLT_DIVIDE_BY_ZERO);
SPRT_CONST(EXCEPTION_FLT_INEXACT_RESULT);
SPRT_CONST(EXCEPTION_FLT_INVALID_OPERATION);
SPRT_CONST(EXCEPTION_FLT_OVERFLOW);
SPRT_CONST(EXCEPTION_FLT_STACK_CHECK);
SPRT_CONST(EXCEPTION_FLT_UNDERFLOW);
SPRT_CONST(EXCEPTION_INT_DIVIDE_BY_ZERO);
SPRT_CONST(EXCEPTION_INT_OVERFLOW);
SPRT_CONST(EXCEPTION_PRIV_INSTRUCTION);
SPRT_CONST(EXCEPTION_IN_PAGE_ERROR);
SPRT_CONST(EXCEPTION_ILLEGAL_INSTRUCTION);
SPRT_CONST(EXCEPTION_NONCONTINUABLE_EXCEPTION);
SPRT_CONST(EXCEPTION_STACK_OVERFLOW);
SPRT_CONST(EXCEPTION_INVALID_DISPOSITION);
SPRT_CONST(EXCEPTION_GUARD_PAGE);
SPRT_CONST(EXCEPTION_INVALID_HANDLE);
SPRT_CONST(CONTROL_C_EXIT);

// === constants: exception filter / handler dispositions ====================
SPRT_CONST(EXCEPTION_EXECUTE_HANDLER);
SPRT_CONST(EXCEPTION_CONTINUE_SEARCH);
SPRT_CONST(EXCEPTION_CONTINUE_EXECUTION);
SPRT_CONST(EXCEPTION_MAXIMUM_PARAMETERS);

// EXCEPTION_DISPOSITION enumerators (ExceptionContinueExecution, ...) omitted:
// the abi header spells them as a plain enum, not __SPRT_-prefixed macros.

// Omitted constants (no __SPRT_ integer form / SPRT-specific):
//   CONTEXT_* (CONTEXT_AMD64/ARM64/CONTROL/INTEGER/... spelled without __SPRT_),
//   ARM64_MAX_BREAKPOINTS/WATCHPOINTS, _JBLEN, _JBTYPE, SPRT-only aliases.
//   __SPRT_UNWIND_HISTORY_TABLE_SIZE is asserted via the struct-array size below.

// ===========================================================================
// arch-neutral structs (identical layout on both targets)
// ===========================================================================

// === EXCEPTION_RECORD ======================================================
SPRT_SIZE(EXCEPTION_RECORD);
SPRT_OFFSET(EXCEPTION_RECORD, ExceptionCode);
SPRT_OFFSET(EXCEPTION_RECORD, ExceptionFlags);
SPRT_OFFSET(EXCEPTION_RECORD, ExceptionRecord);
SPRT_OFFSET(EXCEPTION_RECORD, ExceptionAddress);
SPRT_OFFSET(EXCEPTION_RECORD, NumberParameters);
SPRT_OFFSET(EXCEPTION_RECORD, ExceptionInformation);

// === EXCEPTION_POINTERS ====================================================
SPRT_SIZE(EXCEPTION_POINTERS);
SPRT_OFFSET(EXCEPTION_POINTERS, ExceptionRecord);
SPRT_OFFSET(EXCEPTION_POINTERS, ContextRecord);

// === NT_TIB ================================================================
SPRT_SIZE(NT_TIB);
SPRT_OFFSET(NT_TIB, ExceptionList);
SPRT_OFFSET(NT_TIB, StackBase);
SPRT_OFFSET(NT_TIB, StackLimit);
SPRT_OFFSET(NT_TIB, SubSystemTib);
SPRT_OFFSET(NT_TIB, FiberData);
SPRT_OFFSET(NT_TIB, ArbitraryUserPointer);
SPRT_OFFSET(NT_TIB, Self);

// === UNWIND_HISTORY_TABLE_ENTRY ============================================
SPRT_SIZE(UNWIND_HISTORY_TABLE_ENTRY);
SPRT_OFFSET(UNWIND_HISTORY_TABLE_ENTRY, ImageBase);
SPRT_OFFSET(UNWIND_HISTORY_TABLE_ENTRY, FunctionEntry);

// === UNWIND_HISTORY_TABLE ==================================================
SPRT_SIZE(UNWIND_HISTORY_TABLE);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, Count);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, LocalHint);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, GlobalHint);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, Search);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, Once);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, LowAddress);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, HighAddress);
SPRT_OFFSET(UNWIND_HISTORY_TABLE, Entry);

// === EXCEPTION_DISPOSITION (enum) ==========================================
SPRT_SIZE(EXCEPTION_DISPOSITION);

// === DISPATCHER_CONTEXT ====================================================
SPRT_SIZE(DISPATCHER_CONTEXT);
SPRT_OFFSET(DISPATCHER_CONTEXT, ControlPc);
SPRT_OFFSET(DISPATCHER_CONTEXT, ImageBase);
SPRT_OFFSET(DISPATCHER_CONTEXT, FunctionEntry);
SPRT_OFFSET(DISPATCHER_CONTEXT, EstablisherFrame);
SPRT_OFFSET(DISPATCHER_CONTEXT, ContextRecord);
SPRT_OFFSET(DISPATCHER_CONTEXT, LanguageHandler);
SPRT_OFFSET(DISPATCHER_CONTEXT, HandlerData);
SPRT_OFFSET(DISPATCHER_CONTEXT, HistoryTable);
SPRT_OFFSET(DISPATCHER_CONTEXT, ScopeIndex);

// === RUNTIME_FUNCTION (IMAGE_RUNTIME_FUNCTION_ENTRY) =======================
SPRT_SIZE(IMAGE_RUNTIME_FUNCTION_ENTRY);
SPRT_OFFSET(IMAGE_RUNTIME_FUNCTION_ENTRY, BeginAddress);

// ===========================================================================
#if defined(_M_X64)
// ===========================================================================
// x86_64-specific structs
// ===========================================================================

// === M128A =================================================================
SPRT_SIZE(M128A);
SPRT_OFFSET(M128A, Low);
SPRT_OFFSET(M128A, High);

// === XSAVE_FORMAT / XMM_SAVE_AREA32 ========================================
SPRT_SIZE(XSAVE_FORMAT);
SPRT_OFFSET(XSAVE_FORMAT, ControlWord);
SPRT_OFFSET(XSAVE_FORMAT, StatusWord);
SPRT_OFFSET(XSAVE_FORMAT, TagWord);
SPRT_OFFSET(XSAVE_FORMAT, Reserved1);
SPRT_OFFSET(XSAVE_FORMAT, ErrorOpcode);
SPRT_OFFSET(XSAVE_FORMAT, ErrorOffset);
SPRT_OFFSET(XSAVE_FORMAT, ErrorSelector);
SPRT_OFFSET(XSAVE_FORMAT, Reserved2);
SPRT_OFFSET(XSAVE_FORMAT, DataOffset);
SPRT_OFFSET(XSAVE_FORMAT, DataSelector);
SPRT_OFFSET(XSAVE_FORMAT, Reserved3);
SPRT_OFFSET(XSAVE_FORMAT, MxCsr);
SPRT_OFFSET(XSAVE_FORMAT, MxCsr_Mask);
SPRT_OFFSET(XSAVE_FORMAT, FloatRegisters);
SPRT_OFFSET(XSAVE_FORMAT, XmmRegisters);
SPRT_OFFSET(XSAVE_FORMAT, Reserved4);

// UNWIND_CODE / UNWIND_INFO omitted: not exposed by the SDK through <windows.h>
// (SPRT-provided helper types; SDK gates them behind other headers).

// === CONTEXT (AMD64) =======================================================
SPRT_SIZE(CONTEXT);
SPRT_OFFSET(CONTEXT, P1Home);
SPRT_OFFSET(CONTEXT, P2Home);
SPRT_OFFSET(CONTEXT, P3Home);
SPRT_OFFSET(CONTEXT, P4Home);
SPRT_OFFSET(CONTEXT, P5Home);
SPRT_OFFSET(CONTEXT, P6Home);
SPRT_OFFSET(CONTEXT, ContextFlags);
SPRT_OFFSET(CONTEXT, MxCsr);
SPRT_OFFSET(CONTEXT, SegCs);
SPRT_OFFSET(CONTEXT, SegDs);
SPRT_OFFSET(CONTEXT, SegEs);
SPRT_OFFSET(CONTEXT, SegFs);
SPRT_OFFSET(CONTEXT, SegGs);
SPRT_OFFSET(CONTEXT, SegSs);
SPRT_OFFSET(CONTEXT, EFlags);
SPRT_OFFSET(CONTEXT, Dr0);
SPRT_OFFSET(CONTEXT, Dr1);
SPRT_OFFSET(CONTEXT, Dr2);
SPRT_OFFSET(CONTEXT, Dr3);
SPRT_OFFSET(CONTEXT, Dr6);
SPRT_OFFSET(CONTEXT, Dr7);
SPRT_OFFSET(CONTEXT, Rax);
SPRT_OFFSET(CONTEXT, Rcx);
SPRT_OFFSET(CONTEXT, Rdx);
SPRT_OFFSET(CONTEXT, Rbx);
SPRT_OFFSET(CONTEXT, Rsp);
SPRT_OFFSET(CONTEXT, Rbp);
SPRT_OFFSET(CONTEXT, Rsi);
SPRT_OFFSET(CONTEXT, Rdi);
SPRT_OFFSET(CONTEXT, R8);
SPRT_OFFSET(CONTEXT, R9);
SPRT_OFFSET(CONTEXT, R10);
SPRT_OFFSET(CONTEXT, R11);
SPRT_OFFSET(CONTEXT, R12);
SPRT_OFFSET(CONTEXT, R13);
SPRT_OFFSET(CONTEXT, R14);
SPRT_OFFSET(CONTEXT, R15);
SPRT_OFFSET(CONTEXT, Rip);
SPRT_OFFSET(CONTEXT, FltSave);
SPRT_OFFSET(CONTEXT, VectorRegister);
SPRT_OFFSET(CONTEXT, VectorControl);
SPRT_OFFSET(CONTEXT, DebugControl);
SPRT_OFFSET(CONTEXT, LastBranchToRip);
SPRT_OFFSET(CONTEXT, LastBranchFromRip);
SPRT_OFFSET(CONTEXT, LastExceptionToRip);
SPRT_OFFSET(CONTEXT, LastExceptionFromRip);

SPRT_OFFSET(IMAGE_RUNTIME_FUNCTION_ENTRY, EndAddress);

// ===========================================================================
#elif defined(_M_ARM64)
// ===========================================================================
// aarch64-specific structs
// ===========================================================================

// === NEON128 ===============================================================
SPRT_SIZE(NEON128);
SPRT_OFFSET(NEON128, Low);
SPRT_OFFSET(NEON128, High);
SPRT_OFFSET(NEON128, D);
SPRT_OFFSET(NEON128, S);

// === CONTEXT (ARM64) =======================================================
SPRT_SIZE(CONTEXT);
SPRT_OFFSET(CONTEXT, ContextFlags);
SPRT_OFFSET(CONTEXT, Cpsr);
SPRT_OFFSET(CONTEXT, X0);
SPRT_OFFSET(CONTEXT, X1);
SPRT_OFFSET(CONTEXT, X28);
SPRT_OFFSET(CONTEXT, Fp);
SPRT_OFFSET(CONTEXT, Lr);
SPRT_OFFSET(CONTEXT, X);
SPRT_OFFSET(CONTEXT, Sp);
SPRT_OFFSET(CONTEXT, Pc);
SPRT_OFFSET(CONTEXT, V);
SPRT_OFFSET(CONTEXT, Fpcr);
SPRT_OFFSET(CONTEXT, Fpsr);
SPRT_OFFSET(CONTEXT, Bcr);
SPRT_OFFSET(CONTEXT, Bvr);
SPRT_OFFSET(CONTEXT, Wcr);
SPRT_OFFSET(CONTEXT, Wvr);

#endif

// === UNWIND_HISTORY_TABLE_SIZE (x64 unwind; winnt.h) =======================
#if defined(_M_X64)
SPRT_CONST(UNWIND_HISTORY_TABLE_SIZE);
#endif

// === CONTEXT_* flags + unwind/setjmp (now __SPRT_-prefixed in abi) =========
#if defined(_M_X64)
SPRT_CONST(CONTEXT_AMD64);
SPRT_CONST(CONTEXT_CONTROL);
SPRT_CONST(CONTEXT_INTEGER);
SPRT_CONST(CONTEXT_SEGMENTS);
SPRT_CONST(CONTEXT_FLOATING_POINT);
SPRT_CONST(CONTEXT_DEBUG_REGISTERS);
SPRT_CONST(CONTEXT_FULL);
SPRT_CONST(CONTEXT_ALL);
SPRT_SIZE(UNWIND_CODE);          // ehdata.h
SPRT_OFFSET(UNWIND_CODE, FrameOffset);
SPRT_SIZE(UNWIND_INFO);
SPRT_OFFSET(UNWIND_INFO, SizeOfProlog);
SPRT_OFFSET(UNWIND_INFO, CountOfCodes);
SPRT_OFFSET(UNWIND_INFO, UnwindCode);
SPRT_SIZE(SETJMP_FLOAT128);   // x64-only in abi
SPRT_OFFSET(SETJMP_FLOAT128, Part);
SPRT_SIZE(_JUMP_BUFFER);
SPRT_OFFSET(_JUMP_BUFFER, Frame);
SPRT_OFFSET(_JUMP_BUFFER, Rbx);
SPRT_OFFSET(_JUMP_BUFFER, Rsp);
SPRT_OFFSET(_JUMP_BUFFER, Rbp);
SPRT_OFFSET(_JUMP_BUFFER, Rsi);
SPRT_OFFSET(_JUMP_BUFFER, Rdi);
SPRT_OFFSET(_JUMP_BUFFER, R12);
SPRT_OFFSET(_JUMP_BUFFER, R15);
SPRT_OFFSET(_JUMP_BUFFER, Rip);
SPRT_OFFSET(_JUMP_BUFFER, MxCsr);
SPRT_OFFSET(_JUMP_BUFFER, FpCsr);
SPRT_OFFSET(_JUMP_BUFFER, Spare);
SPRT_OFFSET(_JUMP_BUFFER, Xmm6);
SPRT_OFFSET(_JUMP_BUFFER, Xmm15);
#elif defined(_M_ARM64)
SPRT_CONST(CONTEXT_ARM64);
SPRT_CONST(CONTEXT_CONTROL);
SPRT_CONST(CONTEXT_INTEGER);
SPRT_CONST(CONTEXT_FLOATING_POINT);
SPRT_CONST(CONTEXT_DEBUG_REGISTERS);
SPRT_CONST(CONTEXT_FULL);
SPRT_CONST(CONTEXT_ALL);   // abi ARM64 CONTEXT_ALL was missing X18/FP_LOW/FP_HIGH; fixed in abi
SPRT_CONST(ARM64_MAX_BREAKPOINTS);
SPRT_CONST(ARM64_MAX_WATCHPOINTS);
SPRT_SIZE(_JUMP_BUFFER);
SPRT_OFFSET(_JUMP_BUFFER, Frame);
SPRT_OFFSET(_JUMP_BUFFER, Reserved);
SPRT_OFFSET(_JUMP_BUFFER, X19);
SPRT_OFFSET(_JUMP_BUFFER, X28);
SPRT_OFFSET(_JUMP_BUFFER, Fp);
SPRT_OFFSET(_JUMP_BUFFER, Lr);
SPRT_OFFSET(_JUMP_BUFFER, Sp);
SPRT_OFFSET(_JUMP_BUFFER, Fpcr);
SPRT_OFFSET(_JUMP_BUFFER, Fpsr);
SPRT_OFFSET(_JUMP_BUFFER, D);
#endif
// _JUMP_BUFFER now matches the CRT setjmp.h layout on both arches; _JBLEN too
// (x64 16, arm64 24) after fixing the abi's stale x64 value of 24.
SPRT_CONST(_JBLEN);

#include <ntstatus.h>
SPRT_STATUS(EXCEPTION_POSSIBLE_DEADLOCK);

// ===========================================================================
// new values (wrapper completion): debug loop + WoW64 register context
// ===========================================================================

// === DEBUG_EVENT codes (minwinbase.h) ======================================
SPRT_CONST(EXCEPTION_DEBUG_EVENT);
SPRT_CONST(CREATE_THREAD_DEBUG_EVENT);
SPRT_CONST(CREATE_PROCESS_DEBUG_EVENT);
SPRT_CONST(EXIT_THREAD_DEBUG_EVENT);
SPRT_CONST(EXIT_PROCESS_DEBUG_EVENT);
SPRT_CONST(LOAD_DLL_DEBUG_EVENT);
SPRT_CONST(UNLOAD_DLL_DEBUG_EVENT);
SPRT_CONST(OUTPUT_DEBUG_STRING_EVENT);
SPRT_CONST(RIP_EVENT);

// === DEBUG_EVENT payload structs (written by the kernel; layout must match) =
SPRT_SIZE(EXCEPTION_DEBUG_INFO);
SPRT_OFFSET(EXCEPTION_DEBUG_INFO, ExceptionRecord);
SPRT_OFFSET(EXCEPTION_DEBUG_INFO, dwFirstChance);

SPRT_SIZE(CREATE_THREAD_DEBUG_INFO);
SPRT_OFFSET(CREATE_THREAD_DEBUG_INFO, hThread);
SPRT_OFFSET(CREATE_THREAD_DEBUG_INFO, lpThreadLocalBase);
SPRT_OFFSET(CREATE_THREAD_DEBUG_INFO, lpStartAddress);

SPRT_SIZE(CREATE_PROCESS_DEBUG_INFO);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, hFile);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, hProcess);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, hThread);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, lpBaseOfImage);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, dwDebugInfoFileOffset);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, nDebugInfoSize);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, lpThreadLocalBase);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, lpStartAddress);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, lpImageName);
SPRT_OFFSET(CREATE_PROCESS_DEBUG_INFO, fUnicode);

SPRT_SIZE(EXIT_THREAD_DEBUG_INFO);
SPRT_OFFSET(EXIT_THREAD_DEBUG_INFO, dwExitCode);

SPRT_SIZE(EXIT_PROCESS_DEBUG_INFO);
SPRT_OFFSET(EXIT_PROCESS_DEBUG_INFO, dwExitCode);

SPRT_SIZE(LOAD_DLL_DEBUG_INFO);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, hFile);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, lpBaseOfDll);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, dwDebugInfoFileOffset);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, nDebugInfoSize);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, lpImageName);
SPRT_OFFSET(LOAD_DLL_DEBUG_INFO, fUnicode);

SPRT_SIZE(UNLOAD_DLL_DEBUG_INFO);
SPRT_OFFSET(UNLOAD_DLL_DEBUG_INFO, lpBaseOfDll);

SPRT_SIZE(OUTPUT_DEBUG_STRING_INFO);
SPRT_OFFSET(OUTPUT_DEBUG_STRING_INFO, lpDebugStringData);
SPRT_OFFSET(OUTPUT_DEBUG_STRING_INFO, fUnicode);
SPRT_OFFSET(OUTPUT_DEBUG_STRING_INFO, nDebugStringLength);

SPRT_SIZE(RIP_INFO);
SPRT_OFFSET(RIP_INFO, dwError);
SPRT_OFFSET(RIP_INFO, dwType);

SPRT_SIZE(DEBUG_EVENT);
SPRT_OFFSET(DEBUG_EVENT, dwDebugEventCode);
SPRT_OFFSET(DEBUG_EVENT, dwProcessId);
SPRT_OFFSET(DEBUG_EVENT, dwThreadId);
SPRT_OFFSET(DEBUG_EVENT, u);

// === WoW64 32-bit register context (winnt.h; fixed i386 layout) ============
// The WOW64_* names/struct are the 32-bit-on-64-bit context; asserted on the
// x86_64 host where the SDK spells them (WoW64 shape differs on the arm64 SDK).
#if defined(_M_X64)
SPRT_CONST(WOW64_CONTEXT_i386);
SPRT_CONST(WOW64_CONTEXT_CONTROL);
SPRT_CONST(WOW64_CONTEXT_INTEGER);
SPRT_CONST(WOW64_CONTEXT_SEGMENTS);
SPRT_CONST(WOW64_CONTEXT_FLOATING_POINT);
SPRT_CONST(WOW64_CONTEXT_DEBUG_REGISTERS);
SPRT_CONST(WOW64_CONTEXT_EXTENDED_REGISTERS);
SPRT_CONST(WOW64_CONTEXT_FULL);
SPRT_CONST(WOW64_CONTEXT_ALL);
SPRT_CONST(WOW64_SIZE_OF_80387_REGISTERS);
SPRT_CONST(WOW64_MAXIMUM_SUPPORTED_EXTENSION);

SPRT_SIZE(WOW64_FLOATING_SAVE_AREA);
SPRT_OFFSET(WOW64_FLOATING_SAVE_AREA, ControlWord);
SPRT_OFFSET(WOW64_FLOATING_SAVE_AREA, RegisterArea);
SPRT_OFFSET(WOW64_FLOATING_SAVE_AREA, Cr0NpxState);

SPRT_SIZE(WOW64_CONTEXT);
SPRT_OFFSET(WOW64_CONTEXT, ContextFlags);
SPRT_OFFSET(WOW64_CONTEXT, FloatSave);
SPRT_OFFSET(WOW64_CONTEXT, Eip);
SPRT_OFFSET(WOW64_CONTEXT, Esp);
SPRT_OFFSET(WOW64_CONTEXT, SegSs);
SPRT_OFFSET(WOW64_CONTEXT, ExtendedRegisters);
#endif
