// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/com_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/com_api.h>
#include "abi_check.h"

#include <windows.h>
#include <objbase.h>   // COINIT, COINITBASE, EOLE_AUTHENTICATION_CAPABILITIES
#include <shlobj.h>    // KNOWN_FOLDER_FLAG, KF_CATEGORY, KF_DEFINITION_FLAGS, KNOWNFOLDER_DEFINITION

// The com_api enum values are C++ enum constants (not __SPRT_ macros), so they
// live in namespace sprt_abi and are compared against the global SDK constants.
#define SPRT_ENUM(name) \
	static_assert((long long)(sprt_abi::name) == (long long)(name), \
			"sprt_abi::" #name " != SDK " #name)

// === COINITBASE / COINIT ===================================================
SPRT_ENUM(COINITBASE_MULTITHREADED);
SPRT_ENUM(COINIT_APARTMENTTHREADED);
SPRT_ENUM(COINIT_MULTITHREADED);
SPRT_ENUM(COINIT_DISABLE_OLE1DDE);
SPRT_ENUM(COINIT_SPEED_OVER_MEMORY);

// === KNOWN_FOLDER_FLAG =====================================================
SPRT_ENUM(KF_FLAG_DEFAULT);
SPRT_ENUM(KF_FLAG_FORCE_APP_DATA_REDIRECTION);
SPRT_ENUM(KF_FLAG_RETURN_FILTER_REDIRECTION_TARGET);
SPRT_ENUM(KF_FLAG_FORCE_PACKAGE_REDIRECTION);
SPRT_ENUM(KF_FLAG_NO_PACKAGE_REDIRECTION);
SPRT_ENUM(KF_FLAG_FORCE_APPCONTAINER_REDIRECTION);
SPRT_ENUM(KF_FLAG_NO_APPCONTAINER_REDIRECTION);
SPRT_ENUM(KF_FLAG_CREATE);
SPRT_ENUM(KF_FLAG_DONT_VERIFY);
SPRT_ENUM(KF_FLAG_DONT_UNEXPAND);
SPRT_ENUM(KF_FLAG_NO_ALIAS);
SPRT_ENUM(KF_FLAG_INIT);
SPRT_ENUM(KF_FLAG_DEFAULT_PATH);
SPRT_ENUM(KF_FLAG_NOT_PARENT_RELATIVE);
SPRT_ENUM(KF_FLAG_SIMPLE_IDLIST);
SPRT_ENUM(KF_FLAG_ALIAS_ONLY);

// === KF_CATEGORY ===========================================================
SPRT_ENUM(KF_CATEGORY_VIRTUAL);
SPRT_ENUM(KF_CATEGORY_FIXED);
SPRT_ENUM(KF_CATEGORY_COMMON);
SPRT_ENUM(KF_CATEGORY_PERUSER);

// === EOLE_AUTHENTICATION_CAPABILITIES ======================================
SPRT_ENUM(EOAC_NONE);
SPRT_ENUM(EOAC_MUTUAL_AUTH);
SPRT_ENUM(EOAC_STATIC_CLOAKING);
SPRT_ENUM(EOAC_DYNAMIC_CLOAKING);
SPRT_ENUM(EOAC_ANY_AUTHORITY);
SPRT_ENUM(EOAC_MAKE_FULLSIC);
SPRT_ENUM(EOAC_DEFAULT);
SPRT_ENUM(EOAC_SECURE_REFS);
SPRT_ENUM(EOAC_ACCESS_CONTROL);
SPRT_ENUM(EOAC_APPID);
SPRT_ENUM(EOAC_DYNAMIC);
SPRT_ENUM(EOAC_REQUIRE_FULLSIC);
SPRT_ENUM(EOAC_AUTO_IMPERSONATE);
SPRT_ENUM(EOAC_DISABLE_AAA);
SPRT_ENUM(EOAC_NO_CUSTOM_MARSHAL);
SPRT_ENUM(EOAC_RESERVED1);

// === RPC_C_* integer constants (__SPRT_ macros) ============================
SPRT_CONST(RPC_C_AUTHZ_NONE);
SPRT_CONST(RPC_C_AUTHZ_NAME);
SPRT_CONST(RPC_C_AUTHZ_DCE);
SPRT_CONST(RPC_C_AUTHZ_DEFAULT);

SPRT_CONST(RPC_C_AUTHN_NONE);
SPRT_CONST(RPC_C_AUTHN_DCE_PRIVATE);
SPRT_CONST(RPC_C_AUTHN_DCE_PUBLIC);
SPRT_CONST(RPC_C_AUTHN_DEC_PUBLIC);
SPRT_CONST(RPC_C_AUTHN_GSS_NEGOTIATE);
SPRT_CONST(RPC_C_AUTHN_WINNT);
SPRT_CONST(RPC_C_AUTHN_GSS_SCHANNEL);
SPRT_CONST(RPC_C_AUTHN_GSS_KERBEROS);
SPRT_CONST(RPC_C_AUTHN_DPA);
SPRT_CONST(RPC_C_AUTHN_MSN);

SPRT_CONST(RPC_C_AUTHN_LEVEL_DEFAULT);
SPRT_CONST(RPC_C_AUTHN_LEVEL_NONE);
SPRT_CONST(RPC_C_AUTHN_LEVEL_CONNECT);
SPRT_CONST(RPC_C_AUTHN_LEVEL_CALL);
SPRT_CONST(RPC_C_AUTHN_LEVEL_PKT);
SPRT_CONST(RPC_C_AUTHN_LEVEL_PKT_INTEGRITY);
SPRT_CONST(RPC_C_AUTHN_LEVEL_PKT_PRIVACY);

SPRT_CONST(RPC_C_IMP_LEVEL_DEFAULT);
SPRT_CONST(RPC_C_IMP_LEVEL_ANONYMOUS);
SPRT_CONST(RPC_C_IMP_LEVEL_IDENTIFY);
SPRT_CONST(RPC_C_IMP_LEVEL_IMPERSONATE);
SPRT_CONST(RPC_C_IMP_LEVEL_DELEGATE);

// === KNOWNFOLDER_DEFINITION ================================================
SPRT_SIZE(KNOWNFOLDER_DEFINITION);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, category);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszName);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszDescription);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, fidParent);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszRelativePath);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszParsingName);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszTooltip);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszLocalizedName);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszIcon);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, pszSecurity);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, dwAttributes);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, kfdFlags);
SPRT_OFFSET(KNOWNFOLDER_DEFINITION, ftidType);

// Omitted (SPRT-specific or non-integer / not directly assertable):
//  - _KF_DEFINITION_FLAGS (KFDF_*) enum: covered elsewhere if needed; SDK-matched.
//  - REFKNOWNFOLDERID: a macro/typedef, not a value or shared struct.
//  - typedef aliases (FOLDERTYPEID, KNOWNFOLDERID, IID, OLECHAR, ...): plain GUID/WCHAR aliases.
