// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/monitor_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/monitor_api.h>
#include "abi_check.h"

#include <windows.h>
#include <physicalmonitorenumerationapi.h>   // PHYSICAL_MONITOR, PHYSICAL_MONITOR_DESCRIPTION_SIZE
#include <highlevelmonitorconfigurationapi.h>
#include <setupapi.h>                         // SP_DEVINFO_DATA, SP_DEVICE_INTERFACE_DATA, DIREG_*, DICS_*, DIGCF_*
#include <shellscalingapi.h>                  // PROCESS_DPI_AWARENESS, MONITOR_DPI_TYPE (DPI_AWARENESS is in windef.h)

// enum-value parity: sprt_abi enumerator vs the SDK's identically-named one.
#define SPRT_ENUM(v) \
	static_assert((long long)(sprt_abi::v) == (long long)(::v), "enum " #v " != SDK")

// === MONITORINFO / MONITORINFOEXW =========================================
SPRT_CONST(MONITOR_DEFAULTTONULL);
SPRT_CONST(MONITOR_DEFAULTTOPRIMARY);
SPRT_CONST(MONITOR_DEFAULTTONEAREST);
SPRT_CONST(MONITORINFOF_PRIMARY);

SPRT_SIZE(MONITORINFO);
SPRT_OFFSET(MONITORINFO, cbSize);
SPRT_OFFSET(MONITORINFO, rcMonitor);
SPRT_OFFSET(MONITORINFO, rcWork);
SPRT_OFFSET(MONITORINFO, dwFlags);

SPRT_SIZE(MONITORINFOEXW);
SPRT_OFFSET(MONITORINFOEXW, cbSize);
SPRT_OFFSET(MONITORINFOEXW, rcMonitor);
SPRT_OFFSET(MONITORINFOEXW, rcWork);
SPRT_OFFSET(MONITORINFOEXW, dwFlags);
SPRT_OFFSET(MONITORINFOEXW, szDevice);

// === PHYSICAL_MONITOR =====================================================
SPRT_CONST(PHYSICAL_MONITOR_DESCRIPTION_SIZE);
SPRT_SIZE(PHYSICAL_MONITOR);
SPRT_OFFSET(PHYSICAL_MONITOR, hPhysicalMonitor);
SPRT_OFFSET(PHYSICAL_MONITOR, szPhysicalMonitorDescription);

// === DISPLAY_DEVICEW ======================================================
SPRT_CONST(DISPLAY_DEVICE_ACTIVE);
SPRT_CONST(DISPLAY_DEVICE_ATTACHED);
SPRT_CONST(EDD_GET_DEVICE_INTERFACE_NAME);
SPRT_SIZE(DISPLAY_DEVICEW);
SPRT_OFFSET(DISPLAY_DEVICEW, cb);
SPRT_OFFSET(DISPLAY_DEVICEW, DeviceName);
SPRT_OFFSET(DISPLAY_DEVICEW, DeviceString);
SPRT_OFFSET(DISPLAY_DEVICEW, StateFlags);
SPRT_OFFSET(DISPLAY_DEVICEW, DeviceID);
SPRT_OFFSET(DISPLAY_DEVICEW, DeviceKey);

// === DEVMODEW (top-level named fields only; the printer/display fields live
//               in anonymous unions/structs whose offsets we don't pin) ====
SPRT_CONST(CCHDEVICENAME);
SPRT_CONST(CCHFORMNAME);
SPRT_SIZE(DEVMODEW);
SPRT_OFFSET(DEVMODEW, dmDeviceName);
SPRT_OFFSET(DEVMODEW, dmSpecVersion);
SPRT_OFFSET(DEVMODEW, dmDriverVersion);
SPRT_OFFSET(DEVMODEW, dmSize);
SPRT_OFFSET(DEVMODEW, dmDriverExtra);
SPRT_OFFSET(DEVMODEW, dmFields);
SPRT_OFFSET(DEVMODEW, dmColor);
SPRT_OFFSET(DEVMODEW, dmDuplex);
SPRT_OFFSET(DEVMODEW, dmYResolution);
SPRT_OFFSET(DEVMODEW, dmTTOption);
SPRT_OFFSET(DEVMODEW, dmCollate);
SPRT_OFFSET(DEVMODEW, dmFormName);
SPRT_OFFSET(DEVMODEW, dmLogPixels);
SPRT_OFFSET(DEVMODEW, dmBitsPerPel);
SPRT_OFFSET(DEVMODEW, dmPelsWidth);
SPRT_OFFSET(DEVMODEW, dmPelsHeight);
SPRT_OFFSET(DEVMODEW, dmDisplayFrequency);
SPRT_OFFSET(DEVMODEW, dmICMMethod);
SPRT_OFFSET(DEVMODEW, dmICMIntent);
SPRT_OFFSET(DEVMODEW, dmMediaType);
SPRT_OFFSET(DEVMODEW, dmDitherType);
SPRT_OFFSET(DEVMODEW, dmReserved1);
SPRT_OFFSET(DEVMODEW, dmReserved2);
SPRT_OFFSET(DEVMODEW, dmPanningWidth);
SPRT_OFFSET(DEVMODEW, dmPanningHeight);

// === SetupAPI structs =====================================================
SPRT_SIZE(SP_DEVINFO_DATA);
SPRT_OFFSET(SP_DEVINFO_DATA, cbSize);
SPRT_OFFSET(SP_DEVINFO_DATA, ClassGuid);
SPRT_OFFSET(SP_DEVINFO_DATA, DevInst);
SPRT_OFFSET(SP_DEVINFO_DATA, Reserved);

SPRT_SIZE(SP_DEVICE_INTERFACE_DATA);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DATA, cbSize);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DATA, InterfaceClassGuid);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DATA, Flags);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DATA, Reserved);

// === enums ================================================================
SPRT_SIZE(PROCESS_DPI_AWARENESS);
SPRT_ENUM(PROCESS_DPI_UNAWARE);
SPRT_ENUM(PROCESS_SYSTEM_DPI_AWARE);
SPRT_ENUM(PROCESS_PER_MONITOR_DPI_AWARE);

SPRT_SIZE(MONITOR_DPI_TYPE);
SPRT_ENUM(MDT_EFFECTIVE_DPI);
SPRT_ENUM(MDT_ANGULAR_DPI);
SPRT_ENUM(MDT_RAW_DPI);
SPRT_ENUM(MDT_DEFAULT);

SPRT_SIZE(DPI_AWARENESS);
SPRT_ENUM(DPI_AWARENESS_INVALID);
SPRT_ENUM(DPI_AWARENESS_UNAWARE);
SPRT_ENUM(DPI_AWARENESS_SYSTEM_AWARE);
SPRT_ENUM(DPI_AWARENESS_PER_MONITOR_AWARE);

// === misc integer constants ===============================================
SPRT_CONST(USER_DEFAULT_SCREEN_DPI);
SPRT_CONST(ENUM_CURRENT_SETTINGS);
SPRT_CONST(ENUM_REGISTRY_SETTINGS);

// GetDeviceCaps indices
SPRT_CONST(DRIVERVERSION);
SPRT_CONST(TECHNOLOGY);
SPRT_CONST(HORZSIZE);
SPRT_CONST(VERTSIZE);
SPRT_CONST(HORZRES);
SPRT_CONST(VERTRES);
SPRT_CONST(BITSPIXEL);
SPRT_CONST(PLANES);
SPRT_CONST(NUMBRUSHES);
SPRT_CONST(NUMPENS);
SPRT_CONST(NUMMARKERS);
SPRT_CONST(NUMFONTS);
SPRT_CONST(NUMCOLORS);
SPRT_CONST(PDEVICESIZE);
SPRT_CONST(CURVECAPS);
SPRT_CONST(LINECAPS);
SPRT_CONST(POLYGONALCAPS);
SPRT_CONST(TEXTCAPS);
SPRT_CONST(CLIPCAPS);
SPRT_CONST(RASTERCAPS);
SPRT_CONST(ASPECTX);
SPRT_CONST(ASPECTY);
SPRT_CONST(ASPECTXY);
SPRT_CONST(LOGPIXELSX);
SPRT_CONST(LOGPIXELSY);
SPRT_CONST(SIZEPALETTE);
SPRT_CONST(NUMRESERVED);
SPRT_CONST(COLORRES);
SPRT_CONST(PHYSICALWIDTH);
SPRT_CONST(PHYSICALHEIGHT);
SPRT_CONST(PHYSICALOFFSETX);
SPRT_CONST(PHYSICALOFFSETY);
SPRT_CONST(SCALINGFACTORX);
SPRT_CONST(SCALINGFACTORY);
SPRT_CONST(VREFRESH);
SPRT_CONST(BLTALIGNMENT);
SPRT_CONST(SHADEBLENDCAPS);
SPRT_CONST(COLORMGMTCAPS);
// __SPRT_DESKTOPVERTRES / __SPRT_DESKTOPHORZRES: malformed macro bodies in the
// abi header (trailing stray `*/`), can't go through static_assert — skipped.

// GetSystemMetrics indices
SPRT_CONST(SM_XVIRTUALSCREEN);
SPRT_CONST(SM_YVIRTUALSCREEN);
SPRT_CONST(SM_CXVIRTUALSCREEN);
SPRT_CONST(SM_CYVIRTUALSCREEN);
SPRT_CONST(SM_CMONITORS);
SPRT_CONST(SM_SAMEDISPLAYFORMAT);

// DEVMODE dmFields flags
SPRT_CONST(DM_ORIENTATION);
SPRT_CONST(DM_PAPERSIZE);
SPRT_CONST(DM_PAPERLENGTH);
SPRT_CONST(DM_PAPERWIDTH);
SPRT_CONST(DM_SCALE);
SPRT_CONST(DM_POSITION);
SPRT_CONST(DM_NUP);
SPRT_CONST(DM_DISPLAYORIENTATION);
SPRT_CONST(DM_COPIES);
SPRT_CONST(DM_DEFAULTSOURCE);
SPRT_CONST(DM_PRINTQUALITY);
SPRT_CONST(DM_COLOR);
SPRT_CONST(DM_DUPLEX);
SPRT_CONST(DM_YRESOLUTION);
SPRT_CONST(DM_TTOPTION);
SPRT_CONST(DM_COLLATE);
SPRT_CONST(DM_FORMNAME);
SPRT_CONST(DM_LOGPIXELS);
SPRT_CONST(DM_BITSPERPEL);
SPRT_CONST(DM_PELSWIDTH);
SPRT_CONST(DM_PELSHEIGHT);
SPRT_CONST(DM_DISPLAYFLAGS);
SPRT_CONST(DM_DISPLAYFREQUENCY);
SPRT_CONST(DM_ICMMETHOD);
SPRT_CONST(DM_ICMINTENT);
SPRT_CONST(DM_MEDIATYPE);
SPRT_CONST(DM_DITHERTYPE);
SPRT_CONST(DM_PANNINGWIDTH);
SPRT_CONST(DM_PANNINGHEIGHT);
SPRT_CONST(DM_DISPLAYFIXEDOUTPUT);

// ChangeDisplaySettings flags / results
SPRT_CONST(CDS_UPDATEREGISTRY);
SPRT_CONST(CDS_TEST);
SPRT_CONST(CDS_FULLSCREEN);
SPRT_CONST(CDS_GLOBAL);
SPRT_CONST(CDS_SET_PRIMARY);
SPRT_CONST(CDS_VIDEOPARAMETERS);
SPRT_CONST(CDS_RESET);
SPRT_CONST(CDS_RESET_EX);
SPRT_CONST(CDS_NORESET);
SPRT_CONST(DISP_CHANGE_SUCCESSFUL);
SPRT_CONST(DISP_CHANGE_RESTART);
SPRT_CONST(DISP_CHANGE_FAILED);
SPRT_CONST(DISP_CHANGE_BADMODE);
SPRT_CONST(DISP_CHANGE_NOTUPDATED);
SPRT_CONST(DISP_CHANGE_BADFLAGS);
SPRT_CONST(DISP_CHANGE_BADPARAM);
SPRT_CONST(DISP_CHANGE_BADDUALVIEW);

// SetupAPI flags
SPRT_CONST(DIREG_DEV);
SPRT_CONST(DIREG_DRV);
SPRT_CONST(DIREG_BOTH);
SPRT_CONST(DICS_FLAG_GLOBAL);
SPRT_CONST(DICS_FLAG_CONFIGSPECIFIC);
SPRT_CONST(DICS_FLAG_CONFIGGENERAL);
SPRT_CONST(DIGCF_DEFAULT);
SPRT_CONST(DIGCF_PRESENT);
SPRT_CONST(DIGCF_ALLCLASSES);
SPRT_CONST(DIGCF_PROFILE);
SPRT_CONST(DIGCF_DEVICEINTERFACE);

// === omitted (SPRT-specific, pointer/handle-valued, or absent from the SDK) ==
// DPI_AWARENESS_CONTEXT_* : pointer constants ((DPI_AWARENESS_CONTEXT)-N) — skip.
// DESKTOPVERTRES / DESKTOPHORZRES : malformed abi macro bodies — skip (see above).
// SP_DEVICE_INTERFACE_DETAIL_DATA_W : ANYSIZE_ARRAY tail, SDK packs it — not pinned.

// === GetDeviceCaps desktop-resolution indices (wingdi.h) ===================
SPRT_CONST(DESKTOPVERTRES);
SPRT_CONST(DESKTOPHORZRES);

// === SP_DEVICE_INTERFACE_DETAIL_DATA_W (setupapi.h) ===
SPRT_SIZE(SP_DEVICE_INTERFACE_DETAIL_DATA_W);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DETAIL_DATA_W, cbSize);
SPRT_OFFSET(SP_DEVICE_INTERFACE_DETAIL_DATA_W, DevicePath);
