// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/process_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/process_api.h>
#include "abi_check.h"

#include <windows.h>    // PROCESS_INFORMATION, STARTUPINFOW, PROCESS_*, CREATE_*, STARTF_*
#include <shellapi.h>   // SHELLEXECUTEINFOW, SEE_MASK_*
#include <psapi.h>      // PROCESS_MEMORY_COUNTERS

// === PROCESS_* access rights ================================================
SPRT_CONST(PROCESS_TERMINATE);
SPRT_CONST(PROCESS_CREATE_THREAD);
SPRT_CONST(PROCESS_SET_SESSIONID);
SPRT_CONST(PROCESS_VM_OPERATION);
SPRT_CONST(PROCESS_VM_READ);
SPRT_CONST(PROCESS_VM_WRITE);
SPRT_CONST(PROCESS_DUP_HANDLE);
SPRT_CONST(PROCESS_CREATE_PROCESS);
SPRT_CONST(PROCESS_SET_QUOTA);
SPRT_CONST(PROCESS_SET_INFORMATION);
SPRT_CONST(PROCESS_QUERY_INFORMATION);
SPRT_CONST(PROCESS_SUSPEND_RESUME);
SPRT_CONST(PROCESS_QUERY_LIMITED_INFORMATION);
SPRT_CONST(PROCESS_SET_LIMITED_INFORMATION);

// === priority classes =======================================================
SPRT_CONST(NORMAL_PRIORITY_CLASS);
SPRT_CONST(IDLE_PRIORITY_CLASS);
SPRT_CONST(HIGH_PRIORITY_CLASS);
SPRT_CONST(REALTIME_PRIORITY_CLASS);
SPRT_CONST(BELOW_NORMAL_PRIORITY_CLASS);
SPRT_CONST(ABOVE_NORMAL_PRIORITY_CLASS);

// === PROC_THREAD_ATTRIBUTE_* ================================================
SPRT_CONST(PROC_THREAD_ATTRIBUTE_NUMBER);
SPRT_CONST(PROC_THREAD_ATTRIBUTE_THREAD);
SPRT_CONST(PROC_THREAD_ATTRIBUTE_INPUT);
SPRT_CONST(PROC_THREAD_ATTRIBUTE_ADDITIVE);

// === STARTF_* (STARTUPINFO.dwFlags) =========================================
SPRT_CONST(STARTF_USESHOWWINDOW);
SPRT_CONST(STARTF_USESIZE);
SPRT_CONST(STARTF_USEPOSITION);
SPRT_CONST(STARTF_USECOUNTCHARS);
SPRT_CONST(STARTF_USEFILLATTRIBUTE);
SPRT_CONST(STARTF_RUNFULLSCREEN);
SPRT_CONST(STARTF_FORCEONFEEDBACK);
SPRT_CONST(STARTF_FORCEOFFFEEDBACK);
SPRT_CONST(STARTF_USESTDHANDLES);

// === CreateProcess dwCreationFlags ==========================================
SPRT_CONST(DEBUG_PROCESS);
SPRT_CONST(DEBUG_ONLY_THIS_PROCESS);
SPRT_CONST(CREATE_SUSPENDED);
SPRT_CONST(DETACHED_PROCESS);
SPRT_CONST(CREATE_NEW_CONSOLE);
SPRT_CONST(CREATE_NEW_PROCESS_GROUP);
SPRT_CONST(CREATE_UNICODE_ENVIRONMENT);
SPRT_CONST(CREATE_SEPARATE_WOW_VDM);
SPRT_CONST(CREATE_SHARED_WOW_VDM);
SPRT_CONST(CREATE_FORCEDOS);
SPRT_CONST(INHERIT_PARENT_AFFINITY);
SPRT_CONST(INHERIT_CALLER_PRIORITY);
SPRT_CONST(CREATE_PROTECTED_PROCESS);
SPRT_CONST(EXTENDED_STARTUPINFO_PRESENT);
SPRT_CONST(PROCESS_MODE_BACKGROUND_BEGIN);
SPRT_CONST(PROCESS_MODE_BACKGROUND_END);
SPRT_CONST(CREATE_SECURE_PROCESS);
SPRT_CONST(CREATE_BREAKAWAY_FROM_JOB);
SPRT_CONST(CREATE_PRESERVE_CODE_AUTHZ_LEVEL);
SPRT_CONST(CREATE_DEFAULT_ERROR_MODE);
SPRT_CONST(CREATE_NO_WINDOW);
SPRT_CONST(PROFILE_USER);
SPRT_CONST(PROFILE_KERNEL);
SPRT_CONST(PROFILE_SERVER);
SPRT_CONST(CREATE_IGNORE_SYSTEM_DEFAULT);

// === ShellExecuteEx =========================================================
SPRT_CONST(SEE_MASK_NOCLOSEPROCESS);

// Omitted: ProcThreadAttributeValue()/PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES
// are function-like/derived macros. PROC_THREAD_ATTRIBUTE_NUM enum values are
// SPRT-local (no __SPRT_ macro form).

// === PROCESS_INFORMATION ====================================================
SPRT_SIZE(PROCESS_INFORMATION);
SPRT_OFFSET(PROCESS_INFORMATION, hProcess);
SPRT_OFFSET(PROCESS_INFORMATION, hThread);
SPRT_OFFSET(PROCESS_INFORMATION, dwProcessId);
SPRT_OFFSET(PROCESS_INFORMATION, dwThreadId);

// === STARTUPINFOW ===========================================================
SPRT_SIZE(STARTUPINFOW);
SPRT_OFFSET(STARTUPINFOW, cb);
SPRT_OFFSET(STARTUPINFOW, lpReserved);
SPRT_OFFSET(STARTUPINFOW, lpDesktop);
SPRT_OFFSET(STARTUPINFOW, lpTitle);
SPRT_OFFSET(STARTUPINFOW, dwX);
SPRT_OFFSET(STARTUPINFOW, dwY);
SPRT_OFFSET(STARTUPINFOW, dwXSize);
SPRT_OFFSET(STARTUPINFOW, dwYSize);
SPRT_OFFSET(STARTUPINFOW, dwXCountChars);
SPRT_OFFSET(STARTUPINFOW, dwYCountChars);
SPRT_OFFSET(STARTUPINFOW, dwFillAttribute);
SPRT_OFFSET(STARTUPINFOW, dwFlags);
SPRT_OFFSET(STARTUPINFOW, wShowWindow);
SPRT_OFFSET(STARTUPINFOW, cbReserved2);
SPRT_OFFSET(STARTUPINFOW, lpReserved2);
SPRT_OFFSET(STARTUPINFOW, hStdInput);
SPRT_OFFSET(STARTUPINFOW, hStdOutput);
SPRT_OFFSET(STARTUPINFOW, hStdError);

// === STARTUPINFOA ===========================================================
// A distinct type from STARTUPINFOW, not an alias: only the three string members
// differ in pointee type, so the layout matches, but CreateProcessA takes this one.
SPRT_SIZE(STARTUPINFOA);
SPRT_OFFSET(STARTUPINFOA, cb);
SPRT_OFFSET(STARTUPINFOA, lpReserved);
SPRT_OFFSET(STARTUPINFOA, lpDesktop);
SPRT_OFFSET(STARTUPINFOA, lpTitle);
SPRT_OFFSET(STARTUPINFOA, dwX);
SPRT_OFFSET(STARTUPINFOA, dwY);
SPRT_OFFSET(STARTUPINFOA, dwXSize);
SPRT_OFFSET(STARTUPINFOA, dwYSize);
SPRT_OFFSET(STARTUPINFOA, dwXCountChars);
SPRT_OFFSET(STARTUPINFOA, dwYCountChars);
SPRT_OFFSET(STARTUPINFOA, dwFillAttribute);
SPRT_OFFSET(STARTUPINFOA, dwFlags);
SPRT_OFFSET(STARTUPINFOA, wShowWindow);
SPRT_OFFSET(STARTUPINFOA, cbReserved2);
SPRT_OFFSET(STARTUPINFOA, lpReserved2);
SPRT_OFFSET(STARTUPINFOA, hStdInput);
SPRT_OFFSET(STARTUPINFOA, hStdOutput);
SPRT_OFFSET(STARTUPINFOA, hStdError);

// === STARTUPINFOEXW =========================================================
SPRT_SIZE(STARTUPINFOEXW);
SPRT_OFFSET(STARTUPINFOEXW, StartupInfo);
SPRT_OFFSET(STARTUPINFOEXW, lpAttributeList);

// === STARTUPINFOEXA =========================================================
SPRT_SIZE(STARTUPINFOEXA);
SPRT_OFFSET(STARTUPINFOEXA, StartupInfo);
SPRT_OFFSET(STARTUPINFOEXA, lpAttributeList);

// === SHELLEXECUTEINFOW ======================================================
SPRT_SIZE(SHELLEXECUTEINFOW);
SPRT_OFFSET(SHELLEXECUTEINFOW, cbSize);
SPRT_OFFSET(SHELLEXECUTEINFOW, fMask);
SPRT_OFFSET(SHELLEXECUTEINFOW, hwnd);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpVerb);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpFile);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpParameters);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpDirectory);
SPRT_OFFSET(SHELLEXECUTEINFOW, nShow);
SPRT_OFFSET(SHELLEXECUTEINFOW, hInstApp);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpIDList);
SPRT_OFFSET(SHELLEXECUTEINFOW, lpClass);
SPRT_OFFSET(SHELLEXECUTEINFOW, hkeyClass);
SPRT_OFFSET(SHELLEXECUTEINFOW, dwHotKey);
SPRT_OFFSET(SHELLEXECUTEINFOW, hProcess);
// hIcon/hMonitor overlap in an anonymous union -> offsets not takeable.

// === PROCESS_MEMORY_COUNTERS ================================================
SPRT_SIZE(PROCESS_MEMORY_COUNTERS);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, cb);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, PageFaultCount);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, PeakWorkingSetSize);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, WorkingSetSize);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, QuotaPeakPagedPoolUsage);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, QuotaPagedPoolUsage);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, QuotaPeakNonPagedPoolUsage);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, QuotaNonPagedPoolUsage);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, PagefileUsage);
SPRT_OFFSET(PROCESS_MEMORY_COUNTERS, PeakPagefileUsage);

// === PROC_THREAD_ATTRIBUTE_NUM ===
SPRT_ENUM(ProcThreadAttributeParentProcess);
SPRT_ENUM(ProcThreadAttributeHandleList);
SPRT_ENUM(ProcThreadAttributeGroupAffinity);
SPRT_ENUM(ProcThreadAttributePreferredNode);
SPRT_ENUM(ProcThreadAttributeIdealProcessor);
SPRT_ENUM(ProcThreadAttributeUmsThread);
SPRT_ENUM(ProcThreadAttributeMitigationPolicy);
SPRT_ENUM(ProcThreadAttributeSecurityCapabilities);
SPRT_ENUM(ProcThreadAttributeProtectionLevel);
SPRT_ENUM(ProcThreadAttributeJobList);
SPRT_ENUM(ProcThreadAttributeChildProcessPolicy);
SPRT_ENUM(ProcThreadAttributeAllApplicationPackagesPolicy);
SPRT_ENUM(ProcThreadAttributeWin32kFilter);
SPRT_ENUM(ProcThreadAttributeSafeOpenPromptOriginClaim);
SPRT_ENUM(ProcThreadAttributeDesktopAppPolicy);
SPRT_ENUM(ProcThreadAttributePseudoConsole);
SPRT_ENUM(ProcThreadAttributeMitigationAuditPolicy);
SPRT_ENUM(ProcThreadAttributeMachineType);
SPRT_ENUM(ProcThreadAttributeComponentFilter);
SPRT_ENUM(ProcThreadAttributeEnableOptionalXStateFeatures);
SPRT_ENUM(ProcThreadAttributeTrustedApp);
SPRT_ENUM(ProcThreadAttributeSveVectorLength);

// === new values (wrapper completion) =======================================
SPRT_CONST(PROC_THREAD_ATTRIBUTE_HANDLE_LIST);
