// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/windows.h <-> Windows SDK parity. Compile-time only; see check.sh.

// Pin the SDK to Windows 10 so the newer structures (SYSTEM_LOGICAL_PROCESSOR_
// INFORMATION_EX family, JOBOBJECT_*, FILE_RENAME_INFO, FINDEX_*) are declared.
#ifndef _WIN32_WINNT
#define _WIN32_WINNT 0x0A00
#endif
#ifndef WINVER
#define WINVER 0x0A00
#endif

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/windows.h>
#include "abi_check.h"

#include <windows.h>   // SYSTEM_INFO, MEMORYSTATUSEX, SYSTEM_LOGICAL_PROCESSOR_INFORMATION,
                       // CACHE_DESCRIPTOR, CONSOLE_READCONSOLE_CONTROL, REASON_CONTEXT,
                       // LOGICAL_PROCESSOR_RELATIONSHIP, PROCESSOR_CACHE_TYPE, COMPUTER_NAME_FORMAT,
                       // LCMAP_*, NORM_*, MB_*, TIMER_*, CREATE_WAITABLE_TIMER_*, MAP_*, LOCALE_*

// SDK enum-value parity: the abi header spells these as plain enumerators inside
// namespace sprt_abi (no __SPRT_ prefix), so SPRT_CONST cannot reach them.
#define SPRT_ENUM(name) \
	static_assert((long long)(sprt_abi::name) == (long long)(name), \
			"enum " #name " != SDK " #name)

// === structs ===============================================================
SPRT_SIZE(SYSTEM_INFO);
SPRT_OFFSET(SYSTEM_INFO, dwOemId);
SPRT_OFFSET(SYSTEM_INFO, wProcessorArchitecture);
SPRT_OFFSET(SYSTEM_INFO, wReserved);
SPRT_OFFSET(SYSTEM_INFO, dwPageSize);
SPRT_OFFSET(SYSTEM_INFO, lpMinimumApplicationAddress);
SPRT_OFFSET(SYSTEM_INFO, lpMaximumApplicationAddress);
SPRT_OFFSET(SYSTEM_INFO, dwActiveProcessorMask);
SPRT_OFFSET(SYSTEM_INFO, dwNumberOfProcessors);
SPRT_OFFSET(SYSTEM_INFO, dwProcessorType);
SPRT_OFFSET(SYSTEM_INFO, dwAllocationGranularity);
SPRT_OFFSET(SYSTEM_INFO, wProcessorLevel);
SPRT_OFFSET(SYSTEM_INFO, wProcessorRevision);

SPRT_SIZE(MEMORYSTATUSEX);
SPRT_OFFSET(MEMORYSTATUSEX, dwLength);
SPRT_OFFSET(MEMORYSTATUSEX, dwMemoryLoad);
SPRT_OFFSET(MEMORYSTATUSEX, ullTotalPhys);
SPRT_OFFSET(MEMORYSTATUSEX, ullAvailPhys);
SPRT_OFFSET(MEMORYSTATUSEX, ullTotalPageFile);
SPRT_OFFSET(MEMORYSTATUSEX, ullAvailPageFile);
SPRT_OFFSET(MEMORYSTATUSEX, ullTotalVirtual);
SPRT_OFFSET(MEMORYSTATUSEX, ullAvailVirtual);
SPRT_OFFSET(MEMORYSTATUSEX, ullAvailExtendedVirtual);

SPRT_SIZE(SYSTEM_LOGICAL_PROCESSOR_INFORMATION);
SPRT_OFFSET(SYSTEM_LOGICAL_PROCESSOR_INFORMATION, ProcessorMask);
SPRT_OFFSET(SYSTEM_LOGICAL_PROCESSOR_INFORMATION, Relationship);
// DUMMYUNIONNAME: the SDK's trailing union is anonymous (DUMMYUNIONNAME macro
// expands to nothing), so its offset can't be taken; SPRT_SIZE covers it.

SPRT_SIZE(CACHE_DESCRIPTOR);
SPRT_OFFSET(CACHE_DESCRIPTOR, Level);
SPRT_OFFSET(CACHE_DESCRIPTOR, Associativity);
SPRT_OFFSET(CACHE_DESCRIPTOR, LineSize);
SPRT_OFFSET(CACHE_DESCRIPTOR, Size);
SPRT_OFFSET(CACHE_DESCRIPTOR, Type);

SPRT_SIZE(CONSOLE_READCONSOLE_CONTROL);
SPRT_OFFSET(CONSOLE_READCONSOLE_CONTROL, nLength);
SPRT_OFFSET(CONSOLE_READCONSOLE_CONTROL, nInitialChars);
SPRT_OFFSET(CONSOLE_READCONSOLE_CONTROL, dwCtrlWakeupMask);
SPRT_OFFSET(CONSOLE_READCONSOLE_CONTROL, dwControlKeyState);

SPRT_SIZE(REASON_CONTEXT);
SPRT_OFFSET(REASON_CONTEXT, Version);
SPRT_OFFSET(REASON_CONTEXT, Flags);
SPRT_OFFSET(REASON_CONTEXT, Reason);

// === enums =================================================================
SPRT_SIZE(LOGICAL_PROCESSOR_RELATIONSHIP);
SPRT_ENUM(RelationProcessorCore);
SPRT_ENUM(RelationNumaNode);
SPRT_ENUM(RelationCache);
SPRT_ENUM(RelationProcessorPackage);
SPRT_ENUM(RelationGroup);
SPRT_ENUM(RelationProcessorDie);
SPRT_ENUM(RelationNumaNodeEx);
SPRT_ENUM(RelationProcessorModule);
SPRT_ENUM(RelationAll);

SPRT_SIZE(PROCESSOR_CACHE_TYPE);
SPRT_ENUM(CacheUnified);
SPRT_ENUM(CacheInstruction);
SPRT_ENUM(CacheData);
SPRT_ENUM(CacheTrace);
SPRT_ENUM(CacheUnknown);

SPRT_SIZE(COMPUTER_NAME_FORMAT);
SPRT_ENUM(ComputerNameNetBIOS);
SPRT_ENUM(ComputerNameDnsHostname);
SPRT_ENUM(ComputerNameDnsDomain);
SPRT_ENUM(ComputerNameDnsFullyQualified);
SPRT_ENUM(ComputerNamePhysicalNetBIOS);
SPRT_ENUM(ComputerNamePhysicalDnsHostname);
SPRT_ENUM(ComputerNamePhysicalDnsDomain);
SPRT_ENUM(ComputerNamePhysicalDnsFullyQualified);
SPRT_ENUM(ComputerNameMax);

// === LCMAP_* ===============================================================
SPRT_CONST(LCMAP_LOWERCASE);
SPRT_CONST(LCMAP_UPPERCASE);
SPRT_CONST(LCMAP_TITLECASE);
SPRT_CONST(LCMAP_SORTKEY);
SPRT_CONST(LCMAP_BYTEREV);
SPRT_CONST(LCMAP_HIRAGANA);
SPRT_CONST(LCMAP_KATAKANA);
SPRT_CONST(LCMAP_HALFWIDTH);
SPRT_CONST(LCMAP_FULLWIDTH);
SPRT_CONST(LCMAP_LINGUISTIC_CASING);
SPRT_CONST(LCMAP_SIMPLIFIED_CHINESE);
SPRT_CONST(LCMAP_TRADITIONAL_CHINESE);
SPRT_CONST(LCMAP_SORTHANDLE);
SPRT_CONST(LCMAP_HASH);

// === NORM_* / LINGUISTIC_* =================================================
SPRT_CONST(NORM_IGNORECASE);
SPRT_CONST(NORM_IGNORENONSPACE);
SPRT_CONST(NORM_IGNORESYMBOLS);
SPRT_CONST(NORM_IGNOREKANATYPE);
SPRT_CONST(NORM_IGNOREWIDTH);
SPRT_CONST(NORM_LINGUISTIC_CASING);
SPRT_CONST(LINGUISTIC_IGNORECASE);
SPRT_CONST(LINGUISTIC_IGNOREDIACRITIC);

// === MB_* ==================================================================
SPRT_CONST(MB_PRECOMPOSED);
SPRT_CONST(MB_COMPOSITE);
SPRT_CONST(MB_USEGLYPHCHARS);
SPRT_CONST(MB_ERR_INVALID_CHARS);

// === MAP_* =================================================================
SPRT_CONST(MAP_FOLDCZONE);
SPRT_CONST(MAP_PRECOMPOSED);
SPRT_CONST(MAP_COMPOSITE);
SPRT_CONST(MAP_FOLDDIGITS);
SPRT_CONST(MAP_EXPAND_LIGATURES);

// === CSTR_* ================================================================
SPRT_CONST(CSTR_LESS_THAN);
SPRT_CONST(CSTR_EQUAL);
SPRT_CONST(CSTR_GREATER_THAN);

// === TIMER_* / CREATE_WAITABLE_TIMER_* =====================================
SPRT_CONST(TIMER_QUERY_STATE);
SPRT_CONST(TIMER_MODIFY_STATE);
SPRT_CONST(TIMER_ALL_ACCESS);
SPRT_CONST(CREATE_WAITABLE_TIMER_MANUAL_RESET);
SPRT_CONST(CREATE_WAITABLE_TIMER_HIGH_RESOLUTION);

// === misc integer ==========================================================
SPRT_CONST(ALL_PROCESSOR_GROUPS);
SPRT_CONST(LOCALE_NAME_MAX_LENGTH);
SPRT_CONST(LOCALE_NOUSEROVERRIDE);
SPRT_CONST(LOCALE_USE_CP_ACP);
SPRT_CONST(LOCALE_RETURN_NUMBER);
SPRT_CONST(LOCALE_RETURN_GENITIVE_NAMES);
SPRT_CONST(LOCALE_ALLOW_NEUTRAL_NAMES);

// === LOCALE_S* / LOCALE_I* LCTYPE numbers ==================================
SPRT_CONST(LOCALE_ICALENDARTYPE);
SPRT_CONST(LOCALE_ICENTURY);
SPRT_CONST(LOCALE_ICONSTRUCTEDLOCALE);
SPRT_CONST(LOCALE_ICOUNTRY);
SPRT_CONST(LOCALE_ICURRDIGITS);
SPRT_CONST(LOCALE_ICURRENCY);
SPRT_CONST(LOCALE_IDATE);
SPRT_CONST(LOCALE_IDAYLZERO);
SPRT_CONST(LOCALE_IDEFAULTANSICODEPAGE);
SPRT_CONST(LOCALE_IDEFAULTCODEPAGE);
SPRT_CONST(LOCALE_IDEFAULTCOUNTRY);
SPRT_CONST(LOCALE_IDEFAULTEBCDICCODEPAGE);
SPRT_CONST(LOCALE_IDEFAULTLANGUAGE);
SPRT_CONST(LOCALE_IDEFAULTMACCODEPAGE);
SPRT_CONST(LOCALE_IDIALINGCODE);
SPRT_CONST(LOCALE_IDIGITS);
SPRT_CONST(LOCALE_IDIGITSUBSTITUTION);
SPRT_CONST(LOCALE_IFIRSTDAYOFWEEK);
SPRT_CONST(LOCALE_IFIRSTWEEKOFYEAR);
SPRT_CONST(LOCALE_IGEOID);
SPRT_CONST(LOCALE_IINTLCURRDIGITS);
SPRT_CONST(LOCALE_ILANGUAGE);
SPRT_CONST(LOCALE_ILDATE);
SPRT_CONST(LOCALE_ILZERO);
SPRT_CONST(LOCALE_IMEASURE);
SPRT_CONST(LOCALE_IMONLZERO);
SPRT_CONST(LOCALE_INEGATIVEPERCENT);
SPRT_CONST(LOCALE_INEGCURR);
SPRT_CONST(LOCALE_INEGNUMBER);
SPRT_CONST(LOCALE_INEGSEPBYSPACE);
SPRT_CONST(LOCALE_INEGSIGNPOSN);
SPRT_CONST(LOCALE_INEGSYMPRECEDES);
SPRT_CONST(LOCALE_INEUTRAL);
SPRT_CONST(LOCALE_IOPTIONALCALENDAR);
SPRT_CONST(LOCALE_IPAPERSIZE);
SPRT_CONST(LOCALE_IPOSITIVEPERCENT);
SPRT_CONST(LOCALE_IPOSSEPBYSPACE);
SPRT_CONST(LOCALE_IPOSSIGNPOSN);
SPRT_CONST(LOCALE_IPOSSYMPRECEDES);
SPRT_CONST(LOCALE_IREADINGLAYOUT);
SPRT_CONST(LOCALE_ITIME);
SPRT_CONST(LOCALE_ITIMEMARKPOSN);
SPRT_CONST(LOCALE_ITLZERO);
SPRT_CONST(LOCALE_IUSEUTF8LEGACYACP);
SPRT_CONST(LOCALE_IUSEUTF8LEGACYOEMCP);
SPRT_CONST(LOCALE_S1159);
SPRT_CONST(LOCALE_S2359);
SPRT_CONST(LOCALE_SABBREVCTRYNAME);
SPRT_CONST(LOCALE_SABBREVDAYNAME1);
SPRT_CONST(LOCALE_SABBREVDAYNAME2);
SPRT_CONST(LOCALE_SABBREVDAYNAME3);
SPRT_CONST(LOCALE_SABBREVDAYNAME4);
SPRT_CONST(LOCALE_SABBREVDAYNAME5);
SPRT_CONST(LOCALE_SABBREVDAYNAME6);
SPRT_CONST(LOCALE_SABBREVDAYNAME7);
SPRT_CONST(LOCALE_SABBREVLANGNAME);
SPRT_CONST(LOCALE_SABBREVMONTHNAME1);
SPRT_CONST(LOCALE_SABBREVMONTHNAME10);
SPRT_CONST(LOCALE_SABBREVMONTHNAME11);
SPRT_CONST(LOCALE_SABBREVMONTHNAME12);
SPRT_CONST(LOCALE_SABBREVMONTHNAME13);
SPRT_CONST(LOCALE_SABBREVMONTHNAME2);
SPRT_CONST(LOCALE_SABBREVMONTHNAME3);
SPRT_CONST(LOCALE_SABBREVMONTHNAME4);
SPRT_CONST(LOCALE_SABBREVMONTHNAME5);
SPRT_CONST(LOCALE_SABBREVMONTHNAME6);
SPRT_CONST(LOCALE_SABBREVMONTHNAME7);
SPRT_CONST(LOCALE_SABBREVMONTHNAME8);
SPRT_CONST(LOCALE_SABBREVMONTHNAME9);
SPRT_CONST(LOCALE_SAM);
SPRT_CONST(LOCALE_SCONSOLEFALLBACKNAME);
SPRT_CONST(LOCALE_SCOUNTRY);
SPRT_CONST(LOCALE_SCURRENCY);
SPRT_CONST(LOCALE_SDATE);
SPRT_CONST(LOCALE_SDAYNAME1);
SPRT_CONST(LOCALE_SDAYNAME2);
SPRT_CONST(LOCALE_SDAYNAME3);
SPRT_CONST(LOCALE_SDAYNAME4);
SPRT_CONST(LOCALE_SDAYNAME5);
SPRT_CONST(LOCALE_SDAYNAME6);
SPRT_CONST(LOCALE_SDAYNAME7);
SPRT_CONST(LOCALE_SDECIMAL);
SPRT_CONST(LOCALE_SDURATION);
SPRT_CONST(LOCALE_SENGCOUNTRY);
SPRT_CONST(LOCALE_SENGCURRNAME);
SPRT_CONST(LOCALE_SENGLANGUAGE);
SPRT_CONST(LOCALE_SENGLISHCOUNTRYNAME);
SPRT_CONST(LOCALE_SENGLISHDISPLAYNAME);
SPRT_CONST(LOCALE_SENGLISHLANGUAGENAME);
SPRT_CONST(LOCALE_SGROUPING);
SPRT_CONST(LOCALE_SINTLSYMBOL);
SPRT_CONST(LOCALE_SISO3166CTRYNAME);
SPRT_CONST(LOCALE_SISO3166CTRYNAME2);
SPRT_CONST(LOCALE_SISO639LANGNAME);
SPRT_CONST(LOCALE_SISO639LANGNAME2);
SPRT_CONST(LOCALE_SKEYBOARDSTOINSTALL);
SPRT_CONST(LOCALE_SLANGDISPLAYNAME);
SPRT_CONST(LOCALE_SLANGUAGE);
SPRT_CONST(LOCALE_SLIST);
SPRT_CONST(LOCALE_SLOCALIZEDCOUNTRYNAME);
SPRT_CONST(LOCALE_SLOCALIZEDDISPLAYNAME);
SPRT_CONST(LOCALE_SLOCALIZEDLANGUAGENAME);
SPRT_CONST(LOCALE_SLONGDATE);
SPRT_CONST(LOCALE_SMONDECIMALSEP);
SPRT_CONST(LOCALE_SMONGROUPING);
SPRT_CONST(LOCALE_SMONTHDAY);
SPRT_CONST(LOCALE_SMONTHNAME1);
SPRT_CONST(LOCALE_SMONTHNAME10);
SPRT_CONST(LOCALE_SMONTHNAME11);
SPRT_CONST(LOCALE_SMONTHNAME12);
SPRT_CONST(LOCALE_SMONTHNAME13);
SPRT_CONST(LOCALE_SMONTHNAME2);
SPRT_CONST(LOCALE_SMONTHNAME3);
SPRT_CONST(LOCALE_SMONTHNAME4);
SPRT_CONST(LOCALE_SMONTHNAME5);
SPRT_CONST(LOCALE_SMONTHNAME6);
SPRT_CONST(LOCALE_SMONTHNAME7);
SPRT_CONST(LOCALE_SMONTHNAME8);
SPRT_CONST(LOCALE_SMONTHNAME9);
SPRT_CONST(LOCALE_SMONTHOUSANDSEP);
SPRT_CONST(LOCALE_SNAME);
SPRT_CONST(LOCALE_SNAN);
SPRT_CONST(LOCALE_SNATIVECOUNTRYNAME);
SPRT_CONST(LOCALE_SNATIVECTRYNAME);
SPRT_CONST(LOCALE_SNATIVECURRNAME);
SPRT_CONST(LOCALE_SNATIVEDIGITS);
SPRT_CONST(LOCALE_SNATIVEDISPLAYNAME);
SPRT_CONST(LOCALE_SNATIVELANGNAME);
SPRT_CONST(LOCALE_SNATIVELANGUAGENAME);
SPRT_CONST(LOCALE_SNEGATIVESIGN);
SPRT_CONST(LOCALE_SNEGINFINITY);
SPRT_CONST(LOCALE_SOPENTYPELANGUAGETAG);
SPRT_CONST(LOCALE_SPARENT);
SPRT_CONST(LOCALE_SPERCENT);
SPRT_CONST(LOCALE_SPERMILLE);
SPRT_CONST(LOCALE_SPM);
SPRT_CONST(LOCALE_SPOSINFINITY);
SPRT_CONST(LOCALE_SPOSITIVESIGN);
SPRT_CONST(LOCALE_SRELATIVELONGDATE);
SPRT_CONST(LOCALE_SSCRIPTS);
SPRT_CONST(LOCALE_SSHORTDATE);
SPRT_CONST(LOCALE_SSHORTESTAM);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME1);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME2);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME3);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME4);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME5);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME6);
SPRT_CONST(LOCALE_SSHORTESTDAYNAME7);
SPRT_CONST(LOCALE_SSHORTESTPM);
SPRT_CONST(LOCALE_SSHORTTIME);
SPRT_CONST(LOCALE_SSORTLOCALE);
SPRT_CONST(LOCALE_SSORTNAME);
SPRT_CONST(LOCALE_STHOUSAND);
SPRT_CONST(LOCALE_STIME);
SPRT_CONST(LOCALE_STIMEFORMAT);
SPRT_CONST(LOCALE_SYEARMONTH);

// === OMITTED ===============================================================
// LOCALE_NAME_USER_DEFAULT / _INVARIANT / _SYSTEM_DEFAULT : wide-string / nullptr
//   values (not integer-comparable).  NLSVERSIONINFO / OBJECT_ATTRIBUTES: not
//   pinned here (opaque / covered elsewhere).  __SPRT_WINBASEAPI: empty
//   attribute macro, nothing to compare.

// === LOCALE_FONTSIGNATURE + NLSVERSIONINFO (winnls.h) ======================
SPRT_CONST(LOCALE_FONTSIGNATURE);
SPRT_SIZE(NLSVERSIONINFO);
SPRT_OFFSET(NLSVERSIONINFO, dwNLSVersionInfoSize);
SPRT_OFFSET(NLSVERSIONINFO, dwNLSVersion);
SPRT_OFFSET(NLSVERSIONINFO, dwDefinedVersion);
SPRT_OFFSET(NLSVERSIONINFO, dwEffectiveId);
SPRT_OFFSET(NLSVERSIONINFO, guidCustomVersion);

// === new scalar flags (winbase.h / winnt.h) ================================
SPRT_CONST(LTP_PC_SMT);
SPRT_CONST(DRIVE_UNKNOWN);
SPRT_CONST(DRIVE_NO_ROOT_DIR);
SPRT_CONST(DRIVE_REMOVABLE);
SPRT_CONST(DRIVE_FIXED);
SPRT_CONST(DRIVE_REMOTE);
SPRT_CONST(DRIVE_CDROM);
SPRT_CONST(DRIVE_RAMDISK);
SPRT_CONST(VOLUME_NAME_DOS);
SPRT_CONST(VOLUME_NAME_GUID);
SPRT_CONST(VOLUME_NAME_NT);
SPRT_CONST(VOLUME_NAME_NONE);
SPRT_CONST(FIND_FIRST_EX_CASE_SENSITIVE);
SPRT_CONST(FIND_FIRST_EX_LARGE_FETCH);
SPRT_CONST(FIND_FIRST_EX_ON_DISK_ENTRIES_ONLY);

// === SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX family (winnt.h) ==============
// NB: the SDK spells the internal unions DUMMYUNIONNAME (named), while abi uses
// anonymous unions. sizeof/alignment are unaffected, but offsetof cannot reach a
// member that lives inside the SDK's named union, so only direct (non-union)
// fields are offset-checked here; SPRT_SIZE covers the union region.
SPRT_SIZE(PROCESSOR_RELATIONSHIP);
SPRT_OFFSET(PROCESSOR_RELATIONSHIP, Flags);
SPRT_OFFSET(PROCESSOR_RELATIONSHIP, EfficiencyClass);
SPRT_OFFSET(PROCESSOR_RELATIONSHIP, GroupCount);
SPRT_OFFSET(PROCESSOR_RELATIONSHIP, GroupMask); // direct member in both

SPRT_SIZE(NUMA_NODE_RELATIONSHIP);
SPRT_OFFSET(NUMA_NODE_RELATIONSHIP, NodeNumber);
SPRT_OFFSET(NUMA_NODE_RELATIONSHIP, GroupCount);

SPRT_SIZE(CACHE_RELATIONSHIP);
SPRT_OFFSET(CACHE_RELATIONSHIP, Level);
SPRT_OFFSET(CACHE_RELATIONSHIP, Associativity);
SPRT_OFFSET(CACHE_RELATIONSHIP, LineSize);
SPRT_OFFSET(CACHE_RELATIONSHIP, CacheSize);
SPRT_OFFSET(CACHE_RELATIONSHIP, Type);
SPRT_OFFSET(CACHE_RELATIONSHIP, GroupCount);

SPRT_SIZE(PROCESSOR_GROUP_INFO);
SPRT_OFFSET(PROCESSOR_GROUP_INFO, MaximumProcessorCount);
SPRT_OFFSET(PROCESSOR_GROUP_INFO, ActiveProcessorCount);
SPRT_OFFSET(PROCESSOR_GROUP_INFO, ActiveProcessorMask);

SPRT_SIZE(GROUP_RELATIONSHIP);
SPRT_OFFSET(GROUP_RELATIONSHIP, MaximumGroupCount);
SPRT_OFFSET(GROUP_RELATIONSHIP, ActiveGroupCount);
SPRT_OFFSET(GROUP_RELATIONSHIP, GroupInfo); // direct member in both

SPRT_SIZE(SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX);
SPRT_OFFSET(SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, Relationship);
SPRT_OFFSET(SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX, Size);

// === IO_COUNTERS + job-object limit structures (winnt.h) ===================
SPRT_SIZE(IO_COUNTERS);
SPRT_OFFSET(IO_COUNTERS, ReadOperationCount);
SPRT_OFFSET(IO_COUNTERS, WriteOperationCount);
SPRT_OFFSET(IO_COUNTERS, OtherOperationCount);
SPRT_OFFSET(IO_COUNTERS, ReadTransferCount);
SPRT_OFFSET(IO_COUNTERS, WriteTransferCount);
SPRT_OFFSET(IO_COUNTERS, OtherTransferCount);

SPRT_SIZE(JOBOBJECT_BASIC_LIMIT_INFORMATION);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, PerProcessUserTimeLimit);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, PerJobUserTimeLimit);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, LimitFlags);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, MinimumWorkingSetSize);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, MaximumWorkingSetSize);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, ActiveProcessLimit);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, Affinity);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, PriorityClass);
SPRT_OFFSET(JOBOBJECT_BASIC_LIMIT_INFORMATION, SchedulingClass);

SPRT_SIZE(JOBOBJECT_EXTENDED_LIMIT_INFORMATION);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, BasicLimitInformation);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, IoInfo);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, ProcessMemoryLimit);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, JobMemoryLimit);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, PeakProcessMemoryUsed);
SPRT_OFFSET(JOBOBJECT_EXTENDED_LIMIT_INFORMATION, PeakJobMemoryUsed);

// === SetFileInformationByHandle structs (minwinbase.h) =====================
// (single-field struct; SPRT_SIZE fully pins it. The lone field is named
// DeleteFile, which the Win32 DeleteFile->DeleteFileA/W macro would rewrite in an
// offsetof, so no field offset is taken.)
SPRT_SIZE(FILE_DISPOSITION_INFO);

// FILE_RENAME_INFO leads with a DUMMYUNIONNAME (ReplaceIfExists / Flags) in the
// SDK; check size + the fields after the union.
SPRT_SIZE(FILE_RENAME_INFO);
SPRT_OFFSET(FILE_RENAME_INFO, RootDirectory);
SPRT_OFFSET(FILE_RENAME_INFO, FileNameLength);
SPRT_OFFSET(FILE_RENAME_INFO, FileName);

// === enums (winnt.h / minwinbase.h) ========================================
SPRT_ENUM(JobObjectBasicAccountingInformation);
SPRT_ENUM(JobObjectBasicLimitInformation);
SPRT_ENUM(JobObjectBasicProcessIdList);
SPRT_ENUM(JobObjectBasicUIRestrictions);
SPRT_ENUM(JobObjectSecurityLimitInformation);
SPRT_ENUM(JobObjectEndOfJobTimeInformation);
SPRT_ENUM(JobObjectAssociateCompletionPortInformation);
SPRT_ENUM(JobObjectBasicAndIoAccountingInformation);
SPRT_ENUM(JobObjectExtendedLimitInformation);
SPRT_ENUM(JobObjectJobSetInformation);
SPRT_ENUM(JobObjectGroupInformation);

SPRT_ENUM(FindExInfoStandard);
SPRT_ENUM(FindExInfoBasic);
SPRT_ENUM(FindExInfoMaxInfoLevel);
SPRT_ENUM(FindExSearchNameMatch);
SPRT_ENUM(FindExSearchLimitToDirectories);
SPRT_ENUM(FindExSearchLimitToDevices);
SPRT_ENUM(FindExSearchMaxSearchOp);

// === new values (wrapper completion) =======================================
// RIP_INFO / hard-error severity levels (winbase.h).
SPRT_CONST(SLE_ERROR);
SPRT_CONST(SLE_MINORERROR);
SPRT_CONST(SLE_WARNING);

// MEMORY_RESOURCE_NOTIFICATION_TYPE (memoryapi.h).
SPRT_ENUM(LowMemoryResourceNotification);
SPRT_ENUM(HighMemoryResourceNotification);
