// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/debug_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/debug_api.h>
#include "abi_check.h"

#include <windows.h>
#include <dbghelp.h>   // ADDRESS64, KDHELP64, STACKFRAME64, IMAGEHLP_SYMBOL64, IMAGEHLP_LINE64, SYMOPT_*

// enum-value parity: sprt_abi::<name> vs the SDK's <name> (no __SPRT_ macro form).
#define SPRT_ENUM(name) \
	static_assert((long long)(sprt_abi::name) == (long long)(name), \
			"sprt_abi::" #name " != SDK " #name)

// === SYMOPT_* constants ====================================================
SPRT_CONST(SYMOPT_CASE_INSENSITIVE);
SPRT_CONST(SYMOPT_UNDNAME);
SPRT_CONST(SYMOPT_DEFERRED_LOADS);
SPRT_CONST(SYMOPT_NO_CPP);
SPRT_CONST(SYMOPT_LOAD_LINES);
SPRT_CONST(SYMOPT_OMAP_FIND_NEAREST);
SPRT_CONST(SYMOPT_LOAD_ANYTHING);
SPRT_CONST(SYMOPT_IGNORE_CVREC);
SPRT_CONST(SYMOPT_NO_UNQUALIFIED_LOADS);
SPRT_CONST(SYMOPT_FAIL_CRITICAL_ERRORS);
SPRT_CONST(SYMOPT_EXACT_SYMBOLS);
SPRT_CONST(SYMOPT_ALLOW_ABSOLUTE_SYMBOLS);
SPRT_CONST(SYMOPT_IGNORE_NT_SYMPATH);
SPRT_CONST(SYMOPT_INCLUDE_32BIT_MODULES);
SPRT_CONST(SYMOPT_PUBLICS_ONLY);
SPRT_CONST(SYMOPT_NO_PUBLICS);
SPRT_CONST(SYMOPT_AUTO_PUBLICS);
SPRT_CONST(SYMOPT_NO_IMAGE_SEARCH);
SPRT_CONST(SYMOPT_SECURE);
SPRT_CONST(SYMOPT_NO_PROMPTS);
SPRT_CONST(SYMOPT_OVERWRITE);
SPRT_CONST(SYMOPT_IGNORE_IMAGEDIR);
SPRT_CONST(SYMOPT_FLAT_DIRECTORY);
SPRT_CONST(SYMOPT_FAVOR_COMPRESSED);
SPRT_CONST(SYMOPT_ALLOW_ZERO_ADDRESS);
SPRT_CONST(SYMOPT_DISABLE_SYMSRV_AUTODETECT);
SPRT_CONST(SYMOPT_READONLY_CACHE);
SPRT_CONST(SYMOPT_SYMPATH_LAST);
SPRT_CONST(SYMOPT_DISABLE_FAST_SYMBOLS);
SPRT_CONST(SYMOPT_DISABLE_SYMSRV_TIMEOUT);
SPRT_CONST(SYMOPT_DISABLE_SRVSTAR_ON_STARTUP);
SPRT_CONST(SYMOPT_DEBUG);

// === enum ADDRESS_MODE =====================================================
SPRT_SIZE(ADDRESS_MODE);
SPRT_ENUM(AddrMode1616);
SPRT_ENUM(AddrMode1632);
SPRT_ENUM(AddrModeReal);
SPRT_ENUM(AddrModeFlat);

// === ADDRESS64 =============================================================
SPRT_SIZE(ADDRESS64);
SPRT_OFFSET(ADDRESS64, Offset);
SPRT_OFFSET(ADDRESS64, Segment);
SPRT_OFFSET(ADDRESS64, Mode);

// === KDHELP64 ==============================================================
SPRT_SIZE(KDHELP64);
SPRT_OFFSET(KDHELP64, Thread);
SPRT_OFFSET(KDHELP64, ThCallbackStack);
SPRT_OFFSET(KDHELP64, ThCallbackBStore);
SPRT_OFFSET(KDHELP64, NextCallback);
SPRT_OFFSET(KDHELP64, FramePointer);
SPRT_OFFSET(KDHELP64, KiCallUserMode);
SPRT_OFFSET(KDHELP64, KeUserCallbackDispatcher);
SPRT_OFFSET(KDHELP64, SystemRangeStart);
SPRT_OFFSET(KDHELP64, KiUserExceptionDispatcher);
SPRT_OFFSET(KDHELP64, StackBase);
SPRT_OFFSET(KDHELP64, StackLimit);
SPRT_OFFSET(KDHELP64, BuildVersion);
SPRT_OFFSET(KDHELP64, RetpolineStubFunctionTableSize);
SPRT_OFFSET(KDHELP64, RetpolineStubFunctionTable);
SPRT_OFFSET(KDHELP64, RetpolineStubOffset);
SPRT_OFFSET(KDHELP64, RetpolineStubSize);
SPRT_OFFSET(KDHELP64, Reserved0);

// === STACKFRAME64 ==========================================================
SPRT_SIZE(STACKFRAME64);
SPRT_OFFSET(STACKFRAME64, AddrPC);
SPRT_OFFSET(STACKFRAME64, AddrReturn);
SPRT_OFFSET(STACKFRAME64, AddrFrame);
SPRT_OFFSET(STACKFRAME64, AddrStack);
SPRT_OFFSET(STACKFRAME64, AddrBStore);
SPRT_OFFSET(STACKFRAME64, FuncTableEntry);
SPRT_OFFSET(STACKFRAME64, Params);
SPRT_OFFSET(STACKFRAME64, Far);
SPRT_OFFSET(STACKFRAME64, Virtual);
SPRT_OFFSET(STACKFRAME64, Reserved);
SPRT_OFFSET(STACKFRAME64, KdHelp);

// === IMAGEHLP_SYMBOL64 =====================================================
SPRT_SIZE(IMAGEHLP_SYMBOL64);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, SizeOfStruct);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, Address);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, Size);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, Flags);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, MaxNameLength);
SPRT_OFFSET(IMAGEHLP_SYMBOL64, Name);

// === IMAGEHLP_LINE64 =======================================================
SPRT_SIZE(IMAGEHLP_LINE64);
SPRT_OFFSET(IMAGEHLP_LINE64, SizeOfStruct);
SPRT_OFFSET(IMAGEHLP_LINE64, Key);
SPRT_OFFSET(IMAGEHLP_LINE64, LineNumber);
SPRT_OFFSET(IMAGEHLP_LINE64, FileName);
SPRT_OFFSET(IMAGEHLP_LINE64, Address);
