// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/dl_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/dl_api.h>
#include "abi_check.h"

#include <windows.h>   // IMAGE_* live in winnt.h via windows.h; MEM_*/PAGE_* too
#include <winternl.h>   // PEB, PEB_LDR_DATA, LDR_DATA_TABLE_ENTRY (Reserved[]-padded subset)

// === signatures / directory count ==========================================
SPRT_CONST(IMAGE_NUMBEROF_DIRECTORY_ENTRIES);
SPRT_CONST(IMAGE_DOS_SIGNATURE);
SPRT_CONST(IMAGE_OS2_SIGNATURE);
SPRT_CONST(IMAGE_OS2_SIGNATURE_LE);
SPRT_CONST(IMAGE_VXD_SIGNATURE);
SPRT_CONST(IMAGE_NT_SIGNATURE);

// === optional-header magics ================================================
SPRT_CONST(IMAGE_NT_OPTIONAL_HDR32_MAGIC);
SPRT_CONST(IMAGE_NT_OPTIONAL_HDR64_MAGIC);
SPRT_CONST(IMAGE_ROM_OPTIONAL_HDR_MAGIC);

// === MEM_* ==================================================================
SPRT_CONST(MEM_COMMIT);
SPRT_CONST(MEM_RESERVE);
SPRT_CONST(MEM_REPLACE_PLACEHOLDER);
SPRT_CONST(MEM_RESERVE_PLACEHOLDER);
SPRT_CONST(MEM_RESET);
SPRT_CONST(MEM_TOP_DOWN);
SPRT_CONST(MEM_WRITE_WATCH);
SPRT_CONST(MEM_PHYSICAL);
SPRT_CONST(MEM_ROTATE);
SPRT_CONST(MEM_DIFFERENT_IMAGE_BASE_OK);
SPRT_CONST(MEM_RESET_UNDO);
SPRT_CONST(MEM_LARGE_PAGES);
SPRT_CONST(MEM_4MB_PAGES);
SPRT_CONST(MEM_64K_PAGES);
SPRT_CONST(MEM_UNMAP_WITH_TRANSIENT_BOOST);
SPRT_CONST(MEM_COALESCE_PLACEHOLDERS);
SPRT_CONST(MEM_PRESERVE_PLACEHOLDER);
SPRT_CONST(MEM_DECOMMIT);
SPRT_CONST(MEM_RELEASE);
SPRT_CONST(MEM_FREE);

// === PAGE_* =================================================================
SPRT_CONST(PAGE_NOACCESS);
SPRT_CONST(PAGE_READONLY);
SPRT_CONST(PAGE_READWRITE);
SPRT_CONST(PAGE_WRITECOPY);
SPRT_CONST(PAGE_EXECUTE);
SPRT_CONST(PAGE_EXECUTE_READ);
SPRT_CONST(PAGE_EXECUTE_READWRITE);
SPRT_CONST(PAGE_EXECUTE_WRITECOPY);
SPRT_CONST(PAGE_GUARD);
SPRT_CONST(PAGE_NOCACHE);
SPRT_CONST(PAGE_WRITECOMBINE);

// === IMAGE_DIRECTORY_ENTRY_* ================================================
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_EXPORT);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_IMPORT);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_RESOURCE);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_EXCEPTION);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_SECURITY);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_BASERELOC);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_DEBUG);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_ARCHITECTURE);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_GLOBALPTR);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_TLS);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_IAT);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT);
SPRT_CONST(IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR);

// === GetModuleHandleEx flags ================================================
SPRT_CONST(GET_MODULE_HANDLE_EX_FLAG_PIN);
SPRT_CONST(GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT);
SPRT_CONST(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS);

// === DllMain reasons ========================================================
SPRT_CONST(DLL_PROCESS_ATTACH);
SPRT_CONST(DLL_THREAD_ATTACH);
SPRT_CONST(DLL_THREAD_DETACH);
SPRT_CONST(DLL_PROCESS_DETACH);

// === GetUserObjectInformation indices =======================================
SPRT_CONST(UOI_FLAGS);
SPRT_CONST(UOI_NAME);
SPRT_CONST(UOI_TYPE);
SPRT_CONST(UOI_USER_SID);
SPRT_CONST(UOI_HEAPSIZE);
SPRT_CONST(UOI_IO);
SPRT_CONST(UOI_TIMERPROC_EXCEPTION_SUPPRESSION);

// === LoadLibraryEx search-path flags ========================================
SPRT_CONST(LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR);
SPRT_CONST(LOAD_LIBRARY_SEARCH_APPLICATION_DIR);
SPRT_CONST(LOAD_LIBRARY_SEARCH_USER_DIRS);
SPRT_CONST(LOAD_LIBRARY_SEARCH_SYSTEM32);
SPRT_CONST(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);

// === IMAGE_DOS_HEADER =======================================================
SPRT_SIZE(IMAGE_DOS_HEADER);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_magic);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_cblp);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_cp);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_crlc);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_cparhdr);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_minalloc);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_maxalloc);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_ss);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_sp);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_csum);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_ip);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_cs);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_lfarlc);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_ovno);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_res);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_oemid);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_oeminfo);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_res2);
SPRT_OFFSET(IMAGE_DOS_HEADER, e_lfanew);

// === IMAGE_FILE_HEADER ======================================================
SPRT_SIZE(IMAGE_FILE_HEADER);
SPRT_OFFSET(IMAGE_FILE_HEADER, Machine);
SPRT_OFFSET(IMAGE_FILE_HEADER, NumberOfSections);
SPRT_OFFSET(IMAGE_FILE_HEADER, TimeDateStamp);
SPRT_OFFSET(IMAGE_FILE_HEADER, PointerToSymbolTable);
SPRT_OFFSET(IMAGE_FILE_HEADER, NumberOfSymbols);
SPRT_OFFSET(IMAGE_FILE_HEADER, SizeOfOptionalHeader);
SPRT_OFFSET(IMAGE_FILE_HEADER, Characteristics);

// === IMAGE_DATA_DIRECTORY ===================================================
SPRT_SIZE(IMAGE_DATA_DIRECTORY);
SPRT_OFFSET(IMAGE_DATA_DIRECTORY, VirtualAddress);
SPRT_OFFSET(IMAGE_DATA_DIRECTORY, Size);

// === IMAGE_OPTIONAL_HEADER32 ================================================
SPRT_SIZE(IMAGE_OPTIONAL_HEADER32);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, Magic);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MajorLinkerVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MinorLinkerVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfCode);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfInitializedData);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfUninitializedData);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, AddressOfEntryPoint);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, BaseOfCode);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, BaseOfData);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, ImageBase);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SectionAlignment);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, FileAlignment);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MajorOperatingSystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MinorOperatingSystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MajorImageVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MinorImageVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MajorSubsystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, MinorSubsystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, Win32VersionValue);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfImage);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfHeaders);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, CheckSum);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, Subsystem);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, DllCharacteristics);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfStackReserve);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfStackCommit);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfHeapReserve);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, SizeOfHeapCommit);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, LoaderFlags);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, NumberOfRvaAndSizes);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER32, DataDirectory);

// === IMAGE_OPTIONAL_HEADER64 ================================================
SPRT_SIZE(IMAGE_OPTIONAL_HEADER64);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, Magic);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MajorLinkerVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MinorLinkerVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfCode);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfInitializedData);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfUninitializedData);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, AddressOfEntryPoint);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, BaseOfCode);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, ImageBase);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SectionAlignment);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, FileAlignment);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MajorOperatingSystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MinorOperatingSystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MajorImageVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MinorImageVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MajorSubsystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, MinorSubsystemVersion);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, Win32VersionValue);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfImage);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfHeaders);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, CheckSum);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, Subsystem);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, DllCharacteristics);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfStackReserve);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfStackCommit);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfHeapReserve);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, SizeOfHeapCommit);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, LoaderFlags);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, NumberOfRvaAndSizes);
SPRT_OFFSET(IMAGE_OPTIONAL_HEADER64, DataDirectory);

// === IMAGE_OPTIONAL_HEADER (arch-selective typedef; _WIN64 -> 64) ==========
SPRT_SIZE(IMAGE_OPTIONAL_HEADER);

// === IMAGE_NT_HEADERS32 =====================================================
SPRT_SIZE(IMAGE_NT_HEADERS32);
SPRT_OFFSET(IMAGE_NT_HEADERS32, Signature);
SPRT_OFFSET(IMAGE_NT_HEADERS32, FileHeader);
SPRT_OFFSET(IMAGE_NT_HEADERS32, OptionalHeader);

// === IMAGE_NT_HEADERS64 =====================================================
SPRT_SIZE(IMAGE_NT_HEADERS64);
SPRT_OFFSET(IMAGE_NT_HEADERS64, Signature);
SPRT_OFFSET(IMAGE_NT_HEADERS64, FileHeader);
SPRT_OFFSET(IMAGE_NT_HEADERS64, OptionalHeader);

// === IMAGE_NT_HEADERS (arch-selective typedef; _WIN64 -> 64) ===============
SPRT_SIZE(IMAGE_NT_HEADERS);

// === IMAGE_EXPORT_DIRECTORY =================================================
SPRT_SIZE(IMAGE_EXPORT_DIRECTORY);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, Characteristics);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, TimeDateStamp);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, MajorVersion);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, MinorVersion);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, Name);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, Base);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, NumberOfFunctions);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, NumberOfNames);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, AddressOfFunctions);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, AddressOfNames);
SPRT_OFFSET(IMAGE_EXPORT_DIRECTORY, AddressOfNameOrdinals);

// === IMAGE_IMPORT_DESCRIPTOR (leading anonymous union) ======================
SPRT_SIZE(IMAGE_IMPORT_DESCRIPTOR);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, Characteristics);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, OriginalFirstThunk);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, TimeDateStamp);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, ForwarderChain);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, Name);
SPRT_OFFSET(IMAGE_IMPORT_DESCRIPTOR, FirstThunk);

// === IMAGE_TLS_DIRECTORY64 (trailing anonymous union; bitfields skipped) ====
SPRT_SIZE(IMAGE_TLS_DIRECTORY64);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, StartAddressOfRawData);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, EndAddressOfRawData);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, AddressOfIndex);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, AddressOfCallBacks);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, SizeOfZeroFill);
SPRT_OFFSET(IMAGE_TLS_DIRECTORY64, Characteristics);

// === MEMORY_BASIC_INFORMATION ==============================================
SPRT_SIZE(MEMORY_BASIC_INFORMATION);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, BaseAddress);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, AllocationBase);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, AllocationProtect);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, PartitionId);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, RegionSize);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, State);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, Protect);
SPRT_OFFSET(MEMORY_BASIC_INFORMATION, Type);

// OMITTED (SPRT-only / no SDK equivalent or not integer-comparable):
//   - PIMAGE_TLS_CALLBACK (function-pointer typedef, not a constant/struct)
//   - _LDR_DATA_TABLE_ENTRY / _PEB_LDR_DATA / _PEB: SPRT-private loader views
//     whose SDK counterparts are Reserved[]-padded and do not match field-for-field.
//   - IMAGE_ROM_OPTIONAL_HEADER: present but not part of the requested surface.
//   - IMAGE_NT_OPTIONAL_HDR_MAGIC: only an unprefixed arch-selective macro (no __SPRT_ form).

// === PEB family (winternl.h) ===============================================
// abi keeps the full ntdll layout (the loader reads named fields the SDK hides
// behind Reserved[]); sizeof intentionally differs, so only the offsets of the
// fields BOTH the abi and the SDK name are pinned.
SPRT_OFFSET(PEB, BeingDebugged);
SPRT_OFFSET(PEB, Ldr);
SPRT_OFFSET(PEB_LDR_DATA, InMemoryOrderModuleList);
SPRT_OFFSET(LDR_DATA_TABLE_ENTRY, InMemoryOrderLinks);
SPRT_OFFSET(LDR_DATA_TABLE_ENTRY, DllBase);
SPRT_OFFSET(LDR_DATA_TABLE_ENTRY, FullDllName);

// === IMAGE_NT_OPTIONAL_HDR_MAGIC + IMAGE_ROM_OPTIONAL_HEADER ================
SPRT_CONST(IMAGE_NT_OPTIONAL_HDR_MAGIC);
SPRT_SIZE(IMAGE_ROM_OPTIONAL_HEADER);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, Magic);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, MajorLinkerVersion);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, SizeOfCode);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, AddressOfEntryPoint);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, BaseOfCode);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, BaseOfData);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, BaseOfBss);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, GprMask);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, CprMask);
SPRT_OFFSET(IMAGE_ROM_OPTIONAL_HEADER, GpValue);
