// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// abi/file_api.h <-> Windows SDK parity. Compile-time only; see check.sh.

#define SPRT_ABI_HEADER <sprt/wrappers/windows/abi/file_api.h>
#include "abi_check.h"

#include <windows.h> // WIN32_FIND_DATA*, BY_HANDLE_FILE_INFORMATION, FILE_* / CREATE_* / OPEN_* / PIPE_* constants
#include <winternl.h>

// === CreateFile disposition ================================================
SPRT_CONST(CREATE_NEW);
SPRT_CONST(CREATE_ALWAYS);
SPRT_CONST(OPEN_EXISTING);
SPRT_CONST(OPEN_ALWAYS);
SPRT_CONST(TRUNCATE_EXISTING);

// === invalid sentinels (integer-valued casts) ==============================
SPRT_CONST(INVALID_FILE_SIZE);
SPRT_CONST(INVALID_SET_FILE_POINTER);
SPRT_CONST(INVALID_FILE_ATTRIBUTES);

// === specific file access rights ===========================================
SPRT_CONST(FILE_READ_DATA);
SPRT_CONST(FILE_LIST_DIRECTORY);
SPRT_CONST(FILE_WRITE_DATA);
SPRT_CONST(FILE_ADD_FILE);
SPRT_CONST(FILE_APPEND_DATA);
SPRT_CONST(FILE_ADD_SUBDIRECTORY);
SPRT_CONST(FILE_CREATE_PIPE_INSTANCE);
SPRT_CONST(FILE_READ_EA);
SPRT_CONST(FILE_WRITE_EA);
SPRT_CONST(FILE_EXECUTE);
SPRT_CONST(FILE_TRAVERSE);
SPRT_CONST(FILE_DELETE_CHILD);
SPRT_CONST(FILE_READ_ATTRIBUTES);
SPRT_CONST(FILE_WRITE_ATTRIBUTES);
SPRT_CONST(FILE_ALL_ACCESS);
SPRT_CONST(FILE_GENERIC_READ);
SPRT_CONST(FILE_GENERIC_WRITE);
SPRT_CONST(FILE_GENERIC_EXECUTE);

// === share modes ===========================================================
SPRT_CONST(FILE_SHARE_READ);
SPRT_CONST(FILE_SHARE_WRITE);
SPRT_CONST(FILE_SHARE_DELETE);

// === file attributes =======================================================
SPRT_CONST(FILE_ATTRIBUTE_READONLY);
SPRT_CONST(FILE_ATTRIBUTE_HIDDEN);
SPRT_CONST(FILE_ATTRIBUTE_SYSTEM);
SPRT_CONST(FILE_ATTRIBUTE_DIRECTORY);
SPRT_CONST(FILE_ATTRIBUTE_ARCHIVE);
SPRT_CONST(FILE_ATTRIBUTE_DEVICE);
SPRT_CONST(FILE_ATTRIBUTE_NORMAL);
SPRT_CONST(FILE_ATTRIBUTE_TEMPORARY);
SPRT_CONST(FILE_ATTRIBUTE_SPARSE_FILE);
SPRT_CONST(FILE_ATTRIBUTE_REPARSE_POINT);
SPRT_CONST(FILE_ATTRIBUTE_COMPRESSED);
SPRT_CONST(FILE_ATTRIBUTE_OFFLINE);
SPRT_CONST(FILE_ATTRIBUTE_NOT_CONTENT_INDEXED);
SPRT_CONST(FILE_ATTRIBUTE_ENCRYPTED);
SPRT_CONST(FILE_ATTRIBUTE_INTEGRITY_STREAM);
SPRT_CONST(FILE_ATTRIBUTE_VIRTUAL);
SPRT_CONST(FILE_ATTRIBUTE_NO_SCRUB_DATA);
SPRT_CONST(FILE_ATTRIBUTE_EA);
SPRT_CONST(FILE_ATTRIBUTE_PINNED);
SPRT_CONST(FILE_ATTRIBUTE_UNPINNED);
SPRT_CONST(FILE_ATTRIBUTE_RECALL_ON_OPEN);
SPRT_CONST(FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS);

// === filesystem support flags (GetVolumeInformation) =======================
SPRT_CONST(FILE_VOLUME_IS_COMPRESSED);
SPRT_CONST(FILE_SUPPORTS_OBJECT_IDS);
SPRT_CONST(FILE_SUPPORTS_ENCRYPTION);
SPRT_CONST(FILE_NAMED_STREAMS);
SPRT_CONST(FILE_READ_ONLY_VOLUME);
SPRT_CONST(FILE_SEQUENTIAL_WRITE_ONCE);
SPRT_CONST(FILE_SUPPORTS_TRANSACTIONS);
SPRT_CONST(FILE_SUPPORTS_HARD_LINKS);
SPRT_CONST(FILE_SUPPORTS_EXTENDED_ATTRIBUTES);
SPRT_CONST(FILE_SUPPORTS_OPEN_BY_FILE_ID);
SPRT_CONST(FILE_SUPPORTS_USN_JOURNAL);
SPRT_CONST(FILE_SUPPORTS_INTEGRITY_STREAMS);
SPRT_CONST(FILE_SUPPORTS_BLOCK_REFCOUNTING);
SPRT_CONST(FILE_SUPPORTS_SPARSE_VDL);
SPRT_CONST(FILE_DAX_VOLUME);
SPRT_CONST(FILE_SUPPORTS_GHOSTING);

// === CreateFile flags ======================================================
SPRT_CONST(FILE_FLAG_WRITE_THROUGH);
SPRT_CONST(FILE_FLAG_OVERLAPPED);
SPRT_CONST(FILE_FLAG_NO_BUFFERING);
SPRT_CONST(FILE_FLAG_RANDOM_ACCESS);
SPRT_CONST(FILE_FLAG_SEQUENTIAL_SCAN);
SPRT_CONST(FILE_FLAG_DELETE_ON_CLOSE);
SPRT_CONST(FILE_FLAG_BACKUP_SEMANTICS);
SPRT_CONST(FILE_FLAG_POSIX_SEMANTICS);
SPRT_CONST(FILE_FLAG_SESSION_AWARE);
SPRT_CONST(FILE_FLAG_OPEN_REPARSE_POINT);
SPRT_CONST(FILE_FLAG_OPEN_NO_RECALL);
SPRT_CONST(FILE_FLAG_FIRST_PIPE_INSTANCE);

// === reparse tags ==========================================================
SPRT_CONST(IO_REPARSE_TAG_RESERVED_INVALID);
SPRT_CONST(IO_REPARSE_TAG_MOUNT_POINT);
SPRT_CONST(IO_REPARSE_TAG_HSM);
SPRT_CONST(IO_REPARSE_TAG_HSM2);
SPRT_CONST(IO_REPARSE_TAG_SIS);
SPRT_CONST(IO_REPARSE_TAG_WIM);
SPRT_CONST(IO_REPARSE_TAG_CSV);
SPRT_CONST(IO_REPARSE_TAG_DFS);
SPRT_CONST(IO_REPARSE_TAG_SYMLINK);
SPRT_CONST(IO_REPARSE_TAG_DFSR);
SPRT_CONST(IO_REPARSE_TAG_DEDUP);
SPRT_CONST(IO_REPARSE_TAG_NFS);
SPRT_CONST(IO_REPARSE_TAG_FILE_PLACEHOLDER);
SPRT_CONST(IO_REPARSE_TAG_WOF);
SPRT_CONST(IO_REPARSE_TAG_WCI);
SPRT_CONST(IO_REPARSE_TAG_WCI_1);
SPRT_CONST(IO_REPARSE_TAG_GLOBAL_REPARSE);
SPRT_CONST(IO_REPARSE_TAG_CLOUD);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_1);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_2);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_3);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_4);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_5);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_6);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_7);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_8);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_9);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_A);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_B);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_C);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_D);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_E);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_F);
SPRT_CONST(IO_REPARSE_TAG_CLOUD_MASK);
SPRT_CONST(IO_REPARSE_TAG_APPEXECLINK);
SPRT_CONST(IO_REPARSE_TAG_PROJFS);
SPRT_CONST(IO_REPARSE_TAG_STORAGE_SYNC);
SPRT_CONST(IO_REPARSE_TAG_WCI_TOMBSTONE);
SPRT_CONST(IO_REPARSE_TAG_UNHANDLED);
SPRT_CONST(IO_REPARSE_TAG_ONEDRIVE);
SPRT_CONST(IO_REPARSE_TAG_PROJFS_TOMBSTONE);
SPRT_CONST(IO_REPARSE_TAG_AF_UNIX);
SPRT_CONST(IO_REPARSE_TAG_STORAGE_SYNC_FOLDER);
SPRT_CONST(IO_REPARSE_TAG_WCI_LINK);
SPRT_CONST(IO_REPARSE_TAG_WCI_LINK_1);
SPRT_CONST(IO_REPARSE_TAG_DATALESS_CIM);

// === MoveFileEx flags ======================================================
SPRT_CONST(MOVEFILE_REPLACE_EXISTING);
SPRT_CONST(MOVEFILE_COPY_ALLOWED);
SPRT_CONST(MOVEFILE_DELAY_UNTIL_REBOOT);
SPRT_CONST(MOVEFILE_WRITE_THROUGH);
SPRT_CONST(MOVEFILE_CREATE_HARDLINK);
SPRT_CONST(MOVEFILE_FAIL_IF_NOT_TRACKABLE);

// === SetFilePointer origin =================================================
SPRT_CONST(FILE_BEGIN);
SPRT_CONST(FILE_CURRENT);
SPRT_CONST(FILE_END);

// === GetFinalPathNameByHandle flags ========================================
SPRT_CONST(FILE_NAME_NORMALIZED);
SPRT_CONST(FILE_NAME_OPENED);

// === MapViewOfFile access ==================================================
SPRT_CONST(FILE_MAP_WRITE);
SPRT_CONST(FILE_MAP_READ);
SPRT_CONST(FILE_MAP_ALL_ACCESS);
SPRT_CONST(FILE_MAP_EXECUTE);
SPRT_CONST(FILE_MAP_COPY);
SPRT_CONST(FILE_MAP_RESERVE);
SPRT_CONST(FILE_MAP_TARGETS_INVALID);
SPRT_CONST(FILE_MAP_LARGE_PAGES);

// === CreateSymbolicLink flags ==============================================
SPRT_CONST(SYMBOLIC_LINK_FLAG_DIRECTORY);
SPRT_CONST(SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE);

// === section flags =========================================================
SPRT_CONST(SEC_HUGE_PAGES);
SPRT_CONST(SEC_LARGE_PAGES);

// === LockFileEx flags ======================================================
SPRT_CONST(LOCKFILE_FAIL_IMMEDIATELY);
SPRT_CONST(LOCKFILE_EXCLUSIVE_LOCK);

// === named-pipe flags ======================================================
SPRT_CONST(PIPE_ACCESS_INBOUND);
SPRT_CONST(PIPE_ACCESS_OUTBOUND);
SPRT_CONST(PIPE_ACCESS_DUPLEX);
SPRT_CONST(PIPE_TYPE_BYTE);
SPRT_CONST(PIPE_READMODE_BYTE);
SPRT_CONST(PIPE_WAIT);
SPRT_CONST(PIPE_NOWAIT);

#define SPRT_FILE_ENUM(Name) static_assert((long long)::Name == (long long)::sprt_abi::Name, #Name);

SPRT_FILE_ENUM(FileDirectoryInformation);

SPRT_FILE_ENUM(FileBasicInfo);
SPRT_FILE_ENUM(FileStandardInfo);
SPRT_FILE_ENUM(FileNameInfo);
SPRT_FILE_ENUM(FileRenameInfo);
SPRT_FILE_ENUM(FileDispositionInfo);
SPRT_FILE_ENUM(FileAllocationInfo);
SPRT_FILE_ENUM(FileEndOfFileInfo);
SPRT_FILE_ENUM(FileStreamInfo);
SPRT_FILE_ENUM(FileCompressionInfo);
SPRT_FILE_ENUM(FileAttributeTagInfo);
SPRT_FILE_ENUM(FileIdBothDirectoryInfo);
SPRT_FILE_ENUM(FileIdBothDirectoryRestartInfo);
SPRT_FILE_ENUM(FileIoPriorityHintInfo);
SPRT_FILE_ENUM(FileRemoteProtocolInfo);
SPRT_FILE_ENUM(FileFullDirectoryInfo);
SPRT_FILE_ENUM(FileFullDirectoryRestartInfo);
SPRT_FILE_ENUM(FileStorageInfo);
SPRT_FILE_ENUM(FileAlignmentInfo);
SPRT_FILE_ENUM(FileIdInfo);
SPRT_FILE_ENUM(FileIdExtdDirectoryInfo);
SPRT_FILE_ENUM(FileIdExtdDirectoryRestartInfo);
SPRT_FILE_ENUM(FileDispositionInfoEx);
SPRT_FILE_ENUM(FileRenameInfoEx);
SPRT_FILE_ENUM(FileCaseSensitiveInfo);
SPRT_FILE_ENUM(FileNormalizedNameInfo);
SPRT_FILE_ENUM(MaximumFileInfoByHandleClass);

SPRT_FILE_ENUM(GetFileExInfoStandard);
SPRT_FILE_ENUM(GetFileExMaxInfoLevel);

// === BY_HANDLE_FILE_INFORMATION ============================================
SPRT_SIZE(BY_HANDLE_FILE_INFORMATION);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, dwFileAttributes);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, ftCreationTime);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, ftLastAccessTime);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, ftLastWriteTime);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, dwVolumeSerialNumber);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, nFileSizeHigh);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, nFileSizeLow);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, nNumberOfLinks);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, nFileIndexHigh);
SPRT_OFFSET(BY_HANDLE_FILE_INFORMATION, nFileIndexLow);

// === FILE_BASIC_INFO =======================================================
SPRT_SIZE(FILE_BASIC_INFO);
SPRT_OFFSET(FILE_BASIC_INFO, CreationTime);
SPRT_OFFSET(FILE_BASIC_INFO, LastAccessTime);
SPRT_OFFSET(FILE_BASIC_INFO, LastWriteTime);
SPRT_OFFSET(FILE_BASIC_INFO, ChangeTime);
SPRT_OFFSET(FILE_BASIC_INFO, FileAttributes);

// === FILE_STANDARD_INFO ====================================================
SPRT_SIZE(FILE_STANDARD_INFO);
SPRT_OFFSET(FILE_STANDARD_INFO, AllocationSize);
SPRT_OFFSET(FILE_STANDARD_INFO, EndOfFile);
SPRT_OFFSET(FILE_STANDARD_INFO, NumberOfLinks);
SPRT_OFFSET(FILE_STANDARD_INFO, DeletePending);
SPRT_OFFSET(FILE_STANDARD_INFO, Directory);

// === FILE_ATTRIBUTE_TAG_INFO (GetFileInformationByHandleEx: FileAttributeTagInfo) ====
SPRT_SIZE(FILE_ATTRIBUTE_TAG_INFO);
SPRT_OFFSET(FILE_ATTRIBUTE_TAG_INFO, FileAttributes);
SPRT_OFFSET(FILE_ATTRIBUTE_TAG_INFO, ReparseTag);

// === FILE_STORAGE_INFO =====================================================
SPRT_SIZE(FILE_STORAGE_INFO);
SPRT_OFFSET(FILE_STORAGE_INFO, LogicalBytesPerSector);
SPRT_OFFSET(FILE_STORAGE_INFO, PhysicalBytesPerSectorForAtomicity);
SPRT_OFFSET(FILE_STORAGE_INFO, PhysicalBytesPerSectorForPerformance);
SPRT_OFFSET(FILE_STORAGE_INFO, FileSystemEffectivePhysicalBytesPerSectorForAtomicity);
SPRT_OFFSET(FILE_STORAGE_INFO, Flags);
SPRT_OFFSET(FILE_STORAGE_INFO, ByteOffsetForSectorAlignment);
SPRT_OFFSET(FILE_STORAGE_INFO, ByteOffsetForPartitionAlignment);

// === FILE_ID_BOTH_DIR_INFO =================================================
SPRT_SIZE(FILE_ID_BOTH_DIR_INFO);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, NextEntryOffset);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, FileIndex);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, CreationTime);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, LastAccessTime);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, LastWriteTime);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, ChangeTime);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, EndOfFile);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, AllocationSize);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, FileAttributes);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, FileNameLength);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, EaSize);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, ShortNameLength);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, ShortName);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, FileId);
SPRT_OFFSET(FILE_ID_BOTH_DIR_INFO, FileName);

// === FILE_SEGMENT_ELEMENT (union) ==========================================
SPRT_SIZE(FILE_SEGMENT_ELEMENT);
SPRT_OFFSET(FILE_SEGMENT_ELEMENT, Buffer);
SPRT_OFFSET(FILE_SEGMENT_ELEMENT, Alignment);

// === WIN32_FILE_ATTRIBUTE_DATA =============================================
SPRT_SIZE(WIN32_FILE_ATTRIBUTE_DATA);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, dwFileAttributes);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, ftCreationTime);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, ftLastAccessTime);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, ftLastWriteTime);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, nFileSizeHigh);
SPRT_OFFSET(WIN32_FILE_ATTRIBUTE_DATA, nFileSizeLow);

// === WIN32_FIND_DATAA ======================================================
SPRT_SIZE(WIN32_FIND_DATAA);
SPRT_OFFSET(WIN32_FIND_DATAA, dwFileAttributes);
SPRT_OFFSET(WIN32_FIND_DATAA, ftCreationTime);
SPRT_OFFSET(WIN32_FIND_DATAA, ftLastAccessTime);
SPRT_OFFSET(WIN32_FIND_DATAA, ftLastWriteTime);
SPRT_OFFSET(WIN32_FIND_DATAA, nFileSizeHigh);
SPRT_OFFSET(WIN32_FIND_DATAA, nFileSizeLow);
SPRT_OFFSET(WIN32_FIND_DATAA, dwReserved0);
SPRT_OFFSET(WIN32_FIND_DATAA, dwReserved1);
SPRT_OFFSET(WIN32_FIND_DATAA, cFileName);
SPRT_OFFSET(WIN32_FIND_DATAA, cAlternateFileName);

// === WIN32_FIND_DATAW ======================================================
SPRT_SIZE(WIN32_FIND_DATAW);
SPRT_OFFSET(WIN32_FIND_DATAW, dwFileAttributes);
SPRT_OFFSET(WIN32_FIND_DATAW, ftCreationTime);
SPRT_OFFSET(WIN32_FIND_DATAW, ftLastAccessTime);
SPRT_OFFSET(WIN32_FIND_DATAW, ftLastWriteTime);
SPRT_OFFSET(WIN32_FIND_DATAW, nFileSizeHigh);
SPRT_OFFSET(WIN32_FIND_DATAW, nFileSizeLow);
SPRT_OFFSET(WIN32_FIND_DATAW, dwReserved0);
SPRT_OFFSET(WIN32_FIND_DATAW, dwReserved1);
SPRT_OFFSET(WIN32_FIND_DATAW, cFileName);
SPRT_OFFSET(WIN32_FIND_DATAW, cAlternateFileName);

#include <winternl.h>

// === FILE_INFO_BY_HANDLE_CLASS ===
SPRT_ENUM(FileBasicInfo);
SPRT_ENUM(FileStandardInfo);
SPRT_ENUM(FileNameInfo);
SPRT_ENUM(FileRenameInfo);
SPRT_ENUM(FileDispositionInfo);
SPRT_ENUM(FileAllocationInfo);
SPRT_ENUM(FileEndOfFileInfo);
SPRT_ENUM(FileStreamInfo);
SPRT_ENUM(FileCompressionInfo);
SPRT_ENUM(FileAttributeTagInfo);
SPRT_ENUM(FileIdBothDirectoryInfo);
SPRT_ENUM(FileIdBothDirectoryRestartInfo);
SPRT_ENUM(FileIoPriorityHintInfo);
SPRT_ENUM(FileRemoteProtocolInfo);
SPRT_ENUM(FileFullDirectoryInfo);
SPRT_ENUM(FileFullDirectoryRestartInfo);
SPRT_ENUM(FileStorageInfo);
SPRT_ENUM(FileAlignmentInfo);
SPRT_ENUM(FileIdInfo);
SPRT_ENUM(FileIdExtdDirectoryInfo);
SPRT_ENUM(FileIdExtdDirectoryRestartInfo);
SPRT_ENUM(FileDispositionInfoEx);
SPRT_ENUM(FileRenameInfoEx);
SPRT_ENUM(FileCaseSensitiveInfo);
SPRT_ENUM(FileNormalizedNameInfo);
SPRT_ENUM(MaximumFileInfoByHandleClass);

// === GET_FILEEX_INFO_LEVELS ===
SPRT_ENUM(GetFileExInfoStandard);
SPRT_ENUM(GetFileExMaxInfoLevel);

// === FILE_INFORMATION_CLASS ===
SPRT_ENUM(FileDirectoryInformation);

// === new values (wrapper completion): ReadDirectoryChangesW ================
SPRT_CONST(FILE_ACTION_ADDED);
SPRT_CONST(FILE_ACTION_REMOVED);
SPRT_CONST(FILE_ACTION_MODIFIED);
SPRT_CONST(FILE_ACTION_RENAMED_OLD_NAME);
SPRT_CONST(FILE_ACTION_RENAMED_NEW_NAME);

SPRT_CONST(FILE_NOTIFY_CHANGE_FILE_NAME);
SPRT_CONST(FILE_NOTIFY_CHANGE_DIR_NAME);
SPRT_CONST(FILE_NOTIFY_CHANGE_ATTRIBUTES);
SPRT_CONST(FILE_NOTIFY_CHANGE_SIZE);
SPRT_CONST(FILE_NOTIFY_CHANGE_LAST_WRITE);
SPRT_CONST(FILE_NOTIFY_CHANGE_LAST_ACCESS);
SPRT_CONST(FILE_NOTIFY_CHANGE_CREATION);
SPRT_CONST(FILE_NOTIFY_CHANGE_SECURITY);

// FILE_NOTIFY_INFORMATION: written by the kernel into the caller's buffer, so
// the field offsets must match. FileName[1] is a tail array (content skipped).
SPRT_OFFSET(FILE_NOTIFY_INFORMATION, NextEntryOffset);
SPRT_OFFSET(FILE_NOTIFY_INFORMATION, Action);
SPRT_OFFSET(FILE_NOTIFY_INFORMATION, FileNameLength);
SPRT_OFFSET(FILE_NOTIFY_INFORMATION, FileName);
// LPOVERLAPPED_COMPLETION_ROUTINE: a function-pointer typedef, no layout to pin.
