/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef CORE_RUNTIME_INCLUDE_C_CROSS_WINDOWS_SPRT_NETINETDEF_H_
#define CORE_RUNTIME_INCLUDE_C_CROSS_WINDOWS_SPRT_NETINETDEF_H_

// Windows (winsock ws2def.h/ws2ipdef.h) netinet option numbers. Validated
// against the live SDK headers in tests/libc/windows-abi.

#define __SPRT_INET_ADDRSTRLEN 22
#define __SPRT_INET6_ADDRSTRLEN 65

#define __SPRT_IPPORT_RESERVED 1024

#define __SPRT_IPPROTO_IP       0
#define __SPRT_IPPROTO_HOPOPTS  0
#define __SPRT_IPPROTO_ICMP     1
#define __SPRT_IPPROTO_IGMP     2
#define __SPRT_IPPROTO_IPIP     4
#define __SPRT_IPPROTO_TCP      6
#define __SPRT_IPPROTO_EGP      8
#define __SPRT_IPPROTO_PUP      12
#define __SPRT_IPPROTO_UDP      17
#define __SPRT_IPPROTO_IDP      22
#define __SPRT_IPPROTO_TP       29
#define __SPRT_IPPROTO_DCCP     33
#define __SPRT_IPPROTO_IPV6     41
#define __SPRT_IPPROTO_ROUTING  43
#define __SPRT_IPPROTO_FRAGMENT 44
#define __SPRT_IPPROTO_RSVP     46
#define __SPRT_IPPROTO_GRE      47
#define __SPRT_IPPROTO_ESP      50
#define __SPRT_IPPROTO_AH       51
#define __SPRT_IPPROTO_ICMPV6   58
#define __SPRT_IPPROTO_NONE     59
#define __SPRT_IPPROTO_DSTOPTS  60
#define __SPRT_IPPROTO_MTP      92
#define __SPRT_IPPROTO_BEETPH   94
#define __SPRT_IPPROTO_ENCAP    98
#define __SPRT_IPPROTO_PIM      103
#define __SPRT_IPPROTO_COMP     108
#define __SPRT_IPPROTO_SCTP     132
#define __SPRT_IPPROTO_MH       135
#define __SPRT_IPPROTO_UDPLITE  136
#define __SPRT_IPPROTO_MPLS     137
#define __SPRT_IPPROTO_ETHERNET 143
#define __SPRT_IPPROTO_RAW      255
#define __SPRT_IPPROTO_MPTCP    262
#define __SPRT_IPPROTO_MAX 256

#define __SPRT_IP_TOS 3
#define __SPRT_IP_TTL 4
#define __SPRT_IP_HDRINCL 2
#define __SPRT_IP_OPTIONS 1
#define __SPRT_IP_PKTINFO 19
#define __SPRT_IP_MTU_DISCOVER 71
#define __SPRT_IP_RECVERR 75
#define __SPRT_IP_RECVTTL 21
#define __SPRT_IP_RECVTOS 40
#define __SPRT_IP_MTU 73
#define __SPRT_IP_MULTICAST_IF 9
#define __SPRT_IP_MULTICAST_TTL 10
#define __SPRT_IP_MULTICAST_LOOP 11
#define __SPRT_IP_ADD_MEMBERSHIP 12
#define __SPRT_IP_DROP_MEMBERSHIP 13
#define __SPRT_IP_UNBLOCK_SOURCE 18
#define __SPRT_IP_BLOCK_SOURCE 17
#define __SPRT_IP_ADD_SOURCE_MEMBERSHIP 15
#define __SPRT_IP_DROP_SOURCE_MEMBERSHIP 16
#define __SPRT_IP_UNICAST_IF 31

// Windows-only IPv4 options (winsock.h / ws2ipdef.h); absent from POSIX/Linux.
#define __SPRT_IP_DONTFRAGMENT 14
#define __SPRT_IP_HOPLIMIT 21
#define __SPRT_IP_RECEIVE_BROADCAST 22
#define __SPRT_IP_RECVIF 24
#define __SPRT_IP_RECVDSTADDR 25
#define __SPRT_IP_IFLIST 28
#define __SPRT_IP_ADD_IFLIST 29
#define __SPRT_IP_DEL_IFLIST 30
#define __SPRT_IP_RTHDR 32
#define __SPRT_IP_GET_IFLIST 33
#define __SPRT_IP_RECVRTHDR 38
#define __SPRT_IP_TCLASS 39
#define __SPRT_IP_RECVTCLASS 40
#define __SPRT_IP_ORIGINAL_ARRIVAL_IF 47
#define __SPRT_IP_ECN 50
#define __SPRT_IP_RECVECN 50
#define __SPRT_IP_PKTINFO_EX 51
#define __SPRT_IP_WFP_REDIRECT_RECORDS 60
#define __SPRT_IP_WFP_REDIRECT_CONTEXT 70
#define __SPRT_IP_NRT_INTERFACE 74
#define __SPRT_IP_USER_MTU 76

#define __SPRT_IP_PMTUDISC_NOT_SET 0
#define __SPRT_IP_PMTUDISC_DO      1
#define __SPRT_IP_PMTUDISC_DONT    2
#define __SPRT_IP_PMTUDISC_PROBE   3
#define __SPRT_IP_PMTUDISC_MAX     4

#define __SPRT_IP_DEFAULT_MULTICAST_TTL        1
#define __SPRT_IP_DEFAULT_MULTICAST_LOOP       1
#define __SPRT_IP_MAX_MEMBERSHIPS              20

#define __SPRT_MCAST_JOIN_GROUP         41
#define __SPRT_MCAST_LEAVE_GROUP        42
#define __SPRT_MCAST_JOIN_SOURCE_GROUP  45
#define __SPRT_MCAST_LEAVE_SOURCE_GROUP 46
#define __SPRT_MCAST_BLOCK_SOURCE       43
#define __SPRT_MCAST_UNBLOCK_SOURCE     44

#define __SPRT_MCAST_INCLUDE 0
#define __SPRT_MCAST_EXCLUDE 1

#define __SPRT_IPV6_CHECKSUM 26
#define __SPRT_IPV6_UNICAST_HOPS 4
#define __SPRT_IPV6_MULTICAST_IF 9
#define __SPRT_IPV6_MULTICAST_HOPS 10
#define __SPRT_IPV6_MULTICAST_LOOP 11
#define __SPRT_IPV6_JOIN_GROUP 12
#define __SPRT_IPV6_LEAVE_GROUP 13
#define __SPRT_IPV6_MTU_DISCOVER 71
#define __SPRT_IPV6_MTU 72
#define __SPRT_IPV6_RECVERR 75
#define __SPRT_IPV6_V6ONLY 27
#define __SPRT_IPV6_HDRINCL 2

#define __SPRT_IPV6_PKTINFO 19
#define __SPRT_IPV6_HOPLIMIT 21
#define __SPRT_IPV6_HOPOPTS 1
#define __SPRT_IPV6_RECVRTHDR 38
#define __SPRT_IPV6_RTHDR 32
#define __SPRT_IPV6_DONTFRAG 14
#define __SPRT_IPV6_RECVTCLASS 40
#define __SPRT_IPV6_TCLASS 39
#define __SPRT_IPV6_UNICAST_IF 31

// Windows-only IPv6 options (winsock.h); absent from the POSIX/Linux set.
#define __SPRT_IPV6_PROTECTION_LEVEL 23
#define __SPRT_IPV6_RECVIF 24
#define __SPRT_IPV6_RECVDSTADDR 25
#define __SPRT_IPV6_IFLIST 28
#define __SPRT_IPV6_ADD_IFLIST 29
#define __SPRT_IPV6_DEL_IFLIST 30
#define __SPRT_IPV6_GET_IFLIST 33
#define __SPRT_IPV6_ECN 50
#define __SPRT_IPV6_RECVECN 50
#define __SPRT_IPV6_PKTINFO_EX 51
#define __SPRT_IPV6_WFP_REDIRECT_RECORDS 60
#define __SPRT_IPV6_WFP_REDIRECT_CONTEXT 70
#define __SPRT_IPV6_NRT_INTERFACE 74
#define __SPRT_IPV6_USER_MTU 76

#define __SPRT_IPV6_ADD_MEMBERSHIP     __SPRT_IPV6_JOIN_GROUP
#define __SPRT_IPV6_DROP_MEMBERSHIP    __SPRT_IPV6_LEAVE_GROUP

// --- TCP options (IPPROTO_TCP level) -----------------------------------------
#define __SPRT_TCP_INITIAL_RTO_DEFAULT_MAX_SYN_RETRANSMISSIONS 0
#define __SPRT_TCP_INITIAL_RTO_DEFAULT_RTT 0
#define __SPRT_TCP_OFFLOAD_NO_PREFERENCE 0
#define __SPRT_TCP_NODELAY 1
#define __SPRT_TCP_OFFLOAD_NOT_PREFERRED 1
#define __SPRT_TCP_EXPEDITED_1122 2
#define __SPRT_TCP_OFFLOAD_PREFERRED 2
#define __SPRT_TCP_KEEPALIVE 3
#define __SPRT_TCP_KEEPIDLE 3
#define __SPRT_TCP_MAXSEG 4
#define __SPRT_TCP_MAXRT 5
#define __SPRT_TCP_STDURG 6
#define __SPRT_TCP_NOURG 7
#define __SPRT_TCP_ATMARK 8
#define __SPRT_TCP_NOSYNRETRIES 9
#define __SPRT_TCP_TIMESTAMPS 10
#define __SPRT_TCP_OFFLOAD_PREFERENCE 11
#define __SPRT_TCP_CONGESTION_ALGORITHM 12
#define __SPRT_TCP_DELAY_FIN_ACK 13
#define __SPRT_TCP_MAXRTMS 14
#define __SPRT_TCP_FASTOPEN 15
#define __SPRT_TCP_KEEPCNT 16
#define __SPRT_TCP_KEEPINTVL 17
#define __SPRT_TCP_FAIL_CONNECT_ON_ICMP_ERROR 18
#define __SPRT_TCP_ICMP_ERROR_INFO 19
#define __SPRT_TCP_INITIAL_RTO_NO_SYN_RETRANSMISSIONS 254
#define __SPRT_TCP_INITIAL_RTO_UNSPECIFIED_MAX_SYN_RETRANSMISSIONS 255
#define __SPRT_TCP_INITIAL_RTO_UNSPECIFIED_RTT 65535

#endif // CORE_RUNTIME_INCLUDE_C_CROSS_WINDOWS_SPRT_NETINETDEF_H_
