#ifndef CORE_RUNTIME_INCLUDE_C_CROSS_MACOS_SPRT_ERRNO_H_
#define CORE_RUNTIME_INCLUDE_C_CROSS_MACOS_SPRT_ERRNO_H_

// Native macOS (Darwin) errno numbers, mirrored from <sys/errno.h>. The sprt runtime routes
// its errno cell to libSystem's __error() on macOS, so these MUST equal the system values —
// the static_asserts in libc_wrapper/c/common/errno.cc verify this on a hosted build.

#define __SPRT_EPERM            1
#define __SPRT_ENOENT           2
#define __SPRT_ESRCH            3
#define __SPRT_EINTR            4
#define __SPRT_EIO              5
#define __SPRT_ENXIO            6
#define __SPRT_E2BIG            7
#define __SPRT_ENOEXEC          8
#define __SPRT_EBADF            9
#define __SPRT_ECHILD           10
#define __SPRT_EDEADLK          11
#define __SPRT_ENOMEM           12
#define __SPRT_EACCES           13
#define __SPRT_EFAULT           14
#define __SPRT_ENOTBLK          15
#define __SPRT_EBUSY            16
#define __SPRT_EEXIST           17
#define __SPRT_EXDEV            18
#define __SPRT_ENODEV           19
#define __SPRT_ENOTDIR          20
#define __SPRT_EISDIR           21
#define __SPRT_EINVAL           22
#define __SPRT_ENFILE           23
#define __SPRT_EMFILE           24
#define __SPRT_ENOTTY           25
#define __SPRT_ETXTBSY          26
#define __SPRT_EFBIG            27
#define __SPRT_ENOSPC           28
#define __SPRT_ESPIPE           29
#define __SPRT_EROFS            30
#define __SPRT_EMLINK           31
#define __SPRT_EPIPE            32
#define __SPRT_EDOM             33
#define __SPRT_ERANGE           34
#define __SPRT_EAGAIN           35
#define __SPRT_EWOULDBLOCK      __SPRT_EAGAIN
#define __SPRT_EINPROGRESS      36
#define __SPRT_EALREADY         37
#define __SPRT_ENOTSOCK         38
#define __SPRT_EDESTADDRREQ     39
#define __SPRT_EMSGSIZE         40
#define __SPRT_EPROTOTYPE       41
#define __SPRT_ENOPROTOOPT      42
#define __SPRT_EPROTONOSUPPORT  43
#define __SPRT_ESOCKTNOSUPPORT  44
#define __SPRT_ENOTSUP          45
#define __SPRT_EPFNOSUPPORT     46
#define __SPRT_EAFNOSUPPORT     47
#define __SPRT_EADDRINUSE       48
#define __SPRT_EADDRNOTAVAIL    49
#define __SPRT_ENETDOWN         50
#define __SPRT_ENETUNREACH      51
#define __SPRT_ENETRESET        52
#define __SPRT_ECONNABORTED     53
#define __SPRT_ECONNRESET       54
#define __SPRT_ENOBUFS          55
#define __SPRT_EISCONN          56
#define __SPRT_ENOTCONN         57
#define __SPRT_ESHUTDOWN        58
#define __SPRT_ETOOMANYREFS     59
#define __SPRT_ETIMEDOUT        60
#define __SPRT_ECONNREFUSED     61
#define __SPRT_ELOOP            62
#define __SPRT_ENAMETOOLONG     63
#define __SPRT_EHOSTDOWN        64
#define __SPRT_EHOSTUNREACH     65
#define __SPRT_ENOTEMPTY        66
#define __SPRT_EPROCLIM         67
#define __SPRT_EUSERS           68
#define __SPRT_EDQUOT           69
#define __SPRT_ESTALE           70
#define __SPRT_EREMOTE          71
#define __SPRT_EBADRPC          72
#define __SPRT_ERPCMISMATCH     73
#define __SPRT_EPROGUNAVAIL     74
#define __SPRT_EPROGMISMATCH    75
#define __SPRT_EPROCUNAVAIL     76
#define __SPRT_ENOLCK           77
#define __SPRT_ENOSYS           78
#define __SPRT_EFTYPE           79
#define __SPRT_EAUTH            80
#define __SPRT_ENEEDAUTH        81
#define __SPRT_EPWROFF          82
#define __SPRT_EDEVERR          83
#define __SPRT_EOVERFLOW        84
#define __SPRT_EBADEXEC         85
#define __SPRT_EBADARCH         86
#define __SPRT_ESHLIBVERS       87
#define __SPRT_EBADMACHO        88
#define __SPRT_ECANCELED        89
#define __SPRT_EIDRM            90
#define __SPRT_ENOMSG           91
#define __SPRT_EILSEQ           92
#define __SPRT_ENOATTR          93
#define __SPRT_EBADMSG          94
#define __SPRT_EMULTIHOP        95
#define __SPRT_ENODATA          96
#define __SPRT_ENOLINK          97
#define __SPRT_ENOSR            98
#define __SPRT_ENOSTR           99
#define __SPRT_EPROTO           100
#define __SPRT_ETIME            101
#define __SPRT_EOPNOTSUPP       102
#define __SPRT_ENOPOLICY        103
#define __SPRT_ENOTRECOVERABLE  104
#define __SPRT_EOWNERDEAD       105
#define __SPRT_EQFULL           106
#define __SPRT_ENOTCAPABLE      107

#ifndef EPERM
#define EPERM            __SPRT_EPERM
#define ENOENT           __SPRT_ENOENT
#define ESRCH            __SPRT_ESRCH
#define EINTR            __SPRT_EINTR
#define EIO              __SPRT_EIO
#define ENXIO            __SPRT_ENXIO
#define E2BIG            __SPRT_E2BIG
#define ENOEXEC          __SPRT_ENOEXEC
#define EBADF            __SPRT_EBADF
#define ECHILD           __SPRT_ECHILD
#define EDEADLK          __SPRT_EDEADLK
#define ENOMEM           __SPRT_ENOMEM
#define EACCES           __SPRT_EACCES
#define EFAULT           __SPRT_EFAULT
#define ENOTBLK          __SPRT_ENOTBLK
#define EBUSY            __SPRT_EBUSY
#define EEXIST           __SPRT_EEXIST
#define EXDEV            __SPRT_EXDEV
#define ENODEV           __SPRT_ENODEV
#define ENOTDIR          __SPRT_ENOTDIR
#define EISDIR           __SPRT_EISDIR
#define EINVAL           __SPRT_EINVAL
#define ENFILE           __SPRT_ENFILE
#define EMFILE           __SPRT_EMFILE
#define ENOTTY           __SPRT_ENOTTY
#define ETXTBSY          __SPRT_ETXTBSY
#define EFBIG            __SPRT_EFBIG
#define ENOSPC           __SPRT_ENOSPC
#define ESPIPE           __SPRT_ESPIPE
#define EROFS            __SPRT_EROFS
#define EMLINK           __SPRT_EMLINK
#define EPIPE            __SPRT_EPIPE
#define EDOM             __SPRT_EDOM
#define ERANGE           __SPRT_ERANGE
#define EAGAIN           __SPRT_EAGAIN
#define EWOULDBLOCK      __SPRT_EWOULDBLOCK
#define EINPROGRESS      __SPRT_EINPROGRESS
#define EALREADY         __SPRT_EALREADY
#define ENOTSOCK         __SPRT_ENOTSOCK
#define EDESTADDRREQ     __SPRT_EDESTADDRREQ
#define EMSGSIZE         __SPRT_EMSGSIZE
#define EPROTOTYPE       __SPRT_EPROTOTYPE
#define ENOPROTOOPT      __SPRT_ENOPROTOOPT
#define EPROTONOSUPPORT  __SPRT_EPROTONOSUPPORT
#define ESOCKTNOSUPPORT  __SPRT_ESOCKTNOSUPPORT
#define ENOTSUP          __SPRT_ENOTSUP
#define EPFNOSUPPORT     __SPRT_EPFNOSUPPORT
#define EAFNOSUPPORT     __SPRT_EAFNOSUPPORT
#define EADDRINUSE       __SPRT_EADDRINUSE
#define EADDRNOTAVAIL    __SPRT_EADDRNOTAVAIL
#define ENETDOWN         __SPRT_ENETDOWN
#define ENETUNREACH      __SPRT_ENETUNREACH
#define ENETRESET        __SPRT_ENETRESET
#define ECONNABORTED     __SPRT_ECONNABORTED
#define ECONNRESET       __SPRT_ECONNRESET
#define ENOBUFS          __SPRT_ENOBUFS
#define EISCONN          __SPRT_EISCONN
#define ENOTCONN         __SPRT_ENOTCONN
#define ESHUTDOWN        __SPRT_ESHUTDOWN
#define ETOOMANYREFS     __SPRT_ETOOMANYREFS
#define ETIMEDOUT        __SPRT_ETIMEDOUT
#define ECONNREFUSED     __SPRT_ECONNREFUSED
#define ELOOP            __SPRT_ELOOP
#define ENAMETOOLONG     __SPRT_ENAMETOOLONG
#define EHOSTDOWN        __SPRT_EHOSTDOWN
#define EHOSTUNREACH     __SPRT_EHOSTUNREACH
#define ENOTEMPTY        __SPRT_ENOTEMPTY
#define EPROCLIM         __SPRT_EPROCLIM
#define EUSERS           __SPRT_EUSERS
#define EDQUOT           __SPRT_EDQUOT
#define ESTALE           __SPRT_ESTALE
#define EREMOTE          __SPRT_EREMOTE
#define EBADRPC          __SPRT_EBADRPC
#define ERPCMISMATCH     __SPRT_ERPCMISMATCH
#define EPROGUNAVAIL     __SPRT_EPROGUNAVAIL
#define EPROGMISMATCH    __SPRT_EPROGMISMATCH
#define EPROCUNAVAIL     __SPRT_EPROCUNAVAIL
#define ENOLCK           __SPRT_ENOLCK
#define ENOSYS           __SPRT_ENOSYS
#define EFTYPE           __SPRT_EFTYPE
#define EAUTH            __SPRT_EAUTH
#define ENEEDAUTH        __SPRT_ENEEDAUTH
#define EPWROFF          __SPRT_EPWROFF
#define EDEVERR          __SPRT_EDEVERR
#define EOVERFLOW        __SPRT_EOVERFLOW
#define EBADEXEC         __SPRT_EBADEXEC
#define EBADARCH         __SPRT_EBADARCH
#define ESHLIBVERS       __SPRT_ESHLIBVERS
#define EBADMACHO        __SPRT_EBADMACHO
#define ECANCELED        __SPRT_ECANCELED
#define EIDRM            __SPRT_EIDRM
#define ENOMSG           __SPRT_ENOMSG
#define EILSEQ           __SPRT_EILSEQ
#define ENOATTR          __SPRT_ENOATTR
#define EBADMSG          __SPRT_EBADMSG
#define EMULTIHOP        __SPRT_EMULTIHOP
#define ENODATA          __SPRT_ENODATA
#define ENOLINK          __SPRT_ENOLINK
#define ENOSR            __SPRT_ENOSR
#define ENOSTR           __SPRT_ENOSTR
#define EPROTO           __SPRT_EPROTO
#define ETIME            __SPRT_ETIME
#define EOPNOTSUPP       __SPRT_EOPNOTSUPP
#define ENOPOLICY        __SPRT_ENOPOLICY
#define ENOTRECOVERABLE  __SPRT_ENOTRECOVERABLE
#define EOWNERDEAD       __SPRT_EOWNERDEAD
#define EQFULL           __SPRT_EQFULL
#define ENOTCAPABLE      __SPRT_ENOTCAPABLE
#endif

#endif
