# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

ifndef NDK
ifdef ANDROID_NDK_ROOT
NDK := $(ANDROID_NDK_ROOT)
else
NDK := $(HOME)/Android/Ndk
endif
endif

ifeq ($(NDK),)
ifdef ANDROID_NDK_ROOT
NDK := $(ANDROID_NDK_ROOT)
else
NDK := $(HOME)/Android/Ndk
endif
endif

ANDROID_SYSROOT := $(NDK)/toolchains/llvm/prebuilt/$(ANDROID_HOST)/sysroot
ANDROID_SYSROOT_INCLUDE_CXX := $(realpath $(ANDROID_SYSROOT)/usr/include/c++/v1)
ANDROID_SYSROOT_INCLUDE_COMMON := \
	$(abspath $(ANDROID_SYSROOT)/usr/include/$$(BUILD_ARCH)) \
	$(realpath $(ANDROID_SYSROOT)/usr/include)

$(call print_verbose,(defaults.mk) ANDROID_SYSROOT: $(ANDROID_SYSROOT))

OSTYPE_IS_ANDROID := 1

OSTYPE_EXEC_SUFFIX :=
OSTYPE_DSO_SUFFIX := .so
OSTYPE_LIB_SUFFIX := .a
OSTYPE_LIB_PREFIX := lib

OSTYPE_CONFIG_FLAGS := ANDROID

OSTYPE_LIBS_REALPATH := 1

HOST_CC := ndk-build
HOST_CXX := ndk-build

ANDROID_EXPORT_PREFIX ?= $(GLOBAL_ROOT)
ANDROID_EXPORT_PATH := $(if $(LOCAL_ROOT),,$(GLOBAL_ROOT)/)$(LOCAL_OUTDIR)/unknown-ndk-linux-android
ANDROID_TARGET ?= aarch64-linux-android24

OSTYPE_GENERAL_CFLAGS := -Wall -fvisibility=hidden
OSTYPE_LIB_CFLAGS := -fPIC -DPIC
OSTYPE_EXEC_CFLAGS :=

OSTYPE_GENERAL_CXXFLAGS := -Wall -Wno-overloaded-virtual -frtti -fvisibility=hidden -fvisibility-inlines-hidden
OSTYPE_LIB_CXXFLAGS := -fPIC -DPIC
OSTYPE_EXEC_CXXFLAGS :=

OSTYPE_GENERAL_LDFLAGS :=
OSTYPE_EXEC_LDFLAGS := 
OSTYPE_LIB_LDFLAGS := -rdynamic -Wl,--exclude-libs,ALL

android_lib_list = \
	$(foreach lib,$(filter %.a,$(1)),$(2)_$(basename $(subst -,_,$(notdir $(lib))))_generic)

android_lib_defs = \
	$(foreach lib,$(1),\n\ninclude $$(CLEAR_VARS)\nLOCAL_MODULE := $(2)_$(basename $(subst -,_,$(notdir $(lib))))_generic\nLOCAL_SRC_FILES := $(abspath $(lib))\ninclude $$(PREBUILT_STATIC_LIBRARY))

android_filter_libs = \
	$(filter %.a,$(1))

android_filter_build_type = \
	$(subst /$(BUILD_TYPE)/,/$$(BUILD_TYPE)/,$(1))

define ANDROID_write_file
@echo '$(tab)$(2) \' >> $(1)$(newline)$(tab)
endef

$(ANDROID_EXPORT_PATH)/Android.mk.tmp:
	@$(call rule_mkdir,$(ANDROID_EXPORT_PATH))
	@echo '# Autogenerated by makefile' > $@
	@echo 'BUILD_TYPE := $$(if $$(filter 1,$$(NDK_DEBUG)),debug,release)' >> $@
	@echo 'ifeq ($$(TARGET_ARCH_ABI),armeabi-v7a)' >> $@
	@echo 'BUILD_ARCH := armv7a-linux-androideabi' >> $@
	@echo 'endif' >> $@
	@echo 'ifeq ($$(TARGET_ARCH_ABI),arm64-v8a)' >> $@
	@echo 'BUILD_ARCH := aarch64-linux-android' >> $@
	@echo 'endif' >> $@
	@echo 'ifeq ($$(TARGET_ARCH_ABI),x86_64)' >> $@
	@echo 'BUILD_ARCH := x86_64-linux-android' >> $@
	@echo 'endif' >> $@
	@echo 'ifeq ($$(TARGET_ARCH_ABI),x86)' >> $@
	@echo 'BUILD_ARCH := i686-linux-android' >> $@
	@echo 'endif' >> $@
	@echo 'include $$(CLEAR_VARS)' >> $@
	@echo 'LOCAL_MODULE := stappler_application_generic' >> $@
	@echo 'LOCAL_EXPORT_LDLIBS := -llog -landroid -lc++abi' >> $@
	@echo 'LOCAL_C_INCLUDES := \' >> $@
	$(foreach file,$(realpath $(BUILD_INCLUDES)) $(TOOLKIT_INCLUDES) $(abspath $(dir $(call android_filter_build_type,$(BUILD_EXEC_CONFIG)))),\
		$(call ANDROID_write_file,$@,$(file)))
	$(foreach file,$(abspath $(sort $(call android_filter_build_type,\
		$(BUILD_SHADERS_OUTDIR)))),\
		$(call ANDROID_write_file,$@,$(file)))
	@echo '	$(TARGET_SYSROOT)/usr/include $(TARGET_SYSROOT)/usr/include/$$(BUILD_ARCH)' >> $@
	@echo '' >> $@
	@echo 'LOCAL_CFLAGS := -DUSE_FILE32API $(strip $(TOOLKIT_GENERAL_CFLAGS) $(TOOLKIT_LIB_CFLAGS))' >> $@
	@echo 'LOCAL_SRC_FILES := \' >> $@
	$(foreach file,$(realpath $(BUILD_LIB_SRCS)) $(abspath $(call android_filter_build_type,$(BUILD_APP_CONFIG_SOURCE))),\
		$(call ANDROID_write_file,$@,$(file)))
	@echo '' >> $@
	@echo 'LOCAL_WHOLE_STATIC_LIBRARIES := cpufeatures $(call android_lib_list,$(sort $(BUILD_LIBS)),build)' >> $@
	@echo 'include $$(BUILD_STATIC_LIBRARY)' >> $@
	@echo -e '$(call android_lib_defs,$(call android_filter_libs,$(sort $(BUILD_LIBS))),build)' >> $@
	@echo '' >> $@
	@echo '$$(call import-module,android/cpufeatures)' >> $@

$(ANDROID_EXPORT_PATH)/Application.mk.tmp:
	@$(call rule_mkdir,$(ANDROID_EXPORT_PATH))
	@echo '# Autogenerated by makefile' > $@
	@echo 'APP_STL := none' >> $@
	@echo 'APP_ABI := arm64-v8a x86_64 armeabi-v7a x86' >> $@
	@echo 'APP_CPPFLAGS := -frtti -fno-exceptions -std=gnu++20 -nostdinc++ \' >> $@
	@echo '	-Wno-extern-c-compat -Wno-gnu-string-literal-operator-template -Wno-unqualified-std-cast-call \' >> $@
	@echo '	-Wnullability-completeness $(strip $(TOOLKIT_GENERAL_CXXFLAGS) $(TOOLKIT_LIB_CXXFLAGS))' >> $@

android-export: $(ANDROID_EXPORT_PATH)/Android.mk.tmp $(ANDROID_EXPORT_PATH)/Application.mk.tmp
	@if cmp -s "$(ANDROID_EXPORT_PATH)/Android.mk.tmp" "$(ANDROID_EXPORT_PATH)/Android.mk" ; then\
		echo "$(ANDROID_EXPORT_PATH)/Android.mk is up to date"; \
		rm $(ANDROID_EXPORT_PATH)/Android.mk.tmp; \
	else \
		rm -f $(ANDROID_EXPORT_PATH)/Android.mk; \
		mv $(ANDROID_EXPORT_PATH)/Android.mk.tmp $(ANDROID_EXPORT_PATH)/Android.mk; \
		touch $(ANDROID_EXPORT_PATH)/Android.mk; \
		echo "$(ANDROID_EXPORT_PATH)/Android.mk was updated"; \
	fi
	@if cmp -s "$(ANDROID_EXPORT_PATH)/Application.mk.tmp" "$(ANDROID_EXPORT_PATH)/Application.mk" ; then\
		echo "$(ANDROID_EXPORT_PATH)/Application.mk is up to date"; \
		rm $(ANDROID_EXPORT_PATH)/Application.mk.tmp; \
	else \
		rm -f $(ANDROID_EXPORT_PATH)/Application.mk; \
		mv $(ANDROID_EXPORT_PATH)/Application.mk.tmp $(ANDROID_EXPORT_PATH)/Application.mk; \
		touch $(ANDROID_EXPORT_PATH)/Application.mk; \
		echo "$(ANDROID_EXPORT_PATH)/Application.mk was updated"; \
	fi

.PHONY: android android-clean android-export

ANDROID := 1