# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Build libc++abi + libunwind for the NuttX target.
#
# NuttX flat build links no C++ ABI runtime of its own (libxx.a is the bare
# minimum), and libsprt is built -fexceptions: clang lowers throw/catch into
# __cxa_* calls + a DWARF unwinder. This file builds the LLVM runtimes
# (libc++abi with merged libunwind) against the imported NuttX libc, the same
# "runtimes superbuild" shape target-wasm uses for compiler-rt/libunwind.
#
# Output: usr/lib/libc++abi.a + usr/lib/libunwind.a in the target sysroot.
# libsprt is the STL — libc++ itself is NOT built here (that is the wasm model
# too).
#
# NuttX porting notes:
#   * LIBUNWIND_IS_BAREMETAL=ON selects libunwind's baremetal path, which looks
#     up the EH sections via extern __eh_frame_hdr_{start,end} symbols instead
#     of dl_iterate_phdr() — NuttX has no <link.h> / dl_iterate_phdr (single
#     flat ELF, no dynamic loader), so the dl_iterate path cannot compile.
#     baremetal also switches _LIBUNWIND_REMEMBER_ALLOC to __builtin_alloca and
#     silences the fprintf-based debug log under NDEBUG.
#   * The base toolchain.cmake bakes -fno-exceptions -fno-rtti -nostdinc++ into
#     CMAKE_CXX_FLAGS_INIT (it is meant for the NuttX flat app, not the C++
#     runtime). libcxxabi needs -fexceptions/-frtti; libunwind manages its own
#     -fno-exceptions/-fno-rtti. We override CMAKE_CXX_FLAGS_INIT here, sourcing
#     only the NuttX libc -isystem + -D__NuttX__ + target triple, and let each
#     runtime add the EH/RTTI flags it needs.
#   * libcxxabi's sources include <exception>, <stdexcept>, <typeinfo>,
#     <cstdlib>, <cstring> from libc++. The engine's own vendored libc++ tree
#     (runtime/libcxx/include) is a sprt-STL hybrid that needs the full
#     runtime/include_libc/cxx overlay to compile — unusable here. libcxxabi
#     needs upstream libc++ with working C-header wrappers, so we point at the
#     LLVM monorepo's libc++ headers ($(LLVM_SRC)/libcxx/include) and generate
#     a __config_site overlay carrying _LIBCPP_ABI_NAMESPACE=__sprt so the
#     typeinfo/vtable symbols libcxxabi emits line up with the engine's
#     -D_LIBCPP_ABI_NAMESPACE=__sprt build.

.DEFAULT_GOAL := all

LIBNAME := llvm-project
# LLVM monorepo: prefer LIB_SRC_DIR (CI / out-of-tree); fall back to the
# conventional builder location where the engine build host has it checked out.
LLVM_SRC ?= $(if $(wildcard $(LIB_SRC_DIR)/$(LIBNAME)),$(LIB_SRC_DIR)/$(LIBNAME),/build/toolchain-src/$(LIBNAME))

# Build inside OUT (writable) — same pattern as the simde rule in init-target.mk.
BUILD_DIR := $(TOOLCHAIN_OUTPUT_DIR)/_runtimes-build-nuttx

include ../common/utils/detect-platform.mk
include ../common/utils/init-shell.mk

# The runtimes superbuild needs the toolchain.cmake generated by init-target.mk
# (sets --target=aarch64-none-elf, -resource-dir, the NuttX libc include path).
SP_TOOLCHAIN_FILE := $(TOOLCHAIN_OUTPUT_DIR)/toolchain.cmake
SP_INSTALL_PREFIX := $(TOOLCHAIN_OUTPUT_DIR)/sysroot

# libc++abi's sources include <exception>, <stdexcept>, <typeinfo>, <cstdlib>,
# <cstring> ... from libc++. The engine's own vendored libc++ tree
# (runtime/libcxx/include) is NOT usable here: it is a sprt-STL hybrid that
# only compiles with the full runtime/include_libc/cxx overlay (it has no
# standalone <cstdlib>/<cstring> C-header wrappers, and its __config pulls in
# sprt-internal headers). libcxxabi needs upstream libc++ with the working
# C-header wrappers + cmake-generated __config_site/__assertion_handler, so we
# include libcxx in LLVM_ENABLE_RUNTIMES below: the runtimes superbuild runs
# libcxx's cmake configure (which generates those headers into the per-runtime
# build dir) even though we only build+install the cxxabi + unwind targets.
SP_LIBCXX_INCLUDES := $(LLVM_SRC)/libcxx/include

# NuttX libc sysroot include dir (matches the -isystem baked into toolchain.cmake).
SP_NUTTX_LIBC_INCLUDES := $(SP_INSTALL_PREFIX)/usr/include

# CXX flags for the runtimes build: keep the NuttX libc on the search path and
# __NuttX__ defined, and leave exception/RTTI handling to each runtime
# (libcxxabi forces -fexceptions/-frtti on its TUs, libunwind forces
# -fno-exceptions/-fno-rtti on its own). The base toolchain.cmake's
# -fno-exceptions/-fno-rtti/-nostdinc++ are dropped here — they are for the
# NuttX flat app, not for the C++ ABI runtime. We deliberately do NOT add
# libc++'s include dir here: the runtimes superbuild adds it itself (per-TU,
# after generating __config_site/__assertion_handler via libcxx's configure),
# and a stray -isystem here would put NuttX's <stdlib.h> ahead of libc++'s
# wrapper, tripping libc++'s _LIBCPP_STDLIB_H sanity check.
# NuttX flat build has no PT_TLS segment and the engine/libsprt compile with
# -femulated-tls (thread_local lowers to __emutls_get_address). Match that
# here so libc++abi/libunwind stay linkable without a PT_TLS-aware linker
# script: -femulated-tls keeps the same __emutls_* ABI the engine uses.
SP_RUNTIMES_CXX_FLAGS := --target=$(SP_ARCH_TARGET_CLANG) -march=armv8-a \
	-isystem $(SP_NUTTX_LIBC_INCLUDES) \
	-D__NuttX__ -D_LDBL_EQ_DBL -fno-common -femulated-tls

# LLVM_ENABLE_RUNTIMES lists what the superbuild CONFIGURES; libcxx is in the
# list only so its cmake configure generates __config_site / __assertion_handler
# / the C-header wrappers into the per-runtime build tree (libcxxabi's sources
# #include <cstdlib>/<cstring>/<exception>/... and need those generated bits).
# We do NOT build/install libcxx itself — the build target below is cxxabi+unwind
# only — so this costs configure time, not compile time. libsprt remains the STL.
#
# LIBCXX_ABI_NAMESPACE=__sprt is the load-bearing knob: it makes libcxx's
# configure emit _LIBCPP_ABI_NAMESPACE=__sprt into __config_site, so libcxxabi's
# typeinfo/vtable symbols land in std::__sprt and match the engine's
# -D_LIBCPP_ABI_NAMESPACE=__sprt build. Without it libcxxabi would emit std::__1
# symbols and the flat-image link would still miss _ZTINSt6__sprt9bad_allocE.
CONFIGURE := \
	-G "Ninja" \
	-S $(LLVM_SRC)/runtimes \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_TOOLCHAIN_FILE=$(realpath $(SP_TOOLCHAIN_FILE)) \
	-DCMAKE_INSTALL_PREFIX=$(SP_INSTALL_PREFIX) \
	-DCMAKE_INSTALL_LIBDIR=$(SP_INSTALL_PREFIX)/usr/lib \
	-DCMAKE_INSTALL_INCLUDEDIR=$(SP_INSTALL_PREFIX)/usr/include \
	-DLLVM_ENABLE_RUNTIMES="libcxx;libunwind;libcxxabi" \
	-DLLVM_INCLUDE_TESTS=Off \
	-DLIBCXX_INCLUDE_TESTS=Off \
	-DLIBCXXABI_INCLUDE_TESTS=Off \
	-DLIBUNWIND_INCLUDE_TESTS=Off \
	-DLLVM_ENABLE_PIC=Off \
	-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=Off \
	-DLLVM_DEFAULT_TARGET_TRIPLE=$(SP_ARCH_TARGET_CLANG) \
	-DLLVM_HOST_TRIPLE=$(SP_ARCH_TARGET_CLANG) \
	-DLIBUNWIND_ENABLE_SHARED=Off \
	-DLIBUNWIND_ENABLE_STATIC=On \
	-DLIBUNWIND_SHARED_OUTPUT_NAME=unwind_shared \
	-DLIBUNWIND_ENABLE_THREADS=On \
	-DLIBUNWIND_USE_COMPILER_RT=On \
	-DLIBUNWIND_INSTALL_LIBRARY_DIR=usr/lib \
	-DLIBUNWIND_HAS_PTHREAD_THREAD=On \
	-DLIBUNWIND_IS_BAREMETAL=On \
	-DLIBCXX_ENABLE_SHARED=Off \
	-DLIBCXX_ENABLE_STATIC=On \
	-DLIBCXX_STATIC_OUTPUT_NAME=c++_static \
	-DLIBCXX_ENABLE_FILESYSTEM=Off \
	-DLIBCXX_ENABLE_RANDOM_DEVICE=Off \
	-DLIBCXX_ENABLE_LOCALIZATION=Off \
	-DLIBCXX_ENABLE_TIME_ZONE_DATABASE=Off \
	-DLIBCXX_ENABLE_WIDE_CHARACTERS=On \
	-DLIBCXX_ENABLE_UNICODE=Off \
	-DLIBCXX_ABI_NAMESPACE=__sprt \
	-DLIBCXX_HARDENING_MODE=none \
	-DLIBCXXABI_ENABLE_SHARED=Off \
	-DLIBCXXABI_ENABLE_STATIC=On \
	-DLIBCXXABI_SHARED_OUTPUT_NAME=c++abi_shared \
	-DLIBCXXABI_ENABLE_THREADS=On \
	-DLIBCXXABI_ENABLE_EXCEPTIONS=On \
	-DLIBCXXABI_USE_LLVM_UNWINDER=On \
	-DLIBCXXABI_USE_COMPILER_RT=On \
	-DLIBCXXABI_ENABLE_STATIC_UNWINDER=Off \
	-DLIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS=Off \
	-DLIBCXXABI_INSTALL_LIBRARY_DIR=usr/lib \
	-DCMAKE_CXX_FLAGS="$(SP_RUNTIMES_CXX_FLAGS)"
# Build only the cxxabi + unwind static archives; skip libcxx itself (libsprt
# is the STL) and the runtimes-uber-targets (check-runtimes / install would
# also build libcxx). The `cxx_static`/`unwind_static` archive-link targets
# depend on libcxx's header-generation step (generate-cxx-headers emits the
# __config_site / __assertion_handler libcxxabi's TUs compile against), so we
# do not need to schedule it separately.
RUNTIMES_BUILD_TARGETS := cxxabi_static unwind_static

# Where the static archives land in the runtimes build tree. The runtimes
# superbuild puts them at <build>/lib/<name>.a (the `build/` prefix was an old
# guess; the actual ninja archive rules emit build/lib/libc++abi.a, but the
# runtimes-bins subdir layout drops the build/ prefix — verified against the
# generated build.ninja).
SP_LIBCXXABI_A := $(BUILD_DIR)/lib/libc++abi.a
SP_LIBUNWIND_A := $(BUILD_DIR)/lib/libunwind.a
SP_LIBCXXABI_DST := $(SP_INSTALL_PREFIX)/usr/lib/libc++abi.a
SP_LIBUNWIND_DST := $(SP_INSTALL_PREFIX)/usr/lib/libunwind.a

all:
	@if [ -f "$(SP_LIBCXXABI_DST)" ] && [ -f "$(SP_LIBUNWIND_DST)" ]; then \
		echo "ok: libc++abi/libunwind already staged"; \
	else \
		rm -rf "$(BUILD_DIR)"; \
		mkdir -p "$(BUILD_DIR)"; \
		cd "$(BUILD_DIR)" && cmake $(CONFIGURE) && \
			cmake --build . --config Release --target $(RUNTIMES_BUILD_TARGETS); \
		mkdir -p "$(dir $(SP_LIBCXXABI_DST))"; \
		cp -f "$(SP_LIBCXXABI_A)" "$(SP_LIBCXXABI_DST)"; \
		cp -f "$(SP_LIBUNWIND_A)" "$(SP_LIBUNWIND_DST)"; \
		rm -rf "$(BUILD_DIR)"; \
	fi

.PHONY: all
