/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_ABI_WINCRYPT_H_
#define SPRT_WRAPPERS_WINDOWS_ABI_WINCRYPT_H_


#include <sprt/wrappers/windows/abi/structures.h>
#include <sprt/wrappers/windows/abi/constants.h>

// clang-format off
#define __SPRT_PROV_RSA_FULL           1
#define __SPRT_PROV_RSA_SIG            2
#define __SPRT_PROV_DSS                3
#define __SPRT_PROV_FORTEZZA           4
#define __SPRT_PROV_MS_EXCHANGE        5
#define __SPRT_PROV_SSL                6
#define __SPRT_PROV_RSA_SCHANNEL       12
#define __SPRT_PROV_DSS_DH             13
#define __SPRT_PROV_EC_ECDSA_SIG       14
#define __SPRT_PROV_EC_ECNRA_SIG       15
#define __SPRT_PROV_EC_ECDSA_FULL      16
#define __SPRT_PROV_EC_ECNRA_FULL      17
#define __SPRT_PROV_DH_SCHANNEL        18
#define __SPRT_PROV_SPYRUS_LYNKS       20
#define __SPRT_PROV_RNG                21
#define __SPRT_PROV_INTEL_SEC          22
#define __SPRT_PROV_REPLACE_OWF        23
#define __SPRT_PROV_RSA_AES            24

#define __SPRT_CRYPT_VERIFYCONTEXT     0xF0000000
#define __SPRT_CRYPT_NEWKEYSET         0x00000008
#define __SPRT_CRYPT_DELETEKEYSET      0x00000010
#define __SPRT_CRYPT_MACHINE_KEYSET    0x00000020
#define __SPRT_CRYPT_SILENT            0x00000040
#define __SPRT_CRYPT_EXPORTABLE        0x00000001
#define __SPRT_CRYPT_USER_PROTECTED    0x00000002
#define __SPRT_CRYPT_CREATE_SALT       0x00000004
#define __SPRT_CRYPT_UPDATE_KEY        0x00000008
#define __SPRT_CRYPT_NO_SALT           0x00000010
#define __SPRT_CRYPT_PREGEN            0x00000040
#define __SPRT_CRYPT_RECIPIENT         0x00000010
#define __SPRT_CRYPT_INITIATOR         0x00000040
#define __SPRT_CRYPT_ONLINE            0x00000080
#define __SPRT_CRYPT_SF                0x00000100
#define __SPRT_CRYPT_CREATE_IV         0x00000200
#define __SPRT_CRYPT_KEK               0x00000400
#define __SPRT_CRYPT_DATA_KEY          0x00000800
#define __SPRT_CRYPT_VOLATILE          0x00001000
#define __SPRT_CRYPT_SGCKEY            0x00002000

#define __SPRT_CERT_ENCODING_TYPE_MASK     0x0000FFFF
#define __SPRT_CMSG_ENCODING_TYPE_MASK     0xFFFF0000
#define __SPRT_GET_CERT_ENCODING_TYPE(X)   (X & __SPRT_CERT_ENCODING_TYPE_MASK)
#define __SPRT_GET_CMSG_ENCODING_TYPE(X)   (X & __SPRT_CMSG_ENCODING_TYPE_MASK)

#define __SPRT_CRYPT_ASN_ENCODING          0x00000001
#define __SPRT_CRYPT_NDR_ENCODING          0x00000002
#define __SPRT_X509_ASN_ENCODING           0x00000001
#define __SPRT_X509_NDR_ENCODING           0x00000002
#define __SPRT_PKCS_7_ASN_ENCODING         0x00010000
#define __SPRT_PKCS_7_NDR_ENCODING         0x00020000

#define __SPRT_CERT_INFO_VERSION_FLAG                      1
#define __SPRT_CERT_INFO_SERIAL_NUMBER_FLAG                2
#define __SPRT_CERT_INFO_SIGNATURE_ALGORITHM_FLAG          3
#define __SPRT_CERT_INFO_ISSUER_FLAG                       4
#define __SPRT_CERT_INFO_NOT_BEFORE_FLAG                   5
#define __SPRT_CERT_INFO_NOT_AFTER_FLAG                    6
#define __SPRT_CERT_INFO_SUBJECT_FLAG                      7
#define __SPRT_CERT_INFO_SUBJECT_PUBLIC_KEY_INFO_FLAG      8
#define __SPRT_CERT_INFO_ISSUER_UNIQUE_ID_FLAG             9
#define __SPRT_CERT_INFO_SUBJECT_UNIQUE_ID_FLAG            10
#define __SPRT_CERT_INFO_EXTENSION_FLAG                    11

#define __SPRT_CERT_COMPARE_MASK           0xFFFF
#define __SPRT_CERT_COMPARE_SHIFT          16
#define __SPRT_CERT_COMPARE_ANY            0
#define __SPRT_CERT_COMPARE_SHA1_HASH      1
#define __SPRT_CERT_COMPARE_NAME           2
#define __SPRT_CERT_COMPARE_ATTR           3
#define __SPRT_CERT_COMPARE_MD5_HASH       4
#define __SPRT_CERT_COMPARE_PROPERTY       5
#define __SPRT_CERT_COMPARE_PUBLIC_KEY     6
#define __SPRT_CERT_COMPARE_HASH           __SPRT_CERT_COMPARE_SHA1_HASH
#define __SPRT_CERT_COMPARE_NAME_STR_A     7
#define __SPRT_CERT_COMPARE_NAME_STR_W     8
#define __SPRT_CERT_COMPARE_KEY_SPEC       9
#define __SPRT_CERT_COMPARE_ENHKEY_USAGE   10
#define __SPRT_CERT_COMPARE_CTL_USAGE      __SPRT_CERT_COMPARE_ENHKEY_USAGE
#define __SPRT_CERT_COMPARE_SUBJECT_CERT   11
#define __SPRT_CERT_COMPARE_ISSUER_OF      12
#define __SPRT_CERT_COMPARE_EXISTING       13
#define __SPRT_CERT_COMPARE_SIGNATURE_HASH 14
#define __SPRT_CERT_COMPARE_KEY_IDENTIFIER 15
#define __SPRT_CERT_COMPARE_CERT_ID        16
#define __SPRT_CERT_COMPARE_CROSS_CERT_DIST_POINTS 17
#define __SPRT_CERT_COMPARE_PUBKEY_MD5_HASH 18
#define __SPRT_CERT_COMPARE_SUBJECT_INFO_ACCESS 19
#define __SPRT_CERT_COMPARE_HASH_STR       20
#define __SPRT_CERT_COMPARE_HAS_PRIVATE_KEY 21
#define __SPRT_CERT_COMPARE_SHA256_HASH    22
#define __SPRT_CERT_COMPARE_SHA1_SHA256_HASH 23

#define __SPRT_CERT_FIND_ANY           (__SPRT_CERT_COMPARE_ANY << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_SHA1_HASH     (__SPRT_CERT_COMPARE_SHA1_HASH << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_SHA256_HASH   (__SPRT_CERT_COMPARE_SHA256_HASH << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_SHA1_SHA256_HASH   (__SPRT_CERT_COMPARE_SHA1_SHA256_HASH << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_MD5_HASH      (__SPRT_CERT_COMPARE_MD5_HASH << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_SIGNATURE_HASH (__SPRT_CERT_COMPARE_SIGNATURE_HASH << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_KEY_IDENTIFIER (__SPRT_CERT_COMPARE_KEY_IDENTIFIER << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_HASH          __SPRT_CERT_FIND_SHA1_HASH
#define __SPRT_CERT_FIND_PROPERTY      (__SPRT_CERT_COMPARE_PROPERTY << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_PUBLIC_KEY    (__SPRT_CERT_COMPARE_PUBLIC_KEY << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_SUBJECT_NAME  (__SPRT_CERT_COMPARE_NAME << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_SUBJECT_FLAG)
#define __SPRT_CERT_FIND_SUBJECT_ATTR  (__SPRT_CERT_COMPARE_ATTR << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_SUBJECT_FLAG)
#define __SPRT_CERT_FIND_ISSUER_NAME   (__SPRT_CERT_COMPARE_NAME << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_ISSUER_FLAG)
#define __SPRT_CERT_FIND_ISSUER_ATTR   (__SPRT_CERT_COMPARE_ATTR << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_ISSUER_FLAG)
#define __SPRT_CERT_FIND_SUBJECT_STR_A (__SPRT_CERT_COMPARE_NAME_STR_A << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_SUBJECT_FLAG)
#define __SPRT_CERT_FIND_SUBJECT_STR_W (__SPRT_CERT_COMPARE_NAME_STR_W << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_SUBJECT_FLAG)
#define __SPRT_CERT_FIND_SUBJECT_STR   __SPRT_CERT_FIND_SUBJECT_STR_W
#define __SPRT_CERT_FIND_ISSUER_STR_A  (__SPRT_CERT_COMPARE_NAME_STR_A << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_ISSUER_FLAG)
#define __SPRT_CERT_FIND_ISSUER_STR_W  (__SPRT_CERT_COMPARE_NAME_STR_W << __SPRT_CERT_COMPARE_SHIFT | \
                                 __SPRT_CERT_INFO_ISSUER_FLAG)
#define __SPRT_CERT_FIND_ISSUER_STR    __SPRT_CERT_FIND_ISSUER_STR_W
#define __SPRT_CERT_FIND_KEY_SPEC      (__SPRT_CERT_COMPARE_KEY_SPEC << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_ENHKEY_USAGE  (__SPRT_CERT_COMPARE_ENHKEY_USAGE << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_CTL_USAGE     __SPRT_CERT_FIND_ENHKEY_USAGE

#define __SPRT_CERT_FIND_SUBJECT_CERT  (__SPRT_CERT_COMPARE_SUBJECT_CERT << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_ISSUER_OF     (__SPRT_CERT_COMPARE_ISSUER_OF << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_EXISTING      (__SPRT_CERT_COMPARE_EXISTING << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_CERT_ID       (__SPRT_CERT_COMPARE_CERT_ID << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_CROSS_CERT_DIST_POINTS \
                    (__SPRT_CERT_COMPARE_CROSS_CERT_DIST_POINTS << __SPRT_CERT_COMPARE_SHIFT)


#define __SPRT_CERT_FIND_PUBKEY_MD5_HASH \
                    (__SPRT_CERT_COMPARE_PUBKEY_MD5_HASH << __SPRT_CERT_COMPARE_SHIFT)

#define __SPRT_CERT_FIND_SUBJECT_INFO_ACCESS \
                    (__SPRT_CERT_COMPARE_SUBJECT_INFO_ACCESS << __SPRT_CERT_COMPARE_SHIFT)

#define __SPRT_CERT_FIND_HASH_STR      (__SPRT_CERT_COMPARE_HASH_STR << __SPRT_CERT_COMPARE_SHIFT)
#define __SPRT_CERT_FIND_HAS_PRIVATE_KEY (__SPRT_CERT_COMPARE_HAS_PRIVATE_KEY << __SPRT_CERT_COMPARE_SHIFT)

#define __SPRT_SIMPLEBLOB              0x1
#define __SPRT_PUBLICKEYBLOB           0x6
#define __SPRT_PRIVATEKEYBLOB          0x7
#define __SPRT_PLAINTEXTKEYBLOB        0x8
#define __SPRT_OPAQUEKEYBLOB           0x9
#define __SPRT_PUBLICKEYBLOBEX         0xA
#define __SPRT_SYMMETRICWRAPKEYBLOB    0xB
#define __SPRT_KEYSTATEBLOB            0xC

#define __SPRT_ALG_CLASS_ANY                   (0)
#define __SPRT_ALG_CLASS_SIGNATURE             (1 << 13)
#define __SPRT_ALG_CLASS_MSG_ENCRYPT           (2 << 13)
#define __SPRT_ALG_CLASS_DATA_ENCRYPT          (3 << 13)
#define __SPRT_ALG_CLASS_HASH                  (4 << 13)
#define __SPRT_ALG_CLASS_KEY_EXCHANGE          (5 << 13)
#define __SPRT_ALG_CLASS_ALL                   (7 << 13)

#define __SPRT_ALG_TYPE_ANY                    (0)
#define __SPRT_ALG_TYPE_DSS                    (1 << 9)
#define __SPRT_ALG_TYPE_RSA                    (2 << 9)
#define __SPRT_ALG_TYPE_BLOCK                  (3 << 9)
#define __SPRT_ALG_TYPE_STREAM                 (4 << 9)
#define __SPRT_ALG_TYPE_DH                     (5 << 9)
#define __SPRT_ALG_TYPE_SECURECHANNEL          (6 << 9)
#define __SPRT_ALG_TYPE_ECDH                   (7 << 9)
#define __SPRT_ALG_TYPE_THIRDPARTY             (8 << 9)

#define __SPRT_ALG_SID_ANY                     (0)

#define __SPRT_ALG_SID_THIRDPARTY_ANY          (0)

// Some RSA sub-ids
#define __SPRT_ALG_SID_RSA_ANY                 0
#define __SPRT_ALG_SID_RSA_PKCS                1
#define __SPRT_ALG_SID_RSA_MSATWORK            2
#define __SPRT_ALG_SID_RSA_ENTRUST             3
#define __SPRT_ALG_SID_RSA_PGP                 4

// Some DSS sub-ids
//
#define __SPRT_ALG_SID_DSS_ANY                 0
#define __SPRT_ALG_SID_DSS_PKCS                1
#define __SPRT_ALG_SID_DSS_DMS                 2
#define __SPRT_ALG_SID_ECDSA                   3

// DES sub_ids
#define __SPRT_ALG_SID_DES                     1
#define __SPRT_ALG_SID_3DES                    3
#define __SPRT_ALG_SID_DESX                    4
#define __SPRT_ALG_SID_IDEA                    5
#define __SPRT_ALG_SID_CAST                    6
#define __SPRT_ALG_SID_SAFERSK64               7
#define __SPRT_ALG_SID_SAFERSK128              8
#define __SPRT_ALG_SID_3DES_112                9
#define __SPRT_ALG_SID_CYLINK_MEK              12
#define __SPRT_ALG_SID_RC5                     13
#define __SPRT_ALG_SID_AES_128                 14
#define __SPRT_ALG_SID_AES_192                 15
#define __SPRT_ALG_SID_AES_256                 16
#define __SPRT_ALG_SID_AES                     17

// Fortezza sub-ids
#define __SPRT_ALG_SID_SKIPJACK                10
#define __SPRT_ALG_SID_TEK                     11

// KP_MODE
#define __SPRT_CRYPT_MODE_CBCI                 6       // ANSI CBC Interleaved
#define __SPRT_CRYPT_MODE_CFBP                 7       // ANSI CFB Pipelined
#define __SPRT_CRYPT_MODE_OFBP                 8       // ANSI OFB Pipelined
#define __SPRT_CRYPT_MODE_CBCOFM               9       // ANSI CBC + OF Masking
#define __SPRT_CRYPT_MODE_CBCOFMI              10      // ANSI CBC + OFM Interleaved

#define __SPRT_ALG_SID_RC2                     2

#define __SPRT_ALG_SID_RC4                     1
#define __SPRT_ALG_SID_SEAL                    2

#define __SPRT_ALG_SID_DH_SANDF                1
#define __SPRT_ALG_SID_DH_EPHEM                2
#define __SPRT_ALG_SID_AGREED_KEY_ANY          3
#define __SPRT_ALG_SID_KEA                     4
#define __SPRT_ALG_SID_ECDH                    5
#define __SPRT_ALG_SID_ECDH_EPHEM              6

#define __SPRT_ALG_SID_MD2                     1
#define __SPRT_ALG_SID_MD4                     2
#define __SPRT_ALG_SID_MD5                     3
#define __SPRT_ALG_SID_SHA                     4
#define __SPRT_ALG_SID_SHA1                    4
#define __SPRT_ALG_SID_MAC                     5
#define __SPRT_ALG_SID_RIPEMD                  6
#define __SPRT_ALG_SID_RIPEMD160               7
#define __SPRT_ALG_SID_SSL3SHAMD5              8
#define __SPRT_ALG_SID_HMAC                    9
#define __SPRT_ALG_SID_TLS1PRF                 10
#define __SPRT_ALG_SID_HASH_REPLACE_OWF        11
#define __SPRT_ALG_SID_SHA_256                 12
#define __SPRT_ALG_SID_SHA_384                 13
#define __SPRT_ALG_SID_SHA_512                 14
#define __SPRT_ALG_SID_SSL3_MASTER             1
#define __SPRT_ALG_SID_SCHANNEL_MASTER_HASH    2
#define __SPRT_ALG_SID_SCHANNEL_MAC_KEY        3
#define __SPRT_ALG_SID_PCT1_MASTER             4
#define __SPRT_ALG_SID_SSL2_MASTER             5
#define __SPRT_ALG_SID_TLS1_MASTER             6
#define __SPRT_ALG_SID_SCHANNEL_ENC_KEY        7
#define __SPRT_ALG_SID_ECMQV                   1
#define __SPRT_ALG_SID_EXAMPLE                 80

#define __SPRT_CALG_MD2                (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_MD2)
#define __SPRT_CALG_MD4                (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_MD4)
#define __SPRT_CALG_MD5                (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_MD5)
#define __SPRT_CALG_SHA                (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SHA)
#define __SPRT_CALG_SHA1               (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SHA1)
#define __SPRT_CALG_MAC                (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_MAC)           // Deprecated. Don't use.
#define __SPRT_CALG_RSA_SIGN           (__SPRT_ALG_CLASS_SIGNATURE | __SPRT_ALG_TYPE_RSA | __SPRT_ALG_SID_RSA_ANY)
#define __SPRT_CALG_DSS_SIGN           (__SPRT_ALG_CLASS_SIGNATURE | __SPRT_ALG_TYPE_DSS | __SPRT_ALG_SID_DSS_ANY)
#define __SPRT_CALG_NO_SIGN            (__SPRT_ALG_CLASS_SIGNATURE | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_ANY)
#define __SPRT_CALG_RSA_KEYX           (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_RSA|__SPRT_ALG_SID_RSA_ANY)
#define __SPRT_CALG_DES                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_DES)
#define __SPRT_CALG_3DES_112           (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_3DES_112)
#define __SPRT_CALG_3DES               (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_3DES)
#define __SPRT_CALG_DESX               (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_DESX)
#define __SPRT_CALG_RC2                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_RC2)
#define __SPRT_CALG_RC4                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_STREAM|__SPRT_ALG_SID_RC4)
#define __SPRT_CALG_SEAL               (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_STREAM|__SPRT_ALG_SID_SEAL)
#define __SPRT_CALG_DH_SF              (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_DH|__SPRT_ALG_SID_DH_SANDF)
#define __SPRT_CALG_DH_EPHEM           (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_DH|__SPRT_ALG_SID_DH_EPHEM)
#define __SPRT_CALG_AGREEDKEY_ANY      (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_DH|__SPRT_ALG_SID_AGREED_KEY_ANY)
#define __SPRT_CALG_KEA_KEYX           (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_DH|__SPRT_ALG_SID_KEA)
#define __SPRT_CALG_HUGHES_MD5         (__SPRT_ALG_CLASS_KEY_EXCHANGE|__SPRT_ALG_TYPE_ANY|__SPRT_ALG_SID_MD5)
#define __SPRT_CALG_SKIPJACK           (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_SKIPJACK)
#define __SPRT_CALG_TEK                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_TEK)
#define __SPRT_CALG_CYLINK_MEK         (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_CYLINK_MEK)  // Deprecated. Do not use
#define __SPRT_CALG_SSL3_SHAMD5        (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SSL3SHAMD5)
#define __SPRT_CALG_SSL3_MASTER        (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_SSL3_MASTER)
#define __SPRT_CALG_SCHANNEL_MASTER_HASH   (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_SCHANNEL_MASTER_HASH)
#define __SPRT_CALG_SCHANNEL_MAC_KEY   (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_SCHANNEL_MAC_KEY)
#define __SPRT_CALG_SCHANNEL_ENC_KEY   (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_SCHANNEL_ENC_KEY)
#define __SPRT_CALG_PCT1_MASTER        (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_PCT1_MASTER)
#define __SPRT_CALG_SSL2_MASTER        (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_SSL2_MASTER)
#define __SPRT_CALG_TLS1_MASTER        (__SPRT_ALG_CLASS_MSG_ENCRYPT|__SPRT_ALG_TYPE_SECURECHANNEL|__SPRT_ALG_SID_TLS1_MASTER)
#define __SPRT_CALG_RC5                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_RC5)
#define __SPRT_CALG_HMAC               (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_HMAC)
#define __SPRT_CALG_TLS1PRF            (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_TLS1PRF)
#define __SPRT_CALG_HASH_REPLACE_OWF   (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_HASH_REPLACE_OWF)
#define __SPRT_CALG_AES_128            (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_AES_128)
#define __SPRT_CALG_AES_192            (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_AES_192)
#define __SPRT_CALG_AES_256            (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_AES_256)
#define __SPRT_CALG_AES                (__SPRT_ALG_CLASS_DATA_ENCRYPT|__SPRT_ALG_TYPE_BLOCK|__SPRT_ALG_SID_AES)
#define __SPRT_CALG_SHA_256            (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SHA_256)
#define __SPRT_CALG_SHA_384            (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SHA_384)
#define __SPRT_CALG_SHA_512            (__SPRT_ALG_CLASS_HASH | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_SHA_512)
#define __SPRT_CALG_ECDH               (__SPRT_ALG_CLASS_KEY_EXCHANGE | __SPRT_ALG_TYPE_DH | __SPRT_ALG_SID_ECDH)
#define __SPRT_CALG_ECDH_EPHEM         (__SPRT_ALG_CLASS_KEY_EXCHANGE | __SPRT_ALG_TYPE_ECDH | __SPRT_ALG_SID_ECDH_EPHEM)
#define __SPRT_CALG_ECMQV              (__SPRT_ALG_CLASS_KEY_EXCHANGE | __SPRT_ALG_TYPE_ANY | __SPRT_ALG_SID_ECMQV)
#define __SPRT_CALG_ECDSA              (__SPRT_ALG_CLASS_SIGNATURE | __SPRT_ALG_TYPE_DSS | __SPRT_ALG_SID_ECDSA)
#define __SPRT_CALG_NULLCIPHER         (__SPRT_ALG_CLASS_DATA_ENCRYPT | __SPRT_ALG_TYPE_ANY | 0)
#define __SPRT_CALG_THIRDPARTY_KEY_EXCHANGE    (__SPRT_ALG_CLASS_KEY_EXCHANGE | __SPRT_ALG_TYPE_THIRDPARTY | __SPRT_ALG_SID_THIRDPARTY_ANY)
#define __SPRT_CALG_THIRDPARTY_SIGNATURE       (__SPRT_ALG_CLASS_SIGNATURE    | __SPRT_ALG_TYPE_THIRDPARTY | __SPRT_ALG_SID_THIRDPARTY_ANY)
#define __SPRT_CALG_THIRDPARTY_CIPHER          (__SPRT_ALG_CLASS_DATA_ENCRYPT | __SPRT_ALG_TYPE_THIRDPARTY | __SPRT_ALG_SID_THIRDPARTY_ANY)
#define __SPRT_CALG_THIRDPARTY_HASH            (__SPRT_ALG_CLASS_HASH         | __SPRT_ALG_TYPE_THIRDPARTY | __SPRT_ALG_SID_THIRDPARTY_ANY)

#define __SPRT_HP_ALGID                0x0001  // Hash algorithm
#define __SPRT_HP_HASHVAL              0x0002  // Hash value
#define __SPRT_HP_HASHSIZE             0x0004  // Hash value size
#define __SPRT_HP_HMAC_INFO            0x0005  // information for creating an HMAC
#define __SPRT_HP_TLS1PRF_LABEL        0x0006  // label for TLS1 PRF
#define __SPRT_HP_TLS1PRF_SEED         0x0007  // seed for TLS1 PRF

#define __SPRT_CERT_DIGITAL_SIGNATURE_KEY_USAGE     0x80
#define __SPRT_CERT_NON_REPUDIATION_KEY_USAGE       0x40
#define __SPRT_CERT_KEY_ENCIPHERMENT_KEY_USAGE      0x20
#define __SPRT_CERT_DATA_ENCIPHERMENT_KEY_USAGE     0x10
#define __SPRT_CERT_KEY_AGREEMENT_KEY_USAGE         0x08
#define __SPRT_CERT_KEY_CERT_SIGN_KEY_USAGE         0x04
#define __SPRT_CERT_OFFLINE_CRL_SIGN_KEY_USAGE      0x02
#define __SPRT_CERT_CRL_SIGN_KEY_USAGE              0x02
#define __SPRT_CERT_ENCIPHER_ONLY_KEY_USAGE         0x01
#define __SPRT_CERT_DECIPHER_ONLY_KEY_USAGE         0x80

// clang-format on

typedef unsigned int ALG_ID;

typedef ULONG_PTR HCRYPTKEY;
typedef ULONG_PTR HCRYPTHASH;
typedef ULONG_PTR HCRYPTPROV;
typedef ULONG_PTR HCRYPTPROV_LEGACY;

typedef void *HCERTSTORE;

typedef struct _CRYPTOAPI_BLOB {
	DWORD cbData;
	BYTE *pbData;
} CRYPT_INTEGER_BLOB, *PCRYPT_INTEGER_BLOB, CRYPT_UINT_BLOB, *PCRYPT_UINT_BLOB, CRYPT_OBJID_BLOB,
		*PCRYPT_OBJID_BLOB, CERT_NAME_BLOB, *PCERT_NAME_BLOB, CERT_RDN_VALUE_BLOB,
		*PCERT_RDN_VALUE_BLOB, CERT_BLOB, *PCERT_BLOB, CRL_BLOB, *PCRL_BLOB, DATA_BLOB, *PDATA_BLOB,
		CRYPT_DATA_BLOB, *PCRYPT_DATA_BLOB, CRYPT_HASH_BLOB, *PCRYPT_HASH_BLOB, CRYPT_DIGEST_BLOB,
		*PCRYPT_DIGEST_BLOB, CRYPT_DER_BLOB, *PCRYPT_DER_BLOB, CRYPT_ATTR_BLOB, *PCRYPT_ATTR_BLOB;

typedef struct _CRYPT_ALGORITHM_IDENTIFIER {
	LPSTR pszObjId;
	CRYPT_OBJID_BLOB Parameters;
} CRYPT_ALGORITHM_IDENTIFIER, *PCRYPT_ALGORITHM_IDENTIFIER;

typedef struct _CRYPT_BIT_BLOB {
	DWORD cbData;
	BYTE *pbData;
	DWORD cUnusedBits;
} CRYPT_BIT_BLOB, *PCRYPT_BIT_BLOB;

typedef struct _CERT_PUBLIC_KEY_INFO {
	CRYPT_ALGORITHM_IDENTIFIER Algorithm;
	CRYPT_BIT_BLOB PublicKey;
} CERT_PUBLIC_KEY_INFO, *PCERT_PUBLIC_KEY_INFO;

typedef struct _CERT_EXTENSION {
	LPSTR pszObjId;
	BOOL fCritical;
	CRYPT_OBJID_BLOB Value;
} CERT_EXTENSION, *PCERT_EXTENSION;
typedef const CERT_EXTENSION *PCCERT_EXTENSION;

typedef struct _CERT_INFO {
	DWORD dwVersion;
	CRYPT_INTEGER_BLOB SerialNumber;
	CRYPT_ALGORITHM_IDENTIFIER SignatureAlgorithm;
	CERT_NAME_BLOB Issuer;
	FILETIME NotBefore;
	FILETIME NotAfter;
	CERT_NAME_BLOB Subject;
	CERT_PUBLIC_KEY_INFO SubjectPublicKeyInfo;
	CRYPT_BIT_BLOB IssuerUniqueId;
	CRYPT_BIT_BLOB SubjectUniqueId;
	DWORD cExtension;
	PCERT_EXTENSION rgExtension;
} CERT_INFO, *PCERT_INFO;

typedef struct _CERT_CONTEXT {
	DWORD dwCertEncodingType;
	BYTE *pbCertEncoded;
	DWORD cbCertEncoded;
	PCERT_INFO pCertInfo;
	HCERTSTORE hCertStore;
} CERT_CONTEXT, *PCERT_CONTEXT;
typedef const CERT_CONTEXT *PCCERT_CONTEXT;

typedef struct _PUBLICKEYSTRUC {
	BYTE bType;
	BYTE bVersion;
	WORD reserved;
	ALG_ID aiKeyAlg;
} BLOBHEADER, PUBLICKEYSTRUC;

typedef struct _CTL_USAGE {
	DWORD cUsageIdentifier;
	LPSTR *rgpszUsageIdentifier;
} CTL_USAGE, *PCTL_USAGE, CERT_ENHKEY_USAGE, *PCERT_ENHKEY_USAGE;
typedef const CTL_USAGE *PCCTL_USAGE;
typedef const CERT_ENHKEY_USAGE *PCCERT_ENHKEY_USAGE;


#endif // SPRT_WRAPPERS_WINDOWS_ABI_WINCRYPT_H_
