#!/usr/bin/env python3
"""Drive ui::MarkdownView over a LONG document (XL_MARKDOWN_TEST).

The other script, markdown-check.py, asks whether the widget is correct on a document of forty
lines. This one asks the question milestone M7 is about: what a document of ten thousand lines
costs, and whether it is still the same document once only the visible part of it is laid out.

Two claims are being pinned here, and they pull against each other:

  * only what the reader can see is shaped - the widget keeps a handful of blocks live out of
    thousands, and the first frame arrives without laying out the rest;
  * and yet the document is unchanged - it is as tall as it would be if every block were laid
    out, the reading order still spans all of it, and copying the whole of it still returns the
    source file byte for byte.

The second is what makes the first safe to have. A virtualized document that is shorter than the
real one, or that cannot be copied past the fold, would be a different document.

    tests/window/markdown-perf-check.py [path-to-testapp]

big.md is generated by gen-big-md.py if it is missing.
"""
import json, os, socket, struct, subprocess, sys, threading, time

ADDR = os.environ.get("XENOLITH_INSPECTOR_SOCK", "/tmp/xl-markdown-perf.sock")
HERE = os.path.dirname(os.path.abspath(__file__))


class Session:
    def __init__(self, path=ADDR, timeout=600.0):
        self.s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self.s.settimeout(timeout)
        self.s.connect(path)
        self.s.sendall(b"xenolith/1 json\n")
        line = b""
        while not line.endswith(b"\n"):
            line += self.s.recv(1)
        assert line.startswith(b"# xenolith/1 ok"), line
        self.serial = 0
        self.buf = b""
        self.lock = threading.Lock()

    def call(self, cmd, **kw):
        with self.lock:
            self.serial += 1
            want = self.serial
            req = {"serial": want, "cmd": cmd}
            req.update(kw)
            payload = json.dumps(req).encode()
            self.s.sendall(struct.pack("<I", len(payload)) + payload)
            while True:
                while len(self.buf) < 4:
                    self.buf += self.s.recv(1 << 20)
                size = struct.unpack("<I", self.buf[:4])[0]
                while len(self.buf) < 4 + size:
                    self.buf += self.s.recv(1 << 20)
                frame = self.buf[4:4 + size]
                self.buf = self.buf[4 + size:]
                resp = json.loads(frame)
                if resp.get("serial") == want:
                    return resp

    def ok(self, cmd, **kw):
        r = self.call(cmd, **kw)
        if r.get("status") != "ok":
            raise SystemExit(f"{cmd} failed: {r.get('error')}")
        return r.get("result")

    def close(self):
        self.s.close()


def start_app(binary):
    env = dict(os.environ)
    env["XL_MARKDOWN_TEST"] = "1"
    env["XENOLITH_INSPECTOR_ADDRESS"] = "unix:" + ADDR
    try:
        os.unlink(ADDR)
    except OSError:
        pass

    # Inside a memory-capped scope: a document this size used to exhaust the machine, and a
    # regression that brings that back should take its own process down and nothing else.
    cmd = ["systemd-run", "--user", "--scope", "-p", "MemoryMax=4G", "-p", "MemorySwapMax=0",
            "--quiet", "--"] if os.environ.get("XL_NO_CGROUP") != "1" else []
    proc = subprocess.Popen(cmd + [binary, "--headless", "--width", "1100", "--height", "900"],
            env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(1200):
        if os.path.exists(ADDR):
            try:
                Session().close()
                return proc
            except OSError:
                pass
        time.sleep(0.05)
    proc.kill()
    raise SystemExit("app did not come up")


checks = 0
failures = 0


def check(name, ok, detail=""):
    global checks, failures
    checks += 1
    if ok:
        print(f"  ok   {name}")
    else:
        failures += 1
        print(f"  FAIL {name} {detail}")


doc = os.path.join(HERE, "big.md")
if not os.path.exists(doc):
    subprocess.run([sys.executable, os.path.join(HERE, "gen-big-md.py")], check=True)

binary = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE,
        "stappler-build/x86_64-unknown-linux-gnu/debug/cc/testapp")

proc = start_app(binary)
s = Session()
s.ok("render")


def md(name, **args):
    args.setdefault("settle", 0.0)
    return s.ok("invoke", name="markdown." + name, args=args)


def settle(limit=600):
    """Step frames until the measuring pass has covered the document."""
    for _ in range(limit):
        s.ok("frame", count=1)
        t = md("timings")
        if not t.get("virtual") or t.get("measuredBlocks") == t.get("virtualBlocks"):
            s.ok("frame", count=2)
            return md("timings")
    return md("timings")


# --- the same document, laid out whole, for the numbers everything else is compared against ------

md("virtual", threshold=4000000)
t0 = time.monotonic()
md("load", path=doc)
whole = settle()
whole_wall = time.monotonic() - t0
check("the whole document lays out", whole["blocks"] > 10000, whole["blocks"])
check("and virtualization is off for it", not whole["virtual"])
reference_height = whole["height"]

# --- and now with only its visible part laid out -------------------------------------------------

md("virtual")
t0 = time.monotonic()
first = md("load", path=doc)
build_wall = time.monotonic() - t0

check("building the tree is not the expensive part", first["build"] < 3e9,
        f"{first['build']/1e6:.0f}ms")
check("a long document turns virtualization on", md("timings")["virtual"])

virt = settle()
check("every block ends up measured", virt["measuredBlocks"] == virt["virtualBlocks"],
        (virt["measuredBlocks"], virt["virtualBlocks"]))

# The claim that makes the rest safe: the document is the height it would be anyway. A tolerance
# of a few pixels covers the last block's own bottom margin, which has no successor to measure
# against.
check("the virtualized document is as tall as the real one",
        abs(virt["height"] - reference_height) <= 32,
        (virt["height"], reference_height))

# ... while almost none of it is live.
check("and almost none of it is laid out at once",
        virt["visibleBlocks"] * 20 < virt["virtualBlocks"],
        (virt["visibleBlocks"], virt["virtualBlocks"]))

print(f"  ---- whole {whole_wall*1000:.0f}ms wall, virtual {build_wall*1000:.0f}ms to build, "
      f"{virt['virtualBlocks']} blocks, {virt['visibleBlocks']} live")

# --- the reading order still covers the whole document -------------------------------------------

flow = md("flow")
check("the reading order spans the document", md("timings")["textLength"] > 500000,
        md("timings")["textLength"])

source_len = md("timings")["sourceLength"]
markup = md("range", begin=0)["markup"]
check("selecting all of it returns the source", len(markup) >= source_len - 4,
        (len(markup), source_len))

text = md("range", begin=0)["text"]
check("and its readable text is shorter than its markup", 0 < len(text) < len(markup),
        (len(text), len(markup)))

# --- scrolling into the part that was never on screen ---------------------------------------------

anchors = md("anchors")
check("the document has anchors", len(anchors["anchors"]) > 100, len(anchors["anchors"]))

deep = sorted(anchors["anchors"], key=lambda a: a["position"])[-1]
before = md("anchors")["scrollY"]
jumped = md("anchor", id=deep["id"])
for _ in range(30):
    s.ok("frame", count=1)
after = md("anchors")["scrollY"]
check("an anchor near the end is reachable", jumped["found"], jumped)
check("and following it scrolls there", after > before + 1000, (before, after))

deep_state = md("timings")
check("and the window moved with it rather than growing",
        deep_state["visibleBlocks"] * 20 < deep_state["virtualBlocks"],
        (deep_state["visibleBlocks"], deep_state["virtualBlocks"]))
check("the document is still its own height", abs(deep_state["height"] - reference_height) <= 32,
        (deep_state["height"], reference_height))

s.ok("render", stop=True)
s.close()
proc.kill()

print(f"{checks} checks, {failures} failures")
sys.exit(1 if failures else 0)
