/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef CORE_RUNTIME_INCLUDE_LIBC_ARPA___INET_H_
#define CORE_RUNTIME_INCLUDE_LIBC_ARPA___INET_H_

#include <sprt/c/cross/__sprt_socket.h>
#include <sprt/c/cross/__sprt_netinet.h>
#include <sprt/c/__sprt_stdint.h>

#define INADDR_ANY __SPRT_INADDR_ANY
#define INADDR_LOOPBACK __SPRT_INADDR_LOOPBACK
#define INADDR_BROADCAST __SPRT_INADDR_BROADCAST
#define INADDR_NONE __SPRT_INADDR_NONE

#define INADDR_UNSPEC_GROUP __SPRT_INADDR_UNSPEC_GROUP
#define INADDR_ALLHOSTS_GROUP __SPRT_INADDR_ALLHOSTS_GROUP
#define INADDR_ALLRTRS_GROUP __SPRT_INADDR_ALLRTRS_GROUP
#define INADDR_MAX_LOCAL_GROUP __SPRT_INADDR_MAX_LOCAL_GROUP

// --- Address string lengths --------------------------------------------------
#ifndef INET_ADDRSTRLEN
#define INET_ADDRSTRLEN __SPRT_INET_ADDRSTRLEN
#endif
#ifndef INET6_ADDRSTRLEN
#define INET6_ADDRSTRLEN __SPRT_INET6_ADDRSTRLEN
#endif

// --- IP protocol numbers (IPPROTO_*) -----------------------------------------
#ifndef IPPROTO_IP
#define IPPROTO_IP __SPRT_IPPROTO_IP
#endif
#ifndef IPPROTO_HOPOPTS
#define IPPROTO_HOPOPTS __SPRT_IPPROTO_HOPOPTS
#endif
#ifndef IPPROTO_ICMP
#define IPPROTO_ICMP __SPRT_IPPROTO_ICMP
#endif
#ifndef IPPROTO_IGMP
#define IPPROTO_IGMP __SPRT_IPPROTO_IGMP
#endif
#ifndef IPPROTO_IPIP
#define IPPROTO_IPIP __SPRT_IPPROTO_IPIP
#endif
#ifndef IPPROTO_TCP
#define IPPROTO_TCP __SPRT_IPPROTO_TCP
#endif
#ifndef IPPROTO_EGP
#define IPPROTO_EGP __SPRT_IPPROTO_EGP
#endif
#ifndef IPPROTO_PUP
#define IPPROTO_PUP __SPRT_IPPROTO_PUP
#endif
#ifndef IPPROTO_UDP
#define IPPROTO_UDP __SPRT_IPPROTO_UDP
#endif
#ifndef IPPROTO_IDP
#define IPPROTO_IDP __SPRT_IPPROTO_IDP
#endif
#ifndef IPPROTO_TP
#define IPPROTO_TP __SPRT_IPPROTO_TP
#endif
#ifndef IPPROTO_DCCP
#define IPPROTO_DCCP __SPRT_IPPROTO_DCCP
#endif
#ifndef IPPROTO_IPV6
#define IPPROTO_IPV6 __SPRT_IPPROTO_IPV6
#endif
#ifndef IPPROTO_ROUTING
#define IPPROTO_ROUTING __SPRT_IPPROTO_ROUTING
#endif
#ifndef IPPROTO_FRAGMENT
#define IPPROTO_FRAGMENT __SPRT_IPPROTO_FRAGMENT
#endif
#ifndef IPPROTO_RSVP
#define IPPROTO_RSVP __SPRT_IPPROTO_RSVP
#endif
#ifndef IPPROTO_GRE
#define IPPROTO_GRE __SPRT_IPPROTO_GRE
#endif
#ifndef IPPROTO_ESP
#define IPPROTO_ESP __SPRT_IPPROTO_ESP
#endif
#ifndef IPPROTO_AH
#define IPPROTO_AH __SPRT_IPPROTO_AH
#endif
#ifndef IPPROTO_ICMPV6
#define IPPROTO_ICMPV6 __SPRT_IPPROTO_ICMPV6
#endif
#ifndef IPPROTO_NONE
#define IPPROTO_NONE __SPRT_IPPROTO_NONE
#endif
#ifndef IPPROTO_DSTOPTS
#define IPPROTO_DSTOPTS __SPRT_IPPROTO_DSTOPTS
#endif
#ifndef IPPROTO_MTP
#define IPPROTO_MTP __SPRT_IPPROTO_MTP
#endif
#ifndef IPPROTO_BEETPH
#define IPPROTO_BEETPH __SPRT_IPPROTO_BEETPH
#endif
#ifndef IPPROTO_ENCAP
#define IPPROTO_ENCAP __SPRT_IPPROTO_ENCAP
#endif
#ifndef IPPROTO_PIM
#define IPPROTO_PIM __SPRT_IPPROTO_PIM
#endif
#ifndef IPPROTO_COMP
#define IPPROTO_COMP __SPRT_IPPROTO_COMP
#endif
#ifndef IPPROTO_SCTP
#define IPPROTO_SCTP __SPRT_IPPROTO_SCTP
#endif
#ifndef IPPROTO_MH
#define IPPROTO_MH __SPRT_IPPROTO_MH
#endif
#ifndef IPPROTO_UDPLITE
#define IPPROTO_UDPLITE __SPRT_IPPROTO_UDPLITE
#endif
#ifndef IPPROTO_MPLS
#define IPPROTO_MPLS __SPRT_IPPROTO_MPLS
#endif
#ifndef IPPROTO_ETHERNET
#define IPPROTO_ETHERNET __SPRT_IPPROTO_ETHERNET
#endif
#ifndef IPPROTO_RAW
#define IPPROTO_RAW __SPRT_IPPROTO_RAW
#endif
#ifndef IPPROTO_MPTCP
#define IPPROTO_MPTCP __SPRT_IPPROTO_MPTCP
#endif
#ifndef IPPROTO_MAX
#define IPPROTO_MAX __SPRT_IPPROTO_MAX
#endif

// --- Reserved port range -----------------------------------------------------
#ifndef IPPORT_RESERVED
#define IPPORT_RESERVED __SPRT_IPPORT_RESERVED
#endif

// --- IPv4 address classes ----------------------------------------------------
#ifndef IN_CLASSA
#define IN_CLASSA(a) __SPRT_IN_CLASSA(a)
#endif
#ifndef IN_CLASSA_NET
#define IN_CLASSA_NET __SPRT_IN_CLASSA_NET
#endif
#ifndef IN_CLASSA_NSHIFT
#define IN_CLASSA_NSHIFT __SPRT_IN_CLASSA_NSHIFT
#endif
#ifndef IN_CLASSA_HOST
#define IN_CLASSA_HOST __SPRT_IN_CLASSA_HOST
#endif
#ifndef IN_CLASSA_MAX
#define IN_CLASSA_MAX __SPRT_IN_CLASSA_MAX
#endif
#ifndef IN_CLASSB
#define IN_CLASSB(a) __SPRT_IN_CLASSB(a)
#endif
#ifndef IN_CLASSB_NET
#define IN_CLASSB_NET __SPRT_IN_CLASSB_NET
#endif
#ifndef IN_CLASSB_NSHIFT
#define IN_CLASSB_NSHIFT __SPRT_IN_CLASSB_NSHIFT
#endif
#ifndef IN_CLASSB_HOST
#define IN_CLASSB_HOST __SPRT_IN_CLASSB_HOST
#endif
#ifndef IN_CLASSB_MAX
#define IN_CLASSB_MAX __SPRT_IN_CLASSB_MAX
#endif
#ifndef IN_CLASSC
#define IN_CLASSC(a) __SPRT_IN_CLASSC(a)
#endif
#ifndef IN_CLASSC_NET
#define IN_CLASSC_NET __SPRT_IN_CLASSC_NET
#endif
#ifndef IN_CLASSC_NSHIFT
#define IN_CLASSC_NSHIFT __SPRT_IN_CLASSC_NSHIFT
#endif
#ifndef IN_CLASSC_HOST
#define IN_CLASSC_HOST __SPRT_IN_CLASSC_HOST
#endif
#ifndef IN_CLASSD
#define IN_CLASSD(a) __SPRT_IN_CLASSD(a)
#endif
#ifndef IN_MULTICAST
#define IN_MULTICAST(a) __SPRT_IN_MULTICAST(a)
#endif
#ifndef IN_EXPERIMENTAL
#define IN_EXPERIMENTAL(a) __SPRT_IN_EXPERIMENTAL(a)
#endif
#ifndef IN_BADCLASS
#define IN_BADCLASS(a) __SPRT_IN_BADCLASS(a)
#endif
#ifndef IN_LOOPBACKNET
#define IN_LOOPBACKNET __SPRT_IN_LOOPBACKNET
#endif

// --- IPv6 address test macros ------------------------------------------------
#ifndef IN6_IS_ADDR_UNSPECIFIED
#define IN6_IS_ADDR_UNSPECIFIED(a) __SPRT_IN6_IS_ADDR_UNSPECIFIED(a)
#endif
#ifndef IN6_IS_ADDR_LOOPBACK
#define IN6_IS_ADDR_LOOPBACK(a) __SPRT_IN6_IS_ADDR_LOOPBACK(a)
#endif
#ifndef IN6_IS_ADDR_MULTICAST
#define IN6_IS_ADDR_MULTICAST(a) __SPRT_IN6_IS_ADDR_MULTICAST(a)
#endif
#ifndef IN6_IS_ADDR_LINKLOCAL
#define IN6_IS_ADDR_LINKLOCAL(a) __SPRT_IN6_IS_ADDR_LINKLOCAL(a)
#endif
#ifndef IN6_IS_ADDR_SITELOCAL
#define IN6_IS_ADDR_SITELOCAL(a) __SPRT_IN6_IS_ADDR_SITELOCAL(a)
#endif
#ifndef IN6_IS_ADDR_V4MAPPED
#define IN6_IS_ADDR_V4MAPPED(a) __SPRT_IN6_IS_ADDR_V4MAPPED(a)
#endif
#ifndef IN6_IS_ADDR_V4COMPAT
#define IN6_IS_ADDR_V4COMPAT(a) __SPRT_IN6_IS_ADDR_V4COMPAT(a)
#endif
#ifndef IN6_IS_ADDR_MC_NODELOCAL
#define IN6_IS_ADDR_MC_NODELOCAL(a) __SPRT_IN6_IS_ADDR_MC_NODELOCAL(a)
#endif
#ifndef IN6_IS_ADDR_MC_LINKLOCAL
#define IN6_IS_ADDR_MC_LINKLOCAL(a) __SPRT_IN6_IS_ADDR_MC_LINKLOCAL(a)
#endif
#ifndef IN6_IS_ADDR_MC_SITELOCAL
#define IN6_IS_ADDR_MC_SITELOCAL(a) __SPRT_IN6_IS_ADDR_MC_SITELOCAL(a)
#endif
#ifndef IN6_IS_ADDR_MC_ORGLOCAL
#define IN6_IS_ADDR_MC_ORGLOCAL(a) __SPRT_IN6_IS_ADDR_MC_ORGLOCAL(a)
#endif
#ifndef IN6_IS_ADDR_MC_GLOBAL
#define IN6_IS_ADDR_MC_GLOBAL(a) __SPRT_IN6_IS_ADDR_MC_GLOBAL(a)
#endif
#ifndef IN6_ARE_ADDR_EQUAL
#define IN6_ARE_ADDR_EQUAL(a, b) __SPRT_IN6_ARE_ADDR_EQUAL(a, b)
#endif

// --- IPv4 socket options (IPPROTO_IP level) ----------------------------------
#ifndef IP_TOS
#define IP_TOS __SPRT_IP_TOS
#endif
#ifndef IP_TTL
#define IP_TTL __SPRT_IP_TTL
#endif
#ifndef IP_HDRINCL
#define IP_HDRINCL __SPRT_IP_HDRINCL
#endif
#ifndef IP_OPTIONS
#define IP_OPTIONS __SPRT_IP_OPTIONS
#endif
#ifndef IP_ROUTER_ALERT
#define IP_ROUTER_ALERT __SPRT_IP_ROUTER_ALERT
#endif
#ifndef IP_RECVOPTS
#define IP_RECVOPTS __SPRT_IP_RECVOPTS
#endif
#ifndef IP_RETOPTS
#define IP_RETOPTS __SPRT_IP_RETOPTS
#endif
#ifndef IP_PKTINFO
#define IP_PKTINFO __SPRT_IP_PKTINFO
#endif
#ifndef IP_PKTOPTIONS
#define IP_PKTOPTIONS __SPRT_IP_PKTOPTIONS
#endif
#ifndef IP_PMTUDISC
#define IP_PMTUDISC __SPRT_IP_PMTUDISC
#endif
#ifndef IP_MTU_DISCOVER
#define IP_MTU_DISCOVER __SPRT_IP_MTU_DISCOVER
#endif
#ifndef IP_RECVERR
#define IP_RECVERR __SPRT_IP_RECVERR
#endif
#ifndef IP_RECVTTL
#define IP_RECVTTL __SPRT_IP_RECVTTL
#endif
#ifndef IP_RECVTOS
#define IP_RECVTOS __SPRT_IP_RECVTOS
#endif
#ifndef IP_MTU
#define IP_MTU __SPRT_IP_MTU
#endif
#ifndef IP_FREEBIND
#define IP_FREEBIND __SPRT_IP_FREEBIND
#endif
#ifndef IP_IPSEC_POLICY
#define IP_IPSEC_POLICY __SPRT_IP_IPSEC_POLICY
#endif
#ifndef IP_XFRM_POLICY
#define IP_XFRM_POLICY __SPRT_IP_XFRM_POLICY
#endif
#ifndef IP_PASSSEC
#define IP_PASSSEC __SPRT_IP_PASSSEC
#endif
#ifndef IP_TRANSPARENT
#define IP_TRANSPARENT __SPRT_IP_TRANSPARENT
#endif
#ifndef IP_ORIGDSTADDR
#define IP_ORIGDSTADDR __SPRT_IP_ORIGDSTADDR
#endif
#ifndef IP_RECVORIGDSTADDR
#define IP_RECVORIGDSTADDR __SPRT_IP_RECVORIGDSTADDR
#endif
#ifndef IP_MINTTL
#define IP_MINTTL __SPRT_IP_MINTTL
#endif
#ifndef IP_NODEFRAG
#define IP_NODEFRAG __SPRT_IP_NODEFRAG
#endif
#ifndef IP_CHECKSUM
#define IP_CHECKSUM __SPRT_IP_CHECKSUM
#endif
#ifndef IP_BIND_ADDRESS_NO_PORT
#define IP_BIND_ADDRESS_NO_PORT __SPRT_IP_BIND_ADDRESS_NO_PORT
#endif
#ifndef IP_RECVFRAGSIZE
#define IP_RECVFRAGSIZE __SPRT_IP_RECVFRAGSIZE
#endif
#ifndef IP_RECVERR_RFC4884
#define IP_RECVERR_RFC4884 __SPRT_IP_RECVERR_RFC4884
#endif
#ifndef IP_MULTICAST_IF
#define IP_MULTICAST_IF __SPRT_IP_MULTICAST_IF
#endif
#ifndef IP_MULTICAST_TTL
#define IP_MULTICAST_TTL __SPRT_IP_MULTICAST_TTL
#endif
#ifndef IP_MULTICAST_LOOP
#define IP_MULTICAST_LOOP __SPRT_IP_MULTICAST_LOOP
#endif
#ifndef IP_ADD_MEMBERSHIP
#define IP_ADD_MEMBERSHIP __SPRT_IP_ADD_MEMBERSHIP
#endif
#ifndef IP_DROP_MEMBERSHIP
#define IP_DROP_MEMBERSHIP __SPRT_IP_DROP_MEMBERSHIP
#endif
#ifndef IP_UNBLOCK_SOURCE
#define IP_UNBLOCK_SOURCE __SPRT_IP_UNBLOCK_SOURCE
#endif
#ifndef IP_BLOCK_SOURCE
#define IP_BLOCK_SOURCE __SPRT_IP_BLOCK_SOURCE
#endif
#ifndef IP_ADD_SOURCE_MEMBERSHIP
#define IP_ADD_SOURCE_MEMBERSHIP __SPRT_IP_ADD_SOURCE_MEMBERSHIP
#endif
#ifndef IP_DROP_SOURCE_MEMBERSHIP
#define IP_DROP_SOURCE_MEMBERSHIP __SPRT_IP_DROP_SOURCE_MEMBERSHIP
#endif
#ifndef IP_MSFILTER
#define IP_MSFILTER __SPRT_IP_MSFILTER
#endif
#ifndef IP_MULTICAST_ALL
#define IP_MULTICAST_ALL __SPRT_IP_MULTICAST_ALL
#endif
#ifndef IP_UNICAST_IF
#define IP_UNICAST_IF __SPRT_IP_UNICAST_IF
#endif
#ifndef IP_RECVRETOPTS
#define IP_RECVRETOPTS __SPRT_IP_RECVRETOPTS
#endif
#ifndef IP_PMTUDISC_DONT
#define IP_PMTUDISC_DONT __SPRT_IP_PMTUDISC_DONT
#endif
#ifndef IP_PMTUDISC_WANT
#define IP_PMTUDISC_WANT __SPRT_IP_PMTUDISC_WANT
#endif
#ifndef IP_PMTUDISC_DO
#define IP_PMTUDISC_DO __SPRT_IP_PMTUDISC_DO
#endif
#ifndef IP_PMTUDISC_PROBE
#define IP_PMTUDISC_PROBE __SPRT_IP_PMTUDISC_PROBE
#endif
#ifndef IP_PMTUDISC_INTERFACE
#define IP_PMTUDISC_INTERFACE __SPRT_IP_PMTUDISC_INTERFACE
#endif
#ifndef IP_PMTUDISC_OMIT
#define IP_PMTUDISC_OMIT __SPRT_IP_PMTUDISC_OMIT
#endif
#ifndef IP_DEFAULT_MULTICAST_TTL
#define IP_DEFAULT_MULTICAST_TTL __SPRT_IP_DEFAULT_MULTICAST_TTL
#endif
#ifndef IP_DEFAULT_MULTICAST_LOOP
#define IP_DEFAULT_MULTICAST_LOOP __SPRT_IP_DEFAULT_MULTICAST_LOOP
#endif
#ifndef IP_MAX_MEMBERSHIPS
#define IP_MAX_MEMBERSHIPS __SPRT_IP_MAX_MEMBERSHIPS
#endif

// --- IPv4 socket options (Windows-only; guarded on __SPRT_ presence) ---------
#ifdef __SPRT_IP_DONTFRAGMENT
#ifndef IP_DONTFRAGMENT
#define IP_DONTFRAGMENT __SPRT_IP_DONTFRAGMENT
#endif
#endif
#ifdef __SPRT_IP_HOPLIMIT
#ifndef IP_HOPLIMIT
#define IP_HOPLIMIT __SPRT_IP_HOPLIMIT
#endif
#endif
#ifdef __SPRT_IP_RECEIVE_BROADCAST
#ifndef IP_RECEIVE_BROADCAST
#define IP_RECEIVE_BROADCAST __SPRT_IP_RECEIVE_BROADCAST
#endif
#endif
#ifdef __SPRT_IP_RECVIF
#ifndef IP_RECVIF
#define IP_RECVIF __SPRT_IP_RECVIF
#endif
#endif
#ifdef __SPRT_IP_RECVDSTADDR
#ifndef IP_RECVDSTADDR
#define IP_RECVDSTADDR __SPRT_IP_RECVDSTADDR
#endif
#endif
#ifdef __SPRT_IP_IFLIST
#ifndef IP_IFLIST
#define IP_IFLIST __SPRT_IP_IFLIST
#endif
#endif
#ifdef __SPRT_IP_ADD_IFLIST
#ifndef IP_ADD_IFLIST
#define IP_ADD_IFLIST __SPRT_IP_ADD_IFLIST
#endif
#endif
#ifdef __SPRT_IP_DEL_IFLIST
#ifndef IP_DEL_IFLIST
#define IP_DEL_IFLIST __SPRT_IP_DEL_IFLIST
#endif
#endif
#ifdef __SPRT_IP_RTHDR
#ifndef IP_RTHDR
#define IP_RTHDR __SPRT_IP_RTHDR
#endif
#endif
#ifdef __SPRT_IP_GET_IFLIST
#ifndef IP_GET_IFLIST
#define IP_GET_IFLIST __SPRT_IP_GET_IFLIST
#endif
#endif
#ifdef __SPRT_IP_RECVRTHDR
#ifndef IP_RECVRTHDR
#define IP_RECVRTHDR __SPRT_IP_RECVRTHDR
#endif
#endif
#ifdef __SPRT_IP_TCLASS
#ifndef IP_TCLASS
#define IP_TCLASS __SPRT_IP_TCLASS
#endif
#endif
#ifdef __SPRT_IP_RECVTCLASS
#ifndef IP_RECVTCLASS
#define IP_RECVTCLASS __SPRT_IP_RECVTCLASS
#endif
#endif
#ifdef __SPRT_IP_ORIGINAL_ARRIVAL_IF
#ifndef IP_ORIGINAL_ARRIVAL_IF
#define IP_ORIGINAL_ARRIVAL_IF __SPRT_IP_ORIGINAL_ARRIVAL_IF
#endif
#endif
#ifdef __SPRT_IP_ECN
#ifndef IP_ECN
#define IP_ECN __SPRT_IP_ECN
#endif
#endif
#ifdef __SPRT_IP_RECVECN
#ifndef IP_RECVECN
#define IP_RECVECN __SPRT_IP_RECVECN
#endif
#endif
#ifdef __SPRT_IP_PKTINFO_EX
#ifndef IP_PKTINFO_EX
#define IP_PKTINFO_EX __SPRT_IP_PKTINFO_EX
#endif
#endif
#ifdef __SPRT_IP_WFP_REDIRECT_RECORDS
#ifndef IP_WFP_REDIRECT_RECORDS
#define IP_WFP_REDIRECT_RECORDS __SPRT_IP_WFP_REDIRECT_RECORDS
#endif
#endif
#ifdef __SPRT_IP_WFP_REDIRECT_CONTEXT
#ifndef IP_WFP_REDIRECT_CONTEXT
#define IP_WFP_REDIRECT_CONTEXT __SPRT_IP_WFP_REDIRECT_CONTEXT
#endif
#endif
#ifdef __SPRT_IP_NRT_INTERFACE
#ifndef IP_NRT_INTERFACE
#define IP_NRT_INTERFACE __SPRT_IP_NRT_INTERFACE
#endif
#endif
#ifdef __SPRT_IP_USER_MTU
#ifndef IP_USER_MTU
#define IP_USER_MTU __SPRT_IP_USER_MTU
#endif
#endif

// --- MCAST_* group membership ------------------------------------------------
#ifndef MCAST_JOIN_GROUP
#define MCAST_JOIN_GROUP __SPRT_MCAST_JOIN_GROUP
#endif
#ifndef MCAST_BLOCK_SOURCE
#define MCAST_BLOCK_SOURCE __SPRT_MCAST_BLOCK_SOURCE
#endif
#ifndef MCAST_UNBLOCK_SOURCE
#define MCAST_UNBLOCK_SOURCE __SPRT_MCAST_UNBLOCK_SOURCE
#endif
#ifndef MCAST_LEAVE_GROUP
#define MCAST_LEAVE_GROUP __SPRT_MCAST_LEAVE_GROUP
#endif
#ifndef MCAST_JOIN_SOURCE_GROUP
#define MCAST_JOIN_SOURCE_GROUP __SPRT_MCAST_JOIN_SOURCE_GROUP
#endif
#ifndef MCAST_LEAVE_SOURCE_GROUP
#define MCAST_LEAVE_SOURCE_GROUP __SPRT_MCAST_LEAVE_SOURCE_GROUP
#endif
#ifndef MCAST_MSFILTER
#define MCAST_MSFILTER __SPRT_MCAST_MSFILTER
#endif
#ifndef MCAST_EXCLUDE
#define MCAST_EXCLUDE __SPRT_MCAST_EXCLUDE
#endif
#ifndef MCAST_INCLUDE
#define MCAST_INCLUDE __SPRT_MCAST_INCLUDE
#endif

// --- IPv6 socket options (IPPROTO_IPV6 level) --------------------------------
#ifndef IPV6_ADDRFORM
#define IPV6_ADDRFORM __SPRT_IPV6_ADDRFORM
#endif
#ifndef IPV6_2292PKTINFO
#define IPV6_2292PKTINFO __SPRT_IPV6_2292PKTINFO
#endif
#ifndef IPV6_2292HOPOPTS
#define IPV6_2292HOPOPTS __SPRT_IPV6_2292HOPOPTS
#endif
#ifndef IPV6_2292DSTOPTS
#define IPV6_2292DSTOPTS __SPRT_IPV6_2292DSTOPTS
#endif
#ifndef IPV6_2292RTHDR
#define IPV6_2292RTHDR __SPRT_IPV6_2292RTHDR
#endif
#ifndef IPV6_2292PKTOPTIONS
#define IPV6_2292PKTOPTIONS __SPRT_IPV6_2292PKTOPTIONS
#endif
#ifndef IPV6_CHECKSUM
#define IPV6_CHECKSUM __SPRT_IPV6_CHECKSUM
#endif
#ifndef IPV6_2292HOPLIMIT
#define IPV6_2292HOPLIMIT __SPRT_IPV6_2292HOPLIMIT
#endif
#ifndef IPV6_NEXTHOP
#define IPV6_NEXTHOP __SPRT_IPV6_NEXTHOP
#endif
#ifndef IPV6_AUTHHDR
#define IPV6_AUTHHDR __SPRT_IPV6_AUTHHDR
#endif
#ifndef IPV6_UNICAST_HOPS
#define IPV6_UNICAST_HOPS __SPRT_IPV6_UNICAST_HOPS
#endif
#ifndef IPV6_MULTICAST_IF
#define IPV6_MULTICAST_IF __SPRT_IPV6_MULTICAST_IF
#endif
#ifndef IPV6_MULTICAST_HOPS
#define IPV6_MULTICAST_HOPS __SPRT_IPV6_MULTICAST_HOPS
#endif
#ifndef IPV6_MULTICAST_LOOP
#define IPV6_MULTICAST_LOOP __SPRT_IPV6_MULTICAST_LOOP
#endif
#ifndef IPV6_JOIN_GROUP
#define IPV6_JOIN_GROUP __SPRT_IPV6_JOIN_GROUP
#endif
#ifndef IPV6_LEAVE_GROUP
#define IPV6_LEAVE_GROUP __SPRT_IPV6_LEAVE_GROUP
#endif
#ifndef IPV6_ROUTER_ALERT
#define IPV6_ROUTER_ALERT __SPRT_IPV6_ROUTER_ALERT
#endif
#ifndef IPV6_MTU_DISCOVER
#define IPV6_MTU_DISCOVER __SPRT_IPV6_MTU_DISCOVER
#endif
#ifndef IPV6_MTU
#define IPV6_MTU __SPRT_IPV6_MTU
#endif
#ifndef IPV6_RECVERR
#define IPV6_RECVERR __SPRT_IPV6_RECVERR
#endif
#ifndef IPV6_V6ONLY
#define IPV6_V6ONLY __SPRT_IPV6_V6ONLY
#endif
#ifndef IPV6_JOIN_ANYCAST
#define IPV6_JOIN_ANYCAST __SPRT_IPV6_JOIN_ANYCAST
#endif
#ifndef IPV6_LEAVE_ANYCAST
#define IPV6_LEAVE_ANYCAST __SPRT_IPV6_LEAVE_ANYCAST
#endif
#ifndef IPV6_MULTICAST_ALL
#define IPV6_MULTICAST_ALL __SPRT_IPV6_MULTICAST_ALL
#endif
#ifndef IPV6_ROUTER_ALERT_ISOLATE
#define IPV6_ROUTER_ALERT_ISOLATE __SPRT_IPV6_ROUTER_ALERT_ISOLATE
#endif
#ifndef IPV6_IPSEC_POLICY
#define IPV6_IPSEC_POLICY __SPRT_IPV6_IPSEC_POLICY
#endif
#ifndef IPV6_XFRM_POLICY
#define IPV6_XFRM_POLICY __SPRT_IPV6_XFRM_POLICY
#endif
#ifndef IPV6_HDRINCL
#define IPV6_HDRINCL __SPRT_IPV6_HDRINCL
#endif
#ifndef IPV6_RECVPKTINFO
#define IPV6_RECVPKTINFO __SPRT_IPV6_RECVPKTINFO
#endif
#ifndef IPV6_PKTINFO
#define IPV6_PKTINFO __SPRT_IPV6_PKTINFO
#endif
#ifndef IPV6_RECVHOPLIMIT
#define IPV6_RECVHOPLIMIT __SPRT_IPV6_RECVHOPLIMIT
#endif
#ifndef IPV6_HOPLIMIT
#define IPV6_HOPLIMIT __SPRT_IPV6_HOPLIMIT
#endif
#ifndef IPV6_RECVHOPOPTS
#define IPV6_RECVHOPOPTS __SPRT_IPV6_RECVHOPOPTS
#endif
#ifndef IPV6_HOPOPTS
#define IPV6_HOPOPTS __SPRT_IPV6_HOPOPTS
#endif
#ifndef IPV6_RTHDRDSTOPTS
#define IPV6_RTHDRDSTOPTS __SPRT_IPV6_RTHDRDSTOPTS
#endif
#ifndef IPV6_RECVRTHDR
#define IPV6_RECVRTHDR __SPRT_IPV6_RECVRTHDR
#endif
#ifndef IPV6_RTHDR
#define IPV6_RTHDR __SPRT_IPV6_RTHDR
#endif
#ifndef IPV6_RECVDSTOPTS
#define IPV6_RECVDSTOPTS __SPRT_IPV6_RECVDSTOPTS
#endif
#ifndef IPV6_DSTOPTS
#define IPV6_DSTOPTS __SPRT_IPV6_DSTOPTS
#endif
#ifndef IPV6_RECVPATHMTU
#define IPV6_RECVPATHMTU __SPRT_IPV6_RECVPATHMTU
#endif
#ifndef IPV6_PATHMTU
#define IPV6_PATHMTU __SPRT_IPV6_PATHMTU
#endif
#ifndef IPV6_DONTFRAG
#define IPV6_DONTFRAG __SPRT_IPV6_DONTFRAG
#endif
#ifndef IPV6_RECVTCLASS
#define IPV6_RECVTCLASS __SPRT_IPV6_RECVTCLASS
#endif
#ifndef IPV6_TCLASS
#define IPV6_TCLASS __SPRT_IPV6_TCLASS
#endif
#ifndef IPV6_AUTOFLOWLABEL
#define IPV6_AUTOFLOWLABEL __SPRT_IPV6_AUTOFLOWLABEL
#endif
#ifndef IPV6_ADDR_PREFERENCES
#define IPV6_ADDR_PREFERENCES __SPRT_IPV6_ADDR_PREFERENCES
#endif
#ifndef IPV6_MINHOPCOUNT
#define IPV6_MINHOPCOUNT __SPRT_IPV6_MINHOPCOUNT
#endif
#ifndef IPV6_ORIGDSTADDR
#define IPV6_ORIGDSTADDR __SPRT_IPV6_ORIGDSTADDR
#endif
#ifndef IPV6_RECVORIGDSTADDR
#define IPV6_RECVORIGDSTADDR __SPRT_IPV6_RECVORIGDSTADDR
#endif
#ifndef IPV6_TRANSPARENT
#define IPV6_TRANSPARENT __SPRT_IPV6_TRANSPARENT
#endif
#ifndef IPV6_UNICAST_IF
#define IPV6_UNICAST_IF __SPRT_IPV6_UNICAST_IF
#endif
#ifndef IPV6_RECVFRAGSIZE
#define IPV6_RECVFRAGSIZE __SPRT_IPV6_RECVFRAGSIZE
#endif
#ifndef IPV6_FREEBIND
#define IPV6_FREEBIND __SPRT_IPV6_FREEBIND
#endif

// --- IPv6 socket options (Windows-only; guarded on __SPRT_ presence) ---------
#ifdef __SPRT_IPV6_PROTECTION_LEVEL
#ifndef IPV6_PROTECTION_LEVEL
#define IPV6_PROTECTION_LEVEL __SPRT_IPV6_PROTECTION_LEVEL
#endif
#endif
#ifdef __SPRT_IPV6_RECVIF
#ifndef IPV6_RECVIF
#define IPV6_RECVIF __SPRT_IPV6_RECVIF
#endif
#endif
#ifdef __SPRT_IPV6_RECVDSTADDR
#ifndef IPV6_RECVDSTADDR
#define IPV6_RECVDSTADDR __SPRT_IPV6_RECVDSTADDR
#endif
#endif
#ifdef __SPRT_IPV6_IFLIST
#ifndef IPV6_IFLIST
#define IPV6_IFLIST __SPRT_IPV6_IFLIST
#endif
#endif
#ifdef __SPRT_IPV6_ADD_IFLIST
#ifndef IPV6_ADD_IFLIST
#define IPV6_ADD_IFLIST __SPRT_IPV6_ADD_IFLIST
#endif
#endif
#ifdef __SPRT_IPV6_DEL_IFLIST
#ifndef IPV6_DEL_IFLIST
#define IPV6_DEL_IFLIST __SPRT_IPV6_DEL_IFLIST
#endif
#endif
#ifdef __SPRT_IPV6_GET_IFLIST
#ifndef IPV6_GET_IFLIST
#define IPV6_GET_IFLIST __SPRT_IPV6_GET_IFLIST
#endif
#endif
#ifdef __SPRT_IPV6_ECN
#ifndef IPV6_ECN
#define IPV6_ECN __SPRT_IPV6_ECN
#endif
#endif
#ifdef __SPRT_IPV6_RECVECN
#ifndef IPV6_RECVECN
#define IPV6_RECVECN __SPRT_IPV6_RECVECN
#endif
#endif
#ifdef __SPRT_IPV6_PKTINFO_EX
#ifndef IPV6_PKTINFO_EX
#define IPV6_PKTINFO_EX __SPRT_IPV6_PKTINFO_EX
#endif
#endif
#ifdef __SPRT_IPV6_WFP_REDIRECT_RECORDS
#ifndef IPV6_WFP_REDIRECT_RECORDS
#define IPV6_WFP_REDIRECT_RECORDS __SPRT_IPV6_WFP_REDIRECT_RECORDS
#endif
#endif
#ifdef __SPRT_IPV6_WFP_REDIRECT_CONTEXT
#ifndef IPV6_WFP_REDIRECT_CONTEXT
#define IPV6_WFP_REDIRECT_CONTEXT __SPRT_IPV6_WFP_REDIRECT_CONTEXT
#endif
#endif
#ifdef __SPRT_IPV6_NRT_INTERFACE
#ifndef IPV6_NRT_INTERFACE
#define IPV6_NRT_INTERFACE __SPRT_IPV6_NRT_INTERFACE
#endif
#endif
#ifdef __SPRT_IPV6_USER_MTU
#ifndef IPV6_USER_MTU
#define IPV6_USER_MTU __SPRT_IPV6_USER_MTU
#endif
#endif
#ifndef IPV6_ADD_MEMBERSHIP
#define IPV6_ADD_MEMBERSHIP __SPRT_IPV6_ADD_MEMBERSHIP
#endif
#ifndef IPV6_DROP_MEMBERSHIP
#define IPV6_DROP_MEMBERSHIP __SPRT_IPV6_DROP_MEMBERSHIP
#endif
#ifndef IPV6_RXHOPOPTS
#define IPV6_RXHOPOPTS __SPRT_IPV6_RXHOPOPTS
#endif
#ifndef IPV6_RXDSTOPTS
#define IPV6_RXDSTOPTS __SPRT_IPV6_RXDSTOPTS
#endif
#ifndef IPV6_PMTUDISC_DONT
#define IPV6_PMTUDISC_DONT __SPRT_IPV6_PMTUDISC_DONT
#endif
#ifndef IPV6_PMTUDISC_WANT
#define IPV6_PMTUDISC_WANT __SPRT_IPV6_PMTUDISC_WANT
#endif
#ifndef IPV6_PMTUDISC_DO
#define IPV6_PMTUDISC_DO __SPRT_IPV6_PMTUDISC_DO
#endif
#ifndef IPV6_PMTUDISC_PROBE
#define IPV6_PMTUDISC_PROBE __SPRT_IPV6_PMTUDISC_PROBE
#endif
#ifndef IPV6_PMTUDISC_INTERFACE
#define IPV6_PMTUDISC_INTERFACE __SPRT_IPV6_PMTUDISC_INTERFACE
#endif
#ifndef IPV6_PMTUDISC_OMIT
#define IPV6_PMTUDISC_OMIT __SPRT_IPV6_PMTUDISC_OMIT
#endif
#ifndef IPV6_PREFER_SRC_TMP
#define IPV6_PREFER_SRC_TMP __SPRT_IPV6_PREFER_SRC_TMP
#endif
#ifndef IPV6_PREFER_SRC_PUBLIC
#define IPV6_PREFER_SRC_PUBLIC __SPRT_IPV6_PREFER_SRC_PUBLIC
#endif
#ifndef IPV6_PREFER_SRC_PUBTMP_DEFAULT
#define IPV6_PREFER_SRC_PUBTMP_DEFAULT __SPRT_IPV6_PREFER_SRC_PUBTMP_DEFAULT
#endif
#ifndef IPV6_PREFER_SRC_COA
#define IPV6_PREFER_SRC_COA __SPRT_IPV6_PREFER_SRC_COA
#endif
#ifndef IPV6_PREFER_SRC_HOME
#define IPV6_PREFER_SRC_HOME __SPRT_IPV6_PREFER_SRC_HOME
#endif
#ifndef IPV6_PREFER_SRC_CGA
#define IPV6_PREFER_SRC_CGA __SPRT_IPV6_PREFER_SRC_CGA
#endif
#ifndef IPV6_PREFER_SRC_NONCGA
#define IPV6_PREFER_SRC_NONCGA __SPRT_IPV6_PREFER_SRC_NONCGA
#endif
#ifndef IPV6_RTHDR_LOOSE
#define IPV6_RTHDR_LOOSE __SPRT_IPV6_RTHDR_LOOSE
#endif
#ifndef IPV6_RTHDR_STRICT
#define IPV6_RTHDR_STRICT __SPRT_IPV6_RTHDR_STRICT
#endif
#ifndef IPV6_RTHDR_TYPE_0
#define IPV6_RTHDR_TYPE_0 __SPRT_IPV6_RTHDR_TYPE_0
#endif
// clang-format on

#endif // CORE_RUNTIME_INCLUDE_LIBC_ARPA___INET_H_
