/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_BASIC_API_H_
#define SPRT_WRAPPERS_WINDOWS_BASIC_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/basic_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/basic_api.h) */
#define CP_ACP __SPRT_CP_ACP
#define CP_OEMCP __SPRT_CP_OEMCP
#define CP_MACCP __SPRT_CP_MACCP
#define CP_THREAD_ACP __SPRT_CP_THREAD_ACP
#define CP_SYMBOL __SPRT_CP_SYMBOL
#define CP_UTF8 __SPRT_CP_UTF8
#define STD_INPUT_HANDLE __SPRT_STD_INPUT_HANDLE
#define STD_OUTPUT_HANDLE __SPRT_STD_OUTPUT_HANDLE
#define STD_ERROR_HANDLE __SPRT_STD_ERROR_HANDLE
#define ENABLE_PROCESSED_INPUT __SPRT_ENABLE_PROCESSED_INPUT
#define ENABLE_LINE_INPUT __SPRT_ENABLE_LINE_INPUT
#define ENABLE_ECHO_INPUT __SPRT_ENABLE_ECHO_INPUT
#define ENABLE_WINDOW_INPUT __SPRT_ENABLE_WINDOW_INPUT
#define ENABLE_MOUSE_INPUT __SPRT_ENABLE_MOUSE_INPUT
#define ENABLE_INSERT_MODE __SPRT_ENABLE_INSERT_MODE
#define ENABLE_QUICK_EDIT_MODE __SPRT_ENABLE_QUICK_EDIT_MODE
#define ENABLE_EXTENDED_FLAGS __SPRT_ENABLE_EXTENDED_FLAGS
#define ENABLE_AUTO_POSITION __SPRT_ENABLE_AUTO_POSITION
#define ENABLE_VIRTUAL_TERMINAL_INPUT __SPRT_ENABLE_VIRTUAL_TERMINAL_INPUT
#define ENABLE_PROCESSED_OUTPUT __SPRT_ENABLE_PROCESSED_OUTPUT
#define ENABLE_WRAP_AT_EOL_OUTPUT __SPRT_ENABLE_WRAP_AT_EOL_OUTPUT
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING __SPRT_ENABLE_VIRTUAL_TERMINAL_PROCESSING
#define DISABLE_NEWLINE_AUTO_RETURN __SPRT_DISABLE_NEWLINE_AUTO_RETURN
#define ENABLE_LVB_GRID_WORLDWIDE __SPRT_ENABLE_LVB_GRID_WORLDWIDE
#define FOREGROUND_BLUE __SPRT_FOREGROUND_BLUE
#define FOREGROUND_GREEN __SPRT_FOREGROUND_GREEN
#define FOREGROUND_RED __SPRT_FOREGROUND_RED
#define FOREGROUND_INTENSITY __SPRT_FOREGROUND_INTENSITY
#define BACKGROUND_BLUE __SPRT_BACKGROUND_BLUE
#define BACKGROUND_GREEN __SPRT_BACKGROUND_GREEN
#define BACKGROUND_RED __SPRT_BACKGROUND_RED
#define BACKGROUND_INTENSITY __SPRT_BACKGROUND_INTENSITY
#define COMMON_LVB_LEADING_BYTE __SPRT_COMMON_LVB_LEADING_BYTE
#define COMMON_LVB_TRAILING_BYTE __SPRT_COMMON_LVB_TRAILING_BYTE
#define COMMON_LVB_GRID_HORIZONTAL __SPRT_COMMON_LVB_GRID_HORIZONTAL
#define COMMON_LVB_GRID_LVERTICAL __SPRT_COMMON_LVB_GRID_LVERTICAL
#define COMMON_LVB_GRID_RVERTICAL __SPRT_COMMON_LVB_GRID_RVERTICAL
#define COMMON_LVB_REVERSE_VIDEO __SPRT_COMMON_LVB_REVERSE_VIDEO
#define COMMON_LVB_UNDERSCORE __SPRT_COMMON_LVB_UNDERSCORE
#define THREAD_MODE_BACKGROUND_BEGIN __SPRT_THREAD_MODE_BACKGROUND_BEGIN
#define THREAD_MODE_BACKGROUND_END __SPRT_THREAD_MODE_BACKGROUND_END
#define VER_NT_SERVER __SPRT_VER_NT_SERVER
#define JOB_OBJECT_LIMIT_PROCESS_MEMORY __SPRT_JOB_OBJECT_LIMIT_PROCESS_MEMORY
#define LIST_MODULES_64BIT __SPRT_LIST_MODULES_64BIT
#define HEAP_NO_SERIALIZE __SPRT_HEAP_NO_SERIALIZE
#define HEAP_GROWABLE __SPRT_HEAP_GROWABLE
#define HEAP_GENERATE_EXCEPTIONS __SPRT_HEAP_GENERATE_EXCEPTIONS
#define HEAP_ZERO_MEMORY __SPRT_HEAP_ZERO_MEMORY
#define HEAP_REALLOC_IN_PLACE_ONLY __SPRT_HEAP_REALLOC_IN_PLACE_ONLY
#define HEAP_TAIL_CHECKING_ENABLED __SPRT_HEAP_TAIL_CHECKING_ENABLED
#define HEAP_FREE_CHECKING_ENABLED __SPRT_HEAP_FREE_CHECKING_ENABLED
#define HEAP_DISABLE_COALESCE_ON_FREE __SPRT_HEAP_DISABLE_COALESCE_ON_FREE
#define HEAP_CREATE_ALIGN_16 __SPRT_HEAP_CREATE_ALIGN_16
#define HEAP_CREATE_ENABLE_TRACING __SPRT_HEAP_CREATE_ENABLE_TRACING
#define HEAP_CREATE_ENABLE_EXECUTE __SPRT_HEAP_CREATE_ENABLE_EXECUTE
#define HEAP_MAXIMUM_TAG __SPRT_HEAP_MAXIMUM_TAG
#define HEAP_PSEUDO_TAG_FLAG __SPRT_HEAP_PSEUDO_TAG_FLAG
#define HEAP_TAG_SHIFT __SPRT_HEAP_TAG_SHIFT
#define HEAP_CREATE_SEGMENT_HEAP __SPRT_HEAP_CREATE_SEGMENT_HEAP
#define HEAP_CREATE_HARDENED __SPRT_HEAP_CREATE_HARDENED
#define MEM_COMMIT __SPRT_MEM_COMMIT
#define MEM_RESERVE __SPRT_MEM_RESERVE
#define MEM_REPLACE_PLACEHOLDER __SPRT_MEM_REPLACE_PLACEHOLDER
#define MEM_RESERVE_PLACEHOLDER __SPRT_MEM_RESERVE_PLACEHOLDER
#define MEM_RESET __SPRT_MEM_RESET
#define MEM_TOP_DOWN __SPRT_MEM_TOP_DOWN
#define MEM_WRITE_WATCH __SPRT_MEM_WRITE_WATCH
#define MEM_PHYSICAL __SPRT_MEM_PHYSICAL
#define MEM_ROTATE __SPRT_MEM_ROTATE
#define MEM_DIFFERENT_IMAGE_BASE_OK __SPRT_MEM_DIFFERENT_IMAGE_BASE_OK
#define MEM_RESET_UNDO __SPRT_MEM_RESET_UNDO
#define MEM_LARGE_PAGES __SPRT_MEM_LARGE_PAGES
#define MEM_4MB_PAGES __SPRT_MEM_4MB_PAGES
#define MEM_64K_PAGES __SPRT_MEM_64K_PAGES
#define MEM_UNMAP_WITH_TRANSIENT_BOOST __SPRT_MEM_UNMAP_WITH_TRANSIENT_BOOST
#define MEM_COALESCE_PLACEHOLDERS __SPRT_MEM_COALESCE_PLACEHOLDERS
#define MEM_PRESERVE_PLACEHOLDER __SPRT_MEM_PRESERVE_PLACEHOLDER
#define MEM_DECOMMIT __SPRT_MEM_DECOMMIT
#define MEM_RELEASE __SPRT_MEM_RELEASE
#define MEM_FREE __SPRT_MEM_FREE
#define PAGE_NOACCESS __SPRT_PAGE_NOACCESS
#define PAGE_READONLY __SPRT_PAGE_READONLY
#define PAGE_READWRITE __SPRT_PAGE_READWRITE
#define PAGE_WRITECOPY __SPRT_PAGE_WRITECOPY
#define PAGE_EXECUTE __SPRT_PAGE_EXECUTE
#define PAGE_EXECUTE_READ __SPRT_PAGE_EXECUTE_READ
#define PAGE_EXECUTE_READWRITE __SPRT_PAGE_EXECUTE_READWRITE
#define PAGE_EXECUTE_WRITECOPY __SPRT_PAGE_EXECUTE_WRITECOPY
#define PAGE_GUARD __SPRT_PAGE_GUARD
#define PAGE_NOCACHE __SPRT_PAGE_NOCACHE
#define PAGE_WRITECOMBINE __SPRT_PAGE_WRITECOMBINE
#define LHND __SPRT_LHND
#define LPTR __SPRT_LPTR

#define MINCHAR __SPRT_MINCHAR
#define MAXCHAR __SPRT_MAXCHAR
#define MINSHORT __SPRT_MINSHORT
#define MAXSHORT __SPRT_MAXSHORT
#define MINLONG __SPRT_MINLONG
#define MAXLONG __SPRT_MAXLONG
#define MAXBYTE __SPRT_MAXBYTE
#define MAXWORD __SPRT_MAXWORD
#define MAXDWORD __SPRT_MAXDWORD

#include <sprt/c/__sprt_string.h>

__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI HLOCAL LocalAlloc(UINT uFlags, SIZE_T uBytes);

__SPRT_WIN_IMPORT WINAPI HLOCAL LocalFree(HLOCAL hMem);

__SPRT_WIN_IMPORT WINAPI LPVOID HeapAlloc(HANDLE hHeap, DWORD dwFlags, SIZE_T dwBytes);

__SPRT_WIN_IMPORT WINAPI LPVOID HeapReAlloc(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem,
		SIZE_T dwBytes);

__SPRT_WIN_IMPORT WINAPI BOOL HeapFree(HANDLE hHeap, DWORD dwFlags, LPVOID lpMem);

__SPRT_WIN_IMPORT WINAPI SIZE_T HeapSize(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem);

__SPRT_WIN_IMPORT WINAPI HANDLE HeapCreate(DWORD flOptions, SIZE_T dwInitialSize,
		SIZE_T dwMaximumSize);

__SPRT_WIN_IMPORT WINAPI BOOL HeapDestroy(HANDLE hHeap);

__SPRT_WIN_IMPORT WINAPI BOOL HeapValidate(HANDLE hHeap, DWORD dwFlags, LPCVOID lpMem);

__SPRT_WIN_IMPORT WINAPI SIZE_T HeapCompact(HANDLE hHeap, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI HANDLE GetProcessHeap(VOID);

__SPRT_WIN_IMPORT WINAPI LPVOID VirtualAlloc(LPVOID lpAddress, SIZE_T dwSize,
		DWORD flAllocationType, DWORD flProtect);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualProtect(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect,
		PDWORD lpflOldProtect);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualFree(LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType);

__SPRT_WIN_IMPORT WINAPI LPVOID VirtualAllocEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize,
		DWORD flAllocationType, DWORD flProtect);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualFreeEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize,
		DWORD dwFreeType);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualProtectEx(HANDLE hProcess, LPVOID lpAddress, SIZE_T dwSize,
		DWORD flNewProtect, PDWORD lpflOldProtect);

__SPRT_WIN_IMPORT WINAPI DWORD DiscardVirtualMemory(PVOID VirtualAddress, SIZE_T Size);

__SPRT_WIN_IMPORT WINAPI DWORD GetLastError(void);

__SPRT_WIN_IMPORT WINAPI VOID SetLastError(DWORD dwErrCode);

__SPRT_WIN_IMPORT WINAPI BOOL CloseHandle(HANDLE hObject);

__SPRT_WIN_IMPORT WINAPI BOOL GetHandleInformation(HANDLE hObject, LPDWORD lpdwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL SetHandleInformation(HANDLE hObject, DWORD dwMask, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL DuplicateHandle(HANDLE hSourceProcess, HANDLE hSourceHandle,
		HANDLE hTargetProcess, PHANDLE lpDuplicateHandle, DWORD dwDesiredAccess,
		BOOL bInheritHandle, DWORD dwOptions);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualLock(LPVOID lpAddress, SIZE_T dwSize);

__SPRT_WIN_IMPORT WINAPI BOOL VirtualUnlock(LPVOID lpAddress, SIZE_T dwSize);

__SPRT_WIN_IMPORT WINAPI DWORD GetEnvironmentVariableA(LPCSTR lpName, LPSTR lpBuffer, DWORD nSize);

__SPRT_WIN_IMPORT WINAPI BOOL SetEnvironmentVariableA(LPCSTR lpName, LPCSTR lpValue);

__SPRT_WIN_IMPORT WINAPI DWORD GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer,
		DWORD nSize);

__SPRT_WIN_IMPORT WINAPI BOOL SetEnvironmentVariableW(LPCWSTR lpName, LPCWSTR lpValue);

__SPRT_WIN_IMPORT WINAPI LPWCH GetEnvironmentStringsW();

__SPRT_WIN_IMPORT WINAPI VOID Sleep(DWORD dwMilliseconds);

__SPRT_WIN_IMPORT WINAPI DWORD SleepEx(DWORD dwMilliseconds, BOOL bAlertable);

__SPRT_WIN_IMPORT WINAPI BOOL WaitOnAddress(volatile VOID *Address, PVOID CompareAddress,
		SIZE_T AddressSize, DWORD dwMilliseconds);

__SPRT_WIN_IMPORT WINAPI VOID WakeByAddressSingle(PVOID Address);

__SPRT_WIN_IMPORT WINAPI VOID WakeByAddressAll(PVOID Address);

__SPRT_WIN_IMPORT WINAPI BOOL IsDebuggerPresent();

__SPRT_WIN_IMPORT WINAPI HANDLE GetStdHandle(DWORD nStdHandle);

__SPRT_WIN_IMPORT WINAPI BOOL GetConsoleScreenBufferInfo(HANDLE hConsoleOutput,
		PCONSOLE_SCREEN_BUFFER_INFO lpConsoleScreenBufferInfo);

__SPRT_WIN_IMPORT WINAPI BOOL SetConsoleCP(UINT wCodePageID);

__SPRT_WIN_IMPORT WINAPI BOOL SetConsoleOutputCP(UINT wCodePageID);

__SPRT_WIN_IMPORT WINAPI BOOL GetConsoleMode(HANDLE hConsoleHandle, LPDWORD lpMode);

__SPRT_WIN_IMPORT WINAPI BOOL SetConsoleMode(HANDLE hConsoleHandle, DWORD dwMode);

__SPRT_WIN_IMPORT WINAPI BOOL SetConsoleTextAttribute(HANDLE hConsoleOutput, WORD wAttributes);

__SPRT_WIN_IMPORT WINAPI BOOL WriteConsoleW(HANDLE hConsoleOutput, const void *lpBuffer,
		DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved);

typedef BOOL(WINAPI *PHANDLER_ROUTINE)(DWORD dwCtrlType);

__SPRT_WIN_IMPORT WINAPI BOOL SetConsoleCtrlHandler(PHANDLER_ROUTINE HandlerRoutine, BOOL Add);

__SPRT_WIN_IMPORT WINAPI DWORD GetCurrentProcessorNumber(VOID);

__SPRT_WIN_IMPORT WINAPI VOID OutputDebugStringA(LPCSTR lpOutputString);

__SPRT_WIN_IMPORT WINAPI VOID OutputDebugStringW(LPCWSTR lpOutputString);

WINAPI WINAPI_PROVIDER GetWinApiProvider();

SPRT_FORCEINLINE void CopyMemory(LPVOID Destination, const VOID *Source, SIZE_T Length) {
	__sprt_memcpy(Destination, Source, Length);
}

SPRT_FORCEINLINE void FillMemory(LPVOID Destination, SIZE_T Length, BYTE Value) {
	__sprt_memset(Destination, Value, Length);
}

SPRT_FORCEINLINE void ZeroMemory(LPVOID Destination, SIZE_T Length) {
	__sprt_memset(Destination, 0, Length);
}

// Unlike ZeroMemory, the "Secure" variant must not be optimized away by the compiler
// (it clears sensitive data), so it writes through a volatile pointer rather than
// calling memset. Mirrors the SDK's RtlSecureZeroMemory inline.
SPRT_FORCEINLINE PVOID RtlSecureZeroMemory(PVOID Destination, SIZE_T Length) {
	volatile char *p = (volatile char *)Destination;
	while (Length) {
		*p = 0;
		++p;
		--Length;
	}
	return Destination;
}

#define SecureZeroMemory RtlSecureZeroMemory

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_BASIC_API_H_
