/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_BCRYPT_H_
#define SPRT_WRAPPERS_WINDOWS_BCRYPT_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/bcrypt.h>

/* Clean public names (materialized __SPRT_ values live in abi/bcrypt.h) */
#define BCRYPT_RNG_USE_ENTROPY_IN_BUFFER __SPRT_BCRYPT_RNG_USE_ENTROPY_IN_BUFFER
#define BCRYPT_USE_SYSTEM_PREFERRED_RNG __SPRT_BCRYPT_USE_SYSTEM_PREFERRED_RNG
#define BCRYPT_ALG_HANDLE_HMAC_FLAG __SPRT_BCRYPT_ALG_HANDLE_HMAC_FLAG
#define BCRYPT_HASH_REUSABLE_FLAG __SPRT_BCRYPT_HASH_REUSABLE_FLAG
#define BCRYPT_RSA_ALGORITHM __SPRT_BCRYPT_RSA_ALGORITHM
#define BCRYPT_RSA_SIGN_ALGORITHM __SPRT_BCRYPT_RSA_SIGN_ALGORITHM
#define BCRYPT_DH_ALGORITHM __SPRT_BCRYPT_DH_ALGORITHM
#define BCRYPT_DSA_ALGORITHM __SPRT_BCRYPT_DSA_ALGORITHM
#define BCRYPT_RC2_ALGORITHM __SPRT_BCRYPT_RC2_ALGORITHM
#define BCRYPT_RC4_ALGORITHM __SPRT_BCRYPT_RC4_ALGORITHM
#define BCRYPT_AES_ALGORITHM __SPRT_BCRYPT_AES_ALGORITHM
#define BCRYPT_DES_ALGORITHM __SPRT_BCRYPT_DES_ALGORITHM
#define BCRYPT_DESX_ALGORITHM __SPRT_BCRYPT_DESX_ALGORITHM
#define BCRYPT_3DES_ALGORITHM __SPRT_BCRYPT_3DES_ALGORITHM
#define BCRYPT_3DES_112_ALGORITHM __SPRT_BCRYPT_3DES_112_ALGORITHM
#define BCRYPT_MD2_ALGORITHM __SPRT_BCRYPT_MD2_ALGORITHM
#define BCRYPT_MD4_ALGORITHM __SPRT_BCRYPT_MD4_ALGORITHM
#define BCRYPT_MD5_ALGORITHM __SPRT_BCRYPT_MD5_ALGORITHM
#define BCRYPT_SHA1_ALGORITHM __SPRT_BCRYPT_SHA1_ALGORITHM
#define BCRYPT_SHA256_ALGORITHM __SPRT_BCRYPT_SHA256_ALGORITHM
#define BCRYPT_SHA384_ALGORITHM __SPRT_BCRYPT_SHA384_ALGORITHM
#define BCRYPT_SHA512_ALGORITHM __SPRT_BCRYPT_SHA512_ALGORITHM
#define BCRYPT_AES_GMAC_ALGORITHM __SPRT_BCRYPT_AES_GMAC_ALGORITHM
#define BCRYPT_AES_CMAC_ALGORITHM __SPRT_BCRYPT_AES_CMAC_ALGORITHM
#define BCRYPT_ECDSA_P256_ALGORITHM __SPRT_BCRYPT_ECDSA_P256_ALGORITHM
#define BCRYPT_ECDSA_P384_ALGORITHM __SPRT_BCRYPT_ECDSA_P384_ALGORITHM
#define BCRYPT_ECDSA_P521_ALGORITHM __SPRT_BCRYPT_ECDSA_P521_ALGORITHM
#define BCRYPT_ECDH_P256_ALGORITHM __SPRT_BCRYPT_ECDH_P256_ALGORITHM
#define BCRYPT_ECDH_P384_ALGORITHM __SPRT_BCRYPT_ECDH_P384_ALGORITHM
#define BCRYPT_ECDH_P521_ALGORITHM __SPRT_BCRYPT_ECDH_P521_ALGORITHM
#define BCRYPT_RNG_ALGORITHM __SPRT_BCRYPT_RNG_ALGORITHM
#define BCRYPT_RNG_FIPS186_DSA_ALGORITHM __SPRT_BCRYPT_RNG_FIPS186_DSA_ALGORITHM
#define BCRYPT_RNG_DUAL_EC_ALGORITHM __SPRT_BCRYPT_RNG_DUAL_EC_ALGORITHM
#define BCRYPT_OBJECT_LENGTH __SPRT_BCRYPT_OBJECT_LENGTH
#define BCRYPT_ALGORITHM_NAME __SPRT_BCRYPT_ALGORITHM_NAME
#define BCRYPT_PROVIDER_HANDLE __SPRT_BCRYPT_PROVIDER_HANDLE
#define BCRYPT_CHAINING_MODE __SPRT_BCRYPT_CHAINING_MODE
#define BCRYPT_BLOCK_LENGTH __SPRT_BCRYPT_BLOCK_LENGTH
#define BCRYPT_KEY_LENGTH __SPRT_BCRYPT_KEY_LENGTH
#define BCRYPT_KEY_OBJECT_LENGTH __SPRT_BCRYPT_KEY_OBJECT_LENGTH
#define BCRYPT_KEY_STRENGTH __SPRT_BCRYPT_KEY_STRENGTH
#define BCRYPT_KEY_LENGTHS __SPRT_BCRYPT_KEY_LENGTHS
#define BCRYPT_BLOCK_SIZE_LIST __SPRT_BCRYPT_BLOCK_SIZE_LIST
#define BCRYPT_EFFECTIVE_KEY_LENGTH __SPRT_BCRYPT_EFFECTIVE_KEY_LENGTH
#define BCRYPT_HASH_LENGTH __SPRT_BCRYPT_HASH_LENGTH
#define BCRYPT_HASH_OID_LIST __SPRT_BCRYPT_HASH_OID_LIST
#define BCRYPT_PADDING_SCHEMES __SPRT_BCRYPT_PADDING_SCHEMES
#define BCRYPT_SIGNATURE_LENGTH __SPRT_BCRYPT_SIGNATURE_LENGTH
#define BCRYPT_HASH_BLOCK_LENGTH __SPRT_BCRYPT_HASH_BLOCK_LENGTH
#define BCRYPT_AUTH_TAG_LENGTH __SPRT_BCRYPT_AUTH_TAG_LENGTH
#define BCRYPT_CHAIN_MODE_NA __SPRT_BCRYPT_CHAIN_MODE_NA
#define BCRYPT_CHAIN_MODE_CBC __SPRT_BCRYPT_CHAIN_MODE_CBC
#define BCRYPT_CHAIN_MODE_ECB __SPRT_BCRYPT_CHAIN_MODE_ECB
#define BCRYPT_CHAIN_MODE_CFB __SPRT_BCRYPT_CHAIN_MODE_CFB
#define BCRYPT_CHAIN_MODE_CCM __SPRT_BCRYPT_CHAIN_MODE_CCM
#define BCRYPT_CHAIN_MODE_GCM __SPRT_BCRYPT_CHAIN_MODE_GCM
#define BCRYPT_SUCCESS(Status) __SPRT_BCRYPT_SUCCESS(Status)


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptGenRandom(BCRYPT_ALG_HANDLE hAlgorithm, PUCHAR pbBuffer,
		ULONG cbBuffer, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptGenerateSymmetricKey(BCRYPT_ALG_HANDLE hAlgorithm,
		BCRYPT_KEY_HANDLE *phKey, PUCHAR pbKeyObject, ULONG cbKeyObject, PUCHAR pbSecret,
		ULONG cbSecret, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptDestroyKey(BCRYPT_KEY_HANDLE hKey);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptCreateHash(BCRYPT_ALG_HANDLE hAlgorithm,
		BCRYPT_HASH_HANDLE *phHash, PUCHAR pbHashObject, ULONG cbHashObject, PUCHAR pbSecret,
		ULONG cbSecret, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptHashData(BCRYPT_HASH_HANDLE hHash, PUCHAR pbInput,
		ULONG cbInput, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptFinishHash(BCRYPT_HASH_HANDLE hHash, PUCHAR pbOutput,
		ULONG cbOutput, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptDestroyHash(BCRYPT_HASH_HANDLE hHash);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptGetProperty(BCRYPT_HANDLE hObject, LPCWSTR pszProperty,
		PUCHAR pbOutput, ULONG cbOutput, ULONG *pcbResult, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptSetProperty(BCRYPT_HANDLE hObject, LPCWSTR pszProperty,
		PUCHAR pbInput, ULONG cbInput, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptOpenAlgorithmProvider(BCRYPT_ALG_HANDLE *phAlgorithm,
		LPCWSTR pszAlgId, LPCWSTR pszImplementation, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptCloseAlgorithmProvider(BCRYPT_ALG_HANDLE hAlgorithm,
		ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptDeriveKeyPBKDF2(BCRYPT_ALG_HANDLE hPrf, PUCHAR pbPassword,
		ULONG cbPassword, PUCHAR pbSalt, ULONG cbSalt, ULONGLONG cIterations, PUCHAR pbDerivedKey,
		ULONG cbDerivedKey, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptEncrypt(BCRYPT_KEY_HANDLE hKey, PUCHAR pbInput,
		ULONG cbInput, VOID *pPaddingInfo, PUCHAR pbIV, ULONG cbIV, PUCHAR pbOutput, ULONG cbOutput,
		ULONG *pcbResult, ULONG dwFlags);

__SPRT_WIN_IMPORT WINAPI NTSTATUS BCryptDecrypt(BCRYPT_KEY_HANDLE hKey, PUCHAR pbInput,
		ULONG cbInput, VOID *pPaddingInfo, PUCHAR pbIV, ULONG cbIV, PUCHAR pbOutput, ULONG cbOutput,
		ULONG *pcbResult, ULONG dwFlags);

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_BCRYPT_API_H_
