/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_CONTEXT_API_H_
#define SPRT_WRAPPERS_WINDOWS_CONTEXT_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/context_api.h>

/* Clean public names for the arch-conditional CONTEXT_/_JB/ARM64 macros
   (materialized __SPRT_ values live per-arch in abi/context_api.h). */
#ifdef __SPRT_CONTEXT_AMD64
#define CONTEXT_AMD64 __SPRT_CONTEXT_AMD64
#endif

#ifdef __SPRT_CONTEXT_ARM64
#define CONTEXT_ARM64 __SPRT_CONTEXT_ARM64
#endif

#define CONTEXT_CONTROL __SPRT_CONTEXT_CONTROL
#define CONTEXT_INTEGER __SPRT_CONTEXT_INTEGER
#define CONTEXT_SEGMENTS __SPRT_CONTEXT_SEGMENTS
#define CONTEXT_FLOATING_POINT __SPRT_CONTEXT_FLOATING_POINT
#define CONTEXT_DEBUG_REGISTERS __SPRT_CONTEXT_DEBUG_REGISTERS
#define CONTEXT_FULL __SPRT_CONTEXT_FULL
#define CONTEXT_ALL __SPRT_CONTEXT_ALL
#define _JBLEN __SPRT__JBLEN

#ifdef __SPRT_ARM64_MAX_BREAKPOINTS
#define ARM64_MAX_BREAKPOINTS __SPRT_ARM64_MAX_BREAKPOINTS
#endif

#ifdef __SPRT_ARM64_MAX_WATCHPOINTS
#define ARM64_MAX_WATCHPOINTS __SPRT_ARM64_MAX_WATCHPOINTS
#endif


/* Clean public names (materialized __SPRT_ values live in abi/context_api.h) */
#define IMAGE_SIZEOF_FILE_HEADER __SPRT_IMAGE_SIZEOF_FILE_HEADER
#define IMAGE_FILE_RELOCS_STRIPPED __SPRT_IMAGE_FILE_RELOCS_STRIPPED
#define IMAGE_FILE_EXECUTABLE_IMAGE __SPRT_IMAGE_FILE_EXECUTABLE_IMAGE
#define IMAGE_FILE_LINE_NUMS_STRIPPED __SPRT_IMAGE_FILE_LINE_NUMS_STRIPPED
#define IMAGE_FILE_LOCAL_SYMS_STRIPPED __SPRT_IMAGE_FILE_LOCAL_SYMS_STRIPPED
#define IMAGE_FILE_AGGRESIVE_WS_TRIM __SPRT_IMAGE_FILE_AGGRESIVE_WS_TRIM
#define IMAGE_FILE_LARGE_ADDRESS_AWARE __SPRT_IMAGE_FILE_LARGE_ADDRESS_AWARE
#define IMAGE_FILE_BYTES_REVERSED_LO __SPRT_IMAGE_FILE_BYTES_REVERSED_LO
#define IMAGE_FILE_32BIT_MACHINE __SPRT_IMAGE_FILE_32BIT_MACHINE
#define IMAGE_FILE_DEBUG_STRIPPED __SPRT_IMAGE_FILE_DEBUG_STRIPPED
#define IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP __SPRT_IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP
#define IMAGE_FILE_NET_RUN_FROM_SWAP __SPRT_IMAGE_FILE_NET_RUN_FROM_SWAP
#define IMAGE_FILE_SYSTEM __SPRT_IMAGE_FILE_SYSTEM
#define IMAGE_FILE_DLL __SPRT_IMAGE_FILE_DLL
#define IMAGE_FILE_UP_SYSTEM_ONLY __SPRT_IMAGE_FILE_UP_SYSTEM_ONLY
#define IMAGE_FILE_BYTES_REVERSED_HI __SPRT_IMAGE_FILE_BYTES_REVERSED_HI
#define IMAGE_FILE_MACHINE_UNKNOWN __SPRT_IMAGE_FILE_MACHINE_UNKNOWN
#define IMAGE_FILE_MACHINE_TARGET_HOST __SPRT_IMAGE_FILE_MACHINE_TARGET_HOST
#define IMAGE_FILE_MACHINE_I386 __SPRT_IMAGE_FILE_MACHINE_I386
#define IMAGE_FILE_MACHINE_R3000 __SPRT_IMAGE_FILE_MACHINE_R3000
#define IMAGE_FILE_MACHINE_R4000 __SPRT_IMAGE_FILE_MACHINE_R4000
#define IMAGE_FILE_MACHINE_R10000 __SPRT_IMAGE_FILE_MACHINE_R10000
#define IMAGE_FILE_MACHINE_WCEMIPSV2 __SPRT_IMAGE_FILE_MACHINE_WCEMIPSV2
#define IMAGE_FILE_MACHINE_ALPHA __SPRT_IMAGE_FILE_MACHINE_ALPHA
#define IMAGE_FILE_MACHINE_SH3 __SPRT_IMAGE_FILE_MACHINE_SH3
#define IMAGE_FILE_MACHINE_SH3DSP __SPRT_IMAGE_FILE_MACHINE_SH3DSP
#define IMAGE_FILE_MACHINE_SH3E __SPRT_IMAGE_FILE_MACHINE_SH3E
#define IMAGE_FILE_MACHINE_SH4 __SPRT_IMAGE_FILE_MACHINE_SH4
#define IMAGE_FILE_MACHINE_SH5 __SPRT_IMAGE_FILE_MACHINE_SH5
#define IMAGE_FILE_MACHINE_ARM __SPRT_IMAGE_FILE_MACHINE_ARM
#define IMAGE_FILE_MACHINE_THUMB __SPRT_IMAGE_FILE_MACHINE_THUMB
#define IMAGE_FILE_MACHINE_ARMNT __SPRT_IMAGE_FILE_MACHINE_ARMNT
#define IMAGE_FILE_MACHINE_AM33 __SPRT_IMAGE_FILE_MACHINE_AM33
#define IMAGE_FILE_MACHINE_POWERPC __SPRT_IMAGE_FILE_MACHINE_POWERPC
#define IMAGE_FILE_MACHINE_POWERPCFP __SPRT_IMAGE_FILE_MACHINE_POWERPCFP
#define IMAGE_FILE_MACHINE_IA64 __SPRT_IMAGE_FILE_MACHINE_IA64
#define IMAGE_FILE_MACHINE_MIPS16 __SPRT_IMAGE_FILE_MACHINE_MIPS16
#define IMAGE_FILE_MACHINE_ALPHA64 __SPRT_IMAGE_FILE_MACHINE_ALPHA64
#define IMAGE_FILE_MACHINE_MIPSFPU __SPRT_IMAGE_FILE_MACHINE_MIPSFPU
#define IMAGE_FILE_MACHINE_MIPSFPU16 __SPRT_IMAGE_FILE_MACHINE_MIPSFPU16
#define IMAGE_FILE_MACHINE_AXP64 __SPRT_IMAGE_FILE_MACHINE_AXP64
#define IMAGE_FILE_MACHINE_TRICORE __SPRT_IMAGE_FILE_MACHINE_TRICORE
#define IMAGE_FILE_MACHINE_CEF __SPRT_IMAGE_FILE_MACHINE_CEF
#define IMAGE_FILE_MACHINE_EBC __SPRT_IMAGE_FILE_MACHINE_EBC
#define IMAGE_FILE_MACHINE_AMD64 __SPRT_IMAGE_FILE_MACHINE_AMD64
#define IMAGE_FILE_MACHINE_M32R __SPRT_IMAGE_FILE_MACHINE_M32R
#define IMAGE_FILE_MACHINE_ARM64 __SPRT_IMAGE_FILE_MACHINE_ARM64
#define IMAGE_FILE_MACHINE_CEE __SPRT_IMAGE_FILE_MACHINE_CEE
#define UNW_FLAG_NHANDLER __SPRT_UNW_FLAG_NHANDLER
#define UNW_FLAG_EHANDLER __SPRT_UNW_FLAG_EHANDLER
#define UNW_FLAG_UHANDLER __SPRT_UNW_FLAG_UHANDLER
#define UNW_FLAG_CHAININFO __SPRT_UNW_FLAG_CHAININFO
#define STILL_ACTIVE __SPRT_STILL_ACTIVE
#define EXCEPTION_ACCESS_VIOLATION __SPRT_EXCEPTION_ACCESS_VIOLATION
#define EXCEPTION_DATATYPE_MISALIGNMENT __SPRT_EXCEPTION_DATATYPE_MISALIGNMENT
#define EXCEPTION_BREAKPOINT __SPRT_EXCEPTION_BREAKPOINT
#define EXCEPTION_SINGLE_STEP __SPRT_EXCEPTION_SINGLE_STEP
#define EXCEPTION_ARRAY_BOUNDS_EXCEEDED __SPRT_EXCEPTION_ARRAY_BOUNDS_EXCEEDED
#define EXCEPTION_FLT_DENORMAL_OPERAND __SPRT_EXCEPTION_FLT_DENORMAL_OPERAND
#define EXCEPTION_FLT_DIVIDE_BY_ZERO __SPRT_EXCEPTION_FLT_DIVIDE_BY_ZERO
#define EXCEPTION_FLT_INEXACT_RESULT __SPRT_EXCEPTION_FLT_INEXACT_RESULT
#define EXCEPTION_FLT_INVALID_OPERATION __SPRT_EXCEPTION_FLT_INVALID_OPERATION
#define EXCEPTION_FLT_OVERFLOW __SPRT_EXCEPTION_FLT_OVERFLOW
#define EXCEPTION_FLT_STACK_CHECK __SPRT_EXCEPTION_FLT_STACK_CHECK
#define EXCEPTION_FLT_UNDERFLOW __SPRT_EXCEPTION_FLT_UNDERFLOW
#define EXCEPTION_INT_DIVIDE_BY_ZERO __SPRT_EXCEPTION_INT_DIVIDE_BY_ZERO
#define EXCEPTION_INT_OVERFLOW __SPRT_EXCEPTION_INT_OVERFLOW
#define EXCEPTION_PRIV_INSTRUCTION __SPRT_EXCEPTION_PRIV_INSTRUCTION
#define EXCEPTION_IN_PAGE_ERROR __SPRT_EXCEPTION_IN_PAGE_ERROR
#define EXCEPTION_ILLEGAL_INSTRUCTION __SPRT_EXCEPTION_ILLEGAL_INSTRUCTION
#define EXCEPTION_NONCONTINUABLE __SPRT_EXCEPTION_NONCONTINUABLE
#define EXCEPTION_NONCONTINUABLE_EXCEPTION __SPRT_EXCEPTION_NONCONTINUABLE_EXCEPTION
#define EXCEPTION_STACK_OVERFLOW __SPRT_EXCEPTION_STACK_OVERFLOW
#define EXCEPTION_INVALID_DISPOSITION __SPRT_EXCEPTION_INVALID_DISPOSITION
#define EXCEPTION_GUARD_PAGE __SPRT_EXCEPTION_GUARD_PAGE
#define EXCEPTION_INVALID_HANDLE __SPRT_EXCEPTION_INVALID_HANDLE
#define EXCEPTION_POSSIBLE_DEADLOCK __SPRT_EXCEPTION_POSSIBLE_DEADLOCK
#define CONTROL_C_EXIT __SPRT_CONTROL_C_EXIT
#define EXCEPTION_EXECUTE_HANDLER __SPRT_EXCEPTION_EXECUTE_HANDLER
#define EXCEPTION_CONTINUE_SEARCH __SPRT_EXCEPTION_CONTINUE_SEARCH
#define EXCEPTION_CONTINUE_EXECUTION __SPRT_EXCEPTION_CONTINUE_EXECUTION
#define EXCEPTION_MAXIMUM_PARAMETERS __SPRT_EXCEPTION_MAXIMUM_PARAMETERS
#define UNWIND_HISTORY_TABLE_SIZE __SPRT_UNWIND_HISTORY_TABLE_SIZE

#define WOW64_CONTEXT_i386 __SPRT_WOW64_CONTEXT_i386
#define WOW64_CONTEXT_CONTROL __SPRT_WOW64_CONTEXT_CONTROL
#define WOW64_CONTEXT_INTEGER __SPRT_WOW64_CONTEXT_INTEGER
#define WOW64_CONTEXT_SEGMENTS __SPRT_WOW64_CONTEXT_SEGMENTS
#define WOW64_CONTEXT_FLOATING_POINT __SPRT_WOW64_CONTEXT_FLOATING_POINT
#define WOW64_CONTEXT_DEBUG_REGISTERS __SPRT_WOW64_CONTEXT_DEBUG_REGISTERS
#define WOW64_CONTEXT_EXTENDED_REGISTERS __SPRT_WOW64_CONTEXT_EXTENDED_REGISTERS
#define WOW64_CONTEXT_FULL __SPRT_WOW64_CONTEXT_FULL
#define WOW64_CONTEXT_ALL __SPRT_WOW64_CONTEXT_ALL
#define WOW64_SIZE_OF_80387_REGISTERS __SPRT_WOW64_SIZE_OF_80387_REGISTERS
#define WOW64_MAXIMUM_SUPPORTED_EXTENSION __SPRT_WOW64_MAXIMUM_SUPPORTED_EXTENSION

#define EXCEPTION_DEBUG_EVENT __SPRT_EXCEPTION_DEBUG_EVENT
#define CREATE_THREAD_DEBUG_EVENT __SPRT_CREATE_THREAD_DEBUG_EVENT
#define CREATE_PROCESS_DEBUG_EVENT __SPRT_CREATE_PROCESS_DEBUG_EVENT
#define EXIT_THREAD_DEBUG_EVENT __SPRT_EXIT_THREAD_DEBUG_EVENT
#define EXIT_PROCESS_DEBUG_EVENT __SPRT_EXIT_PROCESS_DEBUG_EVENT
#define LOAD_DLL_DEBUG_EVENT __SPRT_LOAD_DLL_DEBUG_EVENT
#define UNLOAD_DLL_DEBUG_EVENT __SPRT_UNLOAD_DLL_DEBUG_EVENT
#define OUTPUT_DEBUG_STRING_EVENT __SPRT_OUTPUT_DEBUG_STRING_EVENT
#define RIP_EVENT __SPRT_RIP_EVENT

__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI VOID RtlCaptureContext(PCONTEXT ContextRecord);

__SPRT_WIN_IMPORT WINAPI BOOL GetThreadContext(HANDLE hThread, LPCONTEXT lpContext);

__SPRT_WIN_IMPORT WINAPI BOOL SetThreadContext(HANDLE hThread, const CONTEXT *lpContext);

__SPRT_WIN_IMPORT WINAPI BOOL Wow64GetThreadContext(HANDLE hThread, PWOW64_CONTEXT lpContext);

__SPRT_WIN_IMPORT WINAPI BOOL Wow64SetThreadContext(HANDLE hThread, const WOW64_CONTEXT *lpContext);

__SPRT_WIN_IMPORT WINAPI VOID RtlRestoreContext(PCONTEXT ContextRecord,
		EXCEPTION_RECORD *ExceptionRecord);

__SPRT_WIN_IMPORT WINAPI PRUNTIME_FUNCTION RtlLookupFunctionEntry(DWORD64 ControlPc,
		PDWORD64 ImageBase, PUNWIND_HISTORY_TABLE HistoryTable);

__SPRT_WIN_IMPORT WINAPI BOOLEAN RtlAddFunctionTable(PRUNTIME_FUNCTION FunctionTable,
		DWORD EntryCount, DWORD64 BaseAddress);

__SPRT_WIN_IMPORT WINAPI BOOLEAN RtlDeleteFunctionTable(PRUNTIME_FUNCTION FunctionTable);

__SPRT_WIN_IMPORT WINAPI VOID RtlUnwindEx(PVOID TargetFrame, PVOID TargetIp,
		PEXCEPTION_RECORD ExceptionRecord, PVOID ReturnValue, PCONTEXT ContextRecord,
		PUNWIND_HISTORY_TABLE HistoryTable);

__SPRT_WIN_IMPORT WINAPI PEXCEPTION_ROUTINE RtlVirtualUnwind(DWORD HandlerType, DWORD64 ImageBase,
		DWORD64 ControlPc, PRUNTIME_FUNCTION FunctionEntry, PCONTEXT ContextRecord,
		PVOID *HandlerData, PDWORD64 EstablisherFrame, PVOID ContextPointers);

__SPRT_WIN_IMPORT WINAPI WORD RtlCaptureStackBackTrace(DWORD FramesToSkip, DWORD FramesToCapture,
		PVOID *BackTrace, PDWORD BackTraceHash);

__SPRT_WIN_IMPORT WINAPI PVOID AddVectoredExceptionHandler(ULONG First,
		PVECTORED_EXCEPTION_HANDLER Handler);

__SPRT_WIN_IMPORT WINAPI ULONG RemoveVectoredExceptionHandler(PVOID Handle);

__SPRT_WIN_IMPORT WINAPI PVOID AddVectoredContinueHandler(ULONG First,
		PVECTORED_EXCEPTION_HANDLER Handler);

__SPRT_WIN_IMPORT WINAPI ULONG RemoveVectoredContinueHandler(PVOID Handle);

__SPRT_WIN_IMPORT WINAPI BOOL WaitForDebugEvent(LPDEBUG_EVENT lpDebugEvent, DWORD dwMilliseconds);
__SPRT_WIN_IMPORT WINAPI BOOL ContinueDebugEvent(DWORD dwProcessId, DWORD dwThreadId,
		DWORD dwContinueStatus);
__SPRT_WIN_IMPORT WINAPI BOOL DebugActiveProcess(DWORD dwProcessId);
__SPRT_WIN_IMPORT WINAPI BOOL DebugActiveProcessStop(DWORD dwProcessId);
__SPRT_WIN_IMPORT WINAPI BOOL DebugBreakProcess(HANDLE Process);

__SPRT_WIN_IMPORT WINAPI LPTOP_LEVEL_EXCEPTION_FILTER SetUnhandledExceptionFilter(
		LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);

__SPRT_WIN_IMPORT WINAPI NTSTATUS NtContinueEx(CONTEXT *context, void *args);

__SPRT_WIN_IMPORT WINAPI VOID RaiseException(DWORD dwExceptionCode, DWORD dwExceptionFlags,
		DWORD nNumberOfArguments, const ULONG_PTR *lpArguments);

#if defined(_M_AMD64) && !defined(_M_ARM64EC)

SPRT_FORCEINLINE PVOID GetCurrentFiber(VOID) {
	return (PVOID)__readgsqword(__builtin_offsetof(NT_TIB, FiberData));
}

SPRT_FORCEINLINE struct _TEB *NtCurrentTeb(VOID) {
	return (struct _TEB *)__readgsqword(__builtin_offsetof(NT_TIB, Self));
}

#elif defined(_M_ARM64)

// On Windows ARM64 the TEB is held in x18; the NT_TIB layout matches x64.
SPRT_FORCEINLINE PVOID GetCurrentFiber(VOID) {
	return (PVOID)__readx18qword(__builtin_offsetof(NT_TIB, FiberData));
}

SPRT_FORCEINLINE struct _TEB *NtCurrentTeb(VOID) {
	return (struct _TEB *)__readx18qword(__builtin_offsetof(NT_TIB, Self));
}

#endif

SPRT_FORCEINLINE PVOID GetFiberData(VOID) { return *(PVOID *)GetCurrentFiber(); }

// Function prototypes
// When <setjmp is included - this should not be visible
#ifndef CORE_RUNTIME_INCLUDE_LIBC_SETJMP_H_
__attribute__((returns_twice)) int setjmp(struct _JUMP_BUFFER *_Buf, void *);

__SPRT_NORETURN void __cdecl longjmp(struct _JUMP_BUFFER *, int _Value);
#endif

__SPRT_END_DECL

#endif
