/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_DEBUG_API_H_
#define SPRT_WRAPPERS_WINDOWS_DEBUG_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/debug_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/debug_api.h) */
#define SYMOPT_CASE_INSENSITIVE __SPRT_SYMOPT_CASE_INSENSITIVE
#define SYMOPT_UNDNAME __SPRT_SYMOPT_UNDNAME
#define SYMOPT_DEFERRED_LOADS __SPRT_SYMOPT_DEFERRED_LOADS
#define SYMOPT_NO_CPP __SPRT_SYMOPT_NO_CPP
#define SYMOPT_LOAD_LINES __SPRT_SYMOPT_LOAD_LINES
#define SYMOPT_OMAP_FIND_NEAREST __SPRT_SYMOPT_OMAP_FIND_NEAREST
#define SYMOPT_LOAD_ANYTHING __SPRT_SYMOPT_LOAD_ANYTHING
#define SYMOPT_IGNORE_CVREC __SPRT_SYMOPT_IGNORE_CVREC
#define SYMOPT_NO_UNQUALIFIED_LOADS __SPRT_SYMOPT_NO_UNQUALIFIED_LOADS
#define SYMOPT_FAIL_CRITICAL_ERRORS __SPRT_SYMOPT_FAIL_CRITICAL_ERRORS
#define SYMOPT_EXACT_SYMBOLS __SPRT_SYMOPT_EXACT_SYMBOLS
#define SYMOPT_ALLOW_ABSOLUTE_SYMBOLS __SPRT_SYMOPT_ALLOW_ABSOLUTE_SYMBOLS
#define SYMOPT_IGNORE_NT_SYMPATH __SPRT_SYMOPT_IGNORE_NT_SYMPATH
#define SYMOPT_INCLUDE_32BIT_MODULES __SPRT_SYMOPT_INCLUDE_32BIT_MODULES
#define SYMOPT_PUBLICS_ONLY __SPRT_SYMOPT_PUBLICS_ONLY
#define SYMOPT_NO_PUBLICS __SPRT_SYMOPT_NO_PUBLICS
#define SYMOPT_AUTO_PUBLICS __SPRT_SYMOPT_AUTO_PUBLICS
#define SYMOPT_NO_IMAGE_SEARCH __SPRT_SYMOPT_NO_IMAGE_SEARCH
#define SYMOPT_SECURE __SPRT_SYMOPT_SECURE
#define SYMOPT_NO_PROMPTS __SPRT_SYMOPT_NO_PROMPTS
#define SYMOPT_OVERWRITE __SPRT_SYMOPT_OVERWRITE
#define SYMOPT_IGNORE_IMAGEDIR __SPRT_SYMOPT_IGNORE_IMAGEDIR
#define SYMOPT_FLAT_DIRECTORY __SPRT_SYMOPT_FLAT_DIRECTORY
#define SYMOPT_FAVOR_COMPRESSED __SPRT_SYMOPT_FAVOR_COMPRESSED
#define SYMOPT_ALLOW_ZERO_ADDRESS __SPRT_SYMOPT_ALLOW_ZERO_ADDRESS
#define SYMOPT_DISABLE_SYMSRV_AUTODETECT __SPRT_SYMOPT_DISABLE_SYMSRV_AUTODETECT
#define SYMOPT_READONLY_CACHE __SPRT_SYMOPT_READONLY_CACHE
#define SYMOPT_SYMPATH_LAST __SPRT_SYMOPT_SYMPATH_LAST
#define SYMOPT_DISABLE_FAST_SYMBOLS __SPRT_SYMOPT_DISABLE_FAST_SYMBOLS
#define SYMOPT_DISABLE_SYMSRV_TIMEOUT __SPRT_SYMOPT_DISABLE_SYMSRV_TIMEOUT
#define SYMOPT_DISABLE_SRVSTAR_ON_STARTUP __SPRT_SYMOPT_DISABLE_SRVSTAR_ON_STARTUP
#define SYMOPT_DEBUG __SPRT_SYMOPT_DEBUG


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI DWORD SymSetOptions(DWORD SymOptions);

__SPRT_WIN_IMPORT WINAPI BOOL SymInitialize(HANDLE hProcess, PCSTR UserSearchPath,
		BOOL fInvadeProcess);

__SPRT_WIN_IMPORT WINAPI DWORD SymGetOptions(VOID);

__SPRT_WIN_IMPORT WINAPI BOOL SymCleanup(HANDLE hProcess);

__SPRT_WIN_IMPORT WINAPI BOOL StackWalk64(DWORD MachineType, HANDLE hProcess, HANDLE hThread,
		LPSTACKFRAME64 StackFrame, PVOID ContextRecord,
		PREAD_PROCESS_MEMORY_ROUTINE64 ReadMemoryRoutine,
		PFUNCTION_TABLE_ACCESS_ROUTINE64 FunctionTableAccessRoutine,
		PGET_MODULE_BASE_ROUTINE64 GetModuleBaseRoutine,
		PTRANSLATE_ADDRESS_ROUTINE64 TranslateAddress);

__SPRT_WIN_IMPORT WINAPI BOOL SymGetSymFromAddr64(HANDLE hProcess, DWORD64 qwAddr,
		PDWORD64 pdwDisplacement, PIMAGEHLP_SYMBOL64 Symbol);

__SPRT_WIN_IMPORT WINAPI BOOL SymGetLineFromAddr64(HANDLE hProcess, DWORD64 qwAddr,
		PDWORD pdwDisplacement, PIMAGEHLP_LINE64 Line64);

__SPRT_WIN_IMPORT WINAPI DWORD UnDecorateSymbolName(PCSTR name, PSTR outputString,
		DWORD maxStringLength, DWORD flags);

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_DEBUG_API_H_
