/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_DL_API_H_
#define SPRT_WRAPPERS_WINDOWS_DL_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/dl_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/dl_api.h) */
#define IMAGE_NUMBEROF_DIRECTORY_ENTRIES __SPRT_IMAGE_NUMBEROF_DIRECTORY_ENTRIES
#define IMAGE_DOS_SIGNATURE __SPRT_IMAGE_DOS_SIGNATURE
#define IMAGE_OS2_SIGNATURE __SPRT_IMAGE_OS2_SIGNATURE
#define IMAGE_OS2_SIGNATURE_LE __SPRT_IMAGE_OS2_SIGNATURE_LE
#define IMAGE_VXD_SIGNATURE __SPRT_IMAGE_VXD_SIGNATURE
#define IMAGE_NT_SIGNATURE __SPRT_IMAGE_NT_SIGNATURE
#define IMAGE_NT_OPTIONAL_HDR64_MAGIC __SPRT_IMAGE_NT_OPTIONAL_HDR64_MAGIC
#define MEM_COMMIT __SPRT_MEM_COMMIT
#define MEM_RESERVE __SPRT_MEM_RESERVE
#define MEM_REPLACE_PLACEHOLDER __SPRT_MEM_REPLACE_PLACEHOLDER
#define MEM_RESERVE_PLACEHOLDER __SPRT_MEM_RESERVE_PLACEHOLDER
#define MEM_RESET __SPRT_MEM_RESET
#define MEM_TOP_DOWN __SPRT_MEM_TOP_DOWN
#define MEM_WRITE_WATCH __SPRT_MEM_WRITE_WATCH
#define MEM_PHYSICAL __SPRT_MEM_PHYSICAL
#define MEM_ROTATE __SPRT_MEM_ROTATE
#define MEM_DIFFERENT_IMAGE_BASE_OK __SPRT_MEM_DIFFERENT_IMAGE_BASE_OK
#define MEM_RESET_UNDO __SPRT_MEM_RESET_UNDO
#define MEM_LARGE_PAGES __SPRT_MEM_LARGE_PAGES
#define MEM_4MB_PAGES __SPRT_MEM_4MB_PAGES
#define MEM_64K_PAGES __SPRT_MEM_64K_PAGES
#define MEM_UNMAP_WITH_TRANSIENT_BOOST __SPRT_MEM_UNMAP_WITH_TRANSIENT_BOOST
#define MEM_COALESCE_PLACEHOLDERS __SPRT_MEM_COALESCE_PLACEHOLDERS
#define MEM_PRESERVE_PLACEHOLDER __SPRT_MEM_PRESERVE_PLACEHOLDER
#define MEM_DECOMMIT __SPRT_MEM_DECOMMIT
#define MEM_RELEASE __SPRT_MEM_RELEASE
#define MEM_FREE __SPRT_MEM_FREE
#define PAGE_NOACCESS __SPRT_PAGE_NOACCESS
#define PAGE_READONLY __SPRT_PAGE_READONLY
#define PAGE_READWRITE __SPRT_PAGE_READWRITE
#define PAGE_WRITECOPY __SPRT_PAGE_WRITECOPY
#define PAGE_EXECUTE __SPRT_PAGE_EXECUTE
#define PAGE_EXECUTE_READ __SPRT_PAGE_EXECUTE_READ
#define PAGE_EXECUTE_READWRITE __SPRT_PAGE_EXECUTE_READWRITE
#define PAGE_EXECUTE_WRITECOPY __SPRT_PAGE_EXECUTE_WRITECOPY
#define PAGE_GUARD __SPRT_PAGE_GUARD
#define PAGE_NOCACHE __SPRT_PAGE_NOCACHE
#define PAGE_WRITECOMBINE __SPRT_PAGE_WRITECOMBINE
#define IMAGE_DIRECTORY_ENTRY_EXPORT __SPRT_IMAGE_DIRECTORY_ENTRY_EXPORT
#define IMAGE_DIRECTORY_ENTRY_IMPORT __SPRT_IMAGE_DIRECTORY_ENTRY_IMPORT
#define IMAGE_DIRECTORY_ENTRY_RESOURCE __SPRT_IMAGE_DIRECTORY_ENTRY_RESOURCE
#define IMAGE_DIRECTORY_ENTRY_EXCEPTION __SPRT_IMAGE_DIRECTORY_ENTRY_EXCEPTION
#define IMAGE_DIRECTORY_ENTRY_SECURITY __SPRT_IMAGE_DIRECTORY_ENTRY_SECURITY
#define IMAGE_DIRECTORY_ENTRY_BASERELOC __SPRT_IMAGE_DIRECTORY_ENTRY_BASERELOC
#define IMAGE_DIRECTORY_ENTRY_DEBUG __SPRT_IMAGE_DIRECTORY_ENTRY_DEBUG
#define IMAGE_DIRECTORY_ENTRY_ARCHITECTURE __SPRT_IMAGE_DIRECTORY_ENTRY_ARCHITECTURE
#define IMAGE_DIRECTORY_ENTRY_GLOBALPTR __SPRT_IMAGE_DIRECTORY_ENTRY_GLOBALPTR
#define IMAGE_DIRECTORY_ENTRY_TLS __SPRT_IMAGE_DIRECTORY_ENTRY_TLS
#define IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG __SPRT_IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG
#define IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT __SPRT_IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT
#define IMAGE_DIRECTORY_ENTRY_IAT __SPRT_IMAGE_DIRECTORY_ENTRY_IAT
#define IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT __SPRT_IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT
#define IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR __SPRT_IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR
#define GET_MODULE_HANDLE_EX_FLAG_PIN __SPRT_GET_MODULE_HANDLE_EX_FLAG_PIN
#define GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT __SPRT_GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT
#define GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS __SPRT_GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS
#define DLL_PROCESS_ATTACH __SPRT_DLL_PROCESS_ATTACH
#define DLL_THREAD_ATTACH __SPRT_DLL_THREAD_ATTACH
#define DLL_THREAD_DETACH __SPRT_DLL_THREAD_DETACH
#define DLL_PROCESS_DETACH __SPRT_DLL_PROCESS_DETACH
#define UOI_FLAGS __SPRT_UOI_FLAGS
#define UOI_NAME __SPRT_UOI_NAME
#define UOI_TYPE __SPRT_UOI_TYPE
#define UOI_USER_SID __SPRT_UOI_USER_SID
#define UOI_HEAPSIZE __SPRT_UOI_HEAPSIZE
#define UOI_IO __SPRT_UOI_IO
#define UOI_TIMERPROC_EXCEPTION_SUPPRESSION __SPRT_UOI_TIMERPROC_EXCEPTION_SUPPRESSION
#define LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR __SPRT_LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR
#define LOAD_LIBRARY_SEARCH_APPLICATION_DIR __SPRT_LOAD_LIBRARY_SEARCH_APPLICATION_DIR
#define LOAD_LIBRARY_SEARCH_USER_DIRS __SPRT_LOAD_LIBRARY_SEARCH_USER_DIRS
#define LOAD_LIBRARY_SEARCH_SYSTEM32 __SPRT_LOAD_LIBRARY_SEARCH_SYSTEM32
#define LOAD_LIBRARY_SEARCH_DEFAULT_DIRS __SPRT_LOAD_LIBRARY_SEARCH_DEFAULT_DIRS
#define IMAGE_NUMBEROF_DIRECTORY_ENTRIES __SPRT_IMAGE_NUMBEROF_DIRECTORY_ENTRIES
#define IMAGE_NT_OPTIONAL_HDR32_MAGIC __SPRT_IMAGE_NT_OPTIONAL_HDR32_MAGIC
#define IMAGE_NT_OPTIONAL_HDR64_MAGIC __SPRT_IMAGE_NT_OPTIONAL_HDR64_MAGIC
#define IMAGE_ROM_OPTIONAL_HDR_MAGIC __SPRT_IMAGE_ROM_OPTIONAL_HDR_MAGIC
#define IMAGE_NT_OPTIONAL_HDR_MAGIC __SPRT_IMAGE_NT_OPTIONAL_HDR_MAGIC

__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI SIZE_T VirtualQuery(LPCVOID lpAddress, PMEMORY_BASIC_INFORMATION lpBuffer,
		SIZE_T dwLength);

__SPRT_WIN_IMPORT __declspec(noreturn) WINAPI VOID ExitProcess(UINT uExitCode);

__SPRT_WIN_IMPORT WINAPI HMODULE LoadLibraryW(LPCWSTR lpLibFileName);

__SPRT_WIN_IMPORT WINAPI HMODULE LoadLibraryA(LPCSTR lpLibFileName);

__SPRT_WIN_IMPORT WINAPI HMODULE LoadLibraryExW(LPCWSTR lpLibFileName, HANDLE hFile, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL FreeLibrary(HMODULE hModule);

__SPRT_WIN_IMPORT WINAPI FARPROC GetProcAddress(HMODULE hModule, LPCSTR lpProcName);

__SPRT_WIN_IMPORT WINAPI HMODULE GetModuleHandleW(LPCWSTR lpModuleName);

__SPRT_WIN_IMPORT WINAPI BOOL GetModuleHandleExA(DWORD dwFlags, LPCSTR lpModuleName,
		HMODULE *phModule);

__SPRT_WIN_IMPORT WINAPI BOOL GetModuleHandleExW(DWORD dwFlags, LPCWSTR lpModuleName,
		PHMODULE phModule);

__SPRT_WIN_IMPORT WINAPI DWORD GetModuleFileNameW(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);

__SPRT_WIN_IMPORT WINAPI PVOID RtlPcToFileHeader(PVOID PcValue, PVOID *BaseOfImage);

#ifdef UNICODE
#define GetModuleHandle GetModuleHandleW
#define LoadLibrary LoadLibraryW
#else
#define GetModuleHandle GetModuleHandleA
#endif

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_DL_API_H_
