/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_FILE_API_H_
#define SPRT_WRAPPERS_WINDOWS_FILE_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/file_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/file_api.h) */
#define CREATE_NEW __SPRT_CREATE_NEW
#define CREATE_ALWAYS __SPRT_CREATE_ALWAYS
#define OPEN_EXISTING __SPRT_OPEN_EXISTING
#define OPEN_ALWAYS __SPRT_OPEN_ALWAYS
#define TRUNCATE_EXISTING __SPRT_TRUNCATE_EXISTING
#define INVALID_FILE_SIZE __SPRT_INVALID_FILE_SIZE
#define INVALID_SET_FILE_POINTER __SPRT_INVALID_SET_FILE_POINTER
#define INVALID_FILE_ATTRIBUTES __SPRT_INVALID_FILE_ATTRIBUTES
#define FILE_READ_DATA __SPRT_FILE_READ_DATA
#define FILE_LIST_DIRECTORY __SPRT_FILE_LIST_DIRECTORY
#define FILE_WRITE_DATA __SPRT_FILE_WRITE_DATA
#define FILE_ADD_FILE __SPRT_FILE_ADD_FILE
#define FILE_APPEND_DATA __SPRT_FILE_APPEND_DATA
#define FILE_ADD_SUBDIRECTORY __SPRT_FILE_ADD_SUBDIRECTORY
#define FILE_CREATE_PIPE_INSTANCE __SPRT_FILE_CREATE_PIPE_INSTANCE
#define FILE_READ_EA __SPRT_FILE_READ_EA
#define FILE_WRITE_EA __SPRT_FILE_WRITE_EA
#define FILE_EXECUTE __SPRT_FILE_EXECUTE
#define FILE_TRAVERSE __SPRT_FILE_TRAVERSE
#define FILE_DELETE_CHILD __SPRT_FILE_DELETE_CHILD
#define FILE_READ_ATTRIBUTES __SPRT_FILE_READ_ATTRIBUTES
#define FILE_WRITE_ATTRIBUTES __SPRT_FILE_WRITE_ATTRIBUTES
#define FILE_ALL_ACCESS __SPRT_FILE_ALL_ACCESS
#define FILE_GENERIC_READ __SPRT_FILE_GENERIC_READ
#define FILE_GENERIC_WRITE __SPRT_FILE_GENERIC_WRITE
#define FILE_GENERIC_EXECUTE __SPRT_FILE_GENERIC_EXECUTE
#define FILE_SHARE_READ __SPRT_FILE_SHARE_READ
#define FILE_SHARE_WRITE __SPRT_FILE_SHARE_WRITE
#define FILE_SHARE_DELETE __SPRT_FILE_SHARE_DELETE
#define FILE_ATTRIBUTE_READONLY __SPRT_FILE_ATTRIBUTE_READONLY
#define FILE_ATTRIBUTE_HIDDEN __SPRT_FILE_ATTRIBUTE_HIDDEN
#define FILE_ATTRIBUTE_SYSTEM __SPRT_FILE_ATTRIBUTE_SYSTEM
#define FILE_ATTRIBUTE_DIRECTORY __SPRT_FILE_ATTRIBUTE_DIRECTORY
#define FILE_ATTRIBUTE_ARCHIVE __SPRT_FILE_ATTRIBUTE_ARCHIVE
#define FILE_ATTRIBUTE_DEVICE __SPRT_FILE_ATTRIBUTE_DEVICE
#define FILE_ATTRIBUTE_NORMAL __SPRT_FILE_ATTRIBUTE_NORMAL
#define FILE_ATTRIBUTE_TEMPORARY __SPRT_FILE_ATTRIBUTE_TEMPORARY
#define FILE_ATTRIBUTE_SPARSE_FILE __SPRT_FILE_ATTRIBUTE_SPARSE_FILE
#define FILE_ATTRIBUTE_REPARSE_POINT __SPRT_FILE_ATTRIBUTE_REPARSE_POINT
#define FILE_ATTRIBUTE_COMPRESSED __SPRT_FILE_ATTRIBUTE_COMPRESSED
#define FILE_ATTRIBUTE_OFFLINE __SPRT_FILE_ATTRIBUTE_OFFLINE
#define FILE_ATTRIBUTE_NOT_CONTENT_INDEXED __SPRT_FILE_ATTRIBUTE_NOT_CONTENT_INDEXED
#define FILE_ATTRIBUTE_ENCRYPTED __SPRT_FILE_ATTRIBUTE_ENCRYPTED
#define FILE_ATTRIBUTE_INTEGRITY_STREAM __SPRT_FILE_ATTRIBUTE_INTEGRITY_STREAM
#define FILE_ATTRIBUTE_VIRTUAL __SPRT_FILE_ATTRIBUTE_VIRTUAL
#define FILE_ATTRIBUTE_NO_SCRUB_DATA __SPRT_FILE_ATTRIBUTE_NO_SCRUB_DATA
#define FILE_ATTRIBUTE_EA __SPRT_FILE_ATTRIBUTE_EA
#define FILE_ATTRIBUTE_PINNED __SPRT_FILE_ATTRIBUTE_PINNED
#define FILE_ATTRIBUTE_UNPINNED __SPRT_FILE_ATTRIBUTE_UNPINNED
#define FILE_ATTRIBUTE_RECALL_ON_OPEN __SPRT_FILE_ATTRIBUTE_RECALL_ON_OPEN
#define FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS __SPRT_FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS
#define FILE_VOLUME_IS_COMPRESSED __SPRT_FILE_VOLUME_IS_COMPRESSED
#define FILE_SUPPORTS_OBJECT_IDS __SPRT_FILE_SUPPORTS_OBJECT_IDS
#define FILE_SUPPORTS_ENCRYPTION __SPRT_FILE_SUPPORTS_ENCRYPTION
#define FILE_NAMED_STREAMS __SPRT_FILE_NAMED_STREAMS
#define FILE_READ_ONLY_VOLUME __SPRT_FILE_READ_ONLY_VOLUME
#define FILE_SEQUENTIAL_WRITE_ONCE __SPRT_FILE_SEQUENTIAL_WRITE_ONCE
#define FILE_SUPPORTS_TRANSACTIONS __SPRT_FILE_SUPPORTS_TRANSACTIONS
#define FILE_SUPPORTS_HARD_LINKS __SPRT_FILE_SUPPORTS_HARD_LINKS
#define FILE_SUPPORTS_EXTENDED_ATTRIBUTES __SPRT_FILE_SUPPORTS_EXTENDED_ATTRIBUTES
#define FILE_SUPPORTS_OPEN_BY_FILE_ID __SPRT_FILE_SUPPORTS_OPEN_BY_FILE_ID
#define FILE_SUPPORTS_USN_JOURNAL __SPRT_FILE_SUPPORTS_USN_JOURNAL
#define FILE_SUPPORTS_INTEGRITY_STREAMS __SPRT_FILE_SUPPORTS_INTEGRITY_STREAMS
#define FILE_SUPPORTS_BLOCK_REFCOUNTING __SPRT_FILE_SUPPORTS_BLOCK_REFCOUNTING
#define FILE_SUPPORTS_SPARSE_VDL __SPRT_FILE_SUPPORTS_SPARSE_VDL
#define FILE_DAX_VOLUME __SPRT_FILE_DAX_VOLUME
#define FILE_SUPPORTS_GHOSTING __SPRT_FILE_SUPPORTS_GHOSTING
#define FILE_FLAG_WRITE_THROUGH __SPRT_FILE_FLAG_WRITE_THROUGH
#define FILE_FLAG_OVERLAPPED __SPRT_FILE_FLAG_OVERLAPPED
#define FILE_FLAG_NO_BUFFERING __SPRT_FILE_FLAG_NO_BUFFERING
#define FILE_FLAG_RANDOM_ACCESS __SPRT_FILE_FLAG_RANDOM_ACCESS
#define FILE_FLAG_SEQUENTIAL_SCAN __SPRT_FILE_FLAG_SEQUENTIAL_SCAN
#define FILE_FLAG_DELETE_ON_CLOSE __SPRT_FILE_FLAG_DELETE_ON_CLOSE
#define FILE_FLAG_BACKUP_SEMANTICS __SPRT_FILE_FLAG_BACKUP_SEMANTICS
#define FILE_FLAG_POSIX_SEMANTICS __SPRT_FILE_FLAG_POSIX_SEMANTICS
#define FILE_FLAG_SESSION_AWARE __SPRT_FILE_FLAG_SESSION_AWARE
#define FILE_FLAG_OPEN_REPARSE_POINT __SPRT_FILE_FLAG_OPEN_REPARSE_POINT
#define FILE_FLAG_OPEN_NO_RECALL __SPRT_FILE_FLAG_OPEN_NO_RECALL
#define FILE_FLAG_FIRST_PIPE_INSTANCE __SPRT_FILE_FLAG_FIRST_PIPE_INSTANCE
#define IO_REPARSE_TAG_RESERVED_INVALID __SPRT_IO_REPARSE_TAG_RESERVED_INVALID
#define IO_REPARSE_TAG_MOUNT_POINT __SPRT_IO_REPARSE_TAG_MOUNT_POINT
#define IO_REPARSE_TAG_HSM __SPRT_IO_REPARSE_TAG_HSM
#define IO_REPARSE_TAG_HSM2 __SPRT_IO_REPARSE_TAG_HSM2
#define IO_REPARSE_TAG_SIS __SPRT_IO_REPARSE_TAG_SIS
#define IO_REPARSE_TAG_WIM __SPRT_IO_REPARSE_TAG_WIM
#define IO_REPARSE_TAG_CSV __SPRT_IO_REPARSE_TAG_CSV
#define IO_REPARSE_TAG_DFS __SPRT_IO_REPARSE_TAG_DFS
#define IO_REPARSE_TAG_SYMLINK __SPRT_IO_REPARSE_TAG_SYMLINK
#define IO_REPARSE_TAG_DFSR __SPRT_IO_REPARSE_TAG_DFSR
#define IO_REPARSE_TAG_DEDUP __SPRT_IO_REPARSE_TAG_DEDUP
#define IO_REPARSE_TAG_NFS __SPRT_IO_REPARSE_TAG_NFS
#define IO_REPARSE_TAG_FILE_PLACEHOLDER __SPRT_IO_REPARSE_TAG_FILE_PLACEHOLDER
#define IO_REPARSE_TAG_WOF __SPRT_IO_REPARSE_TAG_WOF
#define IO_REPARSE_TAG_WCI __SPRT_IO_REPARSE_TAG_WCI
#define IO_REPARSE_TAG_WCI_1 __SPRT_IO_REPARSE_TAG_WCI_1
#define IO_REPARSE_TAG_GLOBAL_REPARSE __SPRT_IO_REPARSE_TAG_GLOBAL_REPARSE
#define IO_REPARSE_TAG_CLOUD __SPRT_IO_REPARSE_TAG_CLOUD
#define IO_REPARSE_TAG_CLOUD_1 __SPRT_IO_REPARSE_TAG_CLOUD_1
#define IO_REPARSE_TAG_CLOUD_2 __SPRT_IO_REPARSE_TAG_CLOUD_2
#define IO_REPARSE_TAG_CLOUD_3 __SPRT_IO_REPARSE_TAG_CLOUD_3
#define IO_REPARSE_TAG_CLOUD_4 __SPRT_IO_REPARSE_TAG_CLOUD_4
#define IO_REPARSE_TAG_CLOUD_5 __SPRT_IO_REPARSE_TAG_CLOUD_5
#define IO_REPARSE_TAG_CLOUD_6 __SPRT_IO_REPARSE_TAG_CLOUD_6
#define IO_REPARSE_TAG_CLOUD_7 __SPRT_IO_REPARSE_TAG_CLOUD_7
#define IO_REPARSE_TAG_CLOUD_8 __SPRT_IO_REPARSE_TAG_CLOUD_8
#define IO_REPARSE_TAG_CLOUD_9 __SPRT_IO_REPARSE_TAG_CLOUD_9
#define IO_REPARSE_TAG_CLOUD_A __SPRT_IO_REPARSE_TAG_CLOUD_A
#define IO_REPARSE_TAG_CLOUD_B __SPRT_IO_REPARSE_TAG_CLOUD_B
#define IO_REPARSE_TAG_CLOUD_C __SPRT_IO_REPARSE_TAG_CLOUD_C
#define IO_REPARSE_TAG_CLOUD_D __SPRT_IO_REPARSE_TAG_CLOUD_D
#define IO_REPARSE_TAG_CLOUD_E __SPRT_IO_REPARSE_TAG_CLOUD_E
#define IO_REPARSE_TAG_CLOUD_F __SPRT_IO_REPARSE_TAG_CLOUD_F
#define IO_REPARSE_TAG_CLOUD_MASK __SPRT_IO_REPARSE_TAG_CLOUD_MASK
#define IO_REPARSE_TAG_APPEXECLINK __SPRT_IO_REPARSE_TAG_APPEXECLINK
#define IO_REPARSE_TAG_PROJFS __SPRT_IO_REPARSE_TAG_PROJFS
#define IO_REPARSE_TAG_STORAGE_SYNC __SPRT_IO_REPARSE_TAG_STORAGE_SYNC
#define IO_REPARSE_TAG_WCI_TOMBSTONE __SPRT_IO_REPARSE_TAG_WCI_TOMBSTONE
#define IO_REPARSE_TAG_UNHANDLED __SPRT_IO_REPARSE_TAG_UNHANDLED
#define IO_REPARSE_TAG_ONEDRIVE __SPRT_IO_REPARSE_TAG_ONEDRIVE
#define IO_REPARSE_TAG_PROJFS_TOMBSTONE __SPRT_IO_REPARSE_TAG_PROJFS_TOMBSTONE
#define IO_REPARSE_TAG_AF_UNIX __SPRT_IO_REPARSE_TAG_AF_UNIX
#define IO_REPARSE_TAG_STORAGE_SYNC_FOLDER __SPRT_IO_REPARSE_TAG_STORAGE_SYNC_FOLDER
#define IO_REPARSE_TAG_WCI_LINK __SPRT_IO_REPARSE_TAG_WCI_LINK
#define IO_REPARSE_TAG_WCI_LINK_1 __SPRT_IO_REPARSE_TAG_WCI_LINK_1
#define IO_REPARSE_TAG_DATALESS_CIM __SPRT_IO_REPARSE_TAG_DATALESS_CIM
#define MOVEFILE_REPLACE_EXISTING __SPRT_MOVEFILE_REPLACE_EXISTING
#define MOVEFILE_COPY_ALLOWED __SPRT_MOVEFILE_COPY_ALLOWED
#define MOVEFILE_DELAY_UNTIL_REBOOT __SPRT_MOVEFILE_DELAY_UNTIL_REBOOT
#define MOVEFILE_WRITE_THROUGH __SPRT_MOVEFILE_WRITE_THROUGH
#define MOVEFILE_CREATE_HARDLINK __SPRT_MOVEFILE_CREATE_HARDLINK
#define MOVEFILE_FAIL_IF_NOT_TRACKABLE __SPRT_MOVEFILE_FAIL_IF_NOT_TRACKABLE
#define FILE_BEGIN __SPRT_FILE_BEGIN
#define FILE_CURRENT __SPRT_FILE_CURRENT
#define FILE_END __SPRT_FILE_END
#define FILE_NAME_NORMALIZED __SPRT_FILE_NAME_NORMALIZED
#define FILE_NAME_OPENED __SPRT_FILE_NAME_OPENED
#define FILE_MAP_WRITE __SPRT_FILE_MAP_WRITE
#define FILE_MAP_READ __SPRT_FILE_MAP_READ
#define FILE_MAP_ALL_ACCESS __SPRT_FILE_MAP_ALL_ACCESS
#define FILE_MAP_EXECUTE __SPRT_FILE_MAP_EXECUTE
#define FILE_MAP_COPY __SPRT_FILE_MAP_COPY
#define FILE_MAP_RESERVE __SPRT_FILE_MAP_RESERVE
#define FILE_MAP_TARGETS_INVALID __SPRT_FILE_MAP_TARGETS_INVALID
#define FILE_MAP_LARGE_PAGES __SPRT_FILE_MAP_LARGE_PAGES
#define SYMBOLIC_LINK_FLAG_DIRECTORY __SPRT_SYMBOLIC_LINK_FLAG_DIRECTORY
#define SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE __SPRT_SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE
#define SEC_HUGE_PAGES __SPRT_SEC_HUGE_PAGES
#define SEC_LARGE_PAGES __SPRT_SEC_LARGE_PAGES
#define LOCKFILE_FAIL_IMMEDIATELY __SPRT_LOCKFILE_FAIL_IMMEDIATELY
#define LOCKFILE_EXCLUSIVE_LOCK __SPRT_LOCKFILE_EXCLUSIVE_LOCK
#define PIPE_ACCESS_INBOUND __SPRT_PIPE_ACCESS_INBOUND
#define PIPE_ACCESS_OUTBOUND __SPRT_PIPE_ACCESS_OUTBOUND
#define PIPE_ACCESS_DUPLEX __SPRT_PIPE_ACCESS_DUPLEX
#define PIPE_TYPE_BYTE __SPRT_PIPE_TYPE_BYTE
#define PIPE_READMODE_BYTE __SPRT_PIPE_READMODE_BYTE
#define PIPE_WAIT __SPRT_PIPE_WAIT


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI HANDLE CreateFileW(LPCWSTR lpFileName, DWORD dwDesiredAccess,
		DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition,
		DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

__SPRT_WIN_IMPORT WINAPI HANDLE CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess,
		DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition,
		DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);

__SPRT_WIN_IMPORT WINAPI BOOL ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead,
		LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI BOOL WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite,
		LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI BOOL SetFilePointerEx(HANDLE hFile, LARGE_INTEGER liDistanceToMove,
		PLARGE_INTEGER lpNewFilePointer, DWORD dwMoveMethod);

__SPRT_WIN_IMPORT WINAPI BOOL SetEndOfFile(HANDLE hFile);

__SPRT_WIN_IMPORT WINAPI BOOL FlushFileBuffers(HANDLE hFile);

__SPRT_WIN_IMPORT WINAPI DWORD GetFinalPathNameByHandleW(HANDLE hHandle, LPWSTR lpFilePath,
		DWORD nSize, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL SetFileAttributesW(LPCWSTR lpFileName, DWORD dwFileAttributes);

__SPRT_WIN_IMPORT WINAPI BOOL SetFileAttributesA(LPCSTR lpFileName, DWORD dwFileAttributes);

__SPRT_WIN_IMPORT WINAPI BOOL SetFileInformationByHandle(HANDLE hFile,
		FILE_INFO_BY_HANDLE_CLASS FileInformationClass, LPVOID lpFileInformation,
		DWORD dwBufferSize);

__SPRT_WIN_IMPORT WINAPI BOOL CreateDirectoryW(LPCWSTR lpPathName,
		LPSECURITY_ATTRIBUTES lpSecurityAttributes);

__SPRT_WIN_IMPORT WINAPI DWORD GetTempFileNameW(LPCWSTR lpPathName, LPCWSTR lpTemplateFile,
		UINT uUnique, LPWSTR lpTempFileName);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileInformationByHandleEx(HANDLE hFile,
		FILE_INFO_BY_HANDLE_CLASS FileInformationClass, LPVOID lpFileInformation,
		DWORD dwBufferSize);

__SPRT_WIN_IMPORT WINAPI DWORD GetLogicalDrives();

__SPRT_WIN_IMPORT WINAPI BOOL PathIsRelativeW(LPCWSTR pszPath);

__SPRT_WIN_IMPORT WINAPI DWORD GetCurrentDirectoryW(DWORD nBufferLength, LPWSTR lpBuffer);

__SPRT_WIN_IMPORT WINAPI DWORD SetFilePointer(HANDLE hFile, LONG lDistanceToMove,
		LONG *lpDistanceToMoveHigh, DWORD dwMoveMethod);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileInformationByHandle(HANDLE hFile,
		LPBY_HANDLE_FILE_INFORMATION lpFileInformation);

__SPRT_WIN_IMPORT WINAPI HANDLE ReOpenFile(HANDLE hOriginalFile, DWORD dwDesiredAccess,
		DWORD dwShareMode, DWORD dwFlagsAndAttributes);

__SPRT_WIN_IMPORT WINAPI HANDLE CreateFileMappingW(HANDLE hFile,
		LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh,
		DWORD dwMaximumSizeLow, LPCWSTR lpName);

__SPRT_WIN_IMPORT WINAPI HANDLE CreateFileMappingA(HANDLE hFile,
		LPSECURITY_ATTRIBUTES lpFileMappingAttributes, DWORD flProtect, DWORD dwMaximumSizeHigh,
		DWORD dwMaximumSizeLow, LPCSTR lpName);

__SPRT_WIN_IMPORT WINAPI LPVOID MapViewOfFile(HANDLE hFileMappingObject, DWORD dwDesiredAccess,
		DWORD dwFileOffsetHigh, DWORD dwFileOffsetLow, SIZE_T dwNumberOfBytesToMap);

__SPRT_WIN_IMPORT WINAPI BOOL UnmapViewOfFile(LPCVOID lpBaseAddress);

__SPRT_WIN_IMPORT WINAPI BOOL FlushViewOfFile(LPCVOID lpBaseAddress, SIZE_T dwNumberOfBytesToFlush);

__SPRT_WIN_IMPORT WINAPI BOOL DeleteFileW(LPCWSTR lpFileName);

__SPRT_WIN_IMPORT WINAPI BOOL DeleteFileA(LPCSTR lpFileName);

__SPRT_WIN_IMPORT WINAPI BOOL RemoveDirectoryW(LPCWSTR lpPathName);

__SPRT_WIN_IMPORT WINAPI DWORD GetFileAttributesW(LPCWSTR lpFileName);

__SPRT_WIN_IMPORT WINAPI DWORD GetFileAttributesA(LPCSTR lpFileName);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileAttributesExW(LPCWSTR lpFileName,
		GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileAttributesExA(LPCSTR lpFileName,
		GET_FILEEX_INFO_LEVELS fInfoLevelId, LPVOID lpFileInformation);

__SPRT_WIN_IMPORT WINAPI BOOL MoveFileExW(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName,
		DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL MoveFileExA(LPCSTR lpExistingFileName, LPCSTR lpNewFileName,
		DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL SetCurrentDirectoryW(LPCWSTR lpPathName);

__SPRT_WIN_IMPORT WINAPI BOOL GetVolumeInformationW(LPCWSTR lpRootPathName,
		LPWSTR lpVolumeNameBuffer, DWORD nVolumeNameSize, LPDWORD lpVolumeSerialNumber,
		LPDWORD lpMaximumComponentLength, LPDWORD lpFileSystemFlags, LPWSTR lpFileSystemNameBuffer,
		DWORD nFileSystemNameSize);

__SPRT_WIN_IMPORT WINAPI BOOL GetDiskFreeSpaceExW(LPCWSTR lpDirectoryName,
		PULARGE_INTEGER lpFreeBytesAvailableToCaller, PULARGE_INTEGER lpTotalNumberOfBytes,
		PULARGE_INTEGER lpTotalNumberOfFreeBytes);

__SPRT_WIN_IMPORT WINAPI BOOL CreateHardLinkW(LPCWSTR lpFileName, LPCWSTR lpExistingFileName,
		LPSECURITY_ATTRIBUTES lpSecurityAttributes);

__SPRT_WIN_IMPORT WINAPI BOOLEAN CreateSymbolicLinkW(LPCWSTR lpSymlinkFileName,
		LPCWSTR lpTargetFileName, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL CreatePipe(PHANDLE hReadPipe, PHANDLE hWritePipe,
		LPSECURITY_ATTRIBUTES lpPipeAttributes, DWORD nSize);

__SPRT_WIN_IMPORT WINAPI HANDLE CreateNamedPipeW(LPCWSTR lpName, DWORD dwOpenMode, DWORD dwPipeMode,
		DWORD nMaxInstances, DWORD nOutBufferSize, DWORD nInBufferSize, DWORD nDefaultTimeOut,
		LPSECURITY_ATTRIBUTES lpSecurityAttributes);

__SPRT_WIN_IMPORT WINAPI DWORD GetTempPathW(DWORD nBufferLength, LPWSTR lpBuffer);

__SPRT_WIN_IMPORT WINAPI DWORD GetTempPathA(DWORD nBufferLength, LPSTR lpBuffer);

__SPRT_WIN_IMPORT WINAPI HRESULT PathAllocCanonicalize(PCWSTR pszPathIn, ULONG dwFlags,
		PWSTR *ppszPathOut);

__SPRT_WIN_IMPORT WINAPI BOOL ReadFileScatter(HANDLE hFile, FILE_SEGMENT_ELEMENT aSegmentArray[],
		DWORD nNumberOfBytesToRead, LPDWORD lpReserved, LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI BOOL WriteFileGather(HANDLE hFile, FILE_SEGMENT_ELEMENT aSegmentArray[],
		DWORD nNumberOfBytesToWrite, LPDWORD lpReserved, LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI DWORD GetFileSize(HANDLE hFile, LPDWORD lpFileSizeHigh);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileSizeEx(HANDLE hFile, PLARGE_INTEGER lpFileSize);

__SPRT_WIN_IMPORT WINAPI DWORD GetFileType(HANDLE hFile);

__SPRT_WIN_IMPORT WINAPI BOOL AreFileApisANSI(VOID);

__SPRT_WIN_IMPORT WINAPI BOOL GetDiskFreeSpaceA(LPCSTR lpRootPathName, LPDWORD lpSectorsPerCluster,
		LPDWORD lpBytesPerSector, LPDWORD lpNumberOfFreeClusters, LPDWORD lpTotalNumberOfClusters);

__SPRT_WIN_IMPORT WINAPI BOOL GetDiskFreeSpaceW(LPCWSTR lpRootPathName, LPDWORD lpSectorsPerCluster,
		LPDWORD lpBytesPerSector, LPDWORD lpNumberOfFreeClusters, LPDWORD lpTotalNumberOfClusters);

__SPRT_WIN_IMPORT WINAPI DWORD GetFullPathNameW(LPCWSTR lpFileName, DWORD nBufferLength,
		LPWSTR lpBuffer, LPWSTR *lpFilePart);

__SPRT_WIN_IMPORT WINAPI DWORD GetFullPathNameA(LPCSTR lpFileName, DWORD nBufferLength,
		LPSTR lpBuffer, LPSTR *lpFilePart);

__SPRT_WIN_IMPORT WINAPI BOOL LockFile(HANDLE hFile, DWORD dwFileOffsetLow, DWORD dwFileOffsetHigh,
		DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh);

__SPRT_WIN_IMPORT WINAPI BOOL LockFileEx(HANDLE hFile, DWORD dwFlags, DWORD dwReserved,
		DWORD nNumberOfBytesToLockLow, DWORD nNumberOfBytesToLockHigh, LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI BOOL UnlockFile(HANDLE hFile, DWORD dwFileOffsetLow,
		DWORD dwFileOffsetHigh, DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh);

__SPRT_WIN_IMPORT WINAPI BOOL UnlockFileEx(HANDLE hFile, DWORD dwReserved,
		DWORD nNumberOfBytesToUnlockLow, DWORD nNumberOfBytesToUnlockHigh,
		LPOVERLAPPED lpOverlapped);

__SPRT_WIN_IMPORT WINAPI HANDLE FindFirstFileW(LPCWSTR lpFileName,
		LPWIN32_FIND_DATAW lpFindFileData);

__SPRT_WIN_IMPORT WINAPI HANDLE FindFirstFileA(LPCSTR lpFileName,
		LPWIN32_FIND_DATAW lpFindFileData);

__SPRT_WIN_IMPORT WINAPI BOOL FindNextFileW(HANDLE hFindFile, LPWIN32_FIND_DATAW lpFindFileData);

__SPRT_WIN_IMPORT WINAPI BOOL FindNextFileA(HANDLE hFindFile, LPWIN32_FIND_DATAA lpFindFileData);

__SPRT_WIN_IMPORT WINAPI BOOL FindClose(HANDLE hFindFile);

__SPRT_WIN_IMPORT WINAPI LONG CompareFileTime(const FILETIME *lpFileTime1,
		const FILETIME *lpFileTime2);

__SPRT_WIN_IMPORT WINAPI BOOL GetFileTime(HANDLE hFile, LPFILETIME lpCreationTime,
		LPFILETIME lpLastAccessTime, LPFILETIME lpLastWriteTime);

#ifdef UNICODE
#define CreateFileMapping  CreateFileMappingW
#define CreateFile  CreateFileW
#define FindFirstFile  FindFirstFileW
#define FindNextFile  FindNextFileW
#define MoveFileEx  MoveFileExW

typedef WIN32_FIND_DATAW WIN32_FIND_DATA;
typedef PWIN32_FIND_DATAW PWIN32_FIND_DATA;
typedef LPWIN32_FIND_DATAW LPWIN32_FIND_DATA;

#else

#define CreateFileMapping  CreateFileMappingA
#define CreateFile  CreateFileA

typedef WIN32_FIND_DATAA WIN32_FIND_DATA;
typedef PWIN32_FIND_DATAA PWIN32_FIND_DATA;
typedef LPWIN32_FIND_DATAA LPWIN32_FIND_DATA;

#endif

__SPRT_END_DECL

#endif
