/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_MESSAGE_API_H_
#define SPRT_WRAPPERS_WINDOWS_MESSAGE_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/message_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/message_api.h) */
#define LOWORD(l) __SPRT_LOWORD(l)
#define HIWORD(l) __SPRT_HIWORD(l)
#define GET_X_LPARAM(lp) __SPRT_GET_X_LPARAM(lp)
#define GET_Y_LPARAM(lp) __SPRT_GET_Y_LPARAM(lp)
#define GET_KEYSTATE_WPARAM(wParam) __SPRT_GET_KEYSTATE_WPARAM(wParam)
#define GET_NCHITTEST_WPARAM(wParam) __SPRT_GET_NCHITTEST_WPARAM(wParam)
#define GET_XBUTTON_WPARAM(wParam) __SPRT_GET_XBUTTON_WPARAM(wParam)
#define WM_NULL __SPRT_WM_NULL
#define WM_CREATE __SPRT_WM_CREATE
#define WM_DESTROY __SPRT_WM_DESTROY
#define WM_MOVE __SPRT_WM_MOVE
#define WM_SIZE __SPRT_WM_SIZE
#define WM_ACTIVATE __SPRT_WM_ACTIVATE
#define WM_SETFOCUS __SPRT_WM_SETFOCUS
#define WM_KILLFOCUS __SPRT_WM_KILLFOCUS
#define WM_ENABLE __SPRT_WM_ENABLE
#define WM_SETREDRAW __SPRT_WM_SETREDRAW
#define WM_SETTEXT __SPRT_WM_SETTEXT
#define WM_GETTEXT __SPRT_WM_GETTEXT
#define WM_GETTEXTLENGTH __SPRT_WM_GETTEXTLENGTH
#define WM_PAINT __SPRT_WM_PAINT
#define WM_CLOSE __SPRT_WM_CLOSE
#define WM_QUERYENDSESSION __SPRT_WM_QUERYENDSESSION
#define WM_QUERYOPEN __SPRT_WM_QUERYOPEN
#define WM_ENDSESSION __SPRT_WM_ENDSESSION
#define WM_QUIT __SPRT_WM_QUIT
#define WM_ERASEBKGND __SPRT_WM_ERASEBKGND
#define WM_SYSCOLORCHANGE __SPRT_WM_SYSCOLORCHANGE
#define WM_SHOWWINDOW __SPRT_WM_SHOWWINDOW
#define WM_WININICHANGE __SPRT_WM_WININICHANGE
#define WM_SETTINGCHANGE __SPRT_WM_SETTINGCHANGE
#define WM_DEVMODECHANGE __SPRT_WM_DEVMODECHANGE
#define WM_ACTIVATEAPP __SPRT_WM_ACTIVATEAPP
#define WM_FONTCHANGE __SPRT_WM_FONTCHANGE
#define WM_TIMECHANGE __SPRT_WM_TIMECHANGE
#define WM_CANCELMODE __SPRT_WM_CANCELMODE
#define WM_SETCURSOR __SPRT_WM_SETCURSOR
#define WM_MOUSEACTIVATE __SPRT_WM_MOUSEACTIVATE
#define WM_CHILDACTIVATE __SPRT_WM_CHILDACTIVATE
#define WM_QUEUESYNC __SPRT_WM_QUEUESYNC
#define WM_GETMINMAXINFO __SPRT_WM_GETMINMAXINFO
#define WM_PAINTICON __SPRT_WM_PAINTICON
#define WM_ICONERASEBKGND __SPRT_WM_ICONERASEBKGND
#define WM_NEXTDLGCTL __SPRT_WM_NEXTDLGCTL
#define WM_SPOOLERSTATUS __SPRT_WM_SPOOLERSTATUS
#define WM_DRAWITEM __SPRT_WM_DRAWITEM
#define WM_MEASUREITEM __SPRT_WM_MEASUREITEM
#define WM_DELETEITEM __SPRT_WM_DELETEITEM
#define WM_VKEYTOITEM __SPRT_WM_VKEYTOITEM
#define WM_CHARTOITEM __SPRT_WM_CHARTOITEM
#define WM_SETFONT __SPRT_WM_SETFONT
#define WM_GETFONT __SPRT_WM_GETFONT
#define WM_SETHOTKEY __SPRT_WM_SETHOTKEY
#define WM_GETHOTKEY __SPRT_WM_GETHOTKEY
#define WM_QUERYDRAGICON __SPRT_WM_QUERYDRAGICON
#define WM_COMPAREITEM __SPRT_WM_COMPAREITEM
#define WM_GETOBJECT __SPRT_WM_GETOBJECT
#define WM_COMPACTING __SPRT_WM_COMPACTING
#define WM_COMMNOTIFY __SPRT_WM_COMMNOTIFY
#define WM_WINDOWPOSCHANGING __SPRT_WM_WINDOWPOSCHANGING
#define WM_WINDOWPOSCHANGED __SPRT_WM_WINDOWPOSCHANGED
#define WM_POWER __SPRT_WM_POWER
#define WM_COPYDATA __SPRT_WM_COPYDATA
#define WM_CANCELJOURNAL __SPRT_WM_CANCELJOURNAL
#define WM_NOTIFY __SPRT_WM_NOTIFY
#define WM_INPUTLANGCHANGEREQUEST __SPRT_WM_INPUTLANGCHANGEREQUEST
#define WM_INPUTLANGCHANGE __SPRT_WM_INPUTLANGCHANGE
#define WM_TCARD __SPRT_WM_TCARD
#define WM_HELP __SPRT_WM_HELP
#define WM_USERCHANGED __SPRT_WM_USERCHANGED
#define WM_NOTIFYFORMAT __SPRT_WM_NOTIFYFORMAT
#define WM_CONTEXTMENU __SPRT_WM_CONTEXTMENU
#define WM_STYLECHANGING __SPRT_WM_STYLECHANGING
#define WM_STYLECHANGED __SPRT_WM_STYLECHANGED
#define WM_DISPLAYCHANGE __SPRT_WM_DISPLAYCHANGE
#define WM_GETICON __SPRT_WM_GETICON
#define WM_SETICON __SPRT_WM_SETICON
#define ICON_SMALL __SPRT_ICON_SMALL
#define ICON_BIG __SPRT_ICON_BIG
#define ICON_SMALL2 __SPRT_ICON_SMALL2
#define WM_NCCREATE __SPRT_WM_NCCREATE
#define WM_NCDESTROY __SPRT_WM_NCDESTROY
#define WM_NCCALCSIZE __SPRT_WM_NCCALCSIZE
#define WM_NCHITTEST __SPRT_WM_NCHITTEST
#define WM_NCPAINT __SPRT_WM_NCPAINT
#define WM_NCACTIVATE __SPRT_WM_NCACTIVATE
#define WM_GETDLGCODE __SPRT_WM_GETDLGCODE
#define WM_SYNCPAINT __SPRT_WM_SYNCPAINT
#define WM_NCMOUSEMOVE __SPRT_WM_NCMOUSEMOVE
#define WM_NCLBUTTONDOWN __SPRT_WM_NCLBUTTONDOWN
#define WM_NCLBUTTONUP __SPRT_WM_NCLBUTTONUP
#define WM_NCLBUTTONDBLCLK __SPRT_WM_NCLBUTTONDBLCLK
#define WM_NCRBUTTONDOWN __SPRT_WM_NCRBUTTONDOWN
#define WM_NCRBUTTONUP __SPRT_WM_NCRBUTTONUP
#define WM_NCRBUTTONDBLCLK __SPRT_WM_NCRBUTTONDBLCLK
#define WM_NCMBUTTONDOWN __SPRT_WM_NCMBUTTONDOWN
#define WM_NCMBUTTONUP __SPRT_WM_NCMBUTTONUP
#define WM_NCMBUTTONDBLCLK __SPRT_WM_NCMBUTTONDBLCLK
#define WM_NCXBUTTONDOWN __SPRT_WM_NCXBUTTONDOWN
#define WM_NCXBUTTONUP __SPRT_WM_NCXBUTTONUP
#define WM_NCXBUTTONDBLCLK __SPRT_WM_NCXBUTTONDBLCLK
#define WM_INPUT_DEVICE_CHANGE __SPRT_WM_INPUT_DEVICE_CHANGE
#define WM_INPUT __SPRT_WM_INPUT
#define WM_KEYFIRST __SPRT_WM_KEYFIRST
#define WM_KEYDOWN __SPRT_WM_KEYDOWN
#define WM_KEYUP __SPRT_WM_KEYUP
#define WM_CHAR __SPRT_WM_CHAR
#define WM_DEADCHAR __SPRT_WM_DEADCHAR
#define WM_SYSKEYDOWN __SPRT_WM_SYSKEYDOWN
#define WM_SYSKEYUP __SPRT_WM_SYSKEYUP
#define WM_SYSCHAR __SPRT_WM_SYSCHAR
#define WM_SYSDEADCHAR __SPRT_WM_SYSDEADCHAR
#define WM_UNICHAR __SPRT_WM_UNICHAR
#define WM_KEYLAST __SPRT_WM_KEYLAST
#define UNICODE_NOCHAR __SPRT_UNICODE_NOCHAR
#define WM_IME_STARTCOMPOSITION __SPRT_WM_IME_STARTCOMPOSITION
#define WM_IME_ENDCOMPOSITION __SPRT_WM_IME_ENDCOMPOSITION
#define WM_IME_COMPOSITION __SPRT_WM_IME_COMPOSITION
#define WM_IME_KEYLAST __SPRT_WM_IME_KEYLAST
#define WM_INITDIALOG __SPRT_WM_INITDIALOG
#define WM_COMMAND __SPRT_WM_COMMAND
#define WM_SYSCOMMAND __SPRT_WM_SYSCOMMAND
#define WM_TIMER __SPRT_WM_TIMER
#define WM_HSCROLL __SPRT_WM_HSCROLL
#define WM_VSCROLL __SPRT_WM_VSCROLL
#define WM_INITMENU __SPRT_WM_INITMENU
#define WM_INITMENUPOPUP __SPRT_WM_INITMENUPOPUP
#define WM_GESTURE __SPRT_WM_GESTURE
#define WM_GESTURENOTIFY __SPRT_WM_GESTURENOTIFY
#define WM_MENUSELECT __SPRT_WM_MENUSELECT
#define WM_MENUCHAR __SPRT_WM_MENUCHAR
#define WM_ENTERIDLE __SPRT_WM_ENTERIDLE
#define WM_MENURBUTTONUP __SPRT_WM_MENURBUTTONUP
#define WM_MENUDRAG __SPRT_WM_MENUDRAG
#define WM_MENUGETOBJECT __SPRT_WM_MENUGETOBJECT
#define WM_UNINITMENUPOPUP __SPRT_WM_UNINITMENUPOPUP
#define WM_MENUCOMMAND __SPRT_WM_MENUCOMMAND
#define WM_CHANGEUISTATE __SPRT_WM_CHANGEUISTATE
#define WM_UPDATEUISTATE __SPRT_WM_UPDATEUISTATE
#define WM_QUERYUISTATE __SPRT_WM_QUERYUISTATE
#define WM_CTLCOLORMSGBOX __SPRT_WM_CTLCOLORMSGBOX
#define WM_CTLCOLOREDIT __SPRT_WM_CTLCOLOREDIT
#define WM_CTLCOLORLISTBOX __SPRT_WM_CTLCOLORLISTBOX
#define WM_CTLCOLORBTN __SPRT_WM_CTLCOLORBTN
#define WM_CTLCOLORDLG __SPRT_WM_CTLCOLORDLG
#define WM_CTLCOLORSCROLLBAR __SPRT_WM_CTLCOLORSCROLLBAR
#define WM_CTLCOLORSTATIC __SPRT_WM_CTLCOLORSTATIC
#define MN_GETHMENU __SPRT_MN_GETHMENU
#define WM_MOUSEFIRST __SPRT_WM_MOUSEFIRST
#define WM_MOUSEMOVE __SPRT_WM_MOUSEMOVE
#define WM_LBUTTONDOWN __SPRT_WM_LBUTTONDOWN
#define WM_LBUTTONUP __SPRT_WM_LBUTTONUP
#define WM_LBUTTONDBLCLK __SPRT_WM_LBUTTONDBLCLK
#define WM_RBUTTONDOWN __SPRT_WM_RBUTTONDOWN
#define WM_RBUTTONUP __SPRT_WM_RBUTTONUP
#define WM_RBUTTONDBLCLK __SPRT_WM_RBUTTONDBLCLK
#define WM_MBUTTONDOWN __SPRT_WM_MBUTTONDOWN
#define WM_MBUTTONUP __SPRT_WM_MBUTTONUP
#define WM_MBUTTONDBLCLK __SPRT_WM_MBUTTONDBLCLK
#define WM_MOUSEWHEEL __SPRT_WM_MOUSEWHEEL
#define WM_XBUTTONDOWN __SPRT_WM_XBUTTONDOWN
#define WM_XBUTTONUP __SPRT_WM_XBUTTONUP
#define WM_XBUTTONDBLCLK __SPRT_WM_XBUTTONDBLCLK
#define WM_MOUSEHWHEEL __SPRT_WM_MOUSEHWHEEL
#define WM_MOUSELAST __SPRT_WM_MOUSELAST
#define WM_PARENTNOTIFY __SPRT_WM_PARENTNOTIFY
#define WM_ENTERMENULOOP __SPRT_WM_ENTERMENULOOP
#define WM_EXITMENULOOP __SPRT_WM_EXITMENULOOP
#define WM_NEXTMENU __SPRT_WM_NEXTMENU
#define WM_SIZING __SPRT_WM_SIZING
#define WM_CAPTURECHANGED __SPRT_WM_CAPTURECHANGED
#define WM_MOVING __SPRT_WM_MOVING
#define WM_POWERBROADCAST __SPRT_WM_POWERBROADCAST
#define WM_DEVICECHANGE __SPRT_WM_DEVICECHANGE
#define WM_MDICREATE __SPRT_WM_MDICREATE
#define WM_MDIDESTROY __SPRT_WM_MDIDESTROY
#define WM_MDIACTIVATE __SPRT_WM_MDIACTIVATE
#define WM_MDIRESTORE __SPRT_WM_MDIRESTORE
#define WM_MDINEXT __SPRT_WM_MDINEXT
#define WM_MDIMAXIMIZE __SPRT_WM_MDIMAXIMIZE
#define WM_MDITILE __SPRT_WM_MDITILE
#define WM_MDICASCADE __SPRT_WM_MDICASCADE
#define WM_MDIICONARRANGE __SPRT_WM_MDIICONARRANGE
#define WM_MDIGETACTIVE __SPRT_WM_MDIGETACTIVE
#define WM_MDISETMENU __SPRT_WM_MDISETMENU
#define WM_ENTERSIZEMOVE __SPRT_WM_ENTERSIZEMOVE
#define WM_EXITSIZEMOVE __SPRT_WM_EXITSIZEMOVE
#define WM_DROPFILES __SPRT_WM_DROPFILES
#define WM_MDIREFRESHMENU __SPRT_WM_MDIREFRESHMENU
#define WM_POINTERDEVICECHANGE __SPRT_WM_POINTERDEVICECHANGE
#define WM_POINTERDEVICEINRANGE __SPRT_WM_POINTERDEVICEINRANGE
#define WM_POINTERDEVICEOUTOFRANGE __SPRT_WM_POINTERDEVICEOUTOFRANGE
#define WM_TOUCH __SPRT_WM_TOUCH
#define WM_NCPOINTERUPDATE __SPRT_WM_NCPOINTERUPDATE
#define WM_NCPOINTERDOWN __SPRT_WM_NCPOINTERDOWN
#define WM_NCPOINTERUP __SPRT_WM_NCPOINTERUP
#define WM_POINTERUPDATE __SPRT_WM_POINTERUPDATE
#define WM_POINTERDOWN __SPRT_WM_POINTERDOWN
#define WM_POINTERUP __SPRT_WM_POINTERUP
#define WM_POINTERENTER __SPRT_WM_POINTERENTER
#define WM_POINTERLEAVE __SPRT_WM_POINTERLEAVE
#define WM_POINTERACTIVATE __SPRT_WM_POINTERACTIVATE
#define WM_POINTERCAPTURECHANGED __SPRT_WM_POINTERCAPTURECHANGED
#define WM_TOUCHHITTESTING __SPRT_WM_TOUCHHITTESTING
#define WM_POINTERWHEEL __SPRT_WM_POINTERWHEEL
#define WM_POINTERHWHEEL __SPRT_WM_POINTERHWHEEL
#define DM_POINTERHITTEST __SPRT_DM_POINTERHITTEST
#define WM_POINTERROUTEDTO __SPRT_WM_POINTERROUTEDTO
#define WM_POINTERROUTEDAWAY __SPRT_WM_POINTERROUTEDAWAY
#define WM_POINTERROUTEDRELEASED __SPRT_WM_POINTERROUTEDRELEASED
#define WM_IME_SETCONTEXT __SPRT_WM_IME_SETCONTEXT
#define WM_IME_NOTIFY __SPRT_WM_IME_NOTIFY
#define WM_IME_CONTROL __SPRT_WM_IME_CONTROL
#define WM_IME_COMPOSITIONFULL __SPRT_WM_IME_COMPOSITIONFULL
#define WM_IME_SELECT __SPRT_WM_IME_SELECT
#define WM_IME_CHAR __SPRT_WM_IME_CHAR
#define WM_IME_REQUEST __SPRT_WM_IME_REQUEST
#define WM_IME_KEYDOWN __SPRT_WM_IME_KEYDOWN
#define WM_IME_KEYUP __SPRT_WM_IME_KEYUP
#define WM_MOUSEHOVER __SPRT_WM_MOUSEHOVER
#define WM_MOUSELEAVE __SPRT_WM_MOUSELEAVE
#define WM_NCMOUSEHOVER __SPRT_WM_NCMOUSEHOVER
#define WM_NCMOUSELEAVE __SPRT_WM_NCMOUSELEAVE
#define WM_MOUSEHOVER __SPRT_WM_MOUSEHOVER
#define WM_MOUSELEAVE __SPRT_WM_MOUSELEAVE
#define WM_DPICHANGED __SPRT_WM_DPICHANGED
#define WM_DPICHANGED_BEFOREPARENT __SPRT_WM_DPICHANGED_BEFOREPARENT
#define WM_DPICHANGED_AFTERPARENT __SPRT_WM_DPICHANGED_AFTERPARENT
#define WM_GETDPISCALEDSIZE __SPRT_WM_GETDPISCALEDSIZE
#define WM_DWMCOMPOSITIONCHANGED __SPRT_WM_DWMCOMPOSITIONCHANGED
#define WM_DWMNCRENDERINGCHANGED __SPRT_WM_DWMNCRENDERINGCHANGED
#define WM_DWMCOLORIZATIONCOLORCHANGED __SPRT_WM_DWMCOLORIZATIONCOLORCHANGED
#define WM_DWMWINDOWMAXIMIZEDCHANGE __SPRT_WM_DWMWINDOWMAXIMIZEDCHANGE
#define WA_INACTIVE __SPRT_WA_INACTIVE
#define WA_ACTIVE __SPRT_WA_ACTIVE
#define WA_CLICKACTIVE __SPRT_WA_CLICKACTIVE
#define PBT_APMQUERYSUSPEND __SPRT_PBT_APMQUERYSUSPEND
#define PBT_APMQUERYSTANDBY __SPRT_PBT_APMQUERYSTANDBY
#define PBT_APMQUERYSUSPENDFAILED __SPRT_PBT_APMQUERYSUSPENDFAILED
#define PBT_APMQUERYSTANDBYFAILED __SPRT_PBT_APMQUERYSTANDBYFAILED
#define PBT_APMSUSPEND __SPRT_PBT_APMSUSPEND
#define PBT_APMSTANDBY __SPRT_PBT_APMSTANDBY
#define PBT_APMRESUMECRITICAL __SPRT_PBT_APMRESUMECRITICAL
#define PBT_APMRESUMESUSPEND __SPRT_PBT_APMRESUMESUSPEND
#define PBT_APMRESUMESTANDBY __SPRT_PBT_APMRESUMESTANDBY
#define PBT_APMBATTERYLOW __SPRT_PBT_APMBATTERYLOW
#define PBT_APMPOWERSTATUSCHANGE __SPRT_PBT_APMPOWERSTATUSCHANGE
#define PBT_APMOEMEVENT __SPRT_PBT_APMOEMEVENT
#define PBT_APMRESUMEAUTOMATIC __SPRT_PBT_APMRESUMEAUTOMATIC
#define PBT_POWERSETTINGCHANGE __SPRT_PBT_POWERSETTINGCHANGE
#define SM_CXSCREEN __SPRT_SM_CXSCREEN
#define SM_CYSCREEN __SPRT_SM_CYSCREEN
#define SM_CXVSCROLL __SPRT_SM_CXVSCROLL
#define SM_CYHSCROLL __SPRT_SM_CYHSCROLL
#define SM_CYCAPTION __SPRT_SM_CYCAPTION
#define SM_CXBORDER __SPRT_SM_CXBORDER
#define SM_CYBORDER __SPRT_SM_CYBORDER
#define SM_CXDLGFRAME __SPRT_SM_CXDLGFRAME
#define SM_CYDLGFRAME __SPRT_SM_CYDLGFRAME
#define SM_CYVTHUMB __SPRT_SM_CYVTHUMB
#define SM_CXHTHUMB __SPRT_SM_CXHTHUMB
#define SM_CXICON __SPRT_SM_CXICON
#define SM_CYICON __SPRT_SM_CYICON
#define SM_CXCURSOR __SPRT_SM_CXCURSOR
#define SM_CYCURSOR __SPRT_SM_CYCURSOR
#define SM_CYMENU __SPRT_SM_CYMENU
#define SM_CXFULLSCREEN __SPRT_SM_CXFULLSCREEN
#define SM_CYFULLSCREEN __SPRT_SM_CYFULLSCREEN
#define SM_CYKANJIWINDOW __SPRT_SM_CYKANJIWINDOW
#define SM_MOUSEPRESENT __SPRT_SM_MOUSEPRESENT
#define SM_CYVSCROLL __SPRT_SM_CYVSCROLL
#define SM_CXHSCROLL __SPRT_SM_CXHSCROLL
#define SM_DEBUG __SPRT_SM_DEBUG
#define SM_SWAPBUTTON __SPRT_SM_SWAPBUTTON
#define SM_RESERVED1 __SPRT_SM_RESERVED1
#define SM_RESERVED2 __SPRT_SM_RESERVED2
#define SM_RESERVED3 __SPRT_SM_RESERVED3
#define SM_RESERVED4 __SPRT_SM_RESERVED4
#define SM_CXMIN __SPRT_SM_CXMIN
#define SM_CYMIN __SPRT_SM_CYMIN
#define SM_CXSIZE __SPRT_SM_CXSIZE
#define SM_CYSIZE __SPRT_SM_CYSIZE
#define SM_CXFRAME __SPRT_SM_CXFRAME
#define SM_CYFRAME __SPRT_SM_CYFRAME
#define SM_CXMINTRACK __SPRT_SM_CXMINTRACK
#define SM_CYMINTRACK __SPRT_SM_CYMINTRACK
#define SM_CXDOUBLECLK __SPRT_SM_CXDOUBLECLK
#define SM_CYDOUBLECLK __SPRT_SM_CYDOUBLECLK
#define SM_CXICONSPACING __SPRT_SM_CXICONSPACING
#define SM_CYICONSPACING __SPRT_SM_CYICONSPACING
#define SM_MENUDROPALIGNMENT __SPRT_SM_MENUDROPALIGNMENT
#define SM_PENWINDOWS __SPRT_SM_PENWINDOWS
#define SM_DBCSENABLED __SPRT_SM_DBCSENABLED
#define SM_CMOUSEBUTTONS __SPRT_SM_CMOUSEBUTTONS
#define SM_CXFIXEDFRAME __SPRT_SM_CXFIXEDFRAME
#define SM_CYFIXEDFRAME __SPRT_SM_CYFIXEDFRAME
#define SM_CXSIZEFRAME __SPRT_SM_CXSIZEFRAME
#define SM_CYSIZEFRAME __SPRT_SM_CYSIZEFRAME
#define SM_SECURE __SPRT_SM_SECURE
#define SM_CXEDGE __SPRT_SM_CXEDGE
#define SM_CYEDGE __SPRT_SM_CYEDGE
#define SM_CXMINSPACING __SPRT_SM_CXMINSPACING
#define SM_CYMINSPACING __SPRT_SM_CYMINSPACING
#define SM_CXSMICON __SPRT_SM_CXSMICON
#define SM_CYSMICON __SPRT_SM_CYSMICON
#define SM_CYSMCAPTION __SPRT_SM_CYSMCAPTION
#define SM_CXSMSIZE __SPRT_SM_CXSMSIZE
#define SM_CYSMSIZE __SPRT_SM_CYSMSIZE
#define SM_CXMENUSIZE __SPRT_SM_CXMENUSIZE
#define SM_CYMENUSIZE __SPRT_SM_CYMENUSIZE
#define SM_ARRANGE __SPRT_SM_ARRANGE
#define SM_CXMINIMIZED __SPRT_SM_CXMINIMIZED
#define SM_CYMINIMIZED __SPRT_SM_CYMINIMIZED
#define SM_CXMAXTRACK __SPRT_SM_CXMAXTRACK
#define SM_CYMAXTRACK __SPRT_SM_CYMAXTRACK
#define SM_CXMAXIMIZED __SPRT_SM_CXMAXIMIZED
#define SM_CYMAXIMIZED __SPRT_SM_CYMAXIMIZED
#define SM_NETWORK __SPRT_SM_NETWORK
#define SM_CLEANBOOT __SPRT_SM_CLEANBOOT
#define SM_CXDRAG __SPRT_SM_CXDRAG
#define SM_CYDRAG __SPRT_SM_CYDRAG
#define SM_SHOWSOUNDS __SPRT_SM_SHOWSOUNDS
#define SM_CXMENUCHECK __SPRT_SM_CXMENUCHECK
#define SM_CYMENUCHECK __SPRT_SM_CYMENUCHECK
#define SM_SLOWMACHINE __SPRT_SM_SLOWMACHINE
#define SM_MIDEASTENABLED __SPRT_SM_MIDEASTENABLED
#define SM_MOUSEWHEELPRESENT __SPRT_SM_MOUSEWHEELPRESENT
#define SM_XVIRTUALSCREEN __SPRT_SM_XVIRTUALSCREEN
#define SM_YVIRTUALSCREEN __SPRT_SM_YVIRTUALSCREEN
#define SM_CXVIRTUALSCREEN __SPRT_SM_CXVIRTUALSCREEN
#define SM_CYVIRTUALSCREEN __SPRT_SM_CYVIRTUALSCREEN
#define SM_CMONITORS __SPRT_SM_CMONITORS
#define SM_SAMEDISPLAYFORMAT __SPRT_SM_SAMEDISPLAYFORMAT
#define SM_IMMENABLED __SPRT_SM_IMMENABLED
#define SM_CXFOCUSBORDER __SPRT_SM_CXFOCUSBORDER
#define SM_CYFOCUSBORDER __SPRT_SM_CYFOCUSBORDER
#define SM_TABLETPC __SPRT_SM_TABLETPC
#define SM_MEDIACENTER __SPRT_SM_MEDIACENTER
#define SM_STARTER __SPRT_SM_STARTER
#define SM_SERVERR2 __SPRT_SM_SERVERR2
#define SM_MOUSEHORIZONTALWHEELPRESENT __SPRT_SM_MOUSEHORIZONTALWHEELPRESENT
#define SM_CXPADDEDBORDER __SPRT_SM_CXPADDEDBORDER
#define SM_DIGITIZER __SPRT_SM_DIGITIZER
#define SM_MAXIMUMTOUCHES __SPRT_SM_MAXIMUMTOUCHES
#define SM_CMETRICS __SPRT_SM_CMETRICS
#define PM_NOREMOVE __SPRT_PM_NOREMOVE
#define PM_REMOVE __SPRT_PM_REMOVE
#define PM_NOYIELD __SPRT_PM_NOYIELD
#define IMN_CLOSESTATUSWINDOW __SPRT_IMN_CLOSESTATUSWINDOW
#define IMN_OPENSTATUSWINDOW __SPRT_IMN_OPENSTATUSWINDOW
#define IMN_CHANGECANDIDATE __SPRT_IMN_CHANGECANDIDATE
#define IMN_CLOSECANDIDATE __SPRT_IMN_CLOSECANDIDATE
#define IMN_OPENCANDIDATE __SPRT_IMN_OPENCANDIDATE
#define IMN_SETCONVERSIONMODE __SPRT_IMN_SETCONVERSIONMODE
#define IMN_SETSENTENCEMODE __SPRT_IMN_SETSENTENCEMODE
#define IMN_SETOPENSTATUS __SPRT_IMN_SETOPENSTATUS
#define IMN_SETCANDIDATEPOS __SPRT_IMN_SETCANDIDATEPOS
#define IMN_SETCOMPOSITIONFONT __SPRT_IMN_SETCOMPOSITIONFONT
#define IMN_SETCOMPOSITIONWINDOW __SPRT_IMN_SETCOMPOSITIONWINDOW
#define IMN_SETSTATUSWINDOWPOS __SPRT_IMN_SETSTATUSWINDOWPOS
#define IMN_GUIDELINE __SPRT_IMN_GUIDELINE
#define IMN_PRIVATE __SPRT_IMN_PRIVATE
#define IMR_COMPOSITIONWINDOW __SPRT_IMR_COMPOSITIONWINDOW
#define IMR_CANDIDATEWINDOW __SPRT_IMR_CANDIDATEWINDOW
#define IMR_COMPOSITIONFONT __SPRT_IMR_COMPOSITIONFONT
#define IMR_RECONVERTSTRING __SPRT_IMR_RECONVERTSTRING
#define IMR_CONFIRMRECONVERTSTRING __SPRT_IMR_CONFIRMRECONVERTSTRING
#define IMR_QUERYCHARPOSITION __SPRT_IMR_QUERYCHARPOSITION
#define IMR_DOCUMENTFEED __SPRT_IMR_DOCUMENTFEED
#define FORMAT_MESSAGE_ALLOCATE_BUFFER __SPRT_FORMAT_MESSAGE_ALLOCATE_BUFFER
#define FORMAT_MESSAGE_IGNORE_INSERTS __SPRT_FORMAT_MESSAGE_IGNORE_INSERTS
#define FORMAT_MESSAGE_FROM_STRING __SPRT_FORMAT_MESSAGE_FROM_STRING
#define FORMAT_MESSAGE_FROM_HMODULE __SPRT_FORMAT_MESSAGE_FROM_HMODULE
#define FORMAT_MESSAGE_FROM_SYSTEM __SPRT_FORMAT_MESSAGE_FROM_SYSTEM
#define FORMAT_MESSAGE_ARGUMENT_ARRAY __SPRT_FORMAT_MESSAGE_ARGUMENT_ARRAY
#define FORMAT_MESSAGE_MAX_WIDTH_MASK __SPRT_FORMAT_MESSAGE_MAX_WIDTH_MASK
#define LANG_NEUTRAL __SPRT_LANG_NEUTRAL
#define SUBLANG_NEUTRAL __SPRT_SUBLANG_NEUTRAL
#define SUBLANG_DEFAULT __SPRT_SUBLANG_DEFAULT
#define LANG_ENGLISH __SPRT_LANG_ENGLISH
#define SUBLANG_ENGLISH_US __SPRT_SUBLANG_ENGLISH_US
#define MAKELANGID(p, s) __SPRT_MAKELANGID(p, s)
#define MUI_LANGUAGE_ID __SPRT_MUI_LANGUAGE_ID
#define MUI_LANGUAGE_NAME __SPRT_MUI_LANGUAGE_NAME
#define MWMO_WAITALL __SPRT_MWMO_WAITALL
#define MWMO_ALERTABLE __SPRT_MWMO_ALERTABLE
#define MWMO_INPUTAVAILABLE __SPRT_MWMO_INPUTAVAILABLE
#define QS_KEY __SPRT_QS_KEY
#define QS_MOUSEMOVE __SPRT_QS_MOUSEMOVE
#define QS_MOUSEBUTTON __SPRT_QS_MOUSEBUTTON
#define QS_POSTMESSAGE __SPRT_QS_POSTMESSAGE
#define QS_TIMER __SPRT_QS_TIMER
#define QS_PAINT __SPRT_QS_PAINT
#define QS_SENDMESSAGE __SPRT_QS_SENDMESSAGE
#define QS_HOTKEY __SPRT_QS_HOTKEY
#define QS_ALLPOSTMESSAGE __SPRT_QS_ALLPOSTMESSAGE
#define QS_RAWINPUT __SPRT_QS_RAWINPUT
#define QS_TOUCH __SPRT_QS_TOUCH
#define QS_POINTER __SPRT_QS_POINTER
#define QS_MOUSE __SPRT_QS_MOUSE
#define QS_INPUT __SPRT_QS_INPUT
#define QS_ALLEVENTS __SPRT_QS_ALLEVENTS
#define QS_ALLINPUT __SPRT_QS_ALLINPUT


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI DWORD FormatMessageW(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId,
		DWORD dwLanguageId, LPWSTR lpBuffer, DWORD nSize, __builtin_va_list *Arguments);

__SPRT_WIN_IMPORT WINAPI DWORD FormatMessageA(DWORD dwFlags, LPCVOID lpSource, DWORD dwMessageId,
		DWORD dwLanguageId, LPSTR lpBuffer, DWORD nSize, __builtin_va_list *Arguments);

/* Companion to FormatMessage*: the language list it should be asked to render
   a message in. dwFlags selects MUI_LANGUAGE_ID or MUI_LANGUAGE_NAME, and
   pwszLanguagesBuffer receives a double-null-terminated list. */
__SPRT_WIN_IMPORT WINAPI BOOL GetUserPreferredUILanguages(DWORD dwFlags, PULONG pulNumLanguages,
		PZZWSTR pwszLanguagesBuffer, PULONG pcchLanguagesBuffer);

__SPRT_WIN_IMPORT WINAPI LRESULT SendMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);

__SPRT_WIN_IMPORT WINAPI BOOL PostMessageW(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);

__SPRT_WIN_IMPORT WINAPI VOID PostQuitMessage(int nExitCode);

__SPRT_WIN_IMPORT WINAPI BOOL PeekMessageW(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin,
		UINT wMsgFilterMax, UINT wRemoveMsg);

__SPRT_WIN_IMPORT WINAPI BOOL TranslateMessage(const MSG *lpMsg);

__SPRT_WIN_IMPORT WINAPI LRESULT DispatchMessageW(const MSG *lpMsg);

__SPRT_WIN_IMPORT WINAPI LONG GetMessageTime(VOID);

__SPRT_WIN_IMPORT WINAPI DWORD MsgWaitForMultipleObjectsEx(DWORD nCount, const HANDLE *pHandles,
		DWORD dwMilliseconds, DWORD dwWakeMask, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI BOOL GetSystemPowerStatus(LPSYSTEM_POWER_STATUS lpSystemPowerStatus);

__SPRT_WIN_IMPORT WINAPI HRESULT GetCurrentThemeName(LPWSTR pszThemeFileName, int cchMaxNameChars,
		LPWSTR pszColorBuff, int cchMaxColorChars, LPWSTR pszSizeBuff, int cchMaxSizeChars);

__SPRT_WIN_IMPORT WINAPI int GetSystemMetrics(int nIndex);

__SPRT_WIN_IMPORT WINAPI BOOL SystemParametersInfoW(UINT uiAction, UINT uiParam, PVOID pvParam,
		UINT fWinIni);

__SPRT_WIN_IMPORT WINAPI HANDLE GetStockObject(int i);

__SPRT_WIN_IMPORT WINAPI int GetObjectW(HANDLE h, int c, LPVOID pv);

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_MESSAGE_API_H_
