/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_MONITOR_API_H_
#define SPRT_WRAPPERS_WINDOWS_MONITOR_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/monitor_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/monitor_api.h) */
#define DPI_AWARENESS_CONTEXT_UNAWARE __SPRT_DPI_AWARENESS_CONTEXT_UNAWARE
#define DPI_AWARENESS_CONTEXT_SYSTEM_AWARE __SPRT_DPI_AWARENESS_CONTEXT_SYSTEM_AWARE
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE __SPRT_DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE
#define DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2 __SPRT_DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2
#define DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED __SPRT_DPI_AWARENESS_CONTEXT_UNAWARE_GDISCALED
#define MONITOR_DEFAULTTONULL __SPRT_MONITOR_DEFAULTTONULL
#define MONITOR_DEFAULTTOPRIMARY __SPRT_MONITOR_DEFAULTTOPRIMARY
#define MONITOR_DEFAULTTONEAREST __SPRT_MONITOR_DEFAULTTONEAREST
#define MONITORINFOF_PRIMARY __SPRT_MONITORINFOF_PRIMARY
#define PHYSICAL_MONITOR_DESCRIPTION_SIZE __SPRT_PHYSICAL_MONITOR_DESCRIPTION_SIZE
#define CCHFORMNAME __SPRT_CCHFORMNAME
#define CCHDEVICENAME __SPRT_CCHDEVICENAME
#define USER_DEFAULT_SCREEN_DPI __SPRT_USER_DEFAULT_SCREEN_DPI
#define EDD_GET_DEVICE_INTERFACE_NAME __SPRT_EDD_GET_DEVICE_INTERFACE_NAME
#define DISPLAY_DEVICE_ACTIVE __SPRT_DISPLAY_DEVICE_ACTIVE
#define DISPLAY_DEVICE_ATTACHED __SPRT_DISPLAY_DEVICE_ATTACHED
#define DRIVERVERSION __SPRT_DRIVERVERSION
#define TECHNOLOGY __SPRT_TECHNOLOGY
#define HORZSIZE __SPRT_HORZSIZE
#define VERTSIZE __SPRT_VERTSIZE
#define HORZRES __SPRT_HORZRES
#define VERTRES __SPRT_VERTRES
#define BITSPIXEL __SPRT_BITSPIXEL
#define PLANES __SPRT_PLANES
#define NUMBRUSHES __SPRT_NUMBRUSHES
#define NUMPENS __SPRT_NUMPENS
#define NUMMARKERS __SPRT_NUMMARKERS
#define NUMFONTS __SPRT_NUMFONTS
#define NUMCOLORS __SPRT_NUMCOLORS
#define PDEVICESIZE __SPRT_PDEVICESIZE
#define CURVECAPS __SPRT_CURVECAPS
#define LINECAPS __SPRT_LINECAPS
#define POLYGONALCAPS __SPRT_POLYGONALCAPS
#define TEXTCAPS __SPRT_TEXTCAPS
#define CLIPCAPS __SPRT_CLIPCAPS
#define RASTERCAPS __SPRT_RASTERCAPS
#define ASPECTX __SPRT_ASPECTX
#define ASPECTY __SPRT_ASPECTY
#define ASPECTXY __SPRT_ASPECTXY
#define LOGPIXELSX __SPRT_LOGPIXELSX
#define LOGPIXELSY __SPRT_LOGPIXELSY
#define SIZEPALETTE __SPRT_SIZEPALETTE
#define NUMRESERVED __SPRT_NUMRESERVED
#define COLORRES __SPRT_COLORRES
#define PHYSICALWIDTH __SPRT_PHYSICALWIDTH
#define PHYSICALHEIGHT __SPRT_PHYSICALHEIGHT
#define PHYSICALOFFSETX __SPRT_PHYSICALOFFSETX
#define PHYSICALOFFSETY __SPRT_PHYSICALOFFSETY
#define SCALINGFACTORX __SPRT_SCALINGFACTORX
#define SCALINGFACTORY __SPRT_SCALINGFACTORY
#define VREFRESH __SPRT_VREFRESH
#define DESKTOPVERTRES __SPRT_DESKTOPVERTRES
#define DESKTOPHORZRES __SPRT_DESKTOPHORZRES
#define BLTALIGNMENT __SPRT_BLTALIGNMENT
#define SHADEBLENDCAPS __SPRT_SHADEBLENDCAPS
#define COLORMGMTCAPS __SPRT_COLORMGMTCAPS
#define ENUM_CURRENT_SETTINGS __SPRT_ENUM_CURRENT_SETTINGS
#define ENUM_REGISTRY_SETTINGS __SPRT_ENUM_REGISTRY_SETTINGS
#define SM_XVIRTUALSCREEN __SPRT_SM_XVIRTUALSCREEN
#define SM_YVIRTUALSCREEN __SPRT_SM_YVIRTUALSCREEN
#define SM_CXVIRTUALSCREEN __SPRT_SM_CXVIRTUALSCREEN
#define SM_CYVIRTUALSCREEN __SPRT_SM_CYVIRTUALSCREEN
#define SM_CMONITORS __SPRT_SM_CMONITORS
#define SM_SAMEDISPLAYFORMAT __SPRT_SM_SAMEDISPLAYFORMAT
#define DM_ORIENTATION __SPRT_DM_ORIENTATION
#define DM_PAPERSIZE __SPRT_DM_PAPERSIZE
#define DM_PAPERLENGTH __SPRT_DM_PAPERLENGTH
#define DM_PAPERWIDTH __SPRT_DM_PAPERWIDTH
#define DM_SCALE __SPRT_DM_SCALE
#define DM_POSITION __SPRT_DM_POSITION
#define DM_NUP __SPRT_DM_NUP
#define DM_DISPLAYORIENTATION __SPRT_DM_DISPLAYORIENTATION
#define DM_COPIES __SPRT_DM_COPIES
#define DM_DEFAULTSOURCE __SPRT_DM_DEFAULTSOURCE
#define DM_PRINTQUALITY __SPRT_DM_PRINTQUALITY
#define DM_COLOR __SPRT_DM_COLOR
#define DM_DUPLEX __SPRT_DM_DUPLEX
#define DM_YRESOLUTION __SPRT_DM_YRESOLUTION
#define DM_TTOPTION __SPRT_DM_TTOPTION
#define DM_COLLATE __SPRT_DM_COLLATE
#define DM_FORMNAME __SPRT_DM_FORMNAME
#define DM_LOGPIXELS __SPRT_DM_LOGPIXELS
#define DM_BITSPERPEL __SPRT_DM_BITSPERPEL
#define DM_PELSWIDTH __SPRT_DM_PELSWIDTH
#define DM_PELSHEIGHT __SPRT_DM_PELSHEIGHT
#define DM_DISPLAYFLAGS __SPRT_DM_DISPLAYFLAGS
#define DM_DISPLAYFREQUENCY __SPRT_DM_DISPLAYFREQUENCY
#define DM_ICMMETHOD __SPRT_DM_ICMMETHOD
#define DM_ICMINTENT __SPRT_DM_ICMINTENT
#define DM_MEDIATYPE __SPRT_DM_MEDIATYPE
#define DM_DITHERTYPE __SPRT_DM_DITHERTYPE
#define DM_PANNINGWIDTH __SPRT_DM_PANNINGWIDTH
#define DM_PANNINGHEIGHT __SPRT_DM_PANNINGHEIGHT
#define DM_DISPLAYFIXEDOUTPUT __SPRT_DM_DISPLAYFIXEDOUTPUT
#define DIREG_DEV __SPRT_DIREG_DEV
#define DIREG_DRV __SPRT_DIREG_DRV
#define DIREG_BOTH __SPRT_DIREG_BOTH
#define DICS_FLAG_GLOBAL __SPRT_DICS_FLAG_GLOBAL
#define DICS_FLAG_CONFIGSPECIFIC __SPRT_DICS_FLAG_CONFIGSPECIFIC
#define DICS_FLAG_CONFIGGENERAL __SPRT_DICS_FLAG_CONFIGGENERAL
#define DIGCF_DEFAULT __SPRT_DIGCF_DEFAULT
#define DIGCF_PRESENT __SPRT_DIGCF_PRESENT
#define DIGCF_ALLCLASSES __SPRT_DIGCF_ALLCLASSES
#define DIGCF_PROFILE __SPRT_DIGCF_PROFILE
#define DIGCF_DEVICEINTERFACE __SPRT_DIGCF_DEVICEINTERFACE
#define CDS_UPDATEREGISTRY __SPRT_CDS_UPDATEREGISTRY
#define CDS_TEST __SPRT_CDS_TEST
#define CDS_FULLSCREEN __SPRT_CDS_FULLSCREEN
#define CDS_GLOBAL __SPRT_CDS_GLOBAL
#define CDS_SET_PRIMARY __SPRT_CDS_SET_PRIMARY
#define CDS_VIDEOPARAMETERS __SPRT_CDS_VIDEOPARAMETERS
#define CDS_RESET __SPRT_CDS_RESET
#define CDS_RESET_EX __SPRT_CDS_RESET_EX
#define CDS_NORESET __SPRT_CDS_NORESET
#define DISP_CHANGE_SUCCESSFUL __SPRT_DISP_CHANGE_SUCCESSFUL
#define DISP_CHANGE_RESTART __SPRT_DISP_CHANGE_RESTART
#define DISP_CHANGE_FAILED __SPRT_DISP_CHANGE_FAILED
#define DISP_CHANGE_BADMODE __SPRT_DISP_CHANGE_BADMODE
#define DISP_CHANGE_NOTUPDATED __SPRT_DISP_CHANGE_NOTUPDATED
#define DISP_CHANGE_BADFLAGS __SPRT_DISP_CHANGE_BADFLAGS
#define DISP_CHANGE_BADPARAM __SPRT_DISP_CHANGE_BADPARAM
#define DISP_CHANGE_BADDUALVIEW __SPRT_DISP_CHANGE_BADDUALVIEW


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI BOOL GetMonitorInfoW(HMONITOR hMonitor, LPMONITORINFO lpmi);

__SPRT_WIN_IMPORT WINAPI BOOL GetNumberOfPhysicalMonitorsFromHMONITOR(HMONITOR hMonitor,
		LPDWORD pdwNumberOfPhysicalMonitors);

__SPRT_WIN_IMPORT WINAPI BOOL GetPhysicalMonitorsFromHMONITOR(HMONITOR hMonitor,
		DWORD dwPhysicalMonitorArraySize, LPPHYSICAL_MONITOR pPhysicalMonitorArray);

__SPRT_WIN_IMPORT WINAPI HRESULT SetProcessDpiAwareness(PROCESS_DPI_AWARENESS value);

__SPRT_WIN_IMPORT WINAPI HRESULT GetProcessDpiAwareness(HANDLE hprocess,
		PROCESS_DPI_AWARENESS *value);

__SPRT_WIN_IMPORT WINAPI HRESULT GetDpiForMonitor(HMONITOR hmonitor, MONITOR_DPI_TYPE dpiType,
		UINT *dpiX, UINT *dpiY);

__SPRT_WIN_IMPORT WINAPI BOOL EnumDisplayDevicesW(LPCWSTR lpDevice, DWORD iDevNum,
		PDISPLAY_DEVICEW lpDisplayDevice, DWORD dwFlags);

__SPRT_WIN_IMPORT WINAPI HDC CreateDCW(LPCWSTR pwszDriver, LPCWSTR pwszDevice, LPCWSTR pszPort,
		const DEVMODEW *pdm);

__SPRT_WIN_IMPORT WINAPI int GetDeviceCaps(HDC hdc, int index);

__SPRT_WIN_IMPORT WINAPI BOOL EnumDisplayMonitors(HDC hdc, LPCRECT lprcClip,
		MONITORENUMPROC lpfnEnum, LPARAM dwData);

__SPRT_WIN_IMPORT WINAPI BOOL DeleteDC(HDC hdc);

__SPRT_WIN_IMPORT WINAPI BOOL EnumDisplaySettingsW(LPCWSTR lpszDeviceName, DWORD iModeNum,
		DEVMODEW *lpDevMode);

__SPRT_WIN_IMPORT WINAPI LONG ChangeDisplaySettingsExW(LPCWSTR lpszDeviceName, DEVMODEW *lpDevMode,
		HWND hwnd, DWORD dwflags, LPVOID lParam);

__SPRT_WIN_IMPORT WINAPI BOOL DestroyPhysicalMonitor(HANDLE hMonitor);

__SPRT_WIN_IMPORT WINAPI BOOL DestroyPhysicalMonitors(DWORD dwPhysicalMonitorArraySize,
		LPPHYSICAL_MONITOR pPhysicalMonitorArray);

__SPRT_WIN_IMPORT WINAPI BOOL SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT value);

__SPRT_WIN_IMPORT WINAPI int GetSystemMetricsForDpi(int nIndex, UINT dpi);

__SPRT_WIN_IMPORT WINAPI HKEY SetupDiOpenDevRegKey(HDEVINFO DeviceInfoSet,
		PSP_DEVINFO_DATA DeviceInfoData, DWORD Scope, DWORD HwProfile, DWORD KeyType,
		REGSAM samDesired);

__SPRT_WIN_IMPORT WINAPI HDEVINFO SetupDiGetClassDevsExW(const GUID *ClassGuid, PCWSTR Enumerator,
		HWND hwndParent, DWORD Flags, HDEVINFO DeviceInfoSet, PCWSTR MachineName, PVOID Reserved);

__SPRT_WIN_IMPORT WINAPI BOOL SetupDiEnumDeviceInterfaces(HDEVINFO DeviceInfoSet,
		PSP_DEVINFO_DATA DeviceInfoData, const GUID *InterfaceClassGuid, DWORD MemberIndex,
		PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);

__SPRT_WIN_IMPORT WINAPI BOOL SetupDiGetDeviceInterfaceDetailW(HDEVINFO DeviceInfoSet,
		PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData,
		PSP_DEVICE_INTERFACE_DETAIL_DATA_W DeviceInterfaceDetailData,
		DWORD DeviceInterfaceDetailDataSize, PDWORD RequiredSize, PSP_DEVINFO_DATA DeviceInfoData);

__SPRT_WIN_IMPORT WINAPI BOOL SetupDiDestroyDeviceInfoList(HDEVINFO DeviceInfoSet);

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_MONITOR_API_H_
