/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_PROCESS_API_H_
#define SPRT_WRAPPERS_WINDOWS_PROCESS_API_H_

#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/abi/process_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/process_api.h) */
#define PROCESS_TERMINATE __SPRT_PROCESS_TERMINATE
#define PROCESS_CREATE_THREAD __SPRT_PROCESS_CREATE_THREAD
#define PROCESS_SET_SESSIONID __SPRT_PROCESS_SET_SESSIONID
#define PROCESS_VM_OPERATION __SPRT_PROCESS_VM_OPERATION
#define PROCESS_VM_READ __SPRT_PROCESS_VM_READ
#define PROCESS_VM_WRITE __SPRT_PROCESS_VM_WRITE
#define PROCESS_DUP_HANDLE __SPRT_PROCESS_DUP_HANDLE
#define PROCESS_CREATE_PROCESS __SPRT_PROCESS_CREATE_PROCESS
#define PROCESS_SET_QUOTA __SPRT_PROCESS_SET_QUOTA
#define PROCESS_SET_INFORMATION __SPRT_PROCESS_SET_INFORMATION
#define PROCESS_QUERY_INFORMATION __SPRT_PROCESS_QUERY_INFORMATION
#define PROCESS_SUSPEND_RESUME __SPRT_PROCESS_SUSPEND_RESUME
#define PROCESS_QUERY_LIMITED_INFORMATION __SPRT_PROCESS_QUERY_LIMITED_INFORMATION
#define PROCESS_SET_LIMITED_INFORMATION __SPRT_PROCESS_SET_LIMITED_INFORMATION
#define NORMAL_PRIORITY_CLASS __SPRT_NORMAL_PRIORITY_CLASS
#define IDLE_PRIORITY_CLASS __SPRT_IDLE_PRIORITY_CLASS
#define HIGH_PRIORITY_CLASS __SPRT_HIGH_PRIORITY_CLASS
#define REALTIME_PRIORITY_CLASS __SPRT_REALTIME_PRIORITY_CLASS
#define BELOW_NORMAL_PRIORITY_CLASS __SPRT_BELOW_NORMAL_PRIORITY_CLASS
#define ABOVE_NORMAL_PRIORITY_CLASS __SPRT_ABOVE_NORMAL_PRIORITY_CLASS
#define EXTENDED_STARTUPINFO_PRESENT __SPRT_EXTENDED_STARTUPINFO_PRESENT
#define PROC_THREAD_ATTRIBUTE_NUMBER __SPRT_PROC_THREAD_ATTRIBUTE_NUMBER
#define PROC_THREAD_ATTRIBUTE_THREAD __SPRT_PROC_THREAD_ATTRIBUTE_THREAD
#define PROC_THREAD_ATTRIBUTE_INPUT __SPRT_PROC_THREAD_ATTRIBUTE_INPUT
#define PROC_THREAD_ATTRIBUTE_ADDITIVE __SPRT_PROC_THREAD_ATTRIBUTE_ADDITIVE
#define STARTF_USESHOWWINDOW __SPRT_STARTF_USESHOWWINDOW
#define STARTF_USESIZE __SPRT_STARTF_USESIZE
#define STARTF_USEPOSITION __SPRT_STARTF_USEPOSITION
#define STARTF_USECOUNTCHARS __SPRT_STARTF_USECOUNTCHARS
#define STARTF_USEFILLATTRIBUTE __SPRT_STARTF_USEFILLATTRIBUTE
#define STARTF_RUNFULLSCREEN __SPRT_STARTF_RUNFULLSCREEN
#define STARTF_FORCEONFEEDBACK __SPRT_STARTF_FORCEONFEEDBACK
#define STARTF_FORCEOFFFEEDBACK __SPRT_STARTF_FORCEOFFFEEDBACK
#define STARTF_USESTDHANDLES __SPRT_STARTF_USESTDHANDLES
#define DEBUG_PROCESS __SPRT_DEBUG_PROCESS
#define DEBUG_ONLY_THIS_PROCESS __SPRT_DEBUG_ONLY_THIS_PROCESS
#define CREATE_SUSPENDED __SPRT_CREATE_SUSPENDED
#define DETACHED_PROCESS __SPRT_DETACHED_PROCESS
#define CREATE_NEW_CONSOLE __SPRT_CREATE_NEW_CONSOLE
#define NORMAL_PRIORITY_CLASS __SPRT_NORMAL_PRIORITY_CLASS
#define IDLE_PRIORITY_CLASS __SPRT_IDLE_PRIORITY_CLASS
#define HIGH_PRIORITY_CLASS __SPRT_HIGH_PRIORITY_CLASS
#define REALTIME_PRIORITY_CLASS __SPRT_REALTIME_PRIORITY_CLASS
#define CREATE_NEW_PROCESS_GROUP __SPRT_CREATE_NEW_PROCESS_GROUP
#define CREATE_UNICODE_ENVIRONMENT __SPRT_CREATE_UNICODE_ENVIRONMENT
#define CREATE_SEPARATE_WOW_VDM __SPRT_CREATE_SEPARATE_WOW_VDM
#define CREATE_SHARED_WOW_VDM __SPRT_CREATE_SHARED_WOW_VDM
#define CREATE_FORCEDOS __SPRT_CREATE_FORCEDOS
#define BELOW_NORMAL_PRIORITY_CLASS __SPRT_BELOW_NORMAL_PRIORITY_CLASS
#define ABOVE_NORMAL_PRIORITY_CLASS __SPRT_ABOVE_NORMAL_PRIORITY_CLASS
#define INHERIT_PARENT_AFFINITY __SPRT_INHERIT_PARENT_AFFINITY
#define INHERIT_CALLER_PRIORITY __SPRT_INHERIT_CALLER_PRIORITY
#define CREATE_PROTECTED_PROCESS __SPRT_CREATE_PROTECTED_PROCESS
#define EXTENDED_STARTUPINFO_PRESENT __SPRT_EXTENDED_STARTUPINFO_PRESENT
#define PROCESS_MODE_BACKGROUND_BEGIN __SPRT_PROCESS_MODE_BACKGROUND_BEGIN
#define PROCESS_MODE_BACKGROUND_END __SPRT_PROCESS_MODE_BACKGROUND_END
#define CREATE_SECURE_PROCESS __SPRT_CREATE_SECURE_PROCESS
#define CREATE_BREAKAWAY_FROM_JOB __SPRT_CREATE_BREAKAWAY_FROM_JOB
#define CREATE_PRESERVE_CODE_AUTHZ_LEVEL __SPRT_CREATE_PRESERVE_CODE_AUTHZ_LEVEL
#define CREATE_DEFAULT_ERROR_MODE __SPRT_CREATE_DEFAULT_ERROR_MODE
#define CREATE_NO_WINDOW __SPRT_CREATE_NO_WINDOW
#define PROFILE_USER __SPRT_PROFILE_USER
#define PROFILE_KERNEL __SPRT_PROFILE_KERNEL
#define PROFILE_SERVER __SPRT_PROFILE_SERVER
#define CREATE_IGNORE_SYSTEM_DEFAULT __SPRT_CREATE_IGNORE_SYSTEM_DEFAULT
#define SEE_MASK_NOCLOSEPROCESS __SPRT_SEE_MASK_NOCLOSEPROCESS
#define ProcThreadAttributeValue(Number, Thread, Input, Additive) __SPRT_ProcThreadAttributeValue(Number, Thread, Input, Additive)
#define PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES __SPRT_PROC_THREAD_ATTRIBUTE_SECURITY_CAPABILITIES
#ifndef PROC_THREAD_ATTRIBUTE_HANDLE_LIST
#define PROC_THREAD_ATTRIBUTE_HANDLE_LIST __SPRT_PROC_THREAD_ATTRIBUTE_HANDLE_LIST
#endif

// Neutral STARTUPINFO/STARTUPINFOEX names (this sysroot builds with UNICODE).
typedef STARTUPINFOW STARTUPINFO;
typedef LPSTARTUPINFOW LPSTARTUPINFO;
typedef STARTUPINFOEXW STARTUPINFOEX;
typedef LPSTARTUPINFOEXW LPSTARTUPINFOEX;

__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI HANDLE GetCurrentProcess(void);

__SPRT_WIN_IMPORT WINAPI DWORD GetCurrentProcessId(void);

__SPRT_WIN_IMPORT WINAPI HANDLE OpenProcess(DWORD dwDesiredAccess, BOOL bInheritHandle,
		DWORD dwProcessId);

__SPRT_WIN_IMPORT WINAPI BOOL GetExitCodeProcess(HANDLE hProcess, LPDWORD lpExitCode);

__SPRT_WIN_IMPORT WINAPI DWORD GetPriorityClass(HANDLE hProcess);

__SPRT_WIN_IMPORT WINAPI BOOL InitializeProcThreadAttributeList(
		LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList, DWORD dwAttributeCount, DWORD dwFlags,
		PSIZE_T lpSize);

__SPRT_WIN_IMPORT WINAPI BOOL UpdateProcThreadAttribute(
		LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList, DWORD dwFlags, DWORD_PTR Attribute,
		PVOID lpValue, SIZE_T cbSize, PVOID lpPreviousValue, PSIZE_T lpReturnSize);

__SPRT_WIN_IMPORT WINAPI VOID DeleteProcThreadAttributeList(
		LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList);

__SPRT_WIN_IMPORT WINAPI LPWSTR GetCommandLineW(VOID);

__SPRT_WIN_IMPORT WINAPI LPWSTR *CommandLineToArgvW(LPCWSTR lpCmdLine, int *pNumArgs);

__SPRT_WIN_IMPORT WINAPI BOOL CreateProcessW(LPCWSTR lpApplicationName, LPWSTR lpCommandLine,
		LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes,
		BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment,
		LPCWSTR lpCurrentDirectory, LPSTARTUPINFOW lpStartupInfo,
		LPPROCESS_INFORMATION lpProcessInformation);

__SPRT_WIN_IMPORT WINAPI LPSTR GetCommandLineA(VOID);

__SPRT_WIN_IMPORT WINAPI BOOL CreateProcessA(LPCSTR lpApplicationName, LPSTR lpCommandLine,
		LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes,
		BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment,
		LPCSTR lpCurrentDirectory, LPSTARTUPINFOA lpStartupInfo,
		LPPROCESS_INFORMATION lpProcessInformation);

__SPRT_WIN_IMPORT WINAPI BOOL TerminateProcess(HANDLE hProcess, UINT uExitCode);

__SPRT_WIN_IMPORT WINAPI BOOL GetProcessMemoryInfo(HANDLE Process,
		PPROCESS_MEMORY_COUNTERS ppsmemCounters, DWORD cb);

__SPRT_WIN_IMPORT WINAPI BOOL EnumProcessModulesEx(HANDLE hProcess, HMODULE *lphModule, DWORD cb,
		LPDWORD lpcbNeeded, DWORD dwFilterFlag);

__SPRT_WIN_IMPORT WINAPI BOOL IsProcessorFeaturePresent(DWORD ProcessorFeature);

__SPRT_WIN_IMPORT WINAPI BOOL ShellExecuteExW(SHELLEXECUTEINFOW *pExecInfo);

#if __SPRT_ARCH_ID == __SPRT_ARCH_ID_AARCH64
SPRT_FORCEINLINE VOID YieldProcessor() { __yield(); }
#else
SPRT_FORCEINLINE VOID YieldProcessor() { _mm_pause(); }
#endif

__SPRT_WIN_IMPORT WINAPI BOOL QueryFullProcessImageNameW(HANDLE hProcess, DWORD dwFlags,
		LPWSTR lpExeName, PDWORD lpdwSize);

__SPRT_WIN_IMPORT WINAPI BOOL QueryFullProcessImageNameA(HANDLE hProcess, DWORD dwFlags,
		LPSTR lpExeName, PDWORD lpdwSize);

__SPRT_END_DECL

#endif
