/**
 * Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 **/

#ifndef SPRT_WRAPPERS_WINDOWS_SECURITY_API_H_
#define SPRT_WRAPPERS_WINDOWS_SECURITY_API_H_

#include <sprt/wrappers/windows/basic_types.h>
#include <sprt/wrappers/windows/constants.h>
#include <sprt/wrappers/windows/structures.h>
#include <sprt/wrappers/windows/abi/security_api.h>

/* Clean public names (materialized __SPRT_ values live in abi/security_api.h) */
#define SECURITY_CAPABILITY_INTERNET_CLIENT __SPRT_SECURITY_CAPABILITY_INTERNET_CLIENT
#define SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER __SPRT_SECURITY_CAPABILITY_INTERNET_CLIENT_SERVER
#define SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER __SPRT_SECURITY_CAPABILITY_PRIVATE_NETWORK_CLIENT_SERVER
#define SECURITY_CAPABILITY_PICTURES_LIBRARY __SPRT_SECURITY_CAPABILITY_PICTURES_LIBRARY
#define SECURITY_CAPABILITY_VIDEOS_LIBRARY __SPRT_SECURITY_CAPABILITY_VIDEOS_LIBRARY
#define SECURITY_CAPABILITY_MUSIC_LIBRARY __SPRT_SECURITY_CAPABILITY_MUSIC_LIBRARY
#define SECURITY_CAPABILITY_DOCUMENTS_LIBRARY __SPRT_SECURITY_CAPABILITY_DOCUMENTS_LIBRARY
#define SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION __SPRT_SECURITY_CAPABILITY_ENTERPRISE_AUTHENTICATION
#define SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES __SPRT_SECURITY_CAPABILITY_SHARED_USER_CERTIFICATES
#define SECURITY_CAPABILITY_REMOVABLE_STORAGE __SPRT_SECURITY_CAPABILITY_REMOVABLE_STORAGE
#define SECURITY_CAPABILITY_APPOINTMENTS __SPRT_SECURITY_CAPABILITY_APPOINTMENTS
#define SECURITY_CAPABILITY_CONTACTS __SPRT_SECURITY_CAPABILITY_CONTACTS
#define SECURITY_CAPABILITY_INTERNET_EXPLORER __SPRT_SECURITY_CAPABILITY_INTERNET_EXPLORER
#define OWNER_SECURITY_INFORMATION __SPRT_OWNER_SECURITY_INFORMATION
#define GROUP_SECURITY_INFORMATION __SPRT_GROUP_SECURITY_INFORMATION
#define DACL_SECURITY_INFORMATION __SPRT_DACL_SECURITY_INFORMATION
#define SACL_SECURITY_INFORMATION __SPRT_SACL_SECURITY_INFORMATION
#define LABEL_SECURITY_INFORMATION __SPRT_LABEL_SECURITY_INFORMATION
#define ATTRIBUTE_SECURITY_INFORMATION __SPRT_ATTRIBUTE_SECURITY_INFORMATION
#define SCOPE_SECURITY_INFORMATION __SPRT_SCOPE_SECURITY_INFORMATION
#define PROCESS_TRUST_LABEL_SECURITY_INFORMATION __SPRT_PROCESS_TRUST_LABEL_SECURITY_INFORMATION
#define ACCESS_FILTER_SECURITY_INFORMATION __SPRT_ACCESS_FILTER_SECURITY_INFORMATION
#define BACKUP_SECURITY_INFORMATION __SPRT_BACKUP_SECURITY_INFORMATION
#define PROTECTED_DACL_SECURITY_INFORMATION __SPRT_PROTECTED_DACL_SECURITY_INFORMATION
#define PROTECTED_SACL_SECURITY_INFORMATION __SPRT_PROTECTED_SACL_SECURITY_INFORMATION
#define UNPROTECTED_DACL_SECURITY_INFORMATION __SPRT_UNPROTECTED_DACL_SECURITY_INFORMATION
#define UNPROTECTED_SACL_SECURITY_INFORMATION __SPRT_UNPROTECTED_SACL_SECURITY_INFORMATION
#define OBJECT_INHERIT_ACE __SPRT_OBJECT_INHERIT_ACE
#define CONTAINER_INHERIT_ACE __SPRT_CONTAINER_INHERIT_ACE
#define NO_PROPAGATE_INHERIT_ACE __SPRT_NO_PROPAGATE_INHERIT_ACE
#define INHERIT_ONLY_ACE __SPRT_INHERIT_ONLY_ACE
#define INHERITED_ACE __SPRT_INHERITED_ACE
#define VALID_INHERIT_FLAGS __SPRT_VALID_INHERIT_FLAGS
#define SECURITY_APP_PACKAGE_AUTHORITY __SPRT_SECURITY_APP_PACKAGE_AUTHORITY
#define SECURITY_APP_PACKAGE_BASE_RID __SPRT_SECURITY_APP_PACKAGE_BASE_RID
#define SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT __SPRT_SECURITY_BUILTIN_APP_PACKAGE_RID_COUNT
#define SECURITY_APP_PACKAGE_RID_COUNT __SPRT_SECURITY_APP_PACKAGE_RID_COUNT
#define SECURITY_CAPABILITY_BASE_RID __SPRT_SECURITY_CAPABILITY_BASE_RID
#define SECURITY_CAPABILITY_APP_RID __SPRT_SECURITY_CAPABILITY_APP_RID
#define SECURITY_CAPABILITY_APP_SILO_RID __SPRT_SECURITY_CAPABILITY_APP_SILO_RID
#define SECURITY_BUILTIN_CAPABILITY_RID_COUNT __SPRT_SECURITY_BUILTIN_CAPABILITY_RID_COUNT
#define SECURITY_CAPABILITY_RID_COUNT __SPRT_SECURITY_CAPABILITY_RID_COUNT
#define SECURITY_PARENT_PACKAGE_RID_COUNT __SPRT_SECURITY_PARENT_PACKAGE_RID_COUNT
#define SECURITY_CHILD_PACKAGE_RID_COUNT __SPRT_SECURITY_CHILD_PACKAGE_RID_COUNT
#define SE_GROUP_MANDATORY __SPRT_SE_GROUP_MANDATORY
#define SE_GROUP_ENABLED_BY_DEFAULT __SPRT_SE_GROUP_ENABLED_BY_DEFAULT
#define SE_GROUP_ENABLED __SPRT_SE_GROUP_ENABLED
#define SE_GROUP_OWNER __SPRT_SE_GROUP_OWNER
#define SE_GROUP_USE_FOR_DENY_ONLY __SPRT_SE_GROUP_USE_FOR_DENY_ONLY
#define SE_GROUP_INTEGRITY __SPRT_SE_GROUP_INTEGRITY
#define SE_GROUP_INTEGRITY_ENABLED __SPRT_SE_GROUP_INTEGRITY_ENABLED
#define SE_GROUP_LOGON_ID __SPRT_SE_GROUP_LOGON_ID
#define SE_GROUP_RESOURCE __SPRT_SE_GROUP_RESOURCE
#define SE_PRIVILEGE_ENABLED_BY_DEFAULT __SPRT_SE_PRIVILEGE_ENABLED_BY_DEFAULT
#define SE_PRIVILEGE_ENABLED __SPRT_SE_PRIVILEGE_ENABLED
#define SE_PRIVILEGE_REMOVED __SPRT_SE_PRIVILEGE_REMOVED
#define SE_PRIVILEGE_USED_FOR_ACCESS __SPRT_SE_PRIVILEGE_USED_FOR_ACCESS
#define SE_PRIVILEGE_VALID_ATTRIBUTES __SPRT_SE_PRIVILEGE_VALID_ATTRIBUTES
#define E_ACCESSDENIED __SPRT_E_ACCESSDENIED
#define E_INVALIDARG __SPRT_E_INVALIDARG
#define EVENTLOG_SUCCESS __SPRT_EVENTLOG_SUCCESS
#define EVENTLOG_ERROR_TYPE __SPRT_EVENTLOG_ERROR_TYPE
#define EVENTLOG_WARNING_TYPE __SPRT_EVENTLOG_WARNING_TYPE
#define EVENTLOG_INFORMATION_TYPE __SPRT_EVENTLOG_INFORMATION_TYPE
#define EVENTLOG_AUDIT_SUCCESS __SPRT_EVENTLOG_AUDIT_SUCCESS
#define EVENTLOG_AUDIT_FAILURE __SPRT_EVENTLOG_AUDIT_FAILURE


__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI BOOL AllocateAndInitializeSid(
		PSID_IDENTIFIER_AUTHORITY pIdentifierAuthority, BYTE nSubAuthorityCount,
		DWORD nSubAuthority0, DWORD nSubAuthority1, DWORD nSubAuthority2, DWORD nSubAuthority3,
		DWORD nSubAuthority4, DWORD nSubAuthority5, DWORD nSubAuthority6, DWORD nSubAuthority7,
		PSID *pSid);

__SPRT_WIN_IMPORT WINAPI LPBYTE GetSidSubAuthorityCount(LPSID Sid);

__SPRT_WIN_IMPORT WINAPI LPDWORD GetSidSubAuthority(LPSID Sid, DWORD nSubAuthority);

__SPRT_WIN_IMPORT WINAPI PVOID FreeSid(PSID pSid);

__SPRT_WIN_IMPORT WINAPI DWORD GetSecurityInfo(HANDLE handle, SE_OBJECT_TYPE ObjectType,
		SECURITY_INFORMATION SecurityInfo, PSID *ppsidOwner, PSID *ppsidGroup, PACL *ppDacl,
		PACL *ppSacl, PSECURITY_DESCRIPTOR *ppSecurityDescriptor);

__SPRT_WIN_IMPORT WINAPI HRESULT CreateAppContainerProfile(PCWSTR pszAppContainerName,
		PCWSTR pszDisplayName, PCWSTR pszDescription, PSID_AND_ATTRIBUTES pCapabilities,
		DWORD dwCapabilityCount, PSID *ppSidAppContainerSid);

__SPRT_WIN_IMPORT WINAPI HRESULT DeriveAppContainerSidFromAppContainerName(
		PCWSTR pszAppContainerName, PSID *ppsidAppContainerSid);

__SPRT_WIN_IMPORT WINAPI HRESULT GetAppContainerFolderPath(PCWSTR pszAppContainerSid,
		PWSTR *ppszPath);

__SPRT_WIN_IMPORT WINAPI HRESULT DeleteAppContainerProfile(PCWSTR pszAppContainerName);

__SPRT_WIN_IMPORT WINAPI DWORD GetNamedSecurityInfoW(LPCWSTR pObjectName, SE_OBJECT_TYPE ObjectType,
		SECURITY_INFORMATION SecurityInfo, PSID *ppsidOwner, PSID *ppsidGroup, PACL *ppDacl,
		PACL *ppSacl, PSECURITY_DESCRIPTOR *ppSecurityDescriptor);

__SPRT_WIN_IMPORT WINAPI DWORD SetEntriesInAclW(ULONG cCountOfExplicitEntries,
		PEXPLICIT_ACCESS_W pListOfExplicitEntries, PACL OldAcl, PACL *NewAcl);

__SPRT_WIN_IMPORT WINAPI DWORD SetNamedSecurityInfoW(LPWSTR pObjectName, SE_OBJECT_TYPE ObjectType,
		SECURITY_INFORMATION SecurityInfo, PSID psidOwner, PSID psidGroup, PACL pDacl, PACL pSacl);

__SPRT_WIN_IMPORT WINAPI BOOL ConvertSidToStringSidW(PSID Sid, LPWSTR *StringSid);

__SPRT_WIN_IMPORT WINAPI BOOL CloseWindowStation(HWINSTA hWinSta);

__SPRT_WIN_IMPORT WINAPI BOOL SetProcessWindowStation(HWINSTA hWinSta);

__SPRT_WIN_IMPORT WINAPI HWINSTA GetProcessWindowStation(VOID);

__SPRT_WIN_IMPORT WINAPI BOOL GetUserObjectInformationW(HANDLE hObj, int nIndex, PVOID pvInfo,
		DWORD nLength, LPDWORD lpnLengthNeeded);

__SPRT_WIN_IMPORT WINAPI HANDLE RegisterEventSourceW(LPCWSTR lpUNCServerName, LPCWSTR lpSourceName);

__SPRT_WIN_IMPORT WINAPI BOOL DeregisterEventSource(HANDLE hEventLog);

__SPRT_WIN_IMPORT WINAPI BOOL ReportEventW(HANDLE hEventLog, WORD wType, WORD wCategory,
		DWORD dwEventID, PSID lpUserSid, WORD wNumStrings, DWORD dwDataSize, LPCWSTR *lpStrings,
		LPVOID lpRawData);

__SPRT_WIN_IMPORT WINAPI BOOL LookupPrivilegeValueA(LPCSTR lpSystemName, LPCSTR lpName,
		PLUID lpLuid);

__SPRT_WIN_IMPORT WINAPI BOOL LookupPrivilegeValueW(LPCWSTR lpSystemName, LPCWSTR lpName,
		PLUID lpLuid);

__SPRT_WIN_IMPORT WINAPI BOOL AdjustTokenPrivileges(HANDLE TokenHandle, BOOL DisableAllPrivileges,
		PTOKEN_PRIVILEGES NewState, DWORD BufferLength, PTOKEN_PRIVILEGES PreviousState,
		PDWORD ReturnLength);

#ifdef UNICODE
#define LookupPrivilegeValue  LookupPrivilegeValueW
#define ReportEvent  ReportEventW
#define GetUserObjectInformation  GetUserObjectInformationW
#define RegisterEventSource  RegisterEventSourceW
#else
#define LookupPrivilegeValue  LookupPrivilegeValueA
#endif

#ifndef SE_LOCK_MEMORY_NAME
#define SE_LOCK_MEMORY_NAME TEXT("SeLockMemoryPrivilege")
#endif

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_SECURITY_API_H_
