/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_WINSOCK_CONSTANTS_H_
#define SPRT_WRAPPERS_WINDOWS_WINSOCK_CONSTANTS_H_

/*
	Clean public names for the Winsock constants (materialized __SPRT_ values live in
	abi/winsock.h).

	Split out of <winsock.h> because it depends on nothing but the ABI header, while
	<winsock.h> itself pulls in the POSIX socket headers from include_libc. <windows.h>
	provides these constants - the SDK reaches them by including <winsock.h> from inside
	its non-lean block - but lives in include/ and cannot depend on include_libc, so it
	includes this instead.
*/

#include <sprt/wrappers/windows/abi/winsock.h>

#define WSABASEERR __SPRT_WSABASEERR
#define WSAEINTR __SPRT_WSAEINTR
#define WSAEBADF __SPRT_WSAEBADF
#define WSAEACCES __SPRT_WSAEACCES
#define WSAEFAULT __SPRT_WSAEFAULT
#define WSAEINVAL __SPRT_WSAEINVAL
#define WSAEMFILE __SPRT_WSAEMFILE
#define WSAEWOULDBLOCK __SPRT_WSAEWOULDBLOCK
#define WSAEINPROGRESS __SPRT_WSAEINPROGRESS
#define WSAEALREADY __SPRT_WSAEALREADY
#define WSAENOTSOCK __SPRT_WSAENOTSOCK
#define WSAEDESTADDRREQ __SPRT_WSAEDESTADDRREQ
#define WSAEMSGSIZE __SPRT_WSAEMSGSIZE
#define WSAEPROTOTYPE __SPRT_WSAEPROTOTYPE
#define WSAENOPROTOOPT __SPRT_WSAENOPROTOOPT
#define WSAEPROTONOSUPPORT __SPRT_WSAEPROTONOSUPPORT
#define WSAESOCKTNOSUPPORT __SPRT_WSAESOCKTNOSUPPORT
#define WSAEOPNOTSUPP __SPRT_WSAEOPNOTSUPP
#define WSAEPFNOSUPPORT __SPRT_WSAEPFNOSUPPORT
#define WSAEAFNOSUPPORT __SPRT_WSAEAFNOSUPPORT
#define WSAEADDRINUSE __SPRT_WSAEADDRINUSE
#define WSAEADDRNOTAVAIL __SPRT_WSAEADDRNOTAVAIL
#define WSAENETDOWN __SPRT_WSAENETDOWN
#define WSAENETUNREACH __SPRT_WSAENETUNREACH
#define WSAENETRESET __SPRT_WSAENETRESET
#define WSAECONNABORTED __SPRT_WSAECONNABORTED
#define WSAECONNRESET __SPRT_WSAECONNRESET
#define WSAENOBUFS __SPRT_WSAENOBUFS
#define WSAEISCONN __SPRT_WSAEISCONN
#define WSAENOTCONN __SPRT_WSAENOTCONN
#define WSAESHUTDOWN __SPRT_WSAESHUTDOWN
#define WSAETOOMANYREFS __SPRT_WSAETOOMANYREFS
#define WSAETIMEDOUT __SPRT_WSAETIMEDOUT
#define WSAECONNREFUSED __SPRT_WSAECONNREFUSED
#define WSAELOOP __SPRT_WSAELOOP
#define WSAENAMETOOLONG __SPRT_WSAENAMETOOLONG
#define WSAEHOSTDOWN __SPRT_WSAEHOSTDOWN
#define WSAEHOSTUNREACH __SPRT_WSAEHOSTUNREACH
#define WSAENOTEMPTY __SPRT_WSAENOTEMPTY
#define WSAEPROCLIM __SPRT_WSAEPROCLIM
#define WSAEUSERS __SPRT_WSAEUSERS
#define WSAEDQUOT __SPRT_WSAEDQUOT
#define WSAESTALE __SPRT_WSAESTALE
#define WSAEREMOTE __SPRT_WSAEREMOTE
#define WSASYSNOTREADY __SPRT_WSASYSNOTREADY
#define WSAVERNOTSUPPORTED __SPRT_WSAVERNOTSUPPORTED
#define WSANOTINITIALISED __SPRT_WSANOTINITIALISED
#define WSAEDISCON __SPRT_WSAEDISCON
#define WSAENOMORE __SPRT_WSAENOMORE
#define WSAECANCELLED __SPRT_WSAECANCELLED
#define WSAEINVALIDPROCTABLE __SPRT_WSAEINVALIDPROCTABLE
#define WSAEINVALIDPROVIDER __SPRT_WSAEINVALIDPROVIDER
#define WSAEPROVIDERFAILEDINIT __SPRT_WSAEPROVIDERFAILEDINIT
#define WSASYSCALLFAILURE __SPRT_WSASYSCALLFAILURE
#define WSASERVICE_NOT_FOUND __SPRT_WSASERVICE_NOT_FOUND
#define WSATYPE_NOT_FOUND __SPRT_WSATYPE_NOT_FOUND
#define WSA_E_NO_MORE __SPRT_WSA_E_NO_MORE
#define WSA_E_CANCELLED __SPRT_WSA_E_CANCELLED
#define WSAEREFUSED __SPRT_WSAEREFUSED
#define WSAHOST_NOT_FOUND __SPRT_WSAHOST_NOT_FOUND
#define WSATRY_AGAIN __SPRT_WSATRY_AGAIN
#define WSANO_RECOVERY __SPRT_WSANO_RECOVERY
#define WSANO_DATA __SPRT_WSANO_DATA
#define WSA_QOS_RECEIVERS __SPRT_WSA_QOS_RECEIVERS
#define WSA_QOS_SENDERS __SPRT_WSA_QOS_SENDERS
#define WSA_QOS_NO_SENDERS __SPRT_WSA_QOS_NO_SENDERS
#define WSA_QOS_NO_RECEIVERS __SPRT_WSA_QOS_NO_RECEIVERS
#define WSA_QOS_REQUEST_CONFIRMED __SPRT_WSA_QOS_REQUEST_CONFIRMED
#define WSA_QOS_ADMISSION_FAILURE __SPRT_WSA_QOS_ADMISSION_FAILURE
#define WSA_QOS_POLICY_FAILURE __SPRT_WSA_QOS_POLICY_FAILURE
#define WSA_QOS_BAD_STYLE __SPRT_WSA_QOS_BAD_STYLE
#define WSA_QOS_BAD_OBJECT __SPRT_WSA_QOS_BAD_OBJECT
#define WSA_QOS_TRAFFIC_CTRL_ERROR __SPRT_WSA_QOS_TRAFFIC_CTRL_ERROR
#define WSA_QOS_GENERIC_ERROR __SPRT_WSA_QOS_GENERIC_ERROR
#define WSA_QOS_ESERVICETYPE __SPRT_WSA_QOS_ESERVICETYPE
#define WSA_QOS_EFLOWSPEC __SPRT_WSA_QOS_EFLOWSPEC
#define WSA_QOS_EPROVSPECBUF __SPRT_WSA_QOS_EPROVSPECBUF
#define WSA_QOS_EFILTERSTYLE __SPRT_WSA_QOS_EFILTERSTYLE
#define WSA_QOS_EFILTERTYPE __SPRT_WSA_QOS_EFILTERTYPE
#define WSA_QOS_EFILTERCOUNT __SPRT_WSA_QOS_EFILTERCOUNT
#define WSA_QOS_EOBJLENGTH __SPRT_WSA_QOS_EOBJLENGTH
#define WSA_QOS_EFLOWCOUNT __SPRT_WSA_QOS_EFLOWCOUNT
#define WSA_QOS_EUNKOWNPSOBJ __SPRT_WSA_QOS_EUNKOWNPSOBJ
#define WSA_QOS_EPOLICYOBJ __SPRT_WSA_QOS_EPOLICYOBJ
#define WSA_QOS_EFLOWDESC __SPRT_WSA_QOS_EFLOWDESC
#define WSA_QOS_EPSFLOWSPEC __SPRT_WSA_QOS_EPSFLOWSPEC
#define WSA_QOS_EPSFILTERSPEC __SPRT_WSA_QOS_EPSFILTERSPEC
#define WSA_QOS_ESDMODEOBJ __SPRT_WSA_QOS_ESDMODEOBJ
#define WSA_QOS_ESHAPERATEOBJ __SPRT_WSA_QOS_ESHAPERATEOBJ
#define WSA_QOS_RESERVED_PETYPE __SPRT_WSA_QOS_RESERVED_PETYPE
#define WSA_SECURE_HOST_NOT_FOUND __SPRT_WSA_SECURE_HOST_NOT_FOUND
#define WSA_IPSEC_NAME_POLICY_ERROR __SPRT_WSA_IPSEC_NAME_POLICY_ERROR
#define SIO_UDP_CONNRESET __SPRT_SIO_UDP_CONNRESET
#define SIO_UDP_NETRESET __SPRT_SIO_UDP_NETRESET
#define WSA_IO_PENDING __SPRT_WSA_IO_PENDING
#define WSA_IO_INCOMPLETE __SPRT_WSA_IO_INCOMPLETE
#define WSA_INVALID_HANDLE __SPRT_WSA_INVALID_HANDLE
#define WSA_INVALID_PARAMETER __SPRT_WSA_INVALID_PARAMETER
#define WSA_NOT_ENOUGH_MEMORY __SPRT_WSA_NOT_ENOUGH_MEMORY
#define WSA_OPERATION_ABORTED __SPRT_WSA_OPERATION_ABORTED
#define WSA_MAXIMUM_WAIT_EVENTS __SPRT_WSA_MAXIMUM_WAIT_EVENTS
#define WSA_WAIT_FAILED __SPRT_WSA_WAIT_FAILED
#define WSA_WAIT_EVENT_0 __SPRT_WSA_WAIT_EVENT_0
#define WSA_WAIT_IO_COMPLETION __SPRT_WSA_WAIT_IO_COMPLETION
#define WSA_WAIT_TIMEOUT __SPRT_WSA_WAIT_TIMEOUT
#define WSA_INFINITE __SPRT_WSA_INFINITE
#define EAI_AGAIN __SPRT_EAI_AGAIN
#define EAI_BADFLAGS __SPRT_EAI_BADFLAGS
#define EAI_FAIL __SPRT_EAI_FAIL
#define EAI_FAMILY __SPRT_EAI_FAMILY
#define EAI_MEMORY __SPRT_EAI_MEMORY
#define EAI_NOSECURENAME __SPRT_EAI_NOSECURENAME
#define EAI_NONAME __SPRT_EAI_NONAME
#define EAI_SERVICE __SPRT_EAI_SERVICE
#define EAI_SOCKTYPE __SPRT_EAI_SOCKTYPE
#define EAI_IPSECPOLICY __SPRT_EAI_IPSECPOLICY
#define FD_READ_BIT __SPRT_FD_READ_BIT
#define FD_READ __SPRT_FD_READ
#define FD_WRITE_BIT __SPRT_FD_WRITE_BIT
#define FD_WRITE __SPRT_FD_WRITE
#define FD_OOB_BIT __SPRT_FD_OOB_BIT
#define FD_OOB __SPRT_FD_OOB
#define FD_ACCEPT_BIT __SPRT_FD_ACCEPT_BIT
#define FD_ACCEPT __SPRT_FD_ACCEPT
#define FD_CONNECT_BIT __SPRT_FD_CONNECT_BIT
#define FD_CONNECT __SPRT_FD_CONNECT
#define FD_CLOSE_BIT __SPRT_FD_CLOSE_BIT
#define FD_CLOSE __SPRT_FD_CLOSE
#define FD_QOS_BIT __SPRT_FD_QOS_BIT
#define FD_QOS __SPRT_FD_QOS
#define FD_GROUP_QOS_BIT __SPRT_FD_GROUP_QOS_BIT
#define FD_GROUP_QOS __SPRT_FD_GROUP_QOS
#define FD_ROUTING_INTERFACE_CHANGE_BIT __SPRT_FD_ROUTING_INTERFACE_CHANGE_BIT
#define FD_ROUTING_INTERFACE_CHANGE __SPRT_FD_ROUTING_INTERFACE_CHANGE
#define FD_ADDRESS_LIST_CHANGE_BIT __SPRT_FD_ADDRESS_LIST_CHANGE_BIT
#define FD_ADDRESS_LIST_CHANGE __SPRT_FD_ADDRESS_LIST_CHANGE
#define FD_MAX_EVENTS __SPRT_FD_MAX_EVENTS
#define FD_ALL_EVENTS __SPRT_FD_ALL_EVENTS
#define MAX_PROTOCOL_CHAIN __SPRT_MAX_PROTOCOL_CHAIN
#define WSAPROTOCOL_LEN __SPRT_WSAPROTOCOL_LEN

#define IOC_UNIX __SPRT_IOC_UNIX
#define IOC_WS2 __SPRT_IOC_WS2
#define IOC_PROTOCOL __SPRT_IOC_PROTOCOL
#define IOC_VENDOR __SPRT_IOC_VENDOR

#define IOCPARM_MASK __SPRT_IOCPARM_MASK
#define IOC_VOID __SPRT_IOC_VOID
#define IOC_OUT __SPRT_IOC_OUT
#define IOC_IN __SPRT_IOC_IN
#define _IOC_INOUT __SPRT_IOC_INOUT

#endif // SPRT_WRAPPERS_WINDOWS_WINSOCK_CONSTANTS_H_
