/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_WINVER_H_
#define SPRT_WRAPPERS_WINDOWS_WINVER_H_

#include <sprt/wrappers/windows/message_api.h>
#include <sprt/wrappers/windows/abi/winver.h>

/* Clean public names (materialized __SPRT_ values live in abi/winver.h) */
#define VER_EQUAL __SPRT_VER_EQUAL
#define VER_GREATER __SPRT_VER_GREATER
#define VER_GREATER_EQUAL __SPRT_VER_GREATER_EQUAL
#define VER_LESS __SPRT_VER_LESS
#define VER_LESS_EQUAL __SPRT_VER_LESS_EQUAL
#define VER_AND __SPRT_VER_AND
#define VER_OR __SPRT_VER_OR
#define VER_CONDITION_MASK __SPRT_VER_CONDITION_MASK
#define VER_NUM_BITS_PER_CONDITION_MASK __SPRT_VER_NUM_BITS_PER_CONDITION_MASK
#define VER_MINORVERSION __SPRT_VER_MINORVERSION
#define VER_MAJORVERSION __SPRT_VER_MAJORVERSION
#define VER_BUILDNUMBER __SPRT_VER_BUILDNUMBER
#define VER_PLATFORMID __SPRT_VER_PLATFORMID
#define VER_SERVICEPACKMINOR __SPRT_VER_SERVICEPACKMINOR
#define VER_SERVICEPACKMAJOR __SPRT_VER_SERVICEPACKMAJOR
#define VER_SUITENAME __SPRT_VER_SUITENAME
#define VER_PRODUCT_TYPE __SPRT_VER_PRODUCT_TYPE

/* VS_VERSIONINFO resource constants (verrsrc.h) */
#define VS_VERSION_INFO __SPRT_VS_VERSION_INFO
#define VS_USER_DEFINED __SPRT_VS_USER_DEFINED

#define VS_FFI_SIGNATURE __SPRT_VS_FFI_SIGNATURE
#define VS_FFI_STRUCVERSION __SPRT_VS_FFI_STRUCVERSION
#define VS_FFI_FILEFLAGSMASK __SPRT_VS_FFI_FILEFLAGSMASK

#define VS_FF_DEBUG __SPRT_VS_FF_DEBUG
#define VS_FF_PRERELEASE __SPRT_VS_FF_PRERELEASE
#define VS_FF_PATCHED __SPRT_VS_FF_PATCHED
#define VS_FF_PRIVATEBUILD __SPRT_VS_FF_PRIVATEBUILD
#define VS_FF_INFOINFERRED __SPRT_VS_FF_INFOINFERRED
#define VS_FF_SPECIALBUILD __SPRT_VS_FF_SPECIALBUILD

#define VOS_UNKNOWN __SPRT_VOS_UNKNOWN
#define VOS_DOS __SPRT_VOS_DOS
#define VOS_OS216 __SPRT_VOS_OS216
#define VOS_OS232 __SPRT_VOS_OS232
#define VOS_NT __SPRT_VOS_NT
#define VOS_WINCE __SPRT_VOS_WINCE

#define VOS__BASE __SPRT_VOS__BASE
#define VOS__WINDOWS16 __SPRT_VOS__WINDOWS16
#define VOS__PM16 __SPRT_VOS__PM16
#define VOS__PM32 __SPRT_VOS__PM32
#define VOS__WINDOWS32 __SPRT_VOS__WINDOWS32

#define VOS_DOS_WINDOWS16 __SPRT_VOS_DOS_WINDOWS16
#define VOS_DOS_WINDOWS32 __SPRT_VOS_DOS_WINDOWS32
#define VOS_OS216_PM16 __SPRT_VOS_OS216_PM16
#define VOS_OS232_PM32 __SPRT_VOS_OS232_PM32
#define VOS_NT_WINDOWS32 __SPRT_VOS_NT_WINDOWS32

#define VFT_UNKNOWN __SPRT_VFT_UNKNOWN
#define VFT_APP __SPRT_VFT_APP
#define VFT_DLL __SPRT_VFT_DLL
#define VFT_DRV __SPRT_VFT_DRV
#define VFT_FONT __SPRT_VFT_FONT
#define VFT_VXD __SPRT_VFT_VXD
#define VFT_STATIC_LIB __SPRT_VFT_STATIC_LIB

#define VFT2_UNKNOWN __SPRT_VFT2_UNKNOWN
#define VFT2_DRV_PRINTER __SPRT_VFT2_DRV_PRINTER
#define VFT2_DRV_KEYBOARD __SPRT_VFT2_DRV_KEYBOARD
#define VFT2_DRV_LANGUAGE __SPRT_VFT2_DRV_LANGUAGE
#define VFT2_DRV_DISPLAY __SPRT_VFT2_DRV_DISPLAY
#define VFT2_DRV_MOUSE __SPRT_VFT2_DRV_MOUSE
#define VFT2_DRV_NETWORK __SPRT_VFT2_DRV_NETWORK
#define VFT2_DRV_SYSTEM __SPRT_VFT2_DRV_SYSTEM
#define VFT2_DRV_INSTALLABLE __SPRT_VFT2_DRV_INSTALLABLE
#define VFT2_DRV_SOUND __SPRT_VFT2_DRV_SOUND
#define VFT2_DRV_COMM __SPRT_VFT2_DRV_COMM
#define VFT2_DRV_INPUTMETHOD __SPRT_VFT2_DRV_INPUTMETHOD
#define VFT2_DRV_VERSIONED_PRINTER __SPRT_VFT2_DRV_VERSIONED_PRINTER

#define VFT2_FONT_RASTER __SPRT_VFT2_FONT_RASTER
#define VFT2_FONT_VECTOR __SPRT_VFT2_FONT_VECTOR
#define VFT2_FONT_TRUETYPE __SPRT_VFT2_FONT_TRUETYPE

#include <sprt/wrappers/windows/winapifamily.h>

__SPRT_BEGIN_DECL

__SPRT_WIN_IMPORT WINAPI BOOL GetVersionExA(LPOSVERSIONINFOA lpVersionInformation);

__SPRT_WIN_IMPORT WINAPI BOOL GetVersionExW(LPOSVERSIONINFOW lpVersionInformation);

__SPRT_WIN_IMPORT WINAPI ULONGLONG VerSetConditionMask(ULONGLONG ConditionMask, DWORD TypeMask,
		BYTE Condition);

__SPRT_WIN_IMPORT WINAPI BOOL VerifyVersionInfoW(LPOSVERSIONINFOEXW lpVersionInformation,
		DWORD dwTypeMask, DWORDLONG dwlConditionMask);

#ifdef UNICODE
#define VerifyVersionInfo VerifyVersionInfoW
#define GetVersionEx GetVersionExW
typedef OSVERSIONINFOW OSVERSIONINFO;
typedef POSVERSIONINFOW POSVERSIONINFO;
typedef LPOSVERSIONINFOW LPOSVERSIONINFO;
typedef OSVERSIONINFOEXW OSVERSIONINFOEX;
typedef POSVERSIONINFOEXW POSVERSIONINFOEX;
typedef LPOSVERSIONINFOEXW LPOSVERSIONINFOEX;
#else
#define GetVersionEx GetVersionExA
typedef OSVERSIONINFOA OSVERSIONINFO;
typedef POSVERSIONINFOA POSVERSIONINFO;
typedef LPOSVERSIONINFOA LPOSVERSIONINFO;
#endif

__SPRT_END_DECL

#endif // SPRT_WRAPPERS_WINDOWS_WINVER_H_
