# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
# (same MIT license as the rest of the toolchain trees)

# Import an Embox dist-gen export into this target's sysroot.
#
# Embox has no NuttX-style `make export`. Pack `make distgen` output
# (build/dist/{include,lib}) plus the template build.conf into
# embox-export-*.tar.gz. Layout inside the tarball:
#
#   embox-export/
#     include/     merged libc + posix + kernel + arch headers
#     src/         Embox src/*.h (module headers include <../../src/…>)
#     lib/embox.a  lib/embox.o  lib/image.lds  lib/libc.a -> embox.a
#     build.conf   arch flags (CFLAGS / CROSS_COMPILE / ARCH)
#     mods.conf    enabled modules snapshot
#
# Outputs (in $(TOOLCHAIN_OUTPUT_DIR)):
#   embox-export/            unpacked tree
#   sysroot/usr/include      Embox headers
#   sysroot/usr/lib          embox.a / libc.a
#   sysroot/usr/include_libc alias
#   embox-arch-flags.mk      extracted -march/-mtune/--target
#   embox-config.mk          feature notes from mods.conf

.DEFAULT_GOAL := all
THIS_FILE := $(lastword $(MAKEFILE_LIST))
include $(dir $(THIS_FILE))../common/utils/detect-platform.mk
include $(dir $(THIS_FILE))../common/utils/init-shell.mk

OUT := $(TOOLCHAIN_OUTPUT_DIR)
EXPORT_DIR := $(OUT)/embox-export
SYSROOT := $(OUT)/sysroot
ARCH_FLAGS_FILE := $(OUT)/embox-arch-flags.mk
CONFIG_FILE := $(OUT)/embox-config.mk

$(EXPORT_DIR)/.stamp-unpacked:
ifeq ($(EMBOX_EXPORT),)
$(error Embox target requires EMBOX_EXPORT=<embox-export-*.tar.gz> (pack make distgen output + build.conf))
else
	@echo "Unpacking embox-export: $(EMBOX_EXPORT)"
	$(call rule_rm,$(EXPORT_DIR))
	mkdir -p $(EXPORT_DIR)
	cd $(EXPORT_DIR) && tar -xzf "$(abspath $(EMBOX_EXPORT))"
	# Normalise to a single canonical embox-export/ name.
	cd $(EXPORT_DIR) && if [ ! -d embox-export ]; then \
		mv embox-export* embox-export 2>/dev/null || true; \
	fi
endif
	@touch $@

$(SYSROOT)/usr/include: $(EXPORT_DIR)/.stamp-unpacked
	@mkdir -p $(dir $@)
	rm -rf $@
	cp -rf $(EXPORT_DIR)/embox-export/include $@
	# dist-gen copies several include trees into include/; flatten if nested.
	if [ -d $@/include ]; then \
		cp -rf $@/include/. $@/; \
		rm -rf $@/include; \
	fi

$(SYSROOT)/usr/include_libc: $(SYSROOT)/usr/include
	@mkdir -p $(dir $@)
	rm -rf $@
	ln -sf include $@

# File stamp: usr/lib is a directory and GNU make would skip the recipe once
# the directory exists, even after a newer export unpacks src/.
$(SYSROOT)/.stamp-lib: $(EXPORT_DIR)/.stamp-unpacked
	@mkdir -p $(SYSROOT)/usr/lib
	cp -af $(EXPORT_DIR)/embox-export/lib/. $(SYSROOT)/usr/lib/ 2>/dev/null || true
	# Feature probes use -lc/-lm/-lpthread; Embox ships one archive
	# (embox.a). libc.a is in the export; libm/libpthread are not.
	if [ ! -e $(SYSROOT)/usr/lib/libc.a ] && [ -f $(SYSROOT)/usr/lib/embox.a ]; then \
		ln -sfn embox.a $(SYSROOT)/usr/lib/libc.a; \
	fi
	if [ -e $(SYSROOT)/usr/lib/libc.a ]; then \
		ln -sfn libc.a $(SYSROOT)/usr/lib/libm.a; \
		ln -sfn libc.a $(SYSROOT)/usr/lib/libpthread.a; \
	fi
	# Module headers include <../../src/…> relative to usr/include.
	if [ -d $(EXPORT_DIR)/embox-export/src ]; then \
		rm -rf $(SYSROOT)/src; \
		cp -a $(EXPORT_DIR)/embox-export/src $(SYSROOT)/src; \
	fi
	@touch $@

$(SYSROOT)/usr/lib: $(SYSROOT)/.stamp-lib
	@true

# Extract clang/gcc flags from the packed build.conf (Embox C-like conf).
$(ARCH_FLAGS_FILE): $(EXPORT_DIR)/.stamp-unpacked
	@echo "Extracting arch flags from $(EXPORT_DIR)/embox-export/build.conf"
	@{ \
		echo '# Auto-generated by target-embox/import-sysroot.mk'; \
		echo '# Do not edit; regenerate by rebuilding this target.'; \
		echo; \
		conf="$(EXPORT_DIR)/embox-export/build.conf"; \
		cflags=$$(grep -E '^[[:space:]]*CFLAGS[[:space:]]*\+=' "$$conf" | sed -E 's/^[[:space:]]*CFLAGS[[:space:]]*\+=[[:space:]]*//; s|[[:space:]]*/\*.*||' | tr '\n' ' '); \
		cxxflags=$$(grep -E '^[[:space:]]*CXXFLAGS[[:space:]]*\+=' "$$conf" | sed -E 's/^[[:space:]]*CXXFLAGS[[:space:]]*\+=[[:space:]]*//; s|[[:space:]]*/\*.*||' | tr '\n' ' '); \
		echo "EMBOX_ARCH := $$(sed -n 's/^ARCH *= *//p' "$$conf" | head -1)"; \
		echo "EMBOX_CROSSDEV := $$(sed -n 's/^CROSS_COMPILE *= *//p' "$$conf" | head -1)"; \
		echo "EMBOX_ARCHCPUFLAGS := $$cflags"; \
		echo "EMBOX_ARCHCFLAGS := $$cflags"; \
		echo "EMBOX_ARCHCXXFLAGS := $${cxxflags:-$$cflags}"; \
		echo "EMBOX_LDFLAGS :="; \
		echo "EMBOX_LDELFFLAGS :="; \
	} > $@
	@cat $@

$(CONFIG_FILE): $(EXPORT_DIR)/.stamp-unpacked
	@echo "Recording Embox module snapshot"
	@{ \
		echo '# Auto-generated by target-embox/import-sysroot.mk'; \
		echo '# Presence of key modules in mods.conf.'; \
		echo; \
		mods="$(EXPORT_DIR)/embox-export/mods.conf"; \
		if grep -q 'pthread_key' "$$mods" 2>/dev/null; then echo 'EMBOX_HAVE_PTHREAD_KEY := 1'; fi; \
		if grep -q 'compat.libc.all' "$$mods" 2>/dev/null; then echo 'EMBOX_HAVE_LIBC := 1'; fi; \
		if grep -q 'embox.net.socket' "$$mods" 2>/dev/null; then echo 'EMBOX_HAVE_NET := 1'; fi; \
		if grep -q 'driver.video' "$$mods" 2>/dev/null; then echo 'EMBOX_HAVE_FB := 1'; fi; \
		echo 'EMBOX_HAVE_CXX := 0'; \
	} > $@
	@cat $@

all: $(SYSROOT)/usr/include $(SYSROOT)/usr/include_libc $(SYSROOT)/usr/lib \
	$(ARCH_FLAGS_FILE) $(CONFIG_FILE)

.PHONY: all
