# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Build libc++abi + libunwind for the Embox target.
#
# Embox flat build links no C++ ABI runtime of its own (libxx.a is the bare
# minimum), and libsprt is built -fexceptions: clang lowers throw/catch into
# __cxa_* calls + a DWARF unwinder. This file builds the LLVM runtimes
# (libc++abi with merged libunwind) against the imported Embox libc, the same
# "runtimes superbuild" shape target-nuttx uses.
#
# Output: usr/lib/libc++abi.a + usr/lib/libunwind.a in the target sysroot.
# ONLY those two. LLVM's libcxx is neither configured nor built: the STL on this
# target is the engine's own libc++ port (runtime/libcxx, compiled into libsprt
# by runtime/libcxx/libcxx.mk), and libc++abi is built against ITS headers.
#
# Embox porting notes:
#   * LIBUNWIND_IS_BAREMETAL=ON selects libunwind's baremetal path, which looks
#     up the EH sections via extern __eh_frame_{start,end} symbols instead
#     of dl_iterate_phdr() — Embox has no <link.h> / dl_iterate_phdr (single
#     flat ELF, no dynamic loader), so the dl_iterate path cannot compile.
#     Those symbols come from the Embox image linker script; see
#     runtime/libc_wrapper/platform/embox/stubs.cc for the fallback that keeps
#     the relocatable link working when they are absent.
#     baremetal also switches _LIBUNWIND_REMEMBER_ALLOC to __builtin_alloca and
#     silences the fprintf-based debug log under NDEBUG.
#   * The base toolchain.cmake bakes -fno-exceptions -fno-rtti -nostdinc++ into
#     CMAKE_CXX_FLAGS_INIT (it is meant for the Embox flat app, not the C++
#     runtime). libcxxabi needs -fexceptions/-frtti; libunwind manages its own
#     -fno-exceptions/-fno-rtti. We override CMAKE_CXX_FLAGS_INIT here, sourcing
#     only the Embox libc include path + -D__EMBOX__ + target triple, and let
#     each runtime add the EH/RTTI flags it needs.
#   * libcxxabi's sources include <exception>, <stdexcept>, <typeinfo>,
#     <cstdlib>, <cstring> from libc++. Those come from the ENGINE'S OWN libc++
#     port (runtime/libcxx/include + the runtime/include_libc/cxx overlay) — the
#     same headers the engine, the runtime and every third-party C++ dep compile
#     against on this target, so there is exactly one libc++ in the image.
#     LLVM's own libcxx is not configured and not built here.

.DEFAULT_GOAL := all

LIBNAME := llvm-project
# LLVM monorepo: prefer LIB_SRC_DIR (CI / out-of-tree); fall back to the
# conventional builder location where the engine build host has it checked out.
LLVM_SRC ?= $(if $(wildcard $(LIB_SRC_DIR)/$(LIBNAME)),$(LIB_SRC_DIR)/$(LIBNAME),/build/toolchain-src/$(LIBNAME))

# Build inside OUT (writable) — same pattern as the simde rule in init-target.mk.
BUILD_DIR := $(TOOLCHAIN_OUTPUT_DIR)/_runtimes-build-embox

include ../common/utils/detect-platform.mk
include ../common/utils/init-shell.mk

# The runtimes superbuild needs the toolchain.cmake generated by init-target.mk
# (sets --target=aarch64-none-elf, -resource-dir, the Embox libc include path).
SP_TOOLCHAIN_FILE := $(TOOLCHAIN_OUTPUT_DIR)/toolchain.cmake
SP_INSTALL_PREFIX := $(TOOLCHAIN_OUTPUT_DIR)/sysroot

# The engine's libc++ port. libcxxabi's sources include <exception>,
# <stdexcept>, <typeinfo>, <cstdlib>, <cstring>, <version> ... and they must
# resolve to the SAME libc++ the engine and the deps use, or the exception /
# typeinfo classes libcxxabi defines land in a different namespace than the ones
# the rest of the image throws and catches. The port is a sprt-STL hybrid, so the
# whole four-directory chain is needed, in this order (same as runtime.mk's Embox
# branch):
#   include_libc/cxx    the overlay: __config_site (_LIBCPP_ABI_NAMESPACE=__sprt,
#                       the sprt feature switches), __assertion_handler, the
#                       sprt-backed <mutex>/<thread>/... retargeting headers
#   libcxx/include      the vendored libc++ headers themselves
#   include_libc        the sprt libc wrappers (<string.h> -> __sprt_* forwarders)
#   include             the sprt public root
# The private build headers libcxxabi reaches for as #include "include/<hdr>"
# (atomic_support.h, refstring.h, overridable_function.h) live in the port too,
# under libcxx/src/libcxx/ — hence the -I on that directory, and LIBCXXABI_LIBCXX_PATH
# pointed at the port so nothing at all is taken from the LLVM libcxx tree.
SP_RUNTIME_LIBCXX_DIR := $(SP_RUNTIME_ROOT)/libcxx
SP_LIBCXX_INCLUDES := \
	-isystem$(SP_RUNTIME_ROOT)/include_libc/cxx \
	-isystem$(SP_RUNTIME_LIBCXX_DIR)/include \
	-isystem$(SP_RUNTIME_ROOT)/include_libc \
	-isystem$(SP_RUNTIME_ROOT)/include \
	-I$(SP_RUNTIME_LIBCXX_DIR)/src/libcxx
# NB: LIBCXXABI_ADDITIONAL_COMPILE_FLAGS reaches target_compile_options(), which
# DEDUPLICATES repeated entries — a `-isystem;<dir>` list would collapse to one
# `-isystem` followed by four bare paths. Hence the joined `-isystem<dir>` spelling.

# Embox libc sysroot include dir (matches the include path baked into
# toolchain.cmake). Lowest priority (-idirafter, mirroring the deps build): the
# sprt wrappers above must be found first so libc++abi's <cstring> et al. route
# through __sprt_*, with Embox's own headers underneath them.
SP_EMBOX_LIBC_INCLUDES := $(SP_INSTALL_PREFIX)/usr/include

SP_RUNTIMES_FORCEINCLUDE := $(CURDIR)/embox-runtimes-forceinclude.h

# CXX flags shared by BOTH runtimes: the Embox libc at the bottom of the search
# order, __EMBOX__ defined, and exception/RTTI handling left to each runtime
# (libcxxabi forces -fexceptions/-frtti on its TUs, libunwind forces
# -fno-exceptions/-fno-rtti on its own). The base toolchain.cmake's
# -fno-exceptions/-fno-rtti/-nostdinc++ are dropped here — they are for the
# Embox flat app, not for the C++ ABI runtime.
# The libc++ port is NOT added here: libunwind must not see it (it compiles at
# -std=c++17, and the sprt <string.h> wrapper chain needs the C++20 concepts the
# port assumes), so the port rides on LIBCXXABI_ADDITIONAL_COMPILE_FLAGS below,
# which target_compile_options appends AFTER the per-target -std.
# Embox flat build has no PT_TLS segment and the engine/libsprt compile with
# -femulated-tls (thread_local lowers to __emutls_get_address). Match that
# here so libc++abi/libunwind stay linkable without a PT_TLS-aware linker
# script: -femulated-tls keeps the same __emutls_* ABI the engine uses.
# embox-runtimes-forceinclude.h: Embox abort() is not _Noreturn (libunwind
# -Werror=return-type) and pthread.h has no PTHREAD_RWLOCK_INITIALIZER.
SP_RUNTIMES_CXX_FLAGS := --target=$(SP_ARCH_TARGET_CLANG) -march=armv8-a \
	-idirafter $(SP_EMBOX_LIBC_INCLUDES) \
	-D__EMBOX__ -D_LDBL_EQ_DBL -fno-common -femulated-tls \
	-include $(SP_RUNTIMES_FORCEINCLUDE)
# libunwind's C TUs never see the libc++ port, so the Embox libc may stay at
# -isystem for them.
SP_RUNTIMES_C_FLAGS := --target=$(SP_ARCH_TARGET_CLANG) -march=armv8-a \
	-isystem $(SP_EMBOX_LIBC_INCLUDES) \
	-D__EMBOX__ -D_LDBL_EQ_DBL -fno-common -femulated-tls \
	-include $(SP_RUNTIMES_FORCEINCLUDE)

# LLVM_ENABLE_RUNTIMES: unwind + abi only. libcxx is neither configured nor built
# — the engine's own libc++ port is the STL on this target, and libcxxabi compiles
# against its headers (SP_LIBCXX_INCLUDES above), so there is one libc++ tree for
# the whole image: engine, runtime, third-party C++ deps and the ABI library all
# see the same <stdexcept>/<typeinfo>/<new> and the same std::__sprt ABI namespace
# (set by the port's own include_libc/cxx/__config_site, not by a cmake knob).
CONFIGURE := \
	-G "Ninja" \
	-S $(LLVM_SRC)/runtimes \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_TOOLCHAIN_FILE=$(realpath $(SP_TOOLCHAIN_FILE)) \
	-DCMAKE_INSTALL_PREFIX=$(SP_INSTALL_PREFIX) \
	-DCMAKE_INSTALL_LIBDIR=$(SP_INSTALL_PREFIX)/usr/lib \
	-DCMAKE_INSTALL_INCLUDEDIR=$(SP_INSTALL_PREFIX)/usr/include \
	-DLLVM_ENABLE_RUNTIMES="libunwind;libcxxabi" \
	-DLLVM_INCLUDE_TESTS=Off \
	-DLIBCXXABI_INCLUDE_TESTS=Off \
	-DLIBUNWIND_INCLUDE_TESTS=Off \
	-DLLVM_ENABLE_PIC=Off \
	-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=Off \
	-DLLVM_DEFAULT_TARGET_TRIPLE=$(SP_ARCH_TARGET_CLANG) \
	-DLLVM_HOST_TRIPLE=$(SP_ARCH_TARGET_CLANG) \
	-DLIBUNWIND_ENABLE_SHARED=Off \
	-DLIBUNWIND_ENABLE_STATIC=On \
	-DLIBUNWIND_SHARED_OUTPUT_NAME=unwind_shared \
	-DLIBUNWIND_ENABLE_THREADS=On \
	-DLIBUNWIND_USE_COMPILER_RT=On \
	-DLIBUNWIND_INSTALL_LIBRARY_DIR=usr/lib \
	-DLIBUNWIND_HAS_PTHREAD_THREAD=On \
	-DLIBUNWIND_IS_BAREMETAL=On \
	-DLIBCXXABI_ENABLE_SHARED=Off \
	-DLIBCXXABI_ENABLE_STATIC=On \
	-DLIBCXXABI_SHARED_OUTPUT_NAME=c++abi_shared \
	-DLIBCXXABI_ENABLE_THREADS=On \
	-DLIBCXXABI_ENABLE_EXCEPTIONS=On \
	-DLIBCXXABI_HAS_PTHREAD_API=On \
	-DLIBCXXABI_USE_LLVM_UNWINDER=On \
	-DLIBCXXABI_USE_COMPILER_RT=On \
	-DLIBCXXABI_ENABLE_STATIC_UNWINDER=Off \
	-DLIBCXXABI_ENABLE_NEW_DELETE_DEFINITIONS=Off \
	-DLIBCXXABI_INSTALL_LIBRARY_DIR=usr/lib \
	-DLIBCXXABI_LIBCXX_PATH=$(SP_RUNTIME_LIBCXX_DIR) \
	-DLIBCXXABI_ADDITIONAL_COMPILE_FLAGS="-nostdinc++;$(subst $() $(),;,$(SP_LIBCXX_INCLUDES))" \
	-DCMAKE_C_FLAGS="$(SP_RUNTIMES_C_FLAGS)" \
	-DCMAKE_CXX_FLAGS="$(SP_RUNTIMES_CXX_FLAGS)"
# Build only the two static archives (the runtimes-uber-targets would drag in
# check-runtimes / install machinery we do not use).
RUNTIMES_BUILD_TARGETS := cxxabi_static unwind_static

# Where the static archives land in the runtimes build tree. The runtimes
# superbuild puts them at <build>/lib/<name>.a (the `build/` prefix was an old
# guess; the actual ninja archive rules emit build/lib/libc++abi.a, but the
# runtimes-bins subdir layout drops the build/ prefix — verified against the
# generated build.ninja).
SP_LIBCXXABI_A := $(BUILD_DIR)/lib/libc++abi.a
SP_LIBUNWIND_A := $(BUILD_DIR)/lib/libunwind.a
SP_LIBCXXABI_DST := $(SP_INSTALL_PREFIX)/usr/lib/libc++abi.a
SP_LIBUNWIND_DST := $(SP_INSTALL_PREFIX)/usr/lib/libunwind.a

SP_AR := $(TOOLCHAIN_OUTPUT_DIR)/host/bin/llvm-ar

# stdlib_stdexcept.cpp defines the nine <stdexcept> classes' out-of-line members.
# The libc++ port deliberately moves those classes OUT of the canonical namespace
# into std::__sprt (libcxx/patch/0002-runtime-owned-std-symbols-versioned.patch)
# because the RUNTIME owns them — libcxx/src/SPRTCxxStdexcept.cpp defines exactly
# the same set. Compiled against the port's headers, libcxxabi's copy now lands in
# std::__sprt too, and both objects end up in the image (SPRTCxxStdexcept.o is
# always pulled, for __hash_memory / __vector_base_common / bad_optional_access):
# duplicate symbols at the flat-image link. Drop the member — nothing else inside
# libc++abi references those classes (verified with llvm-nm --undefined-only).
# libc++abi keeps everything the port DOES expect from it: the canonical
# std::exception hierarchy, type_info, terminate/new_handler and the __cxa_* ABI.
SP_LIBCXXABI_DROP_MEMBERS := stdlib_stdexcept.cpp.obj

all:
	@if [ -f "$(SP_LIBCXXABI_DST)" ] && [ -f "$(SP_LIBUNWIND_DST)" ]; then \
		echo "ok: libc++abi/libunwind already staged"; \
	else \
		set -e; \
		rm -rf "$(BUILD_DIR)"; \
		mkdir -p "$(BUILD_DIR)"; \
		cd "$(BUILD_DIR)" && cmake $(CONFIGURE) && \
			cmake --build . --config Release --target $(RUNTIMES_BUILD_TARGETS); \
		mkdir -p "$(dir $(SP_LIBCXXABI_DST))"; \
		cp -f "$(SP_LIBCXXABI_A)" "$(SP_LIBCXXABI_DST)"; \
		cp -f "$(SP_LIBUNWIND_A)" "$(SP_LIBUNWIND_DST)"; \
		$(SP_AR) d "$(SP_LIBCXXABI_DST)" $(SP_LIBCXXABI_DROP_MEMBERS); \
		rm -rf "$(BUILD_DIR)"; \
	fi

.PHONY: all
