/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/


#include "XLCommon.h"

#include "widgets/SearchPickerLayout.h"
#include "XLUiStyleResolver.h"

namespace STAPPLER_VERSIONIZED stappler::xenolith::app {

namespace {

static constexpr auto s_pickerCss = StringView(R"css(
search-picker {
	width: 260px;
	height: 34px;
	background-color: #292929;
	outline-color: rgba(255,255,255,.15);
	outline-width: 1px;
	border-radius: 6px;
}
search-picker:hover { outline-color: rgba(255,255,255,.30); }
search-picker:focus { outline-color: #fcb400; }
search-picker.open { outline-color: #fcb400; }
search-picker > label { color: #e8e8e8; font-size: 14px; }
search-picker > icon { width: 18px; height: 18px; color: #9a9aa4; }
search-picker-content {
	background-color: #202026;
	border-radius: 6px;
	outline-color: #3d3d3d;
	outline-width: 1px;
}
text-input {
	height: 30px;
	background-color: #292929;
	outline-width: 1px;
	outline-color: rgba(255,255,255,.15);
	border-radius: 4px;
	padding: 0 8px;
	color: #e8e8e8;
	font-size: 14px;
}
label { color: #e8e8e8; font-size: 14px; }
)css");

// The stems the payload is built from: enough of them that the list is a list, and all shaped like
// the identifiers this widget exists to find.
static const StringView s_prefixes[] = {
	StringView("Vertex"), StringView("Fragment"), StringView("Compute"), StringView("Material"),
	StringView("Texture"), StringView("Buffer"), StringView("Render"), StringView("Scene"),
	StringView("Node"), StringView("Sprite"), StringView("Label"), StringView("Layout"),
	StringView("Shadow"), StringView("Light"), StringView("Camera"), StringView("Particle"),
};

static const StringView s_suffixes[] = {
	StringView("Pass"), StringView("Attachment"), StringView("Descriptor"), StringView("Cache"),
	StringView("Builder"), StringView("Component"), StringView("System"), StringView("Queue"),
};

// The two strings that break a naive implementation, and are therefore never generated by accident.
static const StringView s_specials[] = {
	// Two astral characters: every index after them differs by one between code points and UTF-16.
	StringView("🔴🔵BlendState"),
	// The Turkish dotted capital I: its lowercase form is LONGER in bytes than the original, so a
	// Prefix-mode range taken from the lowered string does not transfer unchanged.
	StringView("İnputListener"),
	// A plain neighbour of the emoji row, so "the emoji row sorted above/below this" is checkable.
	StringView("BlendStateCache"),
};

Value ackValue(bool ok) {
	Value ret;
	ret.setBool(ok, "ok");
	return ret;
}

} // namespace

bool SearchPickerLayout::init() {
	if (!TestLayout::init()) {
		return false;
	}

	setStyleSheet(s_pickerCss);
	addSystem(Rc<ui::StyleResolver>::create(true));

	_search = addSystem(Rc<ui::SearchSystem>::create());
	// English, not the Simple default: Text mode exists for stemming and stop words, and Simple
	// has neither - a stand built on it would assert that "the" is a word like any other.
	_search->setLanguage(search::Language::English);
	// No debounce on the stand: a check drives one query and reads the answer, and a delay would
	// only mean every assertion has to wait out a timer it did not ask for.
	_search->setDebounce(TimeInterval());
	_search->addSource(Rc<ui::StaticSearchSource>::create(StringView("items"), _mode));
	rebuildSource();

	ui::SearchPickerConfig config;
	config.system = _search;
	config.sourceName = String("items");
	config.placeholder = String("Search…");
	config.params.limit = 64;

	// The embedded surface: the whole widget, with no window anywhere near it.
	auto contentConfig = config;
	contentConfig.onActivate = [this](const ui::SearchHit &hit) {
		++_activations;
		_lastActivation = hit.title;
	};

	_content = addChild(Rc<ui::SearchPickerContent>::create(sp::move(contentConfig)), ZOrder(1));
	_content->setName("picker-content");
	_content->setContentSize(Size2(320.0f, 300.0f));

	_picker = addChild(Rc<ui::SearchPicker>::create(), ZOrder(2));
	_picker->setName("picker");
	_picker->setPlaceholder("Pick a type…");

	auto popupConfig = config;
	popupConfig.stylesheetSource = s_pickerCss.str<Interface>();
	popupConfig.idPrefix = String("search-picker-test");
	popupConfig.title = String("Search picker test");
	popupConfig.onActivate = [this](const ui::SearchHit &hit) {
		++_activations;
		_lastActivation = hit.title;
	};
	_picker->setConfig(sp::move(popupConfig));

	// The neighbour: while the surface is up it must not see a single arrow.
	_neighbour = addChild(Rc<ui::TextInput>::create(), ZOrder(3));
	_neighbour->setName("neighbour");
	_neighbour->setText("abcdef");
	_neighbour->setCaretBlink(false);

	return true;
}

void SearchPickerLayout::rebuildSource() {
	auto source = dynamic_cast<ui::StaticSearchSource *>(_search->getSource(StringView("items")));
	if (!source) {
		return;
	}

	Vector<ui::SearchItem> items;
	int64_t id = 1;

	for (auto &special : s_specials) {
		ui::SearchItem item;
		item.id = id++;
		item.tag = 1;
		item.title = special.str<Interface>();
		item.subtitle = String("special");
		item.text = toString(special, " a deliberately awkward name for the highlight arithmetic");
		item.data.setString(special, "id");
		items.emplace_back(sp::move(item));
	}

	for (auto &prefix : s_prefixes) {
		for (auto &suffix : s_suffixes) {
			ui::SearchItem item;
			item.id = id++;
			item.tag = 0;
			item.title = toString(prefix, suffix);
			item.subtitle = toString(prefix, " ", suffix);
			item.text = toString("A ", suffix, " that works on ", prefix, " data.");
			item.data.setString(item.title, "id");
			items.emplace_back(sp::move(item));
		}
	}

	source->setMatchMode(_mode);
	source->setTypoTolerance(_typoTolerance);
	source->setItems(sp::move(items));
}

void SearchPickerLayout::handleContentSizeDirty() {
	TestLayout::handleContentSizeDirty();

	const float top = getWorkTop() - 20.0f;

	if (_picker) {
		_picker->setAnchorPoint(Vec2(0.0f, 1.0f));
		_picker->setPosition(Vec2(48.0f, top));
	}
	if (_neighbour) {
		_neighbour->setAnchorPoint(Vec2(0.0f, 1.0f));
		_neighbour->setPosition(Vec2(48.0f, top - 48.0f));
		_neighbour->setContentSize(Size2(260.0f, 34.0f));
	}
	if (_content) {
		_content->setAnchorPoint(Vec2(0.0f, 1.0f));
		_content->setPosition(Vec2(360.0f, top));
	}
}

Value SearchPickerLayout::encodeContent(ui::SearchPickerContent *content) const {
	Value ret;
	if (!content) {
		return ret;
	}

	ret.setString(content->getQuery(), "query");
	ret.setBool(content->isPending(), "pending");

	auto selected = content->getSelected();
	ret.setInteger(selected == maxOf<size_t>() ? -1 : int64_t(selected), "selected");

	Value rows;
	for (auto &hit : content->getHits()) {
		Value row;
		row.setString(hit.title, "title");
		row.setInteger(hit.id, "id");
		// A float would come back as a float and make an expected-order table depend on formatting.
		// The ORDER is what is asserted, so the score is reported rounded.
		row.setInteger(int64_t(std::lround(hit.score * 1000.0f)), "score");

		Value ranges;
		for (auto &range : hit.ranges) {
			Value r;
			// UTF-16 units, which is what Label::setTextRangeStyle counts in - and the whole point
			// of the emoji row is that these are NOT the code point indices.
			r.setInteger(int64_t(range.first), "start");
			r.setInteger(int64_t(range.second), "length");
			ranges.addValue(sp::move(r));
		}
		row.setValue(sp::move(ranges), "ranges");
		rows.addValue(sp::move(row));
	}
	ret.setValue(sp::move(rows), "rows");
	return ret;
}

Value SearchPickerLayout::encodeState() const {
	Value ret;
	ret.setValue(encodeContent(_content), "content");

	if (_picker) {
		Value picker;
		picker.setString(_picker->getValue(), "value");
		picker.setString(_picker->getValueTitle(), "title");
		picker.setBool(_picker->isOpen(), "open");
		picker.setBool(_picker->isFocused(), "focused");
		if (auto popup = _picker->getPopup()) {
			picker.setString(popup->getId(), "popupId");
			picker.setBool(popup->isNative(), "popupNative");
		}
		ret.setValue(sp::move(picker), "picker");
	}

	switch (_mode) {
	case ui::SearchMatchMode::Subsequence: ret.setString("subsequence", "mode"); break;
	case ui::SearchMatchMode::Prefix: ret.setString("prefix", "mode"); break;
	case ui::SearchMatchMode::Text: ret.setString("text", "mode"); break;
	}
	ret.setBool(_typoTolerance, "typoTolerance");

	ret.setInteger(int64_t(_activations), "activations");
	ret.setString(_lastActivation, "lastActivation");

	if (_neighbour) {
		ret.setString(_neighbour->getText(), "neighbourText");
		ret.setInteger(int64_t(_neighbour->getCursor().start), "neighbourCursor");
		ret.setBool(_neighbour->isFocused(), "neighbourFocused");
	}
	return ret;
}

void SearchPickerLayout::registerCommands() {
	addCommand("state", "Report the embedded surface, the control and the activation log",
			[this](Value &&) { return encodeState(); });

	addCommand("query", "Type into the embedded surface's query line: {value}",
			[this](Value &&args) {
		if (!_content || !_content->getQueryInput()) {
			return ackValue(false);
		}
		_content->getQueryInput()->setText(static_cast<const Value &>(args).getString("value"));
		// setText on an unfocused field writes locally and does not go through the IME echo, so the
		// change callback does not fire - the query is run explicitly.
		_content->refresh();
		return ackValue(true);
	});

	addCommand("select", "Move the selection by {delta}, or set it to {index}",
			[this](Value &&args) {
		if (!_content) {
			return ackValue(false);
		}
		const Value &a = args;
		if (a.isInteger("index")) {
			return ackValue(_content->setSelected(size_t(a.getInteger("index"))));
		}
		return ackValue(_content->moveSelection(int32_t(a.getInteger("delta"))));
	});

	addCommand("activate", "Report the selected row through the activate callback",
			[this](Value &&) { return ackValue(_content && _content->activateSelected()); });

	addCommand("focus-query", "Put the caret in the embedded surface's query line",
			[this](Value &&) {
		if (_content && _content->getQueryInput()) {
			_content->getQueryInput()->focus();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("focus-neighbour", "Put the caret in the field beside the control",
			[this](Value &&) {
		if (_neighbour) {
			_neighbour->focus();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("open", "Open the control's popup", [this](Value &&) {
		if (_picker) {
			_picker->focus();
			return ackValue(_picker->open());
		}
		return ackValue(false);
	});

	addCommand("close", "Dismiss the control's popup", [this](Value &&) {
		if (_picker) {
			_picker->close();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("mode", "Rebuild the source in a match mode: {value=subsequence|prefix|text}",
			[this](Value &&args) {
		auto value = static_cast<const Value &>(args).getString("value");
		if (value == "prefix") {
			_mode = ui::SearchMatchMode::Prefix;
		} else if (value == "text") {
			_mode = ui::SearchMatchMode::Text;
		} else if (value == "subsequence") {
			_mode = ui::SearchMatchMode::Subsequence;
		} else {
			return ackValue(false);
		}
		rebuildSource();
		if (_content) {
			_content->refresh();
		}
		return ackValue(true);
	});

	addCommand("typo", "Turn typo tolerance on or off: {value}", [this](Value &&args) {
		_typoTolerance = static_cast<const Value &>(args).getBool("value");
		rebuildSource();
		if (_content) {
			_content->refresh();
		}
		return ackValue(true);
	});
}

} // namespace stappler::xenolith::app
