/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/


#include "XLCommon.h"

#include "widgets/SearchPickerLayout.h"
#include "XLUiStyleResolver.h"

namespace STAPPLER_VERSIONIZED stappler::xenolith::app {

namespace {

static constexpr auto s_pickerCss = StringView(R"css(
search-picker {
	width: 260px;
	height: 34px;
	background-color: #292929;
	outline-color: rgba(255,255,255,.15);
	outline-width: 1px;
	border-radius: 6px;
}
search-picker:hover { outline-color: rgba(255,255,255,.30); }
search-picker:focus { outline-color: #fcb400; }
search-picker.open { outline-color: #fcb400; }
search-picker > label { color: #e8e8e8; font-size: 14px; }
search-picker > icon { width: 18px; height: 18px; color: #9a9aa4; }
search-picker-content {
	background-color: #202026;
	border-radius: 6px;
	outline-color: #3d3d3d;
	outline-width: 1px;
}
text-input {
	height: 30px;
	background-color: #292929;
	outline-width: 1px;
	outline-color: rgba(255,255,255,.15);
	border-radius: 4px;
	padding: 0 8px;
	color: #e8e8e8;
	font-size: 14px;
}
label { color: #e8e8e8; font-size: 14px; }
)css");

// The stems the payload is built from: enough of them that the list is a list, and all shaped like
// the identifiers this widget exists to find.
static const StringView s_prefixes[] = {
	StringView("Vertex"), StringView("Fragment"), StringView("Compute"), StringView("Material"),
	StringView("Texture"), StringView("Buffer"), StringView("Render"), StringView("Scene"),
	StringView("Node"), StringView("Sprite"), StringView("Label"), StringView("Layout"),
	StringView("Shadow"), StringView("Light"), StringView("Camera"), StringView("Particle"),
};

static const StringView s_suffixes[] = {
	StringView("Pass"), StringView("Attachment"), StringView("Descriptor"), StringView("Cache"),
	StringView("Builder"), StringView("Component"), StringView("System"), StringView("Queue"),
};

// The two strings that break a naive implementation, and are therefore never generated by accident.
static const StringView s_specials[] = {
	// Two astral characters: every index after them differs by one between code points and UTF-16.
	StringView("🔴🔵BlendState"),
	// The Turkish dotted capital I: its lowercase form is LONGER in bytes than the original, so a
	// Prefix-mode range taken from the lowered string does not transfer unchanged.
	StringView("İnputListener"),
	// A plain neighbour of the emoji row, so "the emoji row sorted above/below this" is checkable.
	StringView("BlendStateCache"),
};

Value ackValue(bool ok) {
	Value ret;
	ret.setBool(ok, "ok");
	return ret;
}

} // namespace

bool SearchPickerLayout::init() {
	if (!TestLayout::init()) {
		return false;
	}

	setStyleSheet(s_pickerCss);
	addSystem(Rc<ui::StyleResolver>::create(true));

	_search = addSystem(Rc<ui::SearchSystem>::create());
	// English, not the Simple default: Text mode exists for stemming and stop words, and Simple
	// has neither - a stand built on it would assert that "the" is a word like any other.
	_search->setLanguage(search::Language::English);
	// No debounce on the stand: a check drives one query and reads the answer, and a delay would
	// only mean every assertion has to wait out a timer it did not ask for.
	_search->setDebounce(TimeInterval());
	_search->addSource(Rc<ui::StaticSearchSource>::create(StringView("items"), _mode));
	rebuildSource();

	ui::SearchPickerConfig config;
	config.system = _search;
	config.sourceName = String("items");
	config.placeholder = String("Search…");
	config.params.limit = 64;

	// The embedded surface: the whole widget, with no window anywhere near it.
	auto contentConfig = config;
	contentConfig.onActivate = [this](const ui::SearchHit &hit) {
		++_activations;
		_lastActivation = hit.title;
	};

	_content = addChild(Rc<ui::SearchPickerContent>::create(sp::move(contentConfig)), ZOrder(1));
	_content->setName("picker-content");
	_content->setContentSize(Size2(320.0f, 300.0f));

	/* THE SAME WIDGET, GROUPED. The palette case: with nothing typed there is nothing to rank and a
	list of a hundred names in some deterministic order is a list nobody reads, so the categories
	ARE the answer; as soon as something is typed the ranking is the answer again and the same
	widget collapses to a flat list at depth 0.
	
	Beside the flat one rather than instead of it, so that the two paths cannot drift apart
	unnoticed - which is the same reason the popup surface is here beside the embedded one. */
	_baseConfig = config;
	buildGrouped(StringView());

	_picker = addChild(Rc<ui::SearchPicker>::create(), ZOrder(2));
	_picker->setName("picker");
	_picker->setPlaceholder("Pick a type…");

	auto popupConfig = config;
	popupConfig.stylesheetSource = s_pickerCss.str<Interface>();
	popupConfig.idPrefix = String("search-picker-test");
	popupConfig.title = String("Search picker test");
	popupConfig.onActivate = [this](const ui::SearchHit &hit) {
		++_activations;
		_lastActivation = hit.title;
	};
	_picker->setConfig(sp::move(popupConfig));

	// The neighbour: while the surface is up it must not see a single arrow.
	_neighbour = addChild(Rc<ui::TextInput>::create(), ZOrder(3));
	_neighbour->setName("neighbour");
	_neighbour->setText("abcdef");
	_neighbour->setCaretBlink(false);

	return true;
}

/* A FRESH grouped surface, because `highlight` is settled when the content is built.

Rebuilt rather than mutated: the highlight is what the list opens ON, and a value arriving after the
list is already showing is a different question (that one is `setSelected`). A stand that mutated it
would be asserting about a path no caller has. */
void SearchPickerLayout::buildGrouped(StringView highlight) {
	if (_grouped) {
		_grouped->removeFromParent();
		_grouped = nullptr;
	}

	auto groupedConfig = _baseConfig;
	groupedConfig.grouped = true;
	groupedConfig.highlight = highlight.str<Interface>();
	groupedConfig.onActivate = [this](const ui::SearchHit &hit) {
		++_activations;
		_lastActivation = hit.title;
	};

	_grouped = addChild(Rc<ui::SearchPickerContent>::create(sp::move(groupedConfig)), ZOrder(1));
	_grouped->setName("picker-grouped");
	_grouped->setContentSize(Size2(320.0f, 300.0f));
	_contentSizeDirty = true;
}

void SearchPickerLayout::rebuildSource() {
	auto source = dynamic_cast<ui::StaticSearchSource *>(_search->getSource(StringView("items")));
	if (!source) {
		return;
	}

	Vector<ui::SearchItem> items;
	int64_t id = 1;

	for (auto &special : s_specials) {
		ui::SearchItem item;
		item.id = id++;
		item.tag = 1;
		item.title = special.str<Interface>();
		item.subtitle = String("special");
		item.text = toString(special, " a deliberately awkward name for the highlight arithmetic");
		item.data.setString(special, "id");
		// The grouped surface reads this key and nothing else does, so it is additive: `category`
		// is what SearchPickerConfig::group falls back to, and SearchItem::data already carried it
		// through untouched.
		item.data.setString(StringView("Awkward"), "category");
		items.emplace_back(sp::move(item));
	}

	for (auto &prefix : s_prefixes) {
		for (auto &suffix : s_suffixes) {
			ui::SearchItem item;
			item.id = id++;
			item.tag = 0;
			item.title = toString(prefix, suffix);
			item.subtitle = toString(prefix, " ", suffix);
			item.text = toString("A ", suffix, " that works on ", prefix, " data.");
			item.data.setString(item.title, "id");
			item.data.setString(suffix, "category");
			items.emplace_back(sp::move(item));
		}
	}

	source->setMatchMode(_mode);
	source->setTypoTolerance(_typoTolerance);
	source->setItems(sp::move(items));
}

void SearchPickerLayout::handleContentSizeDirty() {
	TestLayout::handleContentSizeDirty();

	const float top = getWorkTop() - 20.0f;

	if (_picker) {
		_picker->setAnchorPoint(Vec2(0.0f, 1.0f));
		_picker->setPosition(Vec2(48.0f, top));
	}
	if (_neighbour) {
		_neighbour->setAnchorPoint(Vec2(0.0f, 1.0f));
		_neighbour->setPosition(Vec2(48.0f, top - 48.0f));
		_neighbour->setContentSize(Size2(260.0f, 34.0f));
	}
	if (_grouped) {
		_grouped->setAnchorPoint(Vec2(0.0f, 1.0f));
		_grouped->setPosition(Vec2(700.0f, top));
	}
	if (_content) {
		_content->setAnchorPoint(Vec2(0.0f, 1.0f));
		_content->setPosition(Vec2(360.0f, top));
	}
}

Value SearchPickerLayout::encodeContent(ui::SearchPickerContent *content) const {
	Value ret;
	if (!content) {
		return ret;
	}

	ret.setString(content->getQuery(), "query");
	ret.setBool(content->isPending(), "pending");

	auto selected = content->getSelected();
	ret.setInteger(selected == maxOf<size_t>() ? -1 : int64_t(selected), "selected");

	Value rows;
	for (auto &hit : content->getHits()) {
		Value row;
		row.setString(hit.title, "title");
		row.setInteger(hit.id, "id");
		// A float would come back as a float and make an expected-order table depend on formatting.
		// The ORDER is what is asserted, so the score is reported rounded.
		row.setInteger(int64_t(std::lround(hit.score * 1000.0f)), "score");

		Value ranges;
		for (auto &range : hit.ranges) {
			Value r;
			// UTF-16 units, which is what Label::setTextRangeStyle counts in - and the whole point
			// of the emoji row is that these are NOT the code point indices.
			r.setInteger(int64_t(range.first), "start");
			r.setInteger(int64_t(range.second), "length");
			ranges.addValue(sp::move(r));
		}
		row.setValue(sp::move(ranges), "ranges");
		rows.addValue(sp::move(row));
	}
	ret.setValue(sp::move(rows), "rows");
	return ret;
}

/* What the grouped surface is SHOWING, read from its own rows.

Not the hit list: a category is a row that stands for no hit, and expanding one shifts every row
after it - which is exactly the arithmetic a caller keeping a vector beside the model gets wrong. So
the display is reported as the display, and the mapping back to a hit is reported with it. */
Value SearchPickerLayout::encodeRows(ui::SearchPickerContent *content) const {
	Value rows;
	if (!content) {
		return rows;
	}

	auto tree = content->getTree();
	for (size_t i = 0; i < content->getRowCount(); ++i) {
		Value row;
		auto hit = content->getHitForRow(i);
		row.setBool(hit == maxOf<size_t>(), "category");
		if (hit == maxOf<size_t>()) {
			row.setBool(content->isRowExpanded(i), "expanded");
		} else {
			row.setInteger(int64_t(hit), "hit");
			row.setString(content->getHits()[hit].title, "title");
		}
		if (hit == maxOf<size_t>()) {
			// From the widget, not from the tree node underneath it: what a category row SAYS is
			// the one thing about it that is not derivable from the hits, and reaching past the
			// widget for it was a guess about a structure the widget owns.
			row.setString(content->getRowTitle(i), "title");
		}
		if (tree) {
			if (auto r = tree->getRow(i)) {
				row.setInteger(int64_t(r->depth), "depth");
			}
		}
		rows.addValue(sp::move(row));
	}
	return rows;
}

Value SearchPickerLayout::encodeState() const {
	Value ret;
	ret.setValue(encodeContent(_content), "content");

	Value grouped = encodeContent(_grouped);
	grouped.setValue(encodeRows(_grouped), "display");
	if (_grouped) {
		grouped.setBool(_grouped->isGrouping(), "grouping");
		// WHERE the selection shows, which in a tree is not WHAT is selected: a hit under a closed
		// category is selected and at no row, and "nothing is selected" is also at no row.
		const auto row = _grouped->getRowForHit(_grouped->getSelected());
		grouped.setInteger(row == maxOf<size_t>() ? -1 : int64_t(row), "selectedRow");
		if (auto tree = _grouped->getTree()) {
			const auto shown = tree->getSelectedRow();
			grouped.setInteger(shown == maxOf<size_t>() ? -1 : int64_t(shown), "treeRow");
		}
	}
	ret.setValue(sp::move(grouped), "grouped");

	if (_picker) {
		Value picker;
		picker.setString(_picker->getValue(), "value");
		picker.setString(_picker->getValueTitle(), "title");
		picker.setBool(_picker->isOpen(), "open");
		picker.setBool(_picker->isFocused(), "focused");
		if (auto popup = _picker->getPopup()) {
			picker.setString(popup->getId(), "popupId");
			picker.setBool(popup->isNative(), "popupNative");
			// The panel the surface was built AROUND. A popup's layout is a wrapper, so this is not
			// reachable by casting getLayout() - and a caller that tried got null, which is also
			// what a closed picker looks like.
			picker.setBool(popup->getPanel() != nullptr, "popupHasPanel");
		}
		// Typed back to what the picker asked to have built. Null while it is closed.
		if (auto content = _picker->getContent()) {
			picker.setInteger(int64_t(content->getHits().size()), "popupHits");
			picker.setString(content->getQuery(), "popupQuery");
			const auto sel = content->getSelected();
			picker.setInteger(sel == maxOf<size_t>() ? -1 : int64_t(sel), "popupSelected");
			if (sel != maxOf<size_t>()) {
				picker.setString(content->getHits()[sel].title, "popupSelectedTitle");
			}
		}
		ret.setValue(sp::move(picker), "picker");
	}

	switch (_mode) {
	case ui::SearchMatchMode::Subsequence: ret.setString("subsequence", "mode"); break;
	case ui::SearchMatchMode::Prefix: ret.setString("prefix", "mode"); break;
	case ui::SearchMatchMode::Text: ret.setString("text", "mode"); break;
	}
	ret.setBool(_typoTolerance, "typoTolerance");

	ret.setInteger(int64_t(_activations), "activations");
	ret.setString(_lastActivation, "lastActivation");

	if (_neighbour) {
		ret.setString(_neighbour->getText(), "neighbourText");
		ret.setInteger(int64_t(_neighbour->getCursor().start), "neighbourCursor");
		ret.setBool(_neighbour->isFocused(), "neighbourFocused");
	}
	return ret;
}

void SearchPickerLayout::registerCommands() {
	addCommand("state", "Report the embedded surface, the control and the activation log",
			[this](Value &&) { return encodeState(); });

	addCommand("query", "Type into the embedded surface's query line: {value}",
			[this](Value &&args) {
		if (!_content || !_content->getQueryInput()) {
			return ackValue(false);
		}
		_content->getQueryInput()->setText(static_cast<const Value &>(args).getString("value"));
		// setText on an unfocused field writes locally and does not go through the IME echo, so the
		// change callback does not fire - the query is run explicitly.
		_content->refresh();
		return ackValue(true);
	});

	addCommand("select", "Move the selection by {delta}, or set it to {index}",
			[this](Value &&args) {
		if (!_content) {
			return ackValue(false);
		}
		const Value &a = args;
		if (a.isInteger("index")) {
			return ackValue(_content->setSelected(size_t(a.getInteger("index"))));
		}
		return ackValue(_content->moveSelection(int32_t(a.getInteger("delta"))));
	});

	addCommand("activate", "Report the selected row through the activate callback",
			[this](Value &&) { return ackValue(_content && _content->activateSelected()); });

	// ---- the grouped surface ----------------------------------------------------------------

	addCommand("grouped-query", "Type into the grouped surface's query line: {value}",
			[this](Value &&args) {
		if (!_grouped || !_grouped->getQueryInput()) {
			return ackValue(false);
		}
		_grouped->getQueryInput()->setText(static_cast<const Value &>(args).getString("value"));
		// setText does not fire the change callback, so the query is run explicitly - the same
		// thing the flat surface's `query` does.
		_grouped->refresh();
		return ackValue(true);
	});

	addCommand("grouped-select", "Move the grouped selection by {delta}, or set it to {index}",
			[this](Value &&args) {
		if (!_grouped) {
			return ackValue(false);
		}
		const Value &a = args;
		if (a.hasValue("index")) {
			// -1 is `setSelected(maxOf)`: NOTHING SELECTED, which is public API and a state a
			// grouped tree used to draw as a highlighted first category.
			const auto index = a.getInteger("index");
			return ackValue(_grouped->setSelected(index < 0 ? maxOf<size_t>() : size_t(index)));
		}
		return ackValue(_grouped->moveSelection(int32_t(a.getInteger("delta"))));
	});

	addCommand("grouped-highlight", "Rebuild the grouped surface opened ON a value: {value}",
			[this](Value &&args) {
		buildGrouped(static_cast<const Value &>(args).getString("value"));
		return ackValue(_grouped != nullptr);
	});

	addCommand("grouped-toggle", "Open or close the grouped surface's category row {row}",
			[this](Value &&args) {
		return ackValue(_grouped
				&& _grouped->toggleRow(size_t(static_cast<const Value &>(args).getInteger("row"))));
	});

	addCommand("grouped-activate", "Report the grouped selection through the activate callback",
			[this](Value &&) { return ackValue(_grouped && _grouped->activateSelected()); });

	addCommand("focus-query", "Put the caret in the embedded surface's query line",
			[this](Value &&) {
		if (_content && _content->getQueryInput()) {
			_content->getQueryInput()->focus();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("focus-neighbour", "Put the caret in the field beside the control",
			[this](Value &&) {
		if (_neighbour) {
			_neighbour->focus();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("open", "Open the control's popup", [this](Value &&) {
		if (_picker) {
			_picker->focus();
			return ackValue(_picker->open());
		}
		return ackValue(false);
	});

	addCommand("close", "Dismiss the control's popup", [this](Value &&) {
		if (_picker) {
			_picker->close();
			return ackValue(true);
		}
		return ackValue(false);
	});

	addCommand("mode", "Rebuild the source in a match mode: {value=subsequence|prefix|text}",
			[this](Value &&args) {
		auto value = static_cast<const Value &>(args).getString("value");
		if (value == "prefix") {
			_mode = ui::SearchMatchMode::Prefix;
		} else if (value == "text") {
			_mode = ui::SearchMatchMode::Text;
		} else if (value == "subsequence") {
			_mode = ui::SearchMatchMode::Subsequence;
		} else {
			return ackValue(false);
		}
		rebuildSource();
		if (_content) {
			_content->refresh();
		}
		return ackValue(true);
	});

	addCommand("typo", "Turn typo tolerance on or off: {value}", [this](Value &&args) {
		_typoTolerance = static_cast<const Value &>(args).getBool("value");
		rebuildSource();
		if (_content) {
			_content->refresh();
		}
		return ackValue(true);
	});
}

} // namespace stappler::xenolith::app
