= Поддержка Windows

Windows - не POSIX платформа, и потому её поддержка всегда особенная. Windows это платформа без стандартной библиотеки C, а её заместитель, UCRT, во многом не совместима с со стандартными.

Путём долгих мучений, мы пришли к выводу, что наилучший вариант для Xenolith - отказаться от UCRT и реализовать стандартную libc с нуля.

Причин тому несколько:
- Постоянные проблемы несоответствия POSIX libc и UCRT.
- Лицензионные ограничения, которые не позволяют нам поставлять UCRT вместе со своими библиотеками в составе SDK.
- Невозможность использовать UCRT с мета-загрузчиком (об этом далее)
- С UCRT невозможно выстроить настоящую кроссплатформенную разработку, если считать Wine и ReactOS полноценными платформами на базе WinAPI. Считать так нас вынуждает политическая ситуация вокруг Microsoft и их продуктов.

Раз уж мы отказываемся от UCRT, логично исключить зависимость от Windows SDK в в целом, чтобы поставка Stappler SDK работала полностью автономно. Более того, работала на Wine и ReactOS.

== Текущее состояние

- Реализованы все требуемые функции для работы как POSIX libc.
- malloc работает через jemalloc.
- платформно-независимые функции libc реализованы на основе musl libc 
- Частично реализованы специфические функции UCRT
- Частично реализована поддержка локалей на базе Unicode.
- Реализованы базовые функции Microsoft C++ ABI (базовые операторы, RTTI), кроме исключений
- Сборка полностью совместима с Windows 10/11 и Wine
- Windows SDK и заголовки не требуются для сборки
- Сборка тестируется на Linux и Windows

== Задача первая: собрать исполняемый файл без Windows SDK

Задача вполне решаемая, готовый код можно посмотреть [здесь](https://gist.github.com/SBKarr/0e0dfc7675d99405ca2a53d24a6b9925)

Первая проблема, без WinAPI у нас нет импортных библиотек, которые позволяют компилятору связывать приложение с DLL. Решить её можно, если мы получаем возможность динамически загружать функции из DLL, и знаем их описание из заголовка. Однако, без ничего, у нас, казалось бы, нет возможности вызвать функции из kernel32.dll, чтобы загружать другие функции.

В отличии от POSIX платформ, Windows не требует специального кода для запуска приложения (crt0.o и других). Вместо этого, в код приложения автоматически загружаются библиотеки системы, как минимум kernel32.dll и ntdll.dll. Необходимо лишь найти их актуальный адрес в приложении, а после - получить доступ к функциям `LoadLibrary` и `GetProcAddress`.

Делается это на платформе Amd64 через чтение системной записи из регистра процессора %GS, и поиска в ней необходимых адресов загруженных DLL, где будут и ntdll.dll, и kernel32.dll.

Этого достаточно, чтобы собрать Hello world, не имея ни Windows SDK, ни библиотек, ни заголовков, только компилятор, который может компилировать код для Windows.

А если мы можем собрать и запустить Hello World, мы можем запустить всё, что угодно, верно?

А ещё это значит, что нам больше не нужны Windows и Microsoft для компиляции под Windows.

== Задача вторая: мета-загрузчик

Имея доступ к `LoadLibrary` и `GetProcAddress`, мы можем загрузить любую системную DLL, но как узнать, где какая функция определена?

В этом нам поможет подход мета-загрузчика, известный, например, по Vulkan Volk. Воспользуемся llvm-nm для этого:

[source,sh]
----
llvm-nm --dynamic --defined-only system_dll.dll
----

Теперь у нас есть список символов в DLL, и нехитрыми преобразованием с регулярными выражениями можем сгенерировать таблицы символов, по которым может работать наш загрузчик.

Далее, процесс предельно прост: берём описание функции из публичной документации, создаём такую же функцию, но в качестве тела используем интерфейс загрузчика, например:

[source,c++]
----
BOOL CloseHandle(HANDLE hObject) {
	auto loader = sprt::DllLoader::get();
	return loader->kernelbase.call<decltype(&CloseHandle)>(loader->kernelbase.CloseHandle, hObject);
}
----

Процесс легко автоматизируется нейросетью.

После этого, мы имеем полностью функциональные вызовы WinAPI и возможность использовать любую известную нам DLL.

== Задача третья: libc и mainCRTStartup

Реальным приложениям нужно намного больше, чем просто HelloWorld, и здесь вступают в силу публичные соглашения между системой и компилятором, ABI системы. Прелесть в том, что эти соглашения именно публичные, и мы легко можем посмотреть, как их реализует компилятор, чтобы подстроить под него библиотеку.

Тем проще этот процесс, когда нейросети могут искать в коде по запросу на человеческом языке, вместо часа чтения кода самостоятельно с отслеживанием вызовов, нейросеть находит нужное за минуту.

Итак, ключевые моменты, которые нужно знать:

* Как инициализируются и деинициализируются статические переменные
* Как инициализируются и деинициализируются локальные переменные потока
* Как реализуется RTTI
* Как реализуются исключения
* Какие дополнительные требования предъявляет система

=== Статические переменные

В исполняемом формате Windows, адреса конструкторов и деструкторов помещаются в специальные секции файла, читать из которых можно с помощью атрибута `__declspec(allocate("SECTION_NAME"))`. Помеченная таким образом переменная вместо назначенного ей значения получает доступ к записи в исполняемом файле.

[source,c++]
----
static __declspec(allocate(".CRT$XIA")) __ifuncptr __c_init_start[] = {nullptr};
static __declspec(allocate(".CRT$XIZ")) __ifuncptr __c_init_end[] = {nullptr};
static __declspec(allocate(".CRT$XCA")) __funcptr __cxx_init_start[] = {nullptr};
static __declspec(allocate(".CRT$XCZ")) __funcptr __cxx_init_end[] = {nullptr};

static __declspec(allocate(".CRT$XPA")) __funcptr __c_preterm_start[] = {nullptr};
static __declspec(allocate(".CRT$XPZ")) __funcptr __c_preterm_end[] = {nullptr};
static __declspec(allocate(".CRT$XTA")) __funcptr __c_term_start[] = {nullptr};
static __declspec(allocate(".CRT$XTZ")) __funcptr __c_term_end[] = {nullptr};

int __init(__funcptr *__begin, __funcptr *__end) {
	while (__begin < __end) {
		if (*__begin != nullptr) {
			(*__begin)();
		}
		++__begin;
	}
	return 0;
}
----

Получив значения, достаточно просто вызвать их в цикле, один раз при запуске, один раз при остановке. Отвечает за это точка входа в приложение, `mainCRTStartup`.

Важно понимать, что инициализация статических переменных нужна только в том случае, если она нетривиальна. Инициализация нулями или заранее известными данными для неизменного поля выполняется автоматически.

=== Локальные переменные потока

С ними ситуация сложнее. Основа для реализации изначально та же, загрузка адресов конструкторов из специальных секций, однако, в дну специальную секцию `.CRT$XLC` значение нужно записать.

[source,c++]
----
static __declspec(allocate(".CRT$XLC")) PIMAGE_TLS_CALLBACK __tls_delegate = __dyn_tls_init;
static __declspec(allocate(".CRT$XDA")) __funcptr __tls_init_start_fn = nullptr;
static __declspec(allocate(".CRT$XDZ")) __funcptr __tls_init_end_fn = nullptr;
----

Дело в том, что, по умолчанию, приложение отвечает за инициализацию локальных переменных только главного потока. Для других потоков, инициализацию выполняет непосредственно загрузчик ОС, но он может только делегировать её, поскольку не знает реальных деталей приложения. Именно функцию, которой делегируется эта задача, мы и записываем в секцию `.CRT$XLC`.

Задача перекладывается на загрузчик потому, что в современных приложениях локальные переменные потока инициализируются только перед моментом их использования, а не автоматически при запуске потока.

Также, как для статических переменных, инициализации требуют только сложные значения. Это позволяет реализовать переменную, которая будет локальной для потока, и будет защищать от множественной инициализации.

В итоге, инициализация состоит из двух функций и одной переменной. Имя `__dyn_tls_on_demand_init` определено в API, эта функция должна быть реализована.

[source,c++]
----
thread_local bool __tls_guard = false;

void __dyn_tls_init(PVOID, DWORD dwReason, LPVOID) noexcept {
	if (dwReason != DLL_THREAD_ATTACH || __tls_guard == true) {
		return;
	}

	__tls_guard = true;

	__init(&__tls_init_start_fn, &__tls_init_end_fn);
}

void __dyn_tls_on_demand_init() noexcept {
	__dyn_tls_init(nullptr, DLL_THREAD_ATTACH, nullptr); //
}
----

Списка деструкторов для локальных переменных потока нет, вместо этого деструкторы регистрируются при инициализации с помощью определённой в ABI функции `__tlregdtor`. После этого, деструкторы должны быть вызваны приложением в порядке, обратном регистрации. Удобнее всего хранить их в связном списке, расположенном в локальной памяти потока, но с тривиальной реализацией, чтобы для него не требовался собственный конструктор и деструктор.

[source,c++]
----
int __tlregdtor(__funcptr fn) {
	if (!__addDtor(&tl_dtors_list, &tl_dtors_head, fn)) {
		return ENOMEM;
	}
	return 0;
}
----

=== RTTI

RTTI - полезная функция, которая, помимо нелюбимого многими `dynamic_cast` даёт нам оператор typeid и возможность получать имена типов в во время исполнения.

В Microsoft ABI её реализация практически целиком возложена на компилятор, однако, есть нюанс. RTTI это, в сущности, цепочка вывода типов, но компилятор не может создать запись для самого первого, начального типа. Без неё компилятор не сможет найти требуемую внутреннюю переменную `type_info::'vftable'`.

Нестандартное имя с кавычками намекает, что это не просто имя. И действительно, из кода компилятора мы можем узнать, что переменная называется `"??_7type_info@@6B@"` и имеет специфическое содержание, до которого докопались [методом обратной инженерии](https://blog.rop.la/en/reversing/2022/12/13/identifying-vftables-through-ms-cpp-rtti.html).

Мы можем воспользоваться этим знанием.

[source,c++]
----
struct TypeDescriptor {
	const TypeDescriptor *type_info_vtable;
	void *spare;
	char __decorated_name[128];
};

const TypeDescriptor s_type_info_vftable __asm__("??_7type_info@@6B@") = {
	&s_type_info_vftable,
	nullptr,
	".?AVtype_info@@",
};
----

Это решает проблему базового запуска RTTI, из этого можно начать реализовывать другие функции.

Как и все прочие реализации C++, Microsoft ABI хранит имена типов C++ в закодированном виде. Стандартная реализация прозрачно декодирует их во время построения `type_info``, но мы не знаем, как это реализуется на уровне библиотеки. Потому, используем иное решение.

LLVM уже имеет функции для того, чтобы декодировать символы, которые порождает clang. С некоторыми модификациями мы можем встроить библиотеку Demangle прямо в код нашей libc, и с её помощью реализовать функцию Itanium ABI `__cxa_demangle`. Это решает проблему закодированных имён, и, одновременно, убирает различие для функций, которые уже используют Itanium ABI на других платформах.

=== Исключения

Хотя Xenolith Runtime официально не поддерживает исключения, для Windows это работает немного иначе. Дело в том, что в Windows есть разные виды исключений. Мы не поддерживаем C++ исключения, но для нормальной работы (например, setjmp/longjmp) должны поддерживать SEH-исключения.

На данный момент, clang генерирует код для третьей версии исключений:

[source,c++]
----
EXCEPTION_DISPOSITION __CxxFrameHandler3(PEXCEPTION_RECORD ExceptionRecord,
		PVOID EstablisherFrame, PCONTEXT ContextRecord, PDISPATCHER_CONTEXT DispatcherContext)
----

Поскольку нам не нужна полная поддержка исключений, только longjmp, нет нужны реализовывать эту функцию полностью. Тем более, это потребует значительной доли обратного инженеринга.

Однако, для longjmp достаточно разобраться в описании из [документации](https://learn.microsoft.com/en-us/cpp/build/exception-handling-x64?view=msvc-170).

Базовая суть в том, что в данных, предоставляемых системой для обработки исключения, можно найти список специальных обработчиков, которые должны быть вызваны, чтобы исключение обработалось успешно и все данные были зачищены.

Если необходима полная поддержка исключений, нужно найти подходящий catch блок, на котором нужно остановить обработку, однако, у нас такой нужды нет, потому мы просто вызываем полную зачистку данных.

=== Другие требования

Windows требует наличия специальной переменной `_fltused` для индикации использования устаревшей библиотеки работы с числами с плавающей запятой. На сегодня такая библиотека не нужна, но переменная всё ещё должна быть объявлена.

UCRT реализует специальный защищённый режим для vfprintf в функции `__stdio_common_vfprintf`. Функция `__acrt_iob_func` должна связывать файловый дескриптор с FILE из libc. Мы можем просто предоставить их:

[source,c++]
----
int __cdecl __stdio_common_vfprintf(int64_t const options, FILE *f, char const *fmt, locale_t locale, va_list args) {
	auto old = uselocale(locale);
	auto ret = vfprintf(f, fmt, args);
	uselocale(old);
	return ret;
}

int __acrt_iob_func(FILE *f) {
	return fileno(f);
}
----

== Итог

Реализовав все требуемые функции,мы получаем полноценную альтернативу UCRT, которая может собираться и использоваться без Windows SDK вовсе.

Помимо специфичных функций Windows, это требует и реализации libc самой по себе, но это уже совсем другая история.

Такая libc не совместима бинарно с библиотеками на основе UCRT, то есть, библиотеки зависимостей под неё придётся собирать отдельно. Однако, мы всё ещё используем традиционную платформу <arch>-pc-windows-msvc, что обеспечивает отличную совместимость с системными DLL.

При этом, в разработке используется только публичный код Microsoft из их документации, не используется компонентов GNU из MinGW, Wine или ReactOS. То есть, мы можем полноценно лицензировать и публиковать Xenolith Runtime под лицензией MIT, и предоставлять полноценную libc без нужды устанавливать Visual Studio, Windows SDK и прочие специфичные для Microsoft приложения.

В совокупности, это позволяет, например, выстроить полноценную разработку и отладку приложений для Windows на Linux с помощью Wine. Это требует некоторых улучшений для отладчика lldb, но в условиях ручной сборки llvm для Xenolith Runtime - не проблема.
