#!/bin/sh
# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio> — MIT (see open-sysroot.mk)
#
# gen-availability-shims.sh DSL OUTINC
#
# Emit the two version-derived headers that Apple's Libc build normally GENERATES
# (they are not checked into any apple-oss project): <sys/_symbol_aliasing.h> and
# <sys/_posix_availability.h>. They are pure macro headers derived from the public
# OS version list — no proprietary content.
#
#   DSL     AvailabilityVersions/availability.dsl (the version list)
#   OUTINC  sysroot include_libc (files written under OUTINC/sys/)
#
# The runtime targets a fixed, recent macOS deployment, so every macOS symbol
# alias resolves to identity (x). iOS variants are defined identically (unused on
# a macOS build, but referenced by name from <sys/cdefs.h> concatenation).

set -eu

DSL="$1"; INC="$2"
mkdir -p "$INC/sys"

{
	echo '/* generated by gen-availability-shims.sh from availability.dsl */'
	echo '#ifndef _SYS__SYMBOL_ALIASING_H_'
	echo '#define _SYS__SYMBOL_ALIASING_H_'
	awk '$1=="version" && $2=="macos" { v=$3; gsub(/\./,"_",v); print v }' "$DSL" | sort -u | \
		while read v; do echo "#define __DARWIN_ALIAS_STARTING_MAC___MAC_${v}(x) x"; done
	awk '$1=="version" && $2=="ios"   { v=$3; gsub(/\./,"_",v); print v }' "$DSL" | sort -u | \
		while read v; do echo "#define __DARWIN_ALIAS_STARTING_IPHONE___IPHONE_${v}(x) x"; done
	echo '#endif'
} > "$INC/sys/_symbol_aliasing.h"

# _posix_availability.h: mark nothing deprecated (we do not build in strict
# _POSIX_C_SOURCE mode), matching the empty branch of Apple's generated file.
{
	echo '/* generated by gen-availability-shims.sh */'
	echo '#ifndef _SYS__POSIX_AVAILABILITY_H_'
	echo '#define _SYS__POSIX_AVAILABILITY_H_'
	for y in 198808L 199009L 199209L 199309L 199506L 200112L 200809L; do
		echo "#define ___POSIX_C_DEPRECATED_STARTING_${y}"
	done
	echo '#endif'
} > "$INC/sys/_posix_availability.h"

echo "  availability shims: $(grep -c DARWIN_ALIAS "$INC/sys/_symbol_aliasing.h") aliases + _posix_availability.h"
