#!/bin/sh
# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio> — MIT (see open-sysroot.mk)
#
# gen-syscall-header.sh XNU OUT [SDK]
#
# Regenerate the userspace <sys/syscall.h> (the SYS_* numbers) from apple-oss xnu's
# bsd/kern/syscalls.master — the same source Apple's makesyscalls generates the SDK
# copy from at OS-build time (the derived header is not checked into xnu). The result
# is BAKED INTO GIT at open/sysroot/include_libc/sys/syscall.h (installed into the
# +open sysroot by the `stubs` stamp), so a normal +open build does not need this
# script — only regenerating after an OSS_TAG_xnu bump does.
#
#   XNU   apple-oss xnu checkout (needs bsd/kern/syscalls.master)
#   OUT   destination header (e.g. open/sysroot/include_libc/sys/syscall.h)
#   SDK   optional: a real macOS SDK sysroot; when given, the generated SYS_* set
#         is verified EQUAL to $SDK/usr/include/sys/syscall.h (name -> number)
#
# Name derivation mirrors Apple's generator: slot 0 is SYS_syscall; nosys/enosys
# slots are skipped; a `sys_` prototype prefix is stripped. LEGACY_ALIASES keeps
# the SDK-published defines for slots that became nosys in the current xnu.

set -eu

XNU="$1"; OUT="$2"; SDK="${3:-}"

XNU="$XNU" OUT="$OUT" SDK="$SDK" python3 - <<'EOF'
import os, re

xnu, out, sdk = os.environ['XNU'], os.environ['OUT'], os.environ['SDK']
tag = 'unknown'
m = re.search(r'xnu[^/]*$', xnu.rstrip('/'))
try:
    import subprocess
    tag = subprocess.run(['git', '-C', xnu, 'describe', '--tags', '--always'],
                         capture_output=True, text=True).stdout.strip() or tag
except Exception:
    pass

# SDK defines that survive on slots the current syscalls.master marks nosys.
LEGACY_ALIASES = {'invalid': 63, 'register_uexc_handler': 519, 'objc_bp_assist_cfg_np': 535}

gen, maxnum = {}, 0
for line in open(f'{xnu}/bsd/kern/syscalls.master'):
    m = re.match(r'^(\d+)\s+\S+\s+\S+\s+{\s*\S+[^;]*?(\w+)\s*\(', line)
    if not m:
        continue
    num, name = int(m.group(1)), m.group(2)
    maxnum = max(maxnum, num + 1)
    if num == 0:
        gen['syscall'] = 0
        continue
    if name in ('nosys', 'enosys'):
        continue
    if name.startswith('sys_'):
        name = name[4:]
    gen[name] = num
gen.update(LEGACY_ALIASES)

if sdk:
    ref = {}
    for line in open(f'{sdk}/usr/include/sys/syscall.h'):
        m = re.match(r'#define\s+SYS_(\w+)\s+(\d+)', line)
        if m:
            ref[m.group(1)] = int(m.group(2))
    assert ref.pop('MAXSYSCALL') == maxnum, f'MAXSYSCALL: gen={maxnum}'
    assert gen == ref, f'SYS_* set differs from SDK: {set(gen.items()) ^ set(ref.items())}'
    print(f'verified against SDK: {len(gen)} defines equal')

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, 'w') as f:
    f.write(f"""/* Copyright (c) 2026 Xenolith Team <admin@xenolith.studio> — MIT (see open-sysroot.mk)
 * <sys/syscall.h> for *-apple-macosx+open — GENERATED by gen-syscall-header.sh from
 * apple-oss {tag} bsd/kern/syscalls.master (the same source the SDK's copy is
 * generated from). Regenerate after an OSS_TAG_xnu bump:
 *   ./gen-syscall-header.sh <xnu> open/sysroot/include_libc/sys/syscall.h [<sdk>]
 */
#ifndef _SYS_SYSCALL_H_
#define _SYS_SYSCALL_H_

#include <sys/appleapiopts.h>
#ifdef __APPLE_API_PRIVATE

""")
    for name, num in sorted(gen.items(), key=lambda kv: (kv[1], kv[0])):
        f.write(f'#define\tSYS_{name}\t{num}\n')
    f.write(f'\n#define\tSYS_MAXSYSCALL\t{maxnum}\n\n')
    f.write('#endif /* __APPLE_API_PRIVATE */\n#endif /* !_SYS_SYSCALL_H_ */\n')
print(f'wrote {out}: {len(gen)} defines, MAXSYSCALL {maxnum}')
EOF
