#ifndef CORE_RUNTIME_INCLUDE_C_CROSS_EMBOX_SPRT_ERRNO_H_
#define CORE_RUNTIME_INCLUDE_C_CROSS_EMBOX_SPRT_ERRNO_H_

// Native Embox errno numbers from src/compat/libc/include/errno.h.
// Several values diverge from Linux (EPERM=1001, network errors in the 3xx range).

#define __SPRT_EPERM            1001
#define __SPRT_ENOENT           2
#define __SPRT_ESRCH            3
#define __SPRT_EINTR            4
#define __SPRT_EIO              5
#define __SPRT_ENXIO            300
#define __SPRT_E2BIG            7
#define __SPRT_ENOEXEC          8
#define __SPRT_EBADF            9
#define __SPRT_ECHILD           10
#define __SPRT_EAGAIN           11
#define __SPRT_ENOMEM           12
#define __SPRT_EACCES            301
#define __SPRT_EFAULT           14
#define __SPRT_ENOTBLK          15
#define __SPRT_EBUSY            16
#define __SPRT_EEXIST            302
#define __SPRT_EXDEV            18
#define __SPRT_ENODEV           19
#define __SPRT_ENOTDIR          20
#define __SPRT_EISDIR           21
#define __SPRT_EINVAL           22
#define __SPRT_ENFILE           23
#define __SPRT_EMFILE           24
#define __SPRT_ENOTTY            303
#define __SPRT_ETXTBSY          26
#define __SPRT_EFBIG            27
#define __SPRT_ENOSPC           28
#define __SPRT_ESPIPE           29
#define __SPRT_EROFS            30
#define __SPRT_EMLINK           31
#define __SPRT_EPIPE            304
#define __SPRT_EDOM             33
#define __SPRT_ERANGE           34
#define __SPRT_EDEADLK          35
#define __SPRT_ENAMETOOLONG     36
#define __SPRT_ENOLCK            203
#define __SPRT_ENOSYS           38
#define __SPRT_ENOTEMPTY            66
#define __SPRT_ELOOP            40
#define __SPRT_EWOULDBLOCK      __SPRT_EAGAIN
#define __SPRT_ENOMSG           42
#define __SPRT_EIDRM            43
#define __SPRT_ECHRNG           44
#define __SPRT_EL2NSYNC         45
#define __SPRT_EL3HLT           46
#define __SPRT_EL3RST           47
#define __SPRT_ELNRNG           48
#define __SPRT_EUNATCH          49
#define __SPRT_ENOCSI           50
#define __SPRT_EL2HLT           51
#define __SPRT_EBADE            52
#define __SPRT_EBADR            53
#define __SPRT_EXFULL           54
#define __SPRT_ENOANO           55
#define __SPRT_EBADRQC          56
#define __SPRT_EBADSLT          57
#define __SPRT_EDEADLOCK        __SPRT_EDEADLK
#define __SPRT_EBFONT           59
#define __SPRT_ENOSTR           60
#define __SPRT_ENODATA          61
#define __SPRT_ETIME            62
#define __SPRT_ENOSR            63
#define __SPRT_ENONET           64
#define __SPRT_ENOPKG           65
#define __SPRT_EREMOTE          66
#define __SPRT_ENOLINK          67
#define __SPRT_EADV             68
#define __SPRT_ESRMNT           69
#define __SPRT_ECOMM            70
#define __SPRT_EPROTO           71
#define __SPRT_EMULTIHOP        72
#define __SPRT_EDOTDOT          73
#define __SPRT_EBADMSG          74
#define __SPRT_EOVERFLOW        75
#define __SPRT_ENOTUNIQ         76
#define __SPRT_EBADFD           77
#define __SPRT_EREMCHG          78
#define __SPRT_ELIBACC          79
#define __SPRT_ELIBBAD          80
#define __SPRT_ELIBSCN          81
#define __SPRT_ELIBMAX          82
#define __SPRT_ELIBEXEC         83
#define __SPRT_EILSEQ           84
#define __SPRT_ERESTART         85
#define __SPRT_ESTRPIPE         86
#define __SPRT_EUSERS           87
#define __SPRT_ENOTSOCK            320
#define __SPRT_EDESTADDRREQ            321
#define __SPRT_EMSGSIZE            322
#define __SPRT_EPROTOTYPE            323
#define __SPRT_ENOPROTOOPT            324
#define __SPRT_EPROTONOSUPPORT            325
#define __SPRT_ESOCKTNOSUPPORT            326
#define __SPRT_EOPNOTSUPP            327
#define __SPRT_ENOTSUP          95
#define __SPRT_EPFNOSUPPORT            328
#define __SPRT_EAFNOSUPPORT            329
#define __SPRT_EADDRINUSE            330
#define __SPRT_EADDRNOTAVAIL            331
#define __SPRT_ENETDOWN            350
#define __SPRT_ENETUNREACH            351
#define __SPRT_ENETRESET            352
#define __SPRT_ECONNABORTED            353
#define __SPRT_ECONNRESET            354
#define __SPRT_ENOBUFS            355
#define __SPRT_EISCONN            356
#define __SPRT_ENOTCONN            357
#define __SPRT_ESHUTDOWN            358
#define __SPRT_ETOOMANYREFS            359
#define __SPRT_ETIMEDOUT            360
#define __SPRT_ECONNREFUSED            361
#define __SPRT_EHOSTDOWN            364
#define __SPRT_EHOSTUNREACH            365
#define __SPRT_EALREADY            311
#define __SPRT_EINPROGRESS            310
#define __SPRT_ESTALE           116
#define __SPRT_EUCLEAN          117
#define __SPRT_ENOTNAM          118
#define __SPRT_ENAVAIL          119
#define __SPRT_EISNAM           120
#define __SPRT_EREMOTEIO        121
#define __SPRT_EDQUOT           122
#define __SPRT_ENOMEDIUM        123
#define __SPRT_EMEDIUMTYPE      124
#define __SPRT_ECANCELED        125
#define __SPRT_ENOKEY           126
#define __SPRT_EKEYEXPIRED      127
#define __SPRT_EKEYREVOKED      128
#define __SPRT_EKEYREJECTED     129
#define __SPRT_EOWNERDEAD       130
#define __SPRT_ENOTRECOVERABLE  131
#define __SPRT_ERFKILL          132
#define __SPRT_EHWPOISON        133

#ifndef EPERM
#define EPERM            __SPRT_EPERM
#define ENOENT           __SPRT_ENOENT
#define ESRCH            __SPRT_ESRCH
#define EINTR            __SPRT_EINTR
#define EIO              __SPRT_EIO
#define ENXIO            __SPRT_ENXIO
#define E2BIG            __SPRT_E2BIG
#define ENOEXEC          __SPRT_ENOEXEC
#define EBADF            __SPRT_EBADF
#define ECHILD           __SPRT_ECHILD
#define EAGAIN           __SPRT_EAGAIN
#define ENOMEM           __SPRT_ENOMEM
#define EACCES           __SPRT_EACCES
#define EFAULT           __SPRT_EFAULT
#define ENOTBLK          __SPRT_ENOTBLK
#define EBUSY            __SPRT_EBUSY
#define EEXIST           __SPRT_EEXIST
#define EXDEV            __SPRT_EXDEV
#define ENODEV           __SPRT_ENODEV
#define ENOTDIR          __SPRT_ENOTDIR
#define EISDIR           __SPRT_EISDIR
#define EINVAL           __SPRT_EINVAL
#define ENFILE           __SPRT_ENFILE
#define EMFILE           __SPRT_EMFILE
#define ENOTTY           __SPRT_ENOTTY
#define ETXTBSY          __SPRT_ETXTBSY
#define EFBIG            __SPRT_EFBIG
#define ENOSPC           __SPRT_ENOSPC
#define ESPIPE           __SPRT_ESPIPE
#define EROFS            __SPRT_EROFS
#define EMLINK           __SPRT_EMLINK
#define EPIPE            __SPRT_EPIPE
#define EDOM             __SPRT_EDOM
#define ERANGE           __SPRT_ERANGE
#define EDEADLK          __SPRT_EDEADLK
#define ENAMETOOLONG     __SPRT_ENAMETOOLONG
#define ENOLCK           __SPRT_ENOLCK
#define ENOSYS           __SPRT_ENOSYS
#define ENOTEMPTY        __SPRT_ENOTEMPTY
#define ELOOP            __SPRT_ELOOP
#define EWOULDBLOCK      __SPRT_EWOULDBLOCK
#define ENOMSG           __SPRT_ENOMSG
#define EIDRM            __SPRT_EIDRM
#define ECHRNG           __SPRT_ECHRNG
#define EL2NSYNC         __SPRT_EL2NSYNC
#define EL3HLT           __SPRT_EL3HLT
#define EL3RST           __SPRT_EL3RST
#define ELNRNG           __SPRT_ELNRNG
#define EUNATCH          __SPRT_EUNATCH
#define ENOCSI           __SPRT_ENOCSI
#define EL2HLT           __SPRT_EL2HLT
#define EBADE            __SPRT_EBADE
#define EBADR            __SPRT_EBADR
#define EXFULL           __SPRT_EXFULL
#define ENOANO           __SPRT_ENOANO
#define EBADRQC          __SPRT_EBADRQC
#define EBADSLT          __SPRT_EBADSLT
#define EDEADLOCK        __SPRT_EDEADLOCK
#define EBFONT           __SPRT_EBFONT
#define ENOSTR           __SPRT_ENOSTR
#define ENODATA          __SPRT_ENODATA
#define ETIME            __SPRT_ETIME
#define ENOSR            __SPRT_ENOSR
#define ENONET           __SPRT_ENONET
#define ENOPKG           __SPRT_ENOPKG
#define EREMOTE          __SPRT_EREMOTE
#define ENOLINK          __SPRT_ENOLINK
#define EADV             __SPRT_EADV
#define ESRMNT           __SPRT_ESRMNT
#define ECOMM            __SPRT_ECOMM
#define EPROTO           __SPRT_EPROTO
#define EMULTIHOP        __SPRT_EMULTIHOP
#define EDOTDOT          __SPRT_EDOTDOT
#define EBADMSG          __SPRT_EBADMSG
#define EOVERFLOW        __SPRT_EOVERFLOW
#define ENOTUNIQ         __SPRT_ENOTUNIQ
#define EBADFD           __SPRT_EBADFD
#define EREMCHG          __SPRT_EREMCHG
#define ELIBACC          __SPRT_ELIBACC
#define ELIBBAD          __SPRT_ELIBBAD
#define ELIBSCN          __SPRT_ELIBSCN
#define ELIBMAX          __SPRT_ELIBMAX
#define ELIBEXEC         __SPRT_ELIBEXEC
#define EILSEQ           __SPRT_EILSEQ
#define ERESTART         __SPRT_ERESTART
#define ESTRPIPE         __SPRT_ESTRPIPE
#define EUSERS           __SPRT_EUSERS
#define ENOTSOCK         __SPRT_ENOTSOCK
#define EDESTADDRREQ     __SPRT_EDESTADDRREQ
#define EMSGSIZE         __SPRT_EMSGSIZE
#define EPROTOTYPE       __SPRT_EPROTOTYPE
#define ENOPROTOOPT      __SPRT_ENOPROTOOPT
#define EPROTONOSUPPORT  __SPRT_EPROTONOSUPPORT
#define ESOCKTNOSUPPORT  __SPRT_ESOCKTNOSUPPORT
#define EOPNOTSUPP       __SPRT_EOPNOTSUPP
#define ENOTSUP          __SPRT_ENOTSUP
#define EPFNOSUPPORT     __SPRT_EPFNOSUPPORT
#define EAFNOSUPPORT     __SPRT_EAFNOSUPPORT
#define EADDRINUSE       __SPRT_EADDRINUSE
#define EADDRNOTAVAIL    __SPRT_EADDRNOTAVAIL
#define ENETDOWN         __SPRT_ENETDOWN
#define ENETUNREACH      __SPRT_ENETUNREACH
#define ENETRESET        __SPRT_ENETRESET
#define ECONNABORTED     __SPRT_ECONNABORTED
#define ECONNRESET       __SPRT_ECONNRESET
#define ENOBUFS          __SPRT_ENOBUFS
#define EISCONN          __SPRT_EISCONN
#define ENOTCONN         __SPRT_ENOTCONN
#define ESHUTDOWN        __SPRT_ESHUTDOWN
#define ETOOMANYREFS     __SPRT_ETOOMANYREFS
#define ETIMEDOUT        __SPRT_ETIMEDOUT
#define ECONNREFUSED     __SPRT_ECONNREFUSED
#define EHOSTDOWN        __SPRT_EHOSTDOWN
#define EHOSTUNREACH     __SPRT_EHOSTUNREACH
#define EALREADY         __SPRT_EALREADY
#define EINPROGRESS      __SPRT_EINPROGRESS
#define ESTALE           __SPRT_ESTALE
#define EUCLEAN          __SPRT_EUCLEAN
#define ENOTNAM          __SPRT_ENOTNAM
#define ENAVAIL          __SPRT_ENAVAIL
#define EISNAM           __SPRT_EISNAM
#define EREMOTEIO        __SPRT_EREMOTEIO
#define EDQUOT           __SPRT_EDQUOT
#define ENOMEDIUM        __SPRT_ENOMEDIUM
#define EMEDIUMTYPE      __SPRT_EMEDIUMTYPE
#define ECANCELED        __SPRT_ECANCELED
#define ENOKEY           __SPRT_ENOKEY
#define EKEYEXPIRED      __SPRT_EKEYEXPIRED
#define EKEYREVOKED      __SPRT_EKEYREVOKED
#define EKEYREJECTED     __SPRT_EKEYREJECTED
#define EOWNERDEAD       __SPRT_EOWNERDEAD
#define ENOTRECOVERABLE  __SPRT_ENOTRECOVERABLE
#define ERFKILL          __SPRT_ERFKILL
#define EHWPOISON        __SPRT_EHWPOISON
#endif

#endif
