# Copyright (c) 2023-2025 Stappler LLC <admin@stappler.dev>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# Выбираем оптимизацию по умолчанию

ifdef LOCAL_LOG_LEVEL

ifeq ($(LOCAL_LOG_LEVEL),errors)
GLOBAL_LOG_LEVEL := 1
else ifeq ($(LOCAL_LOG_LEVEL),all)
GLOBAL_LOG_LEVEL := 2
else ifeq ($(LOCAL_LOG_LEVEL),none)
GLOBAL_LOG_LEVEL := 0
else
GLOBAL_LOG_LEVEL := $(LOCAL_LOG_LEVEL)
endif

else # LOCAL_LOG_LEVEL

ifeq ($(BUILD_TYPE),release)
GLOBAL_LOG_LEVEL := 1
else
GLOBAL_LOG_LEVEL := 2
endif

endif # LOCAL_LOG_LEVEL

OSTYPE_GCH_FILE := -x c++-header -Xclang -emit-pch
OSTYPE_C_FILE := -x c
OSTYPE_CPP_FILE := -x c++
OSTYPE_MM_FILE := -x objective-c++
OSTYPE_GCH_SUFFIX := .pch

GLOBAL_CONFIG_FLAGS := STAPPLER

BUILD_TYPE_CFLAGS := -DSTAPPLER_LOG_LEVEL=$(GLOBAL_LOG_LEVEL)
BUILD_TYPE_CXXFLAGS := -DSTAPPLER_LOG_LEVEL=$(GLOBAL_LOG_LEVEL)
BUILD_TYPE_LDFLAGS :=

BUILD_TYPE_CFLAGS_RELEASE := $(GLOBAL_OPTIMIZATION)
BUILD_TYPE_CXXFLAGS_RELEASE := $(GLOBAL_OPTIMIZATION)
BUILD_TYPE_LDFLAGS_RELEASE :=

BUILD_TYPE_CFLAGS_DEBUG := -g -funwind-tables
BUILD_TYPE_CXXFLAGS_DEBUG := -g -funwind-tables
BUILD_TYPE_LDFLAGS_DEBUG :=

BUILD_TYPE_CFLAGS_COVERAGE := -g -fprofile-arcs -ftest-coverage
BUILD_TYPE_CXXFLAGS_COVERAGE := -g -fprofile-arcs -ftest-coverage
BUILD_TYPE_LDFLAGS_COVERAGE := -fprofile-arcs -ftest-coverage

# Вычисляем базовый набор флагов
ifeq ($(BUILD_TYPE),release)
	BUILD_TYPE_CFLAGS := $(BUILD_TYPE_CFLAGS) $(BUILD_TYPE_CFLAGS_RELEASE) -DNDEBUG
	BUILD_TYPE_CXXFLAGS := $(BUILD_TYPE_CXXFLAGS) $(BUILD_TYPE_CXXFLAGS_RELEASE) -DNDEBUG
	BUILD_TYPE_LDFLAGS := $(BUILD_TYPE_LDFLAGS) $(BUILD_TYPE_LDFLAGS_RELEASE)
endif

ifeq ($(BUILD_TYPE),debug)
	BUILD_TYPE_CFLAGS := $(BUILD_TYPE_CFLAGS) $(BUILD_TYPE_CFLAGS_DEBUG) -DDEBUG
	BUILD_TYPE_CXXFLAGS := $(BUILD_TYPE_CXXFLAGS) $(BUILD_TYPE_CXXFLAGS_DEBUG) -DDEBUG
	BUILD_TYPE_LDFLAGS := $(BUILD_TYPE_LDFLAGS) $(BUILD_TYPE_LDFLAGS_DEBUG)
endif # ifdef RELEASE

ifeq ($(BUILD_TYPE),coverage)
	BUILD_TYPE_CFLAGS := $(BUILD_TYPE_CFLAGS) $(BUILD_TYPE_CFLAGS_COVERAGE) -DNDEBUG -DCOVERAGE
	BUILD_TYPE_CXXFLAGS := $(BUILD_TYPE_CXXFLAGS) $(BUILD_TYPE_CXXFLAGS_COVERAGE) -DNDEBUG -DCOVERAGE
	BUILD_TYPE_LDFLAGS := $(BUILD_TYPE_LDFLAGS) $(BUILD_TYPE_LDFLAGS_COVERAGE)
endif

GLOBAL_LIB_CFLAGS := $(GLOBAL_LIB_CFLAGS)
GLOBAL_LIB_CXXFLAGS := $(GLOBAL_LIB_CXXFLAGS)
GLOBAL_LIB_LDFLAGS := $(GLOBAL_LIB_LDFLAGS)

GLOBAL_EXEC_CFLAGS := $(GLOBAL_EXEC_CFLAGS)
GLOBAL_EXEC_CXXFLAGS := $(GLOBAL_EXEC_CXXFLAGS)
GLOBAL_EXEC_LDFLAGS := $(GLOBAL_EXEC_LDFLAGS)

ifeq ($(LOCAL_EXEC_LIVE_RELOAD),1)
	GLOBAL_CONFIG_FLAGS += EXEC_LIVE_RELOAD
	GLOBAL_EXEC_LDFLAGS += -rdynamic
endif

ifdef STAPPLER_VERSION_PREFIX
GLOBAL_GENERAL_CFLAGS += -DSTAPPLER_VERSION_PREFIX=$(STAPPLER_VERSION_PREFIX)
endif

GLOBAL_GENERAL_CXXFLAGS := $(GLOBAL_GENERAL_CXXFLAGS) -std=$(GLOBAL_STDXX)
GLOBAL_GENERAL_CFLAGS := $(GLOBAL_GENERAL_CFLAGS) -std=$(GLOBAL_STD)
GLOBAL_GENERAL_LDFLAGS := $(GLOBAL_GENERAL_LDFLAGS)

ifdef BUILD_SHARED
GLOBAL_CONFIG_FLAGS += STAPPLER_SHARED
endif

include $(BUILD_ROOT)/c/rules.mk

BUILD_С_OUTDIR := $(BUILD_OUTDIR)/$(notdir $(GLOBAL_CC))

BUILD_COMPILATION_DATABASE := ./compile_commands.json
