# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_appconfig_value
"$(tab)SharedSymbol(", [char]0x22, "$(2)", [char]0x22, ", &$(2)),`n" | Add-Content -NoNewline -Encoding utf8 $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_appconfig_string
"$(tab)SharedSymbol(", [char]0x22, "$(2)", [char]0x22, ", $(2)),`n" | Add-Content -NoNewline -Encoding utf8 $(1)$(newline)$(tab)
endef

define BUILD_appconfig_source
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(BUILD_APP_CONFIG)
	@$(call rule_mkdir,$(dir $(1)))
	"// Autogenerated appconfig source`n`n#include ", [char]0x22, "stappler-appconfig.h", [char]0x22,\
		"`n#include ", [char]0x22, "SPSharedModule.h", [char]0x22,\
		"`n`nnamespace stappler::appconfig {`nstatic SharedSymbol s_appconfigSharedSymbols[] = {`n"\
			| Set-Content -NoNewline -Encoding utf8 -Path "$(1)"
	$(foreach var,$(3),$(call BUILD_write_appconfig_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(4),$(call BUILD_write_appconfig_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	"};`n`nstatic SharedModule s_bitmapSharedModule(", [char]0x22, "appconfig", [char]0x22,\
		", s_appconfigSharedSymbols, sizeof(s_appconfigSharedSymbols) / sizeof(SharedSymbol))`n`n}`n"\
		| Add-Content -NoNewline -Encoding utf8 $(1)
endef

# $(1) - target path
# $(2) - config flag
define BUILD_write_config_flag
Add-Content  -Encoding utf8 $(1) "#define $(2) 1"$(newline)$(tab)
endef

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_config_value
Add-Content  -Encoding utf8 $(1) "constexpr int $(2) = $(3);"$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_config_string
"constexpr auto $(2) = ", [char]0x22, '$(3)', [char]0x22, ";`n" | Add-Content -NoNewline -Encoding utf8 $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - config namespace
# $(3) - config flags
# $(4) - config values
# $(5) - config strings
define BUILD_config_header
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS)
	@$(call rule_mkdir,$$(dir $$@))
	"// Autogenerated config`n`n#ifndef STAPPLER_CONFIG_$(2)_H_`n#define STAPPLER_CONFIG_$(2)_H_`n"\
		| Set-Content -NoNewline -Encoding utf8 -Path "$(1)"
	$(foreach var,$(3),$(call BUILD_write_config_flag,$(1),$(var)))
	"`n`n#ifdef __cplusplus`nnamespace stappler::$(2) {`n" | Add-Content -NoNewline -Encoding utf8 $(1)
	$(foreach var,$(4),$(call BUILD_write_config_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(5),$(call BUILD_write_config_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	"}`n", "#endif // __cplusplus`n", "#endif // STAPPLER_CONFIG_$(2)_H_`n" | Add-Content -NoNewline -Encoding utf8 $(1)
endef

# $(1) - target path
# $(2) - json files
# $(3) - build dir
define BUILD_cdb
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(2)
	@powershell \
		Set-Content  -Encoding utf8 $(1) "[";\
		Get-Content $(addsuffix *.json,$(sort $(dir $(2)))) | Add-Content  -Encoding utf8 $(1); \
		Add-Content  -Encoding utf8 $(1) "]";
	@echo "[Compilation database] $(1)"
endef
