# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_appconfig_value
@echo '$(tab)SharedSymbol("$(2)", &$(2)),' >> $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_appconfig_string
@echo '$(tab)SharedSymbol("$(2)", $(2)),' >> $(1)$(newline)$(tab)
endef

define BUILD_appconfig_source
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(BUILD_APP_CONFIG)
	@$(call rule_mkdir,$(dir $(1)))
	@echo "// Autogenerated appconfig source" > $(1)
	@echo "" >> $(1)
	@echo '#include "stappler-appconfig.h"' >> $(1)
	@echo '#include "SPSharedModule.h"' >> $(1)
	@echo "" >> $(1)
	@echo "namespace stappler::appconfig {" >> $(1)
	@echo "static SharedSymbol s_appconfigSharedSymbols[] = {" >> $(1)
	$(foreach var,$(3),$(call BUILD_write_appconfig_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(4),$(call BUILD_write_appconfig_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	@echo "};" >> $(1)
	@echo "" >> $(1)
	@echo 'static SharedModule s_bitmapSharedModule("appconfig", s_appconfigSharedSymbols, sizeof(s_appconfigSharedSymbols) / sizeof(SharedSymbol));' >> $(1)
	@echo "" >> $(1)
	@echo "}" >> $(1)
	@echo "" >> $(1)
endef

# $(1) - target path
# $(2) - config flag
define BUILD_write_config_flag
@echo "#define $(2) 1" >> $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_config_value
@echo "constexpr int $(2) = $(3);" >> $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_config_string
@echo 'constexpr auto $(2) = "$(3)";' >> $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - config namespace
# $(3) - config flags
# $(4) - config values
# $(5) - config strings
define BUILD_config_header
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS)
	@$(call rule_mkdir,$$(dir $$@))
	@echo "// Autogenerated config" > $(1)
	@echo "" >> $(1)
	@echo "#ifndef STAPPLER_CONFIG_$(2)_H_" >> $(1)
	@echo "#define STAPPLER_CONFIG_$(2)_H_" >> $(1)
	@echo "" >> $(1)
	$(foreach var,$(3),$(call BUILD_write_config_flag,$(1),$(var)))
	@echo "" >> $(1)
	@echo "#ifdef __cplusplus" >> $(1)
	@echo "namespace stappler::$(2) {" >> $(1)
	$(foreach var,$(4),$(call BUILD_write_config_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(5),$(call BUILD_write_config_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	@echo "}" >> $(1)
	@echo "" >> $(1)
	@echo "#endif // __cplusplus" >> $(1)
	@echo "#endif // STAPPLER_CONFIG_$(2)_H_" >> $(1)
endef


define BUILD_write_cdb_entry
@cat $(2) >> $(1)$(newline)$(tab)
endef

# $(1) - target path
# $(2) - json files
# $(3) - build dir
define BUILD_cdb
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(2)
	@echo "[" > $(1)
	$(foreach file,$(2),$(call BUILD_write_cdb_entry,$(1),$(file)))
	@echo "]" >> $(1)
	@echo "[Compilation database] $(1)"
endef
