# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_appconfig_value
@$(APPEND) $(1) '$(tab)SharedSymbol("$(2)", &$(2)),'$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_appconfig_string
@$(APPEND) $(1) '$(tab)SharedSymbol("$(2)", $(2)),'$(newline)$(tab)
endef

define BUILD_appconfig_source
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(BUILD_APP_CONFIG)
	@$(call rule_mkdir,$(dir $(1)))
	@$(WRITE) $(1) "// Autogenerated appconfig source"
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) '#include "stappler-appconfig.h"'
	@$(APPEND) $(1) '#include "SPSharedModule.h"'
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) "namespace stappler::appconfig {"
	@$(APPEND) $(1) "static SharedSymbol s_appconfigSharedSymbols[] = {"
	$(foreach var,$(3),$(call BUILD_write_appconfig_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(4),$(call BUILD_write_appconfig_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	@$(APPEND) $(1) "};"
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) 'static SharedModule s_bitmapSharedModule("appconfig", s_appconfigSharedSymbols, sizeof(s_appconfigSharedSymbols) / sizeof(SharedSymbol));'
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) "}"
	@$(APPEND) $(1) ""
$(1):.TARGET_NAME := [codegen] $(notdir $(1))
endef

# $(1) - target path
# $(2) - config flag
define BUILD_write_config_flag
@$(APPEND) $(1) "#define $(2) 1"$(newline)$(tab)
endef

# $(1) - target path
# $(2) - value name
# $(3) - value
define BUILD_write_config_value
@$(APPEND) $(1) "constexpr int $(2) = $(3);"$(newline)$(tab)
endef

# $(1) - target path
# $(2) - string name
# $(3) - string value
define BUILD_write_config_string
@$(APPEND) $(1) 'constexpr auto $(2) = "$(3)";'$(newline)$(tab)
endef

# $(1) - target path
# $(2) - config namespace
# $(3) - config flags
# $(4) - config values
# $(5) - config strings
define BUILD_config_header
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS)
	@$(call rule_mkdir,$$(dir $$@))
	@$(WRITE) $(1) "// Autogenerated config"
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) "#ifndef STAPPLER_CONFIG_$(2)_H_"
	@$(APPEND) $(1) "#define STAPPLER_CONFIG_$(2)_H_"
	@$(APPEND) $(1) ""
	$(foreach var,$(3),$(call BUILD_write_config_flag,$(1),$(var)))
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) "#ifdef __cplusplus"
	@$(APPEND) $(1) "namespace stappler::$(2) {"
	$(foreach var,$(4),$(call BUILD_write_config_value,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	$(foreach var,$(5),$(call BUILD_write_config_string,$(1),$(firstword $(subst =, ,$(var))),$(lastword $(subst =, ,$(var)))))
	@$(APPEND) $(1) "}"
	@$(APPEND) $(1) ""
	@$(APPEND) $(1) "#endif // __cplusplus"
	@$(APPEND) $(1) "#endif // STAPPLER_CONFIG_$(2)_H_"
$(1):.TARGET_NAME := [codegen] $(notdir $(1))
endef


define BUILD_write_cdb_entry
@$(APPEND) $(1) $$(xl_cat $(2))$(newline)$(tab)
endef

# $(1) - target path
# $(2) - json files
# $(3) - build dir
define BUILD_cdb
$(1): $$(LOCAL_MAKEFILE) $$(TOOLKIT_MODULES) $$(TOOLKIT_CACHED_FLAGS) $(2)
	@$(WRITE) $(1) "["
	$(foreach file,$(2),$(call BUILD_write_cdb_entry,$(1),$(file)))
	@$(APPEND) $(1) "]"
	$(call target_log,"[Compilation database] $(1)")
$(1):.TARGET_NAME := [Compilation database]
endef
