#include "../include/defs.h"

double exp10(double x);

#if __SPRT_ARCH_ID == __SPRT_ARCH_ID_X86_64 && !SPRT_WINDOWS
#include "../musl-libc/src/math/x86_64/fabsl.c"
#include "../musl-libc/src/math/x86_64/fmodl.c"
#include "../musl-libc/src/math/x86_64/llrintl.c"
#include "../musl-libc/src/math/x86_64/lrintl.c"
#include "../musl-libc/src/math/x86_64/remainderl.c"
#include "../musl-libc/src/math/x86_64/remquol.c"
#include "../musl-libc/src/math/x86_64/rintl.c"
#include "../musl-libc/src/math/x86_64/sqrtl.c"
#else
#include "../musl-libc/src/math/acosl.c"
#include "../musl-libc/src/math/asinl.c"
#include "../musl-libc/src/math/atan2l.c"
#include "../musl-libc/src/math/atanl.c"
#include "../musl-libc/src/math/exp2l.c"
#include "../musl-libc/src/math/expl.c"
#include "../musl-libc/src/math/ceill.c"
#include "../musl-libc/src/math/fabsl.c"
#include "../musl-libc/src/math/fmodl.c"
#include "../musl-libc/src/math/llrintl.c"
#include "../musl-libc/src/math/lrintl.c"
#include "../musl-libc/src/math/expm1l.c"
#include "../musl-libc/src/math/log10l.c"
#include "../musl-libc/src/math/floorl.c"
#include "../musl-libc/src/math/log1pl.c"
#include "../musl-libc/src/math/log2l.c"
#include "../musl-libc/src/math/logl.c"
#include "../musl-libc/src/math/remainderl.c"
#include "../musl-libc/src/math/remquol.c"
#include "../musl-libc/src/math/rintl.c"
#include "../musl-libc/src/math/sqrtl.c"
#include "../musl-libc/src/math/truncl.c"
#endif

#include "../musl-libc/src/math/acoshl.c"
#include "../musl-libc/src/math/asinhl.c"
#include "../musl-libc/src/math/atanhl.c"
#include "../musl-libc/src/math/cbrtl.c"
#include "../musl-libc/src/math/copysignl.c"
#include "../musl-libc/src/math/coshl.c"
#include "../musl-libc/src/math/__cosl.c"
#include "../musl-libc/src/math/cosl.c"
#include "../musl-libc/src/math/erfl.c"
#include "../musl-libc/src/math/exp10l.c"
#include "../musl-libc/src/math/fdiml.c"
#include "../musl-libc/src/math/fmal.c"
#include "../musl-libc/src/math/fmaxl.c"
#include "../musl-libc/src/math/fminl.c"
#include "../musl-libc/src/math/__fpclassifyl.c"
#include "../musl-libc/src/math/frexpl.c"
#include "../musl-libc/src/math/ilogbl.c"
#include "../musl-libc/src/math/__invtrigl.c"
#include "../musl-libc/src/math/ldexpl.c"
#include "../musl-libc/src/math/lgammal.c"
#include "../musl-libc/src/math/llroundl.c"
#include "../musl-libc/src/math/logbl.c"
#include "../musl-libc/src/math/lroundl.c"
#include "../musl-libc/src/math/hypotl.c"
#include "../musl-libc/src/math/roundl.c"
#include "../musl-libc/src/math/__rem_pio2l.c"
#include "../musl-libc/src/math/__math_invalidl.c"
#include "../musl-libc/src/math/modfl.c"
#include "../musl-libc/src/math/nanl.c"
#include "../musl-libc/src/math/nearbyintl.c"
#include "../musl-libc/src/math/nextafterl.c"
#include "../musl-libc/src/math/nexttowardl.c"
#include "../musl-libc/src/math/__polevll.c"
#include "../musl-libc/src/math/powl.c"
#include "../musl-libc/src/math/scalblnl.c"
#include "../musl-libc/src/math/scalbnl.c"
#include "../musl-libc/src/math/__signbitl.c"
#include "../musl-libc/src/math/sinhl.c"
#include "../musl-libc/src/math/__sinl.c"
#include "../musl-libc/src/math/sinl.c"
#include "../musl-libc/src/math/tanhl.c"
#include "../musl-libc/src/math/__tanl.c"
#include "../musl-libc/src/math/tanl.c"
#include "../musl-libc/src/math/tgammal.c"

void sincos(double x, double *sin, double *cos);

#include "../musl-libc/src/math/sincosl.c"
