/**
Copyright (c) 2026 Stappler Team <admin@stappler.org>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

// The generator, over the corpus.
//
// Three claims, and each is a comparison rather than an inspection. The generator is deterministic:
// the same graph written twice is the same bytes. The committed corpus is fresh: regenerating each
// case in memory gives the number the committed unit carries, so a unit that fell behind the graphs
// fails here with the words to fix it. And a unit describes the graph it was written from: loaded
// against the registry, it answers RuntimeGraph::describe() with the same value - through the same
// describer, so what is being compared is two tables.
//
// `flowtest --emit=tests/flow/codegen/gen codegen-emit` writes the corpus, the seeds and their
// manifests (the directory is relative to where it runs); every other run only checks.

#include "codegen_fixture.h"
#include "synth_cases.h"
#include "gen/synth_manifest.gen.h"

#include "../tests.h"
#include "../check/flow_check.h"

#include "SPFilesystem.h"

namespace STAPPLER_VERSIONIZED stappler {

using stappler::test::check;

namespace {

using namespace stappler::test::codegenfx;

constexpr StringView Regenerate(
		"regenerate with `flowtest --emit=tests/flow/codegen/gen codegen-emit`");

bool writeText(StringView dir, StringView file, StringView text) {
	auto path = mem_std::toString(dir, "/", file);
	return filesystem::write(FileInfo{path}, reinterpret_cast<const uint8_t *>(text.data()),
			text.size());
}

// One unit: the header and every part.
bool writeUnit(StringView stem, const codegen::Emitted &unit) {
	auto written = writeText(test::s_emitDir, mem_std::toString(stem, ".gen.h"), unit.header);
	for (uint32_t part = 0; written && part < uint32_t(unit.sources.size()); ++part) {
		written = writeText(test::s_emitDir, sourceName(stem, part), unit.sources[part]);
	}
	return written;
}

// A manifest: every unit, in order, as the table the sections read. `withUnit` declares the row
// type, which the corpus manifest does and the seed manifest takes from it.
mem_std::String manifestText(StringView guard, StringView what, StringView count, StringView table,
		bool withUnit, SpanView<mem_std::String> names, SpanView<mem_std::String> cases) {
	mem_std::String out;
	out.append(mem_std::toString("// Generated by `flowtest --emit=<dir> codegen-emit`: the committed units of ",
			what, ".\n"));
	out.append("// Do not edit: regenerate it.\n");
	out.append(mem_std::toString("#ifndef ", guard, "\n#define ", guard, "\n\n"));
	out.append("#include \"SPFlowCompiled.h\"\n\n");
	for (auto &it : names) { out.append(mem_std::toString("#include \"", it, ".gen.h\"\n")); }
	out.append("\nnamespace STAPPLER_VERSIONIZED stappler::test::codegenfx {\n\n");
	if (withUnit) {
		out.append("struct Unit {\n\tStringView name;\n"
				   "\t::stappler::flow::CompiledTables (*tables)();\n};\n\n");
	}
	out.append(mem_std::toString("inline constexpr uint32_t ", count, " = ", uint32_t(names.size()),
			";\n"));
	out.append(mem_std::toString("inline const Unit ", table, "[",
			uint32_t(names.empty() ? 1 : names.size()), "] = {\n"));
	if (names.empty()) {
		out.append("\t{},\n");
	}
	for (uint32_t i = 0; i < uint32_t(names.size()); ++i) {
		out.append(mem_std::toString("\t{StringView(\"", cases[i], "\"), &::stappler::flow::gen::",
				names[i], "::Tables::tables},\n"));
	}
	out.append("};\n\n} // namespace stappler::test::codegenfx\n\n");
	out.append(mem_std::toString("#endif /* ", guard, " */\n"));
	return out;
}

} // namespace

void performCodegenEmitTests() {
	sprt::cout << "\n== flow codegen: the generator over the corpus ==\n";

	// ---- every case writes out, and writes out the same bytes twice ---------------------------------

	{
		bool emitted = true;
		bool deterministic = true;
		mem_std::Vector<mem_std::String> names;
		mem_std::Vector<mem_std::String> caseNames;
		for (auto &c : corpus::Cases) {
			Fixture a;
			Fixture b;
			codegen::Emitted first;
			codegen::Emitted second;
			mem_std::Value diag;
			if (!emitCase(a, c, first, &diag) || !emitCase(b, c, second)) {
				sprt::cout << "       " << c.name << ": does not emit: "
						   << data::toString<mem_std::Interface>(diag, false) << "\n";
				emitted = false;
				continue;
			}
			if (first.header != second.header || first.sources != second.sources
					|| first.textHash != second.textHash) {
				sprt::cout << "       " << c.name << ": two emissions differ\n";
				deterministic = false;
			}
			names.emplace_back(unitName(c.name));
			caseNames.emplace_back(mem_std::String(c.name.data(), c.name.size()));

			// Writing, when asked to. The manifest follows, once every unit is on disk.
			if (!test::s_emitDir.empty() && !writeUnit(names.back(), first)) {
				sprt::cout << "       " << c.name << ": could not be written to " << test::s_emitDir
						   << "\n";
				emitted = false;
			}
		}
		check(emitted, mem_std::toString("codegen-emit: all ", corpus::CaseCount,
									" cases of the corpus write out as units"));
		check(deterministic, "codegen-emit: and a case written twice is the same bytes");

		if (!test::s_emitDir.empty()) {
			check(writeText(test::s_emitDir, StringView("manifest.gen.h"),
						  manifestText(StringView("TESTS_FLOW_CODEGEN_GEN_MANIFEST_GEN_H_"),
								  StringView("the corpus"), StringView("UnitCount"),
								  StringView("Units"), true, names, caseNames)),
					mem_std::toString("codegen-emit: the corpus and its manifest were written to ",
							test::s_emitDir));
		}
	}

	// ---- the committed corpus is the corpus ---------------------------------------------------------
	//
	// One unit per case, in corpus order, and each carrying the hash the generator gives today.
	// Anything else is a unit that fell behind, and the line says what to run.

	{
		check(UnitCount == corpus::CaseCount,
				mem_std::toString("codegen-emit: the committed corpus holds ", UnitCount, " units for ",
						corpus::CaseCount, " cases - ", Regenerate));

		bool fresh = true;
		for (uint32_t i = 0; i < UnitCount && i < corpus::CaseCount; ++i) {
			auto &unit = Units[i];
			auto c = findCase(unit.name);
			if (!c) {
				sprt::cout << "       unit " << unit.name << " names no case\n";
				fresh = false;
				continue;
			}
			Fixture fx;
			codegen::Emitted now;
			if (!emitCase(fx, *c, now)) {
				fresh = false;
				continue;
			}
			auto tables = unit.tables();
			if (tables.identity.textHash != now.textHash) {
				sprt::cout << "       " << unit.name << ": the committed unit is stale - "
						   << Regenerate << "\n";
				fresh = false;
			}
		}
		check(fresh, "codegen-emit: every committed unit is what the generator writes today");
	}

	// ---- and the generated half, written and checked exactly the same way ------------------------
	//
	// From here down a seed is a case like any other: the same emitter, the same options, the same
	// freshness rule. What a seed is not is a fixed graph - edit the generator and every one of these
	// units goes stale at once, which is what the hash is for and why the seeds are checked here.

	{
		auto &cases = synthCases();
		bool emitted = true;
		mem_std::Vector<mem_std::String> names;
		mem_std::Vector<mem_std::String> caseNames;

		for (auto &sc : cases) {
			auto c = sc.asCase();
			Fixture fx;
			codegen::Emitted unit;
			mem_std::Value diag;
			auto stem = synthUnitName(c.name);
			if (!emitCase(fx, c, unit, &diag, stem)) {
				sprt::cout << "       " << c.name << ": does not emit: "
						   << data::toString<mem_std::Interface>(diag, false) << "\n";
				emitted = false;
				continue;
			}
			names.emplace_back(stem);
			caseNames.emplace_back(mem_std::String(c.name.data(), c.name.size()));

			if (!test::s_emitDir.empty() && !writeUnit(stem, unit)) {
				sprt::cout << "       " << c.name << ": could not be written to " << test::s_emitDir
						   << "\n";
				emitted = false;
			}
		}

		check(emitted, mem_std::toString("codegen-emit: all ", SynthSeedCount,
									" seeds write out as units"));
		if (!test::s_emitDir.empty()) {
			check(writeText(test::s_emitDir, StringView("synth_manifest.gen.h"),
						  manifestText(StringView("TESTS_FLOW_CODEGEN_GEN_SYNTH_MANIFEST_GEN_H_"),
								  StringView("the seeds"), StringView("SynthUnitCount"),
								  StringView("SynthUnits"), false, names, caseNames)),
					"codegen-emit: the seeds and their manifest were written too");
		}

		check(SynthUnitCount == SynthSeedCount,
				mem_std::toString("codegen-emit: the committed seeds hold ", SynthUnitCount,
						" units for ", SynthSeedCount, " seeds - ", Regenerate));

		bool fresh = true;
		for (uint32_t i = 0; i < SynthUnitCount && i < uint32_t(cases.size()); ++i) {
			auto &unit = SynthUnits[i];
			const SynthCase *sc = nullptr;
			for (auto &it : cases) {
				if (StringView(it.name) == unit.name) {
					sc = &it;
					break;
				}
			}
			if (!sc) {
				sprt::cout << "       unit " << unit.name << " names no seed\n";
				fresh = false;
				continue;
			}
			Fixture fx;
			codegen::Emitted now;
			auto c = sc->asCase();
			if (!emitCase(fx, c, now, nullptr, synthUnitName(c.name))) {
				fresh = false;
				continue;
			}
			if (unit.tables().identity.textHash != now.textHash) {
				sprt::cout << "       " << unit.name << ": the committed unit is stale - "
						   << Regenerate << "\n";
				fresh = false;
			}
		}
		check(fresh, "codegen-emit: every committed seed unit is what the generator writes today");
	}

	// ---- a unit describes the graph it was written from ---------------------------------------------
	//
	// Loaded against the fixture's registry - the one the graph was built against - the unit answers
	// describe() with the built graph's value, and both of its contracts, unbound, with the built
	// graph's. The describers are one function over the graph policy, so this is the tables
	// agreeing, row for row.

	{
		bool loads = true;
		bool described = true;
		bool contracts = true;
		bool unbound = true;
		for (uint32_t i = 0; i < UnitCount; ++i) {
			auto &unit = Units[i];
			auto c = findCase(unit.name);
			Fixture fx;
			if (!c || !corpus::prepareCase(fx, *c, false)) {
				loads = false;
				continue;
			}

			CompiledGraph compiled;
			mem_std::Value diag;
			auto &ops = fx.graph.getLink() ? fx.graph.getLink()->getOps() : fx.ops;
			if (compiled.load(unit.tables(), ops, &diag) != Status::Ok || !compiled.isValid()) {
				sprt::cout << "       " << unit.name << ": does not load: "
						   << data::toString<mem_std::Interface>(diag, false) << "\n";
				loads = false;
				continue;
			}

			mem_std::Value expect;
			mem_std::Value got;
			fx.graph.describe(expect);
			compiled.describe(got);
			if (!test::compareValues(got, expect, mem_std::toString(unit.name, " describe"))) {
				described = false;
			}

			// Unbound: no bindings handed out, the contract still readable. The same two answers a
			// built graph gives before a scene is consulted.
			for (uint32_t n = 0; n < compiled.getNodeCount(); ++n) {
				if (!compiled.getSceneBindings(n).empty()
						|| !compiled.getExtensionBindings(n).empty()) {
					unbound = false;
				}
			}
			if (compiled.getSceneRegistry() != nullptr) {
				unbound = false;
			}

			mem_std::Value expectContract;
			mem_std::Value gotContract;
			fx.graph.describeSceneContract(expectContract);
			compiled.describeSceneContract(gotContract);
			if (!test::compareValues(gotContract, expectContract,
						mem_std::toString(unit.name, " scene contract"))) {
				contracts = false;
			}
			mem_std::Value expectExt;
			mem_std::Value gotExt;
			fx.graph.describeExtensionContract(expectExt);
			compiled.describeExtensionContract(gotExt);
			if (!test::compareValues(gotExt, expectExt,
						mem_std::toString(unit.name, " extension contract"))) {
				contracts = false;
			}
		}
		check(loads, "codegen-emit: every committed unit loads against the registry it was written "
					 "against");
		check(described, "codegen-emit: and describes the graph it was written from, row for row");
		check(unbound, "codegen-emit: loaded without a scene, a unit hands out no bindings and keeps "
					   "its contract");
		check(contracts, "codegen-emit: and its scene and extension contracts read as the graph's");
	}
}

} // namespace STAPPLER_VERSIONIZED stappler
