// Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

// ---------------------------------------------------------------------------
// cross/macos_sprt/sysconf.h <-> Darwin <unistd.h> _SC_* parity.
//
// sysconf() selectors are forwarded to libSystem, so a wrong number returns a
// different limit rather than failing. sprt spells them __SPRT_SC_* (no leading
// underscore), hence SPRT_CONST_MAP throughout.
//
// Compile-time only; see check.sh.
// ---------------------------------------------------------------------------

#include <unistd.h>

#define SPRT_ABI_HEADER <sprt/c/cross/__sprt_sysconf.h>
#include "abi_check.h"

// === sysconf() selectors ===================================================
SPRT_CONST_MAP(SC_ARG_MAX, _SC_ARG_MAX);
SPRT_CONST_MAP(SC_CHILD_MAX, _SC_CHILD_MAX);
SPRT_CONST_MAP(SC_CLK_TCK, _SC_CLK_TCK);
SPRT_CONST_MAP(SC_NGROUPS_MAX, _SC_NGROUPS_MAX);
SPRT_CONST_MAP(SC_OPEN_MAX, _SC_OPEN_MAX);
SPRT_CONST_MAP(SC_JOB_CONTROL, _SC_JOB_CONTROL);
SPRT_CONST_MAP(SC_SAVED_IDS, _SC_SAVED_IDS);
SPRT_CONST_MAP(SC_VERSION, _SC_VERSION);
SPRT_CONST_MAP(SC_BC_BASE_MAX, _SC_BC_BASE_MAX);
SPRT_CONST_MAP(SC_BC_DIM_MAX, _SC_BC_DIM_MAX);
SPRT_CONST_MAP(SC_BC_SCALE_MAX, _SC_BC_SCALE_MAX);
SPRT_CONST_MAP(SC_BC_STRING_MAX, _SC_BC_STRING_MAX);
SPRT_CONST_MAP(SC_COLL_WEIGHTS_MAX, _SC_COLL_WEIGHTS_MAX);
SPRT_CONST_MAP(SC_EXPR_NEST_MAX, _SC_EXPR_NEST_MAX);
SPRT_CONST_MAP(SC_LINE_MAX, _SC_LINE_MAX);
SPRT_CONST_MAP(SC_RE_DUP_MAX, _SC_RE_DUP_MAX);
SPRT_CONST_MAP(SC_2_VERSION, _SC_2_VERSION);
SPRT_CONST_MAP(SC_2_C_BIND, _SC_2_C_BIND);
SPRT_CONST_MAP(SC_2_C_DEV, _SC_2_C_DEV);
SPRT_CONST_MAP(SC_2_CHAR_TERM, _SC_2_CHAR_TERM);
SPRT_CONST_MAP(SC_2_FORT_DEV, _SC_2_FORT_DEV);
SPRT_CONST_MAP(SC_2_FORT_RUN, _SC_2_FORT_RUN);
SPRT_CONST_MAP(SC_2_LOCALEDEF, _SC_2_LOCALEDEF);
SPRT_CONST_MAP(SC_2_SW_DEV, _SC_2_SW_DEV);
SPRT_CONST_MAP(SC_2_UPE, _SC_2_UPE);
SPRT_CONST_MAP(SC_STREAM_MAX, _SC_STREAM_MAX);
SPRT_CONST_MAP(SC_TZNAME_MAX, _SC_TZNAME_MAX);
SPRT_CONST_MAP(SC_ASYNCHRONOUS_IO, _SC_ASYNCHRONOUS_IO);
SPRT_CONST_MAP(SC_PAGESIZE, _SC_PAGESIZE);
SPRT_CONST_MAP(SC_MEMLOCK, _SC_MEMLOCK);
SPRT_CONST_MAP(SC_MEMLOCK_RANGE, _SC_MEMLOCK_RANGE);
SPRT_CONST_MAP(SC_MEMORY_PROTECTION, _SC_MEMORY_PROTECTION);
SPRT_CONST_MAP(SC_MESSAGE_PASSING, _SC_MESSAGE_PASSING);
SPRT_CONST_MAP(SC_PRIORITIZED_IO, _SC_PRIORITIZED_IO);
SPRT_CONST_MAP(SC_PRIORITY_SCHEDULING, _SC_PRIORITY_SCHEDULING);
SPRT_CONST_MAP(SC_REALTIME_SIGNALS, _SC_REALTIME_SIGNALS);
SPRT_CONST_MAP(SC_SEMAPHORES, _SC_SEMAPHORES);
SPRT_CONST_MAP(SC_FSYNC, _SC_FSYNC);
SPRT_CONST_MAP(SC_SHARED_MEMORY_OBJECTS, _SC_SHARED_MEMORY_OBJECTS);
SPRT_CONST_MAP(SC_SYNCHRONIZED_IO, _SC_SYNCHRONIZED_IO);
SPRT_CONST_MAP(SC_TIMERS, _SC_TIMERS);
SPRT_CONST_MAP(SC_AIO_LISTIO_MAX, _SC_AIO_LISTIO_MAX);
SPRT_CONST_MAP(SC_AIO_MAX, _SC_AIO_MAX);
SPRT_CONST_MAP(SC_AIO_PRIO_DELTA_MAX, _SC_AIO_PRIO_DELTA_MAX);
SPRT_CONST_MAP(SC_DELAYTIMER_MAX, _SC_DELAYTIMER_MAX);
SPRT_CONST_MAP(SC_MQ_OPEN_MAX, _SC_MQ_OPEN_MAX);
SPRT_CONST_MAP(SC_MAPPED_FILES, _SC_MAPPED_FILES);
SPRT_CONST_MAP(SC_RTSIG_MAX, _SC_RTSIG_MAX);
SPRT_CONST_MAP(SC_SEM_NSEMS_MAX, _SC_SEM_NSEMS_MAX);
SPRT_CONST_MAP(SC_SEM_VALUE_MAX, _SC_SEM_VALUE_MAX);
SPRT_CONST_MAP(SC_SIGQUEUE_MAX, _SC_SIGQUEUE_MAX);
SPRT_CONST_MAP(SC_TIMER_MAX, _SC_TIMER_MAX);
SPRT_CONST_MAP(SC_NPROCESSORS_CONF, _SC_NPROCESSORS_CONF);
SPRT_CONST_MAP(SC_NPROCESSORS_ONLN, _SC_NPROCESSORS_ONLN);
SPRT_CONST_MAP(SC_2_PBS, _SC_2_PBS);
SPRT_CONST_MAP(SC_2_PBS_ACCOUNTING, _SC_2_PBS_ACCOUNTING);
SPRT_CONST_MAP(SC_2_PBS_CHECKPOINT, _SC_2_PBS_CHECKPOINT);
SPRT_CONST_MAP(SC_2_PBS_LOCATE, _SC_2_PBS_LOCATE);
SPRT_CONST_MAP(SC_2_PBS_MESSAGE, _SC_2_PBS_MESSAGE);
SPRT_CONST_MAP(SC_2_PBS_TRACK, _SC_2_PBS_TRACK);
SPRT_CONST_MAP(SC_ADVISORY_INFO, _SC_ADVISORY_INFO);
SPRT_CONST_MAP(SC_BARRIERS, _SC_BARRIERS);
SPRT_CONST_MAP(SC_CLOCK_SELECTION, _SC_CLOCK_SELECTION);
SPRT_CONST_MAP(SC_CPUTIME, _SC_CPUTIME);
SPRT_CONST_MAP(SC_FILE_LOCKING, _SC_FILE_LOCKING);
SPRT_CONST_MAP(SC_GETGR_R_SIZE_MAX, _SC_GETGR_R_SIZE_MAX);
SPRT_CONST_MAP(SC_GETPW_R_SIZE_MAX, _SC_GETPW_R_SIZE_MAX);
SPRT_CONST_MAP(SC_HOST_NAME_MAX, _SC_HOST_NAME_MAX);
SPRT_CONST_MAP(SC_LOGIN_NAME_MAX, _SC_LOGIN_NAME_MAX);
SPRT_CONST_MAP(SC_MONOTONIC_CLOCK, _SC_MONOTONIC_CLOCK);
SPRT_CONST_MAP(SC_MQ_PRIO_MAX, _SC_MQ_PRIO_MAX);
SPRT_CONST_MAP(SC_READER_WRITER_LOCKS, _SC_READER_WRITER_LOCKS);
SPRT_CONST_MAP(SC_REGEXP, _SC_REGEXP);
SPRT_CONST_MAP(SC_SHELL, _SC_SHELL);
SPRT_CONST_MAP(SC_SPAWN, _SC_SPAWN);
SPRT_CONST_MAP(SC_SPIN_LOCKS, _SC_SPIN_LOCKS);
SPRT_CONST_MAP(SC_SPORADIC_SERVER, _SC_SPORADIC_SERVER);
SPRT_CONST_MAP(SC_THREAD_ATTR_STACKADDR, _SC_THREAD_ATTR_STACKADDR);
SPRT_CONST_MAP(SC_THREAD_ATTR_STACKSIZE, _SC_THREAD_ATTR_STACKSIZE);
SPRT_CONST_MAP(SC_THREAD_CPUTIME, _SC_THREAD_CPUTIME);
SPRT_CONST_MAP(SC_THREAD_DESTRUCTOR_ITERATIONS, _SC_THREAD_DESTRUCTOR_ITERATIONS);
SPRT_CONST_MAP(SC_THREAD_KEYS_MAX, _SC_THREAD_KEYS_MAX);
SPRT_CONST_MAP(SC_THREAD_PRIO_INHERIT, _SC_THREAD_PRIO_INHERIT);
SPRT_CONST_MAP(SC_THREAD_PRIO_PROTECT, _SC_THREAD_PRIO_PROTECT);
SPRT_CONST_MAP(SC_THREAD_PRIORITY_SCHEDULING, _SC_THREAD_PRIORITY_SCHEDULING);
SPRT_CONST_MAP(SC_THREAD_PROCESS_SHARED, _SC_THREAD_PROCESS_SHARED);
SPRT_CONST_MAP(SC_THREAD_SAFE_FUNCTIONS, _SC_THREAD_SAFE_FUNCTIONS);
SPRT_CONST_MAP(SC_THREAD_SPORADIC_SERVER, _SC_THREAD_SPORADIC_SERVER);
SPRT_CONST_MAP(SC_THREAD_STACK_MIN, _SC_THREAD_STACK_MIN);
SPRT_CONST_MAP(SC_THREAD_THREADS_MAX, _SC_THREAD_THREADS_MAX);
SPRT_CONST_MAP(SC_TIMEOUTS, _SC_TIMEOUTS);
SPRT_CONST_MAP(SC_THREADS, _SC_THREADS);
SPRT_CONST_MAP(SC_TRACE, _SC_TRACE);
SPRT_CONST_MAP(SC_TRACE_EVENT_FILTER, _SC_TRACE_EVENT_FILTER);
SPRT_CONST_MAP(SC_TRACE_INHERIT, _SC_TRACE_INHERIT);
SPRT_CONST_MAP(SC_TRACE_LOG, _SC_TRACE_LOG);
SPRT_CONST_MAP(SC_TTY_NAME_MAX, _SC_TTY_NAME_MAX);
SPRT_CONST_MAP(SC_TYPED_MEMORY_OBJECTS, _SC_TYPED_MEMORY_OBJECTS);
SPRT_CONST_MAP(SC_V6_ILP32_OFF32, _SC_V6_ILP32_OFF32);
SPRT_CONST_MAP(SC_V6_ILP32_OFFBIG, _SC_V6_ILP32_OFFBIG);
SPRT_CONST_MAP(SC_V6_LP64_OFF64, _SC_V6_LP64_OFF64);
SPRT_CONST_MAP(SC_V6_LPBIG_OFFBIG, _SC_V6_LPBIG_OFFBIG);
SPRT_CONST_MAP(SC_IPV6, _SC_IPV6);
SPRT_CONST_MAP(SC_RAW_SOCKETS, _SC_RAW_SOCKETS);
SPRT_CONST_MAP(SC_SYMLOOP_MAX, _SC_SYMLOOP_MAX);
SPRT_CONST_MAP(SC_ATEXIT_MAX, _SC_ATEXIT_MAX);
SPRT_CONST_MAP(SC_IOV_MAX, _SC_IOV_MAX);
SPRT_CONST_MAP(SC_PAGE_SIZE, _SC_PAGE_SIZE);
SPRT_CONST_MAP(SC_XOPEN_CRYPT, _SC_XOPEN_CRYPT);
SPRT_CONST_MAP(SC_XOPEN_ENH_I18N, _SC_XOPEN_ENH_I18N);
SPRT_CONST_MAP(SC_XOPEN_LEGACY, _SC_XOPEN_LEGACY);
SPRT_CONST_MAP(SC_XOPEN_REALTIME, _SC_XOPEN_REALTIME);
SPRT_CONST_MAP(SC_XOPEN_REALTIME_THREADS, _SC_XOPEN_REALTIME_THREADS);
SPRT_CONST_MAP(SC_XOPEN_SHM, _SC_XOPEN_SHM);
SPRT_CONST_MAP(SC_XOPEN_STREAMS, _SC_XOPEN_STREAMS);
SPRT_CONST_MAP(SC_XOPEN_UNIX, _SC_XOPEN_UNIX);
SPRT_CONST_MAP(SC_XOPEN_VERSION, _SC_XOPEN_VERSION);
SPRT_CONST_MAP(SC_XOPEN_XCU_VERSION, _SC_XOPEN_XCU_VERSION);
SPRT_CONST_MAP(SC_XBS5_ILP32_OFF32, _SC_XBS5_ILP32_OFF32);
SPRT_CONST_MAP(SC_XBS5_ILP32_OFFBIG, _SC_XBS5_ILP32_OFFBIG);
SPRT_CONST_MAP(SC_XBS5_LP64_OFF64, _SC_XBS5_LP64_OFF64);
SPRT_CONST_MAP(SC_XBS5_LPBIG_OFFBIG, _SC_XBS5_LPBIG_OFFBIG);
SPRT_CONST_MAP(SC_SS_REPL_MAX, _SC_SS_REPL_MAX);
SPRT_CONST_MAP(SC_TRACE_EVENT_NAME_MAX, _SC_TRACE_EVENT_NAME_MAX);
SPRT_CONST_MAP(SC_TRACE_NAME_MAX, _SC_TRACE_NAME_MAX);
SPRT_CONST_MAP(SC_TRACE_SYS_MAX, _SC_TRACE_SYS_MAX);
SPRT_CONST_MAP(SC_TRACE_USER_EVENT_MAX, _SC_TRACE_USER_EVENT_MAX);
SPRT_CONST_MAP(SC_PASS_MAX, _SC_PASS_MAX);
SPRT_CONST_MAP(SC_PHYS_PAGES, _SC_PHYS_PAGES);
