#!/usr/bin/env python3
# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio> -- MIT (see check.sh)
#
# tbd-audit.py --sdk SDK --stubs SYSROOT [--exceptions FILE] [--label NAME]
#              [--compare-with REFERENCE]
#
# Audit the +open sysroot's .tbd link stubs against a real macOS SDK.
#
# The +open target ships no system dylibs -- only .tbd stubs carrying exactly the
# symbols this toolchain references -- and links with a two-level namespace and
# no -undefined dynamic_lookup. target-apple/README.md states the rule those
# stubs are built to:
#
#     every symbol in our stubs lives in the same library as in the SDK
#
# and records that it was verified once, by a full audit of every SDK tbd. That
# audit was ad-hoc and its script was not kept. This is the re-runnable form.
#
# Two things are checked for every symbol the stubs export:
#
#   1. it exists somewhere in the SDK at all;
#   2. the library that owns it here is the library that owns it in the SDK.
#
# (2) is the subtle one: a symbol put in the wrong stub still links locally, but
# records a load command naming a dylib that does not actually export it, and
# fails at launch on a real Mac. usr/lib/system/* is folded into the libSystem
# umbrella, matching how the real linker resolves it.
#
# --compare-with additionally diffs the audited stubs against a reference tree
# (the git-tracked open/sysroot). The stubs travel open/sysroot -> intermediate
# -> targets, and nothing re-runs those stages until the target is rebuilt, so an
# installed sysroot can silently lag a re-bake.

import argparse, os, re, sys, glob, collections

SYMBOL_KINDS = {
    'symbols':        lambda s: [s],
    'objc-classes':   lambda s: ['_OBJC_CLASS_$_' + s, '_OBJC_METACLASS_$_' + s],
    'objc-ivars':     lambda s: ['_OBJC_IVAR_$_' + s],
    'objc-eh-types':  lambda s: ['_OBJC_EHTYPE_$_' + s],
}

LIST_RE = re.compile(r'^\s*(symbols|objc-classes|objc-ivars|objc-eh-types):\s*\[(.*?)\]',
                     re.S | re.M)
INSTALL_RE = re.compile(r"^install-name:\s*'?([^'\n]+?)'?\s*$", re.M)


def tbd_symbols(path):
    """Every symbol a .tbd exports, in its linker spelling."""
    text = open(path, errors='replace').read()
    out = set()
    for m in LIST_RE.finditer(text):
        expand = SYMBOL_KINDS[m.group(1)]
        for tok in m.group(2).split(','):
            tok = tok.strip().strip("'").strip('"').strip()
            if tok:
                out.update(expand(tok))
    return out


def install_name(path):
    m = INSTALL_RE.search(open(path, errors='replace').read())
    return m.group(1).strip() if m else path


def owning_library(name):
    """The library a symbol is attributed to, with the libSystem fold applied."""
    if '/usr/lib/system/' in name:
        return 'libSystem.B.dylib'
    return os.path.basename(name)


def index_sdk(sdk):
    idx = collections.defaultdict(set)
    files = (glob.glob(sdk + '/usr/lib/**/*.tbd', recursive=True)
             + glob.glob(sdk + '/System/Library/Frameworks/**/*.tbd', recursive=True))
    for f in files:
        lib = owning_library(install_name(f))
        for s in tbd_symbols(f):
            idx[s].add(lib)
    return idx, len(files)


# Stubs that describe THIS toolchain's own products rather than an Apple
# library. libc++ / libc++abi / libunwind are cross-built here and their tbds are
# generated by `llvm-readtapi -stubify` from the resulting dylibs -- gen-oss-stubs.sh
# classifies the whole C++ ABI set as cxxabi-skip and never bakes them. Their
# symbols are ours, shipped alongside the target; comparing them against Apple's
# libSystem/libc++ would be comparing two different implementations. Same for
# MoltenVK and the sanitizer runtimes if they ever grow a stub.
OWN_PRODUCTS = ('libc++.tbd', 'libc++abi.tbd', 'libunwind.tbd',
                'libc++.1.tbd', 'libc++abi.1.tbd', 'libunwind.1.tbd')


def stub_files(root):
    files = sorted(glob.glob(root + '/usr/lib/*.tbd')
                   + glob.glob(root + '/System/Library/Frameworks/**/*.tbd', recursive=True))
    return [f for f in files if os.path.basename(f) not in OWN_PRODUCTS]


def load_exceptions(path):
    """symbol -> reason, and (library, symbol) -> reason for ownership waivers."""
    allowed = {}
    if not path or not os.path.exists(path):
        return allowed
    for raw in open(path):
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split('|')]
        if len(parts) < 2:
            print('tbd-audit: malformed exception line: %s' % raw.rstrip(), file=sys.stderr)
            continue
        allowed[parts[0]] = parts[1]
    return allowed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--sdk', required=True)
    ap.add_argument('--stubs', required=True)
    ap.add_argument('--exceptions')
    ap.add_argument('--label', default='')
    ap.add_argument('--compare-with')
    a = ap.parse_args()

    label = a.label or a.stubs
    if not stub_files(a.stubs):
        print('tbd-audit: SKIP %s - no .tbd stubs found' % label, file=sys.stderr)
        return 0

    idx, nsdk = index_sdk(a.sdk)
    if not idx:
        print('tbd-audit: SKIP - no .tbd files in SDK %s' % a.sdk, file=sys.stderr)
        return 0
    allowed = load_exceptions(a.exceptions)

    missing, wrong, waived = [], [], 0
    nsym = 0
    for f in stub_files(a.stubs):
        lib = owning_library(install_name(f))
        for s in sorted(tbd_symbols(f)):
            nsym += 1
            key = '%s:%s' % (lib, s)
            if s not in idx:
                if s in allowed or key in allowed:
                    waived += 1
                else:
                    missing.append((lib, s, None))
            elif lib not in idx[s]:
                if key in allowed or s in allowed:
                    waived += 1
                else:
                    wrong.append((lib, s, sorted(idx[s])))

    print('tbd-audit [%s]: %d symbols in %d stubs, against %d SDK tbds (%d indexed symbols)'
          % (label, nsym, len(stub_files(a.stubs)), nsdk, len(idx)))
    for lib, s, _ in missing:
        print('  MISSING  %-28s %s' % (lib, s))
        print('           not exported by any dylib in the SDK. Either it is newer than the '
              'SDK\n           (add it to tbd-exceptions.txt with a reason) or the name is wrong.')
    for lib, s, owners in wrong:
        print('  OWNER    %-28s %s' % (lib, s))
        print('           the SDK exports it from %s. A symbol in the wrong stub links here '
              'but\n           records a load command that fails on a real Mac.' % ', '.join(owners))
    if waived:
        print('  %d symbol(s) waived by %s' % (waived, os.path.basename(a.exceptions or '')))

    rc = 1 if (missing or wrong) else 0

    if a.compare_with:
        ref = {os.path.relpath(f, a.compare_with): f for f in stub_files(a.compare_with)}
        cur = {os.path.relpath(f, a.stubs): f for f in stub_files(a.stubs)}
        drift = []
        for rel, rf in sorted(ref.items()):
            cf = cur.get(rel)
            if cf is None:
                drift.append('  DRIFT    %s is in the tracked overlay but not installed here' % rel)
            elif tbd_symbols(rf) != tbd_symbols(cf):
                only_ref = tbd_symbols(rf) - tbd_symbols(cf)
                only_cur = tbd_symbols(cf) - tbd_symbols(rf)
                drift.append('  DRIFT    %s: %d symbol(s) only in the tracked overlay, %d only here'
                             % (rel, len(only_ref), len(only_cur)))
                for s in sorted(only_ref)[:5]:
                    drift.append('               tracked-only: %s' % s)
                for s in sorted(only_cur)[:5]:
                    drift.append('               installed-only: %s' % s)
        if drift:
            print('  the installed stubs differ from the tracked overlay. The stubs travel')
            print('  open/sysroot -> intermediate/<t> -> targets/<t>, and nothing re-runs those')
            print('  stages until the target is rebuilt, so a re-bake can sit unpublished.')
            print('\n'.join(drift))
            rc = 1

    if rc == 0:
        print('  OK - every symbol exists in the SDK and is owned by the same library')
    return rc


if __name__ == '__main__':
    sys.exit(main())
