// MCST Elbrus (e2k) system call numbers, generated from the lcc delivery's
// asm/unistd.h (the e2k kernel table is its own i386-style remap, NOT the
// x86_64 one). Names the e2k kernel does not implement are pinned to -1L:
// the kernel routes an unknown number to sys_ni_syscall, so the call yields
// ENOSYS instead of reaching a wrong handler. pread64/pwrite64 map onto the
// table's pread/pwrite — identical ABI, historical naming.
//
// SPARK: regenerate after an lcc delivery update:
//   values from <lcc>/fs/usr/include/asm/unistd.h, names from x86_64_sprt/syscall.h
#define __SPRT_SYSCALL_read 3
#define __SPRT_SYSCALL_write 4
#define __SPRT_SYSCALL_open 5
#define __SPRT_SYSCALL_close 6
#define __SPRT_SYSCALL_stat 106
#define __SPRT_SYSCALL_fstat 108
#define __SPRT_SYSCALL_lstat 107
#define __SPRT_SYSCALL_poll 168
#define __SPRT_SYSCALL_lseek 19
#define __SPRT_SYSCALL_mmap 90
#define __SPRT_SYSCALL_mprotect 125
#define __SPRT_SYSCALL_munmap 91
#define __SPRT_SYSCALL_brk 45
#define __SPRT_SYSCALL_rt_sigaction 174
#define __SPRT_SYSCALL_rt_sigprocmask 175
#define __SPRT_SYSCALL_rt_sigreturn 173
#define __SPRT_SYSCALL_ioctl 54
#define __SPRT_SYSCALL_pread64 180
#define __SPRT_SYSCALL_pwrite64 181
#define __SPRT_SYSCALL_readv 145
#define __SPRT_SYSCALL_writev 146
#define __SPRT_SYSCALL_access 33
#define __SPRT_SYSCALL_pipe 42
#define __SPRT_SYSCALL_select 82
#define __SPRT_SYSCALL_sched_yield 158
#define __SPRT_SYSCALL_mremap 163
#define __SPRT_SYSCALL_msync 144
#define __SPRT_SYSCALL_mincore 218
#define __SPRT_SYSCALL_madvise 219
#define __SPRT_SYSCALL_shmget 278
#define __SPRT_SYSCALL_shmat 280
#define __SPRT_SYSCALL_shmctl 279
#define __SPRT_SYSCALL_dup 41
#define __SPRT_SYSCALL_dup2 63
#define __SPRT_SYSCALL_pause 29
#define __SPRT_SYSCALL_nanosleep 162
#define __SPRT_SYSCALL_getitimer 105
#define __SPRT_SYSCALL_alarm 27
#define __SPRT_SYSCALL_setitimer 104
#define __SPRT_SYSCALL_getpid 20
#define __SPRT_SYSCALL_sendfile 187
#define __SPRT_SYSCALL_socket 403
#define __SPRT_SYSCALL_connect 404
#define __SPRT_SYSCALL_accept 405
#define __SPRT_SYSCALL_sendto 406
#define __SPRT_SYSCALL_recvfrom 407
#define __SPRT_SYSCALL_sendmsg 408
#define __SPRT_SYSCALL_recvmsg 409
#define __SPRT_SYSCALL_shutdown 393
#define __SPRT_SYSCALL_bind 410
#define __SPRT_SYSCALL_listen 411
#define __SPRT_SYSCALL_getsockname 412
#define __SPRT_SYSCALL_getpeername 413
#define __SPRT_SYSCALL_socketpair 414
#define __SPRT_SYSCALL_setsockopt 415
#define __SPRT_SYSCALL_getsockopt 416
#define __SPRT_SYSCALL_clone 120
#define __SPRT_SYSCALL_fork 2
#define __SPRT_SYSCALL_vfork 190
#define __SPRT_SYSCALL_execve 11
#define __SPRT_SYSCALL_exit 1
#define __SPRT_SYSCALL_wait4 114
#define __SPRT_SYSCALL_kill 37
#define __SPRT_SYSCALL_uname 122
#define __SPRT_SYSCALL_semget 274
#define __SPRT_SYSCALL_semop 277
#define __SPRT_SYSCALL_semctl 275
#define __SPRT_SYSCALL_shmdt 281
#define __SPRT_SYSCALL_msgget 270
#define __SPRT_SYSCALL_msgsnd 273
#define __SPRT_SYSCALL_msgrcv 272
#define __SPRT_SYSCALL_msgctl 271
#define __SPRT_SYSCALL_fcntl 55
#define __SPRT_SYSCALL_flock 143
#define __SPRT_SYSCALL_fsync 118
#define __SPRT_SYSCALL_fdatasync 148
#define __SPRT_SYSCALL_truncate 92
#define __SPRT_SYSCALL_ftruncate 93
#define __SPRT_SYSCALL_getdents 141
#define __SPRT_SYSCALL_getcwd 183
#define __SPRT_SYSCALL_chdir 12
#define __SPRT_SYSCALL_fchdir 133
#define __SPRT_SYSCALL_rename 38
#define __SPRT_SYSCALL_mkdir 39
#define __SPRT_SYSCALL_rmdir 40
#define __SPRT_SYSCALL_creat 8
#define __SPRT_SYSCALL_link 9
#define __SPRT_SYSCALL_unlink 10
#define __SPRT_SYSCALL_symlink 83
#define __SPRT_SYSCALL_readlink 85
#define __SPRT_SYSCALL_chmod 15
#define __SPRT_SYSCALL_fchmod 94
#define __SPRT_SYSCALL_chown 182
#define __SPRT_SYSCALL_fchown 95
#define __SPRT_SYSCALL_lchown 16
#define __SPRT_SYSCALL_umask 60
#define __SPRT_SYSCALL_gettimeofday 78
#define __SPRT_SYSCALL_getrlimit 76
#define __SPRT_SYSCALL_getrusage 77
#define __SPRT_SYSCALL_sysinfo 116
#define __SPRT_SYSCALL_times 43
#define __SPRT_SYSCALL_ptrace 26
#define __SPRT_SYSCALL_getuid 24
#define __SPRT_SYSCALL_syslog 103
#define __SPRT_SYSCALL_getgid 47
#define __SPRT_SYSCALL_setuid 23
#define __SPRT_SYSCALL_setgid 46
#define __SPRT_SYSCALL_geteuid 49
#define __SPRT_SYSCALL_getegid 50
#define __SPRT_SYSCALL_setpgid 57
#define __SPRT_SYSCALL_getppid 64
#define __SPRT_SYSCALL_getpgrp 65
#define __SPRT_SYSCALL_setsid 66
#define __SPRT_SYSCALL_setreuid 70
#define __SPRT_SYSCALL_setregid 71
#define __SPRT_SYSCALL_getgroups 80
#define __SPRT_SYSCALL_setgroups 81
#define __SPRT_SYSCALL_setresuid 164
#define __SPRT_SYSCALL_getresuid 165
#define __SPRT_SYSCALL_setresgid 170
#define __SPRT_SYSCALL_getresgid 171
#define __SPRT_SYSCALL_getpgid 132
#define __SPRT_SYSCALL_setfsuid 138
#define __SPRT_SYSCALL_setfsgid 139
#define __SPRT_SYSCALL_getsid 147
#define __SPRT_SYSCALL_capget 184
#define __SPRT_SYSCALL_capset 185
#define __SPRT_SYSCALL_rt_sigpending 176
#define __SPRT_SYSCALL_rt_sigtimedwait 177
#define __SPRT_SYSCALL_rt_sigqueueinfo 178
#define __SPRT_SYSCALL_rt_sigsuspend 179
#define __SPRT_SYSCALL_sigaltstack 186
#define __SPRT_SYSCALL_utime 30
#define __SPRT_SYSCALL_mknod 14
#define __SPRT_SYSCALL_uselib 86
#define __SPRT_SYSCALL_personality 136
#define __SPRT_SYSCALL_ustat 62
#define __SPRT_SYSCALL_statfs 99
#define __SPRT_SYSCALL_fstatfs 100
#define __SPRT_SYSCALL_sysfs 135
#define __SPRT_SYSCALL_getpriority 96
#define __SPRT_SYSCALL_setpriority 97
#define __SPRT_SYSCALL_sched_setparam 154
#define __SPRT_SYSCALL_sched_getparam 155
#define __SPRT_SYSCALL_sched_setscheduler 156
#define __SPRT_SYSCALL_sched_getscheduler 157
#define __SPRT_SYSCALL_sched_get_priority_max 159
#define __SPRT_SYSCALL_sched_get_priority_min 160
#define __SPRT_SYSCALL_sched_rr_get_interval 161
#define __SPRT_SYSCALL_mlock 150
#define __SPRT_SYSCALL_munlock 151
#define __SPRT_SYSCALL_mlockall 152
#define __SPRT_SYSCALL_munlockall 153
#define __SPRT_SYSCALL_vhangup 111
#define __SPRT_SYSCALL_modify_ldt -1
#define __SPRT_SYSCALL_pivot_root 217
#define __SPRT_SYSCALL__sysctl -1
#define __SPRT_SYSCALL_prctl 172
#define __SPRT_SYSCALL_arch_prctl 419
#define __SPRT_SYSCALL_adjtimex 124
#define __SPRT_SYSCALL_setrlimit 75
#define __SPRT_SYSCALL_chroot 61
#define __SPRT_SYSCALL_sync 36
#define __SPRT_SYSCALL_acct 51
#define __SPRT_SYSCALL_settimeofday 79
#define __SPRT_SYSCALL_mount 21
#define __SPRT_SYSCALL_umount2 52
#define __SPRT_SYSCALL_swapon 87
#define __SPRT_SYSCALL_swapoff 115
#define __SPRT_SYSCALL_reboot 88
#define __SPRT_SYSCALL_sethostname 74
#define __SPRT_SYSCALL_setdomainname 121
#define __SPRT_SYSCALL_iopl -1
#define __SPRT_SYSCALL_ioperm 101
#define __SPRT_SYSCALL_create_module -1
#define __SPRT_SYSCALL_init_module 128
#define __SPRT_SYSCALL_delete_module 129
#define __SPRT_SYSCALL_get_kernel_syms -1
#define __SPRT_SYSCALL_query_module -1
#define __SPRT_SYSCALL_quotactl 131
#define __SPRT_SYSCALL_nfsservctl -1
#define __SPRT_SYSCALL_getpmsg -1
#define __SPRT_SYSCALL_putpmsg -1
#define __SPRT_SYSCALL_afs_syscall -1
#define __SPRT_SYSCALL_tuxcall -1
#define __SPRT_SYSCALL_security -1
#define __SPRT_SYSCALL_gettid 244
#define __SPRT_SYSCALL_readahead 245
#define __SPRT_SYSCALL_setxattr 232
#define __SPRT_SYSCALL_lsetxattr 233
#define __SPRT_SYSCALL_fsetxattr 234
#define __SPRT_SYSCALL_getxattr 235
#define __SPRT_SYSCALL_lgetxattr 236
#define __SPRT_SYSCALL_fgetxattr 237
#define __SPRT_SYSCALL_listxattr 238
#define __SPRT_SYSCALL_llistxattr 239
#define __SPRT_SYSCALL_flistxattr 240
#define __SPRT_SYSCALL_removexattr 241
#define __SPRT_SYSCALL_lremovexattr 242
#define __SPRT_SYSCALL_fremovexattr 243
#define __SPRT_SYSCALL_tkill 246
#define __SPRT_SYSCALL_time 13
#define __SPRT_SYSCALL_futex 248
#define __SPRT_SYSCALL_sched_setaffinity 249
#define __SPRT_SYSCALL_sched_getaffinity 250
#define __SPRT_SYSCALL_set_thread_area -1
#define __SPRT_SYSCALL_io_setup 294
#define __SPRT_SYSCALL_io_destroy 295
#define __SPRT_SYSCALL_io_getevents 296
#define __SPRT_SYSCALL_io_submit 297
#define __SPRT_SYSCALL_io_cancel 298
#define __SPRT_SYSCALL_get_thread_area -1
#define __SPRT_SYSCALL_lookup_dcookie 301
#define __SPRT_SYSCALL_epoll_create 302
#define __SPRT_SYSCALL_epoll_ctl_old -1
#define __SPRT_SYSCALL_epoll_wait_old -1
#define __SPRT_SYSCALL_remap_file_pages 305
#define __SPRT_SYSCALL_getdents64 220
#define __SPRT_SYSCALL_set_tid_address 259
#define __SPRT_SYSCALL_restart_syscall 0
#define __SPRT_SYSCALL_semtimedop 276
#define __SPRT_SYSCALL_fadvise64 299
#define __SPRT_SYSCALL_timer_create 261
#define __SPRT_SYSCALL_timer_settime 262
#define __SPRT_SYSCALL_timer_gettime 263
#define __SPRT_SYSCALL_timer_getoverrun 264
#define __SPRT_SYSCALL_timer_delete 265
#define __SPRT_SYSCALL_clock_settime 266
#define __SPRT_SYSCALL_clock_gettime 267
#define __SPRT_SYSCALL_clock_getres 268
#define __SPRT_SYSCALL_clock_nanosleep 269
#define __SPRT_SYSCALL_exit_group 300
#define __SPRT_SYSCALL_epoll_wait 304
#define __SPRT_SYSCALL_epoll_ctl 303
#define __SPRT_SYSCALL_tgkill 308
#define __SPRT_SYSCALL_utimes 309
#define __SPRT_SYSCALL_vserver -1
#define __SPRT_SYSCALL_mbind 312
#define __SPRT_SYSCALL_set_mempolicy 314
#define __SPRT_SYSCALL_get_mempolicy 313
#define __SPRT_SYSCALL_mq_open 315
#define __SPRT_SYSCALL_mq_unlink 316
#define __SPRT_SYSCALL_mq_timedsend 317
#define __SPRT_SYSCALL_mq_timedreceive 318
#define __SPRT_SYSCALL_mq_notify 319
#define __SPRT_SYSCALL_mq_getsetattr 320
#define __SPRT_SYSCALL_kexec_load 321
#define __SPRT_SYSCALL_waitid 322
#define __SPRT_SYSCALL_add_key 323
#define __SPRT_SYSCALL_request_key 324
#define __SPRT_SYSCALL_keyctl 325
#define __SPRT_SYSCALL_ioprio_set 289
#define __SPRT_SYSCALL_ioprio_get 290
#define __SPRT_SYSCALL_inotify_init 291
#define __SPRT_SYSCALL_inotify_add_watch 292
#define __SPRT_SYSCALL_inotify_rm_watch 293
#define __SPRT_SYSCALL_migrate_pages 332
#define __SPRT_SYSCALL_openat 335
#define __SPRT_SYSCALL_mkdirat 336
#define __SPRT_SYSCALL_mknodat 337
#define __SPRT_SYSCALL_fchownat 338
#define __SPRT_SYSCALL_futimesat 362
#define __SPRT_SYSCALL_newfstatat 224
#define __SPRT_SYSCALL_unlinkat 339
#define __SPRT_SYSCALL_renameat 340
#define __SPRT_SYSCALL_linkat 341
#define __SPRT_SYSCALL_symlinkat 342
#define __SPRT_SYSCALL_readlinkat 343
#define __SPRT_SYSCALL_fchmodat 344
#define __SPRT_SYSCALL_faccessat 345
#define __SPRT_SYSCALL_pselect6 367
#define __SPRT_SYSCALL_ppoll 368
#define __SPRT_SYSCALL_unshare 364
#define __SPRT_SYSCALL_set_robust_list 366
#define __SPRT_SYSCALL_get_robust_list 365
#define __SPRT_SYSCALL_splice 329
#define __SPRT_SYSCALL_tee 331
#define __SPRT_SYSCALL_sync_file_range 357
#define __SPRT_SYSCALL_vmsplice 330
#define __SPRT_SYSCALL_move_pages 328
#define __SPRT_SYSCALL_utimensat 333
#define __SPRT_SYSCALL_epoll_pwait 346
#define __SPRT_SYSCALL_signalfd -1
#define __SPRT_SYSCALL_timerfd_create 351
#define __SPRT_SYSCALL_eventfd -1
#define __SPRT_SYSCALL_fallocate 356
#define __SPRT_SYSCALL_timerfd_settime 352
#define __SPRT_SYSCALL_timerfd_gettime 353
#define __SPRT_SYSCALL_accept4 286
#define __SPRT_SYSCALL_signalfd4 347
#define __SPRT_SYSCALL_eventfd2 348
#define __SPRT_SYSCALL_epoll_create1 360
#define __SPRT_SYSCALL_dup3 358
#define __SPRT_SYSCALL_pipe2 251
#define __SPRT_SYSCALL_inotify_init1 359
#define __SPRT_SYSCALL_preadv 354
#define __SPRT_SYSCALL_pwritev 355
#define __SPRT_SYSCALL_rt_tgsigqueueinfo 334
#define __SPRT_SYSCALL_perf_event_open 363
#define __SPRT_SYSCALL_recvmmsg 349
#define __SPRT_SYSCALL_fanotify_init 373
#define __SPRT_SYSCALL_fanotify_mark 374
#define __SPRT_SYSCALL_prlimit64 375
#define __SPRT_SYSCALL_name_to_handle_at 400
#define __SPRT_SYSCALL_open_by_handle_at 401
#define __SPRT_SYSCALL_clock_adjtime 376
#define __SPRT_SYSCALL_syncfs 377
#define __SPRT_SYSCALL_sendmmsg 378
#define __SPRT_SYSCALL_setns 379
#define __SPRT_SYSCALL_getcpu 327
#define __SPRT_SYSCALL_process_vm_readv 380
#define __SPRT_SYSCALL_process_vm_writev 381
#define __SPRT_SYSCALL_kcmp 382
#define __SPRT_SYSCALL_finit_module 383
#define __SPRT_SYSCALL_sched_setattr 287
#define __SPRT_SYSCALL_sched_getattr 288
#define __SPRT_SYSCALL_renameat2 384
#define __SPRT_SYSCALL_seccomp 392
#define __SPRT_SYSCALL_getrandom 385
#define __SPRT_SYSCALL_memfd_create 386
#define __SPRT_SYSCALL_kexec_file_load -1
#define __SPRT_SYSCALL_bpf 387
#define __SPRT_SYSCALL_execveat 388
#define __SPRT_SYSCALL_userfaultfd 389
#define __SPRT_SYSCALL_membarrier 390
#define __SPRT_SYSCALL_mlock2 391
#define __SPRT_SYSCALL_copy_file_range 394
#define __SPRT_SYSCALL_preadv2 395
#define __SPRT_SYSCALL_pwritev2 396
#define __SPRT_SYSCALL_pkey_mprotect -1
#define __SPRT_SYSCALL_pkey_alloc -1
#define __SPRT_SYSCALL_pkey_free -1
#define __SPRT_SYSCALL_statx 402
#define __SPRT_SYSCALL_io_pgetevents 285
#define __SPRT_SYSCALL_rseq 284
#define __SPRT_SYSCALL_uretprobe -1
#define __SPRT_SYSCALL_uprobe -1
#define __SPRT_SYSCALL_pidfd_send_signal 205
#define __SPRT_SYSCALL_io_uring_setup 256
#define __SPRT_SYSCALL_io_uring_enter 257
#define __SPRT_SYSCALL_io_uring_register 258
#define __SPRT_SYSCALL_open_tree 282
#define __SPRT_SYSCALL_move_mount 283
#define __SPRT_SYSCALL_fsopen 427
#define __SPRT_SYSCALL_fsconfig 428
#define __SPRT_SYSCALL_fsmount 429
#define __SPRT_SYSCALL_fspick 430
#define __SPRT_SYSCALL_pidfd_open 206
#define __SPRT_SYSCALL_clone3 426
#define __SPRT_SYSCALL_close_range 431
#define __SPRT_SYSCALL_openat2 432
#define __SPRT_SYSCALL_pidfd_getfd 433
#define __SPRT_SYSCALL_faccessat2 434
#define __SPRT_SYSCALL_process_madvise 435
#define __SPRT_SYSCALL_epoll_pwait2 436
#define __SPRT_SYSCALL_mount_setattr 437
#define __SPRT_SYSCALL_quotactl_fd 438
#define __SPRT_SYSCALL_landlock_create_ruleset 439
#define __SPRT_SYSCALL_landlock_add_rule 440
#define __SPRT_SYSCALL_landlock_restrict_self 441
#define __SPRT_SYSCALL_memfd_secret -1
#define __SPRT_SYSCALL_process_mrelease 442
#define __SPRT_SYSCALL_futex_waitv 443
#define __SPRT_SYSCALL_set_mempolicy_home_node 444
#define __SPRT_SYSCALL_cachestat -1
#define __SPRT_SYSCALL_fchmodat2 -1
#define __SPRT_SYSCALL_map_shadow_stack -1
#define __SPRT_SYSCALL_futex_wake -1
#define __SPRT_SYSCALL_futex_wait -1
#define __SPRT_SYSCALL_futex_requeue -1
#define __SPRT_SYSCALL_statmount -1
#define __SPRT_SYSCALL_listmount -1
#define __SPRT_SYSCALL_lsm_get_self_attr -1
#define __SPRT_SYSCALL_lsm_set_self_attr -1
#define __SPRT_SYSCALL_lsm_list_modules -1
#define __SPRT_SYSCALL_mseal -1
#define __SPRT_SYSCALL_setxattrat -1
#define __SPRT_SYSCALL_getxattrat -1
#define __SPRT_SYSCALL_listxattrat -1
#define __SPRT_SYSCALL_removexattrat -1
#define __SPRT_SYSCALL_open_tree_attr -1
#define __SPRT_SYSCALL_file_getattr -1
#define __SPRT_SYSCALL_file_setattr -1
